### ISSUE TITLE
[Issue]: HIP out of memory when allocating more than ~16GB

### ISSUE THREAD

**Issue by peturorri** [ROCm/TheRock#1054]
### Problem Description

When allocating ~16 GB in total I receive an error complaining about running out of memory.
```
torch.OutOfMemoryError: HIP out of memory. Tried to allocate 16.00 GiB. GPU 0 has a total capacity of 15.24 GiB of which 15.09 GiB is free. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

The error message indicates that there are only 15.24 GB of memory available, but the machine should have 96 GB of memory available to the GPU.

dmesg shows this output, so I think I have the settings right (?):
```
[    4.972801] amdgpu 0000:c5:00.0: amdgpu: VRAM: 98304M 0x0000008000000000 - 0x00000097FFFFFFFF (98304M used)
[    4.972828] [drm] Detected VRAM RAM=98304M, BAR=98304M
[    4.973019] [drm] amdgpu: 98304M of VRAM memory ready
```

The machine is an GMKTek Evo-X2 with 128GB unified RAM. I.e. gfx1151.

Please let me know if there is more information that I can provide.

### Operating System

Ubuntu 25.04 (Plucky Puffin)

### CPU

AMD RYZEN AI MAX+ 395 w/ Radeon 8060S

### GPU

AMD RYZEN AI MAX+ 395 w/ Radeon 8060S (gfx1151)

### ROCm Version

7.0.0rc20250715

### Steps to Reproduce

Example interactive shell:
```
$ python
Python 3.13.3 (main, Jun 16 2025, 18:15:32) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> x = torch.ones(2**30*16, dtype=torch.int8).to("cuda")
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    x = torch.ones(2**30*16, dtype=torch.int8).to("cuda")
torch.OutOfMemoryError: HIP out of memory. Tried to allocate 16.00 GiB. GPU 0 has a total capacity of 15.24 GiB of which 15.09 GiB is free. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
>>> x = torch.ones(2**30*15, dtype=torch.int8).to("cuda") # 15 GB, works fine
```

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support
```
ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.16
Runtime Ext Version:     1.8
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
XNACK enabled:           NO
DMAbuf Support:          YES
VMM Support:             YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD RYZEN AI MAX+ 395 w/ Radeon 8060S
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD RYZEN AI MAX+ 395 w/ Radeon 8060S
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      49152(0xc000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   5187                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Memory Properties:       
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    31965264(0x1e7c050) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    31965264(0x1e7c050) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    31965264(0x1e7c050) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 4                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    31965264(0x1e7c050) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1151                            
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon Graphics                
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      2048(0x800) KB                     
    L3:                      16384(0x4000) KB                   
  Chip ID:                 5510(0x1586)                       
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          128(0x80)                          
  Max Clock Freq. (MHz):   2900                               
  BDFID:                   50432                              
  Internal Node ID:        1                                  
  Compute Unit:            40                                 
  SIMDs per CU:            2                                  
  Shader Engines:          2                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Memory Properties:       APU
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        2147483647(0x7fffffff)             
    y                        65535(0xffff)                      
    z                        65535(0xffff)                      
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 29                                 
  SDMA engine uCode::      14                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    15982632(0xf3e028) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    15982632(0xf3e028) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1151         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        2147483647(0x7fffffff)             
        y                        65535(0xffff)                      
        z                        65535(0xffff)                      
      FBarrier Max Size:       32                                 
    ISA 2                    
      Name:                    amdgcn-amd-amdhsa--gfx11-generic   
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        2147483647(0x7fffffff)             
        y                        65535(0xffff)                      
        z                        65535(0xffff)                      
      FBarrier Max Size:       32                                 
*******                  
Agent 3                  
*******                  
  Name:                    aie2                               
  Uuid:                    AIE-XX                             
  Marketing Name:          AIE-ML                             
  Vendor Name:             AMD                                
  Feature:                 AGENT_DISPATCH                     
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        1(0x1)                             
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          64(0x40)                           
  Queue Type:              SINGLE                             
  Node:                    0                                  
  Device Type:             DSP                                
  Cache Info:              
    L2:                      2048(0x800) KB                     
    L3:                      16384(0x4000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          0(0x0)                             
  Max Clock Freq. (MHz):   0                                  
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            0                                  
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:0                                  
  Memory Properties:       
  Features:                AGENT_DISPATCH
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, COARSE GRAINED
      Size:                    31965264(0x1e7c050) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65536(0x10000) KB                  
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    31965264(0x1e7c050) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*** Done ***       
```
### Additional Information

I am running this from a fresh venv with torch installed based on this page: https://github.com/ROCm/TheRock/blob/main/RELEASES.md#installing-pytorch-python-packages
```
python -m pip install --index-url https://d2awnip2yjpvqn.cloudfront.net/v2/gfx1151/ torch
```

**Comment by peturorri** [comment]
I've done some more digging.

This seems to be the same problem as described in #519 - tensors are being allocated in GTT memory instead of VRAM memory. This screenshot from [amdgpu_top](https://github.com/Umio-Yasuno/amdgpu_top) where I allocated a 10GB tensor supports that conclusion:

<img width="1265" height="819" alt="Image" src="https://github.com/user-attachments/assets/276e07f8-d8a2-4597-8105-f7dc8a3c8054" />

To try to work around this, I went and minimized the VRAM allocation in the BIOS to 512MB, leaving the rest to system memory. This results in having approximately half of the memory available as GTT, allowing up to ~61GB for GPU use.

**Comment by peturorri** [comment]
I tried setting the kernel option `amdgpu.gttsize=102400` to get 100 GB available. That looks good on bootup, with dmesg reporting these lines:
```
[    5.223812] [drm] amdgpu: 512M of VRAM memory ready
[    5.223814] [drm] amdgpu: 102400M of GTT memory ready.
```
and `amdgpu_top -d` with these:
```
VRAM              : usage   147 MiB, total   512 MiB (usable   356 MiB)
CPU-Visible VRAM  : usage   147 MiB, total   512 MiB (usable   356 MiB)
GTT               : usage    19 MiB, total 102400 MiB (usable 102380 MiB)
```

However, when I try to allocate memory above ~61GB in torch I get an error similar to before, where it runs out of memory:
```
$ python
Python 3.13.3 (main, Jun 16 2025, 18:15:32) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> x = torch.ones(2**30*80, dtype=torch.int8).to("cuda")
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    x = torch.ones(2**30*80, dtype=torch.int8).to("cuda")
torch.OutOfMemoryError: HIP out of memory. Tried to allocate 80.00 GiB. GPU 0 has a total capacity of 61.35 GiB of which 61.20 GiB is free. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by m0n5t3r** [comment]
I'm wondering if this is caused by some bios setting (I didn't pay much attention to what I did, I only remember changing the VRAM allocation from 64 GB to 96 GB), because this works for me with whatever is installable at the moment from the therock gfx1151 pip index (`2.7.0a0+rocm7.0.0rc20250715`) running in a docker container, with the host running ubuntu 24.04, kernel 6.14, amdgpu-dkms 6.12.12 from the amd repos:

* GTT shows 16 GB, like yours: 
```
VRAM              : usage 28108 MiB, total 98304 MiB (usable 98148 MiB)
CPU-Visible VRAM  : usage 28108 MiB, total 98304 MiB (usable 98148 MiB)
GTT               : usage    36 MiB, total 15864 MiB (usable 15850 MiB)
```
* attempting to allocate 32 GB with your example above gets killed by linux OOM (it seems to be allocated in RAM first?)
 ```
>>> import torch
>>> x = torch.ones(2**30*16, dtype=torch.int8).to("cuda")
>>> x = torch.ones(2**30*32, dtype=torch.int8).to("cuda")
Killed
```
* allocating 20 GB works fine
 ```
>>> import torch
>>> x = torch.ones(2**30*20, dtype=torch.int8).to("cuda")
>>> torch.__version__
'2.7.0a0+rocm7.0.0rc20250715'
```

edit: loading actual models works fine, I've loaded a 70b llama3.1 with ollama at some point to see how ~~fast~~ slow it is 😁

**Comment by fjankovi** [comment]
These Linux kernel changes should fix this:
- https://github.com/torvalds/linux/commit/759e764f7d587283b4e0b01ff930faca64370e59
- https://github.com/torvalds/linux/commit/8b0d068e7dd177eca506d908622095b4a6c9d168

There were added in version 6.15.

**Comment by stellaraccident** [comment]
We got confirmation on #894 (a dup of this one) that upgrading to 6.16 fixes the issue. Marking this one as a dup and will close that one.
