### ISSUE TITLE
[Windows] PyTorch import errors from torch.distributed (e.g. running ComfyUI)

### ISSUE THREAD

**Issue by ScottTodd** [ROCm/TheRock#1202]
> [!IMPORTANT]
> SUMMARY:
> 
> If you see
>
> ```
> ModuleNotFoundError: No module named 'torch._C._distributed_c10d'; 'torch._C' is not a package
> ````
>
> This is due to `import torch.distributed.tensor` failing but being called by the `transformers` package even if `if torch.distributed.is_available()` returns false. A fix has been merged but is not yet included in a stable release of that package: https://github.com/huggingface/transformers/commit/a5fac1c394eafb07312519fcef48ffe8f1a247dc.
>
> The workarounds are _either_
> * For Python < 3.13, install the last working version of `transformers`:
>     ```
>     pip install transformers==4.41.2
>     ```
> * For any Python version, install the latest source which includes a fix:
>     ```
>     pip install git+https://github.com/huggingface/transformers
>     ```

---

Forking from https://github.com/ROCm/TheRock/issues/910#issuecomment-3156199454.

Setup:

```bash
(3.13.venv) λ python -m pip install --index-url https://d2awnip2yjpvqn.cloudfront.net/v2/gfx110X-dgpu/ torch torchvision torchaudio
...
(3.13.venv) λ pip freeze
filelock==3.18.0
fsspec==2025.5.1
Jinja2==3.1.6
MarkupSafe==3.0.2
mpmath==1.3.0
networkx==3.5
numpy==2.3.1
pillow==11.3.0
rocm==7.0.0rc20250805
rocm-sdk-core==7.0.0rc20250805
rocm-sdk-libraries-gfx110X-dgpu==7.0.0rc20250805
setuptools==80.9.0
sympy==1.14.0
torch==2.9.0a0+rocm7.0.0rc20250805
torchaudio==2.8.0a0+rocm7.0.0rc20250805
torchvision==0.24.0a0+rocm7.0.0rc20250805
typing_extensions==4.14.1
```

Then trying to `import torch.distributed.tensor` fails:
```bash
(3.13.venv) λ python
Python 3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch.distributed.tensor
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import torch.distributed.tensor
  File "D:\scratch\therock\3.13.venv\Lib\site-packages\torch\distributed\tensor\__init__.py", line 4, in <module>
    import torch.distributed.tensor._ops  # force import all built-in dtensor ops
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\scratch\therock\3.13.venv\Lib\site-packages\torch\distributed\tensor\_ops\__init__.py", line 2, in <module>
    from ._conv_ops import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\scratch\therock\3.13.venv\Lib\site-packages\torch\distributed\tensor\_ops\_conv_ops.py", line 5, in <module>
    from torch.distributed.tensor._dtensor_spec import DTensorSpec, TensorMeta
  File "D:\scratch\therock\3.13.venv\Lib\site-packages\torch\distributed\tensor\_dtensor_spec.py", line 6, in <module>
    from torch.distributed.tensor.placement_types import (
    ...<4 lines>...
    )
  File "D:\scratch\therock\3.13.venv\Lib\site-packages\torch\distributed\tensor\placement_types.py", line 8, in <module>
    import torch.distributed._functional_collectives as funcol
  File "D:\scratch\therock\3.13.venv\Lib\site-packages\torch\distributed\_functional_collectives.py", line 9, in <module>
    import torch.distributed.distributed_c10d as c10d
  File "D:\scratch\therock\3.13.venv\Lib\site-packages\torch\distributed\distributed_c10d.py", line 23, in <module>
    from torch._C._distributed_c10d import (
    ...<22 lines>...
    )
ModuleNotFoundError: No module named 'torch._C._distributed_c10d'; 'torch._C' is not a package
```

Users report that https://github.com/comfyanonymous/ComfyUI triggers this code path on launch.

---

Copying one of my comments from https://github.com/ROCm/TheRock/issues/1179:

> I would not expect distributed APIs to work until we somehow enable GLOO (the collective communications library used by PyTorch: https://github.com/pytorch/gloo) on Windows:
> 
> https://github.com/ROCm/TheRock/blob/7615bf9fe01815bf0bc3591f9eb859c169f5e9e8/external-builds/pytorch/build_prod_wheels.py#L371-L373
> 
> For that, we would need RCCL (the ROCm Communication Collectives Library), which is currently unsupported on Windows: https://github.com/ROCm/TheRock/blob/main/docs/development/windows_support.md#supported-subprojects
> 
> Maybe we can improve the error message there and note this as a known feature gap until then.

Taking that a step further, maybe we can help this degrade gracefully instead of failing?

**Comment by subunder** [comment]
On a system that's failing like this while running ComfyUI, does any alternative like SD.Next behave the same? Has anyone tried?

**Comment by CS1o** [comment]
Tried to install torch 2.7.0 and 2.9.0 on [Automatic1111 Stable-Diffusion-Webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui)
Venv with Python 3.11.9 64bit and gfx110X-dgpu
Boath get the below error when i try to launch the webui-user.bat afterwards:


```
HIP Library Path: D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\_rocm_sdk_core\bin\amdhip64_7.dll
Traceback (most recent call last):
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\transformers\utils\import_utils.py", line 1086, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\webyo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 27, in <module>
    from ...modeling_utils import PreTrainedModel
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\transformers\modeling_utils.py", line 85, in <module>
    from accelerate import __version__ as accelerate_version
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\accelerate\utils\__init__.py", line 132, in <module>
    from .fsdp_utils import load_fsdp_model, load_fsdp_optimizer, save_fsdp_model, save_fsdp_optimizer
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\accelerate\utils\fsdp_utils.py", line 24, in <module>
    import torch.distributed.checkpoint as dist_cp
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\torch\distributed\checkpoint\__init__.py", line 3, in <module>
    from .default_planner import DefaultLoadPlanner, DefaultSavePlanner
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\torch\distributed\checkpoint\default_planner.py", line 13, in <module>
    from torch.distributed._shard._utils import narrow_tensor_by_index
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\torch\distributed\_shard\__init__.py", line 1, in <module>
    from .api import _shard_tensor, load_with_process_group, shard_module, shard_parameter
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\torch\distributed\_shard\api.py", line 8, in <module>
    from torch.distributed import distributed_c10d
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\torch\distributed\distributed_c10d.py", line 23, in <module>
    from torch._C._distributed_c10d import (
ModuleNotFoundError: No module named 'torch._C._distributed_c10d'; 'torch._C' is not a package

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\launch.py", line 44, in main
    start()
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\modules\launch_utils.py", line 465, in start
    import webui
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\webui.py", line 13, in <module>
    initialize.imports()
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\modules\initialize.py", line 26, in imports
    from modules import paths, timer, import_hook, errors  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\modules\paths.py", line 60, in <module>
    import sgm  # noqa: F401
    ^^^^^^^^^^
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\repositories\generative-models\sgm\__init__.py", line 1, in <module>
    from .models import AutoencodingEngine, DiffusionEngine
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\repositories\generative-models\sgm\models\__init__.py", line 1, in <module>
    from .autoencoder import AutoencodingEngine
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\repositories\generative-models\sgm\models\autoencoder.py", line 12, in <module>
    from ..modules.diffusionmodules.model import Decoder, Encoder
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\repositories\generative-models\sgm\modules\__init__.py", line 1, in <module>
    from .encoders.modules import GeneralConditioner
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\repositories\generative-models\sgm\modules\encoders\modules.py", line 13, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\transformers\utils\import_utils.py", line 1077, in __getattr__
    value = getattr(module, name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\transformers\utils\import_utils.py", line 1076, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programme\AI-Zeug\stable-diffusion-webui\venv\Lib\site-packages\transformers\utils\import_utils.py", line 1088, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
No module named 'torch._C._distributed_c10d'; 'torch._C' is not a package
```

So it currently only works with the .whl files from [here](https://github.com/scottt/rocm-TheRock/releases/tag/v6.5.0rc-pytorch-gfx110x).

**Comment by subunder** [comment]
> 
> So it currently only works with the .whl files from [here](https://github.com/scottt/rocm-TheRock/releases/tag/v6.5.0rc-pytorch-gfx110x).

I see. But @scottt's wheels don't work at all with my gpu, the gfx1200. So all I can do is look forward to @ScottTodd solving this issue.

**Comment by albinose** [comment]
Interestingly, i have ComfyUI working with torch builds for 05.08, win10, python 3.12, rx 9070xt (gfx1201) 
Can provide additional info if needed.
```
(venv) PS C:\ai-shit\ComfyUI> pip freeze
...
rocm==7.0.0rc20250805
rocm-sdk-core==7.0.0rc20250805
rocm-sdk-devel==7.0.0rc20250714
rocm-sdk-libraries-gfx120X-all==7.0.0rc20250805
...
torch==2.9.0a0+rocm7.0.0rc20250805
torchaudio==2.8.0a0+rocm7.0.0rc20250805
...
torchvision==0.24.0a0+rocm7.0.0rc20250805
```

```
(venv) PS C:\ai-shit\ComfyUI> python .\main.py --use-pytorch-cross-attention --fp16-vae --reserve-vram 1
Checkpoint files will always be loaded safely.
HIP Library Path: C:\ai-shit\ComfyUI\venv\Lib\site-packages\_rocm_sdk_core\bin\amdhip64_7.dll
Total VRAM 16304 MB, total RAM 65111 MB
pytorch version: 2.9.0a0+rocm7.0.0rc20250805
AMD arch: gfx1201
ROCm version: (7, 0)
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 9070 XT : native
Using pytorch attention
Python version: 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
ComfyUI version: 0.3.49
ComfyUI frontend version: 1.24.4
[Prompt Server] web root: C:\ai-shit\ComfyUI\venv\Lib\site-packages\comfyui_frontend_package\static
ComfyUI-GGUF: Allowing full torch compile

Import times for custom nodes:
   0.0 seconds: C:\ai-shit\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\ai-shit\ComfyUI\custom_nodes\ComfyUI-GGUF

Context impl SQLiteImpl.
Will assume non-transactional DDL.
No target revision found.
Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.float16
model weight dtype torch.float16, manual cast: None
model_type EPS
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.float16
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load SDXLClipModel
loaded completely 14309.8 1560.802734375 True
C:\ai-shit\ComfyUI\comfy\ldm\modules\attention.py:451: UserWarning: 1Torch was not compiled with memory efficient attention. (Triggered internally at B:\src\torch\aten\src\ATen\native\transformers\hip\sdp_utils.cpp:726.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
Requested to load SDXL
loaded completely 12620.55830078125 4897.0483474731445 True
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:11<00:00,  2.51it/s]
Requested to load AutoencoderKL
loaded completely 4068.0078125 159.55708122253418 True
Prompt executed in 15.17 seconds
```

**Comment by subunder** [comment]
2.51it/s? Now that's something. Can you tell your parameters? So which model are you using and so on
Idk how is this performance possible without any attention optimization, even Scott got way more s/it on his powerful dev systems. But this differs by the model used and other parameters so

**Comment by earthdmitriy** [comment]
@albinose is it default "galaxy bottle" workflow?
size 512x512
sampler 20 steps 
model v1-5-pruned-emaonly-fp16.safetsnsors
?

If yes - you have very slow speed.
With these wheels https://github.com/scottt/rocm-TheRock/releases/tag/v6.5.0rc-pytorch-gfx110x
I have following results:

```
Requested to load BaseModel
loaded completely 14584.29951171875 1639.406135559082 True
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]FETCH ComfyRegistry Data: 75/93
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 10.16it/s]
Requested to load AutoencoderKL
loaded completely 14180.9365234375 159.55708122253418 True
Prompt executed in 9.69 seconds
got prompt
Requested to load BaseModel
loaded completely 14450.73603515625 1639.406135559082 True
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 16.51it/s]
Requested to load AutoencoderKL
loaded completely 14180.9365234375 159.55708122253418 True
Prompt executed in 2.49 seconds

```
Cold run (with time to load model into VRAM) - 9.69s
Hot run (model is in VRAM already) - 2.49s

**Comment by subunder** [comment]
@earthdmitriy Those wheels aren't "official" and will never get any updates. But they include aotriton, so they're much faster than the wheels produced nightly by the CI. Aotriton is currently being integrated into the official wheels, so we just need to wait.

**Comment by earthdmitriy** [comment]
@Nem404 where did you find that these wheels include triton? They're not. Compiling models and sage attention are not available with them. I've tried to compile WAN models, but got errors saying
```
WanVideoSampler
type object 'triton' has no attribute 'runtime'
```

**Comment by pat58151** [comment]
Got the same problem on my gfx1200 setup but with transformers.
Here is the setup.

```
(.venv) PS C:\Users\User\TheRock> python -m pip install --index-url https://d2awnip2yjpvqn.cloudfront.net/v2/gfx120X-all/ torch
(.venv) PS C:\Users\User\TheRock> pip install numpy
(.venv) PS C:\Users\User\TheRock> pip install transformers pillow
(.venv) PS C:\Users\User\TheRock> pip freeze
certifi==2025.8.3
charset-normalizer==3.4.2
colorama==0.4.6
filelock==3.18.0
fsspec==2025.5.1
huggingface-hub==0.34.3
idna==3.10
Jinja2==3.1.6
MarkupSafe==3.0.2
mpmath==1.3.0
networkx==3.5
numpy==2.3.2
packaging==25.0
pillow==11.3.0
PyYAML==6.0.2
regex==2025.7.34
requests==2.32.4
rocm==7.0.0rc20250807
rocm-sdk-core==7.0.0rc20250807
rocm-sdk-libraries-gfx120X-all==7.0.0rc20250807
safetensors==0.6.1
setuptools==80.9.0
sympy==1.14.0
tokenizers==0.21.4
torch==2.9.0a0+rocm7.0.0rc20250807
tqdm==4.67.1
transformers==4.55.0
typing_extensions==4.14.1
urllib3==2.5.0
```

Got this problem.

```
C:\Users\User\TheRock\.venv\Scripts\python.exe C:\Users\User\TheRock\.venv\medgemma.py 
Traceback (most recent call last):
  File "C:\Users\User\TheRock\.venv\medgemma.py", line 1, in <module>
    from transformers import pipeline
  File "C:\Users\User\TheRock\.venv\Lib\site-packages\transformers\__init__.py", line 27, in <module>
    from . import dependency_versions_check
  File "C:\Users\User\TheRock\.venv\Lib\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\User\TheRock\.venv\Lib\site-packages\transformers\utils\__init__.py", line 24, in <module>
    from .auto_docstring import (
    ...<10 lines>...
    )
  File "C:\Users\User\TheRock\.venv\Lib\site-packages\transformers\utils\auto_docstring.py", line 30, in <module>
    from .generic import ModelOutput
  File "C:\Users\User\TheRock\.venv\Lib\site-packages\transformers\utils\generic.py", line 55, in <module>
    from ..model_debugging_utils import model_addition_debugger_context
  File "C:\Users\User\TheRock\.venv\Lib\site-packages\transformers\model_debugging_utils.py", line 29, in <module>
    import torch.distributed.tensor
  File "C:\Users\User\TheRock\.venv\Lib\site-packages\torch\distributed\tensor\__init__.py", line 4, in <module>
    import torch.distributed.tensor._ops  # force import all built-in dtensor ops
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\TheRock\.venv\Lib\site-packages\torch\distributed\tensor\_ops\__init__.py", line 2, in <module>
    from ._conv_ops import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\TheRock\.venv\Lib\site-packages\torch\distributed\tensor\_ops\_conv_ops.py", line 5, in <module>
    from torch.distributed.tensor._dtensor_spec import DTensorSpec, TensorMeta
  File "C:\Users\User\TheRock\.venv\Lib\site-packages\torch\distributed\tensor\_dtensor_spec.py", line 6, in <module>
    from torch.distributed.tensor.placement_types import (
    ...<4 lines>...
    )
  File "C:\Users\User\TheRock\.venv\Lib\site-packages\torch\distributed\tensor\placement_types.py", line 8, in <module>
    import torch.distributed._functional_collectives as funcol
  File "C:\Users\User\TheRock\.venv\Lib\site-packages\torch\distributed\_functional_collectives.py", line 9, in <module>
    import torch.distributed.distributed_c10d as c10d
  File "C:\Users\User\TheRock\.venv\Lib\site-packages\torch\distributed\distributed_c10d.py", line 23, in <module>
    from torch._C._distributed_c10d import (
    ...<22 lines>...
    )
ModuleNotFoundError: No module named 'torch._C._distributed_c10d'; 'torch._C' is not a package
```
Hope this helps in pinpointing the problem.

**Comment by subunder** [comment]
> [@Nem404](https://github.com/Nem404) where did you find that these wheels include triton? They're not. Compiling models and sage attention are not available with them. I've tried to compile WAN models, but got errors saying
> 
> ```
> WanVideoSampler
> type object 'triton' has no attribute 'runtime'
> ```

@scottt and @jammm's "old" wheels include aotriton. This is a fact. That's why those wheels offer way better performance.


https://github.com/ROCm/TheRock/discussions/655
> Features and Known Problems
>
> - torch.nn.functional.scaled_dot_product_attention backed by aotriton 0.9.2
> -  - No need to set any environment variables
> - The Linux wheel is bigger than it should be due to symlink becoming duplicated files and inclusion of unnecessary files

**Comment by subunder** [comment]
But @ScottTodd successfully generated images with ComfyUI during his testing using the `gfx1151` torch:
https://gist.github.com/ScottTodd/f7c72202a3e160baffd715d006238d4a

Also with the `gfx110X-dgpu` torch:
https://gist.github.com/ScottTodd/8c3d2d707b4fb7850fd60e3f8e51cd09

I don't understand why some people don't get this `torch.distributed` error, while others (including me) do, with the exact same version of torch.

**Comment by jammm** [comment]
Ah I forgot to mention how I got torch.distributed import working. IIRC I had enabled libuv and then set USE_DISTRIBUTED=ON. 

* Applied this pytorch patch https://github.com/jammm/TheRock/blob/jam/gfx1151-win/external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0014-ROCm-Windows-Fixes-for-USE_DISTRIBUTED-ON-on-Windows.patch and gloo patch https://github.com/jammm/TheRock/blob/jam/gfx1151-win/external-builds/pytorch/patches/pytorch/v2.7.0/third_party/gloo/0001-ROCm-gloo-windows-specific-fixes.patch
* Build libuv and set libuv_ROOT https://github.com/pytorch/pytorch/blob/main/CMakeLists.txt#L422
* Build pytorch with USE_DISTRIBUTED=ON. Maybe also with USE_GLOO=ON but I don't remember if that was enabled it or not.

**Comment by subunder** [comment]
Can't the CI build torch with this `libuv` and `USE_DISTRIBUTED=ON` so we can use things like ComfyUI out of the box?

**Comment by subunder** [comment]
Also, how come some ppl dont get this error at all?

**Comment by jammm** [comment]
> Also, how come some ppl dont get this error at all?

My old wheel was manually built in an older branch that was never merged as it was for pytorch 2.7.0 and we are focusing on pytorch main for the time being. We're working on getting some changes upstreamed to pytorch that should let us build with USE_DISTRIBUTED=ON

**Comment by leovanalphen** [comment]
@Nem404 The issue lies in the transformers package:

> 
The error comes from Transformers 4.42 now automatically importing torch.distributed.tensor, which causes it to fail on Windows if USE_DISTRIBUTED=0 is set (either by default or due to the wheel being compiled without distributed support). 

I downgraded transformers to pre-4.42 and the error went away.

**Comment by subunder** [comment]
Manually downgrading transformers after `pip install -r .\ComfyUI\requirements.txt`? This actually works?

**Comment by leovanalphen** [comment]
For me it did, see before and after logs:

```
> Checkpoint files will always be loaded safely.
> HIP Library Path: C:\Users\Leo\source\venv\therock\Lib\site-packages\_rocm_sdk_core\bin\amdhip64_7.dll
> Total VRAM 16304 MB, total RAM 32693 MB
> pytorch version: 2.9.0a0+rocm7.0.0rc20250805
> AMD arch: gfx1201
> ROCm version: (7, 0)
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 AMD Radeon RX 9070 XT : native
> Using pytorch attention
> Traceback (most recent call last):
>   File "C:\Users\Leo\source\therock\ComfyUI\main.py", line 147, in <module>
>     import execution
>   File "C:\Users\Leo\source\therock\ComfyUI\execution.py", line 16, in <module>
>     import nodes
>   File "C:\Users\Leo\source\therock\ComfyUI\nodes.py", line 24, in <module>
>     import comfy.diffusers_load
>   File "C:\Users\Leo\source\therock\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
>     import comfy.sd
>   File "C:\Users\Leo\source\therock\ComfyUI\comfy\sd.py", line 29, in <module>
>     from . import model_detection
>   File "C:\Users\Leo\source\therock\ComfyUI\comfy\model_detection.py", line 2, in <module>
>     import comfy.supported_models
>   File "C:\Users\Leo\source\therock\ComfyUI\comfy\supported_models.py", line 5, in <module>
>     from . import sd1_clip
>   File "C:\Users\Leo\source\therock\ComfyUI\comfy\sd1_clip.py", line 3, in <module>
>     from transformers import CLIPTokenizer
>   File "C:\Users\Leo\source\venv\therock\Lib\site-packages\transformers\__init__.py", line 27, in <module>
>     from . import dependency_versions_check
>   File "C:\Users\Leo\source\venv\therock\Lib\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
>     from .utils.versions import require_version, require_version_core
>   File "C:\Users\Leo\source\venv\therock\Lib\site-packages\transformers\utils\__init__.py", line 24, in <module>
>     from .auto_docstring import (
>   File "C:\Users\Leo\source\venv\therock\Lib\site-packages\transformers\utils\auto_docstring.py", line 30, in <module>
>     from .generic import ModelOutput
>   File "C:\Users\Leo\source\venv\therock\Lib\site-packages\transformers\utils\generic.py", line 55, in <module>
>     from ..model_debugging_utils import model_addition_debugger_context
>   File "C:\Users\Leo\source\venv\therock\Lib\site-packages\transformers\model_debugging_utils.py", line 29, in <module>
>     import torch.distributed.tensor
>   File "C:\Users\Leo\source\venv\therock\Lib\site-packages\torch\distributed\tensor\__init__.py", line 4, in <module>
>     import torch.distributed.tensor._ops  # force import all built-in dtensor ops
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Leo\source\venv\therock\Lib\site-packages\torch\distributed\tensor\_ops\__init__.py", line 2, in <module>
>     from ._conv_ops import *  # noqa: F403
>     ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Leo\source\venv\therock\Lib\site-packages\torch\distributed\tensor\_ops\_conv_ops.py", line 5, in <module>
>     from torch.distributed.tensor._dtensor_spec import DTensorSpec, TensorMeta
>   File "C:\Users\Leo\source\venv\therock\Lib\site-packages\torch\distributed\tensor\_dtensor_spec.py", line 6, in <module>
>     from torch.distributed.tensor.placement_types import (
>   File "C:\Users\Leo\source\venv\therock\Lib\site-packages\torch\distributed\tensor\placement_types.py", line 8, in <module>
>     import torch.distributed._functional_collectives as funcol
>   File "C:\Users\Leo\source\venv\therock\Lib\site-packages\torch\distributed\_functional_collectives.py", line 9, in <module>
>     import torch.distributed.distributed_c10d as c10d
>   File "C:\Users\Leo\source\venv\therock\Lib\site-packages\torch\distributed\distributed_c10d.py", line 23, in <module>
>     from torch._C._distributed_c10d import (
> ModuleNotFoundError: No module named 'torch._C._distributed_c10d'; 'torch._C' is not a package
> (therock) PS C:\Users\Leo\source\therock\ComfyUI> uv pip install transformers==4.40
> Using Python 3.12.10 environment at: C:\Users\Leo\source\venv\therock
> Resolved 18 packages in 256ms
> Prepared 2 packages in 1.36s
> Uninstalled 2 packages in 509ms
> Installed 2 packages in 512ms
>  - tokenizers==0.21.4
>  + tokenizers==0.19.1
>  - transformers==4.55.0
>  + transformers==4.40.0
> (therock) PS C:\Users\Leo\source\therock\ComfyUI> python main.py
> [START] Security scan
> [DONE] Security scan
> ## ComfyUI-Manager: installing dependencies done.
> ** ComfyUI startup time: 2025-08-07 21:08:02.069
> ** Platform: Windows
> ** Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
> ** Python executable: C:\Users\Leo\source\venv\therock\Scripts\python.exe
> ** ComfyUI Path: C:\Users\Leo\source\therock\ComfyUI
> ** ComfyUI Base Folder Path: C:\Users\Leo\source\therock\ComfyUI
> ** User directory: C:\Users\Leo\source\therock\ComfyUI\user
> ** ComfyUI-Manager config path: C:\Users\Leo\source\therock\ComfyUI\user\default\ComfyUI-Manager\config.ini
> ** Log path: C:\Users\Leo\source\therock\ComfyUI\user\comfyui.log
> 
> Prestartup times for custom nodes:
>    2.2 seconds: C:\Users\Leo\source\therock\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Checkpoint files will always be loaded safely.
> HIP Library Path: C:\Users\Leo\source\venv\therock\Lib\site-packages\_rocm_sdk_core\bin\amdhip64_7.dll
> Total VRAM 16304 MB, total RAM 32693 MB
> pytorch version: 2.9.0a0+rocm7.0.0rc20250805
> AMD arch: gfx1201
> ROCm version: (7, 0)
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 AMD Radeon RX 9070 XT : native
> Using pytorch attention
> Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
> ComfyUI version: 0.3.49
> ComfyUI frontend version: 1.24.4
> [Prompt Server] web root: C:\Users\Leo\source\venv\therock\Lib\site-packages\comfyui_frontend_package\static
> ### Loading: ComfyUI-Manager (V3.35)
> [ComfyUI-Manager] network_mode: public
> ### ComfyUI Version: v0.3.49-6-g05df2df4 | Released on '2025-08-07'
> 
> Import times for custom nodes:
>    0.0 seconds: C:\Users\Leo\source\therock\ComfyUI\custom_nodes\websocket_image_save.py
>    0.5 seconds: C:\Users\Leo\source\therock\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
> Context impl SQLiteImpl.
> Will assume non-transactional DDL.
> No target revision found.
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188
> FETCH ComfyRegistry Data: 5/93
```

**Comment by subunder** [comment]
just tried:
`pip uninstall transformers`
then
`pip install transformers==4.41.2`
and it's no longer throwing the error.
Thx @leovanalphen

**Comment by subunder** [comment]
Now it runs. Got this error at the VAE stage:
`MIOpen(HIP): Error [EvaluateInvokers] C:/home/runner/_work/TheRock/TheRock/ml-libs/MIOpen/src/conv/solver_finders.cpp:303: Invalid elapsed time detected in EvaluateInvokers, failed condition: elapsed <= 0`
It doesn’t crash though, still finishes and outputs a "normal-looking" image.

**Comment by 0xDELUXA** [comment]
Eyy, cant believe @jammm already forked gloo and made a PR over there: https://github.com/pytorch/gloo/pull/461
Lightning-fast work.

**Comment by 0xDELUXA** [comment]
Idk how, but I'm getting better performance - like 2x or more - compared to my WSL2 setup, using the same parameters and everything. Right now, even without aotriton. 
Over on WSL2, I was using the AMD-recommended wheels (6.4.2): torch, torchvision, torchaudio, and that pytorch-triton-rocm wheel.

This is based on my quick personal testing. Your mileage may warry.

**Comment by leovanalphen** [comment]
> Idk how, but I'm getting better performance - like 2x or more - compared to my WSL2 setup, using the same parameters and everything. Right now, even without aotriton. Over on WSL2, I was using the AMD-recommended wheels (6.4.2): torch, torchvision, torchaudio, and that pytorch-triton-rocm wheel.
> 
> This is based on my quick personal testing. Your mileage may warry.

Huh, Was writing a reply to say earlier this evening when I tested I got around ~1,5it/s when generating an SDXL 512x512. Just restarted Comfyui because i couldn't precisely remember the number, just ran it again and I suddenly see ~7.5it/s:

``got prompt
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  7.45it/s]
Prompt executed in 12.54 seconds

The only reason it still takes 12.5 seconds because I started Comfy with --cpu-vae, without it either my PC crashes or Comfyui crashes, I can try --fp16-vae but have to grab an updated VAE model otherwise I get black images.

edit:

1024x1024 gives me 3.5it/s. 
got prompt
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [01:09<00:00,  3.48s/it]

That is comparable perf. to my 7800xt running rocm7beta under linux, but that install has working triton, flash attention, toch compile and tuned miopen. Curious what we will see with these working under Windows.

**Comment by subunder** [comment]
I also needed to use tiled vae. Without it, no no
Also  `--reserve-vram 0.9` and `--fp16-vae`

Other things to try:
```
set PYTORCH_TUNABLEOP_ENABLED=1
set PYTORCH_TUNABLEOP_VERBOSE=1
set PYTORCH_HIP_ALLOC_CONF=expandable_segments:True
set PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.80,max_split_size_mb:512
```
If someone wants to experiment

**Comment by earthdmitriy** [comment]
UPD
I've managed to run comfyui after downgrading transformers

IMPORTANT!!!
transformers==4.41.2 
won't work on python 3.13, I'd need to downgrade it on my system to 3.12

Performance after warmup (512x512 default workflow):

```
Requested to load BaseModel
loaded completely 14266.04853515625 1639.406135559082 True
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 12.25it/s]
Requested to load AutoencoderKL
loaded completely 13996.2490234375 159.55708122253418 True
Prompt executed in 2.68 seconds
```

**Comment by subunder** [comment]
> 
> IMPORTANT!!! transformers==4.41.2 won't work on python 3.13, I'd need to downgrade it on my system to 3.12
> 
Yes, forgot to mention I was using python 3.12

**Comment by RSabbagh52** [comment]
@Nem404 
Thank You! I was having the same issue with gfx1151. Downgrading transforms did the trick. fyi running python 3.11. SOOO much better than using directml

**Comment by 0xDELUXA** [comment]
In my case, I was getting around 1 it/s with WSL, and now, using native PyTorch ROCm on Windows, I'm getting around 1.8 it/s in my daily workflow. I thought it would be slower without AOTriton, but it's quite impressive already. And it will only get better.

AMD really made a smart move by enabling native PyTorch support on Windows using ROCm, and embracing open source as a whole.

together we advance_

**Comment by subunder** [comment]
> [@Nem404](https://github.com/Nem404) Thank You! I was having the same issue with gfx1151. Downgrading transforms did the trick. fyi running python 3.11. SOOO much better than using directml

Np, but actually it was @leovanalphen who came up with this "workaround".

**Comment by RSabbagh52** [comment]
@leovanalphen 
Thank you very much! first time running on rocm!

**Comment by subunder** [comment]
> [@leovanalphen](https://github.com/leovanalphen) Thank you very much! first time running on rocm!

In my opinion DirectML is not just slow for this type of workload, it also fills up even if you have 128 GB of VRAM within the 1st second, and crashes due to out-of-memory errors. But why? It's a great thing we don't need to use it at all. Long live ROCm!

**Comment by earthdmitriy** [comment]
A few more tests of comfyui with different command line args

Benchmark -default "galaxy bottle" workflow, image size - 512x512, batch size - 5. After warmup (first run doesn't count).

Why not 1 image in batch? It's very fast and measure is noisy.
Why not 1024x1024? Current version of wheels have weird memory issue - sampler use all VRAM and additionally 16GB of shared GPU memory. In this case PCE-e bandwidth becomes the bottleneck and measure make no sense.

Default settings (with --use-pytorch-cross-attention):
`
2.80it/s
Prompt executed in 12.16 seconds
`

--bf16-unet --bf16-vae (scottt and jammm wheels worked best with these args)
`
 2.79it/s
Prompt executed in 7.98 seconds
`
Sampler performance is same, but VAE decode is lightning-fast

--fp16-vae
VAE decode fails

**Comment by subunder** [comment]
Every benchmark is welcome so other users know how they can use the wheels most efficiently

**Comment by subunder** [comment]
@earthdmitriy did you try `set PYTORCH_TUNABLEOP_ENABLED=1`? Does it do anything, apart from that very slow initial run?

**Comment by earthdmitriy** [comment]
`set PYTORCH_TUNABLEOP_ENABLED=1` definitely have some effect - at first run GPU load was 100% for ~7 minutes while sampling itself was not started. Same for VAE - here was additional phase for "tuning".

Next runs:
```
2.88it/s
Prompt executed in 8.58 seconds
```
Sampler performance is a little bit better.

**Comment by albinose** [comment]
Some benches on rx 9070xt, with light UV
I still use builds for 05.08, python 3.12, with transformers 4.52.3

with SDXL, 832x1216 (about 1 MP), 28 steps, single image averaged from several runs:

--use-pytorch-cross-attention - ~2.75 it/s;
--use-split-cross-attention - ~3.25 it/s;
--use-quad-cross-attention - ~3.55 it/s (comfy defaults to this);
--bf16-unet is a tiny bit slower (like 0.05 it/s);

MIOPEN_FIND_MODE = "FAST" seems to help with responsiveness, especially on VAE decode, and less OOMs

TUNABLEOP gives about 0.1 it/s speedup, not so worth it

TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL = "1" seems to do nothing now (same speed with all attn optimisations)

Flux kontext, 1024x1024 - ~3.7 s/it first gen, 12.2 s/it on second and too long to wait on third try (so unironically faster to restart for each gen)

Scottt's torch 2.7 builds from may was 1.8 to 2.2 it/s on same setting for sdxl, and died on flux, so we surely got some progress!

**Comment by subunder** [comment]
@albinose `TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1` only has any effect if torch was built with aotriton, and as of now the wheels don't include it. But the devs are working on it rn

**Comment by subunder** [comment]
> edit:
> 
> 1024x1024 gives me 3.5it/s. got prompt 100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [01:09<00:00, 3.48s/it]

@leovanalphen I'm not trying to nitpick here, but 3.5 it/s and 3.5 s/it aren't nearly the same. Np, just a typo, but you should correct it in my op

**Comment by CS1o** [comment]
The transformers downgrade fix didnt worked for Auto1111.
But I got ReForge to work with the latest torch and rocm packages installed.
I still get the `No module named 'torch._C._distributed_c10d'; 'torch._C' is not a package` in ReForge but it still launches (not like Auto1111)

**GPU: 7900XTX OC/UV/ VRAM OC PL+15**
Image settings:
Model: Illustrious Plantmilk Walnut
Resolution: 832x1216
Sampling Steps: 30, Euler a
SDXL_FP16_VAE used.

**ReForge** with Python 3.11.9 and launch args: `--skip-python-version-check --update-all-extensions --cuda-stream`
Speed: 3.00 it/s
With `set PYTORCH_TUNABLEOP_ENABLED=1` getting crazy coil whine until the image gen starts.
Speed: 3.33 it/s
Hires Fix and Adetailer freezing the PC and crashing the GPU Driver no matter what.

Scotts 2.7.0 wheels didnt had any issues with hires fix or adetailer in auto1111, forge and reforge.
Speed with these on Reforge: 3.94 it/s

Installed **ComfyUI** Portable zip version freshly. Changed to the latest Pytorch and ROCm whls. No error and no transformers downgrade needed with that.
Comes with Python 3.12
Tiled Vae Decode needed.
Speed / Launch Args:
3.03 it/s --reserve-vram 0.5 --vae-fp16 (used pytorch attention by default)
3.44 it/s --use-split-cross-attention
3.75 it/s --use-quad-cross-attention

**Comment by subunder** [comment]
> Scotts 2.7.0 wheels didnt have any issues with hires fix or adetailer in auto1111, forge and reforge.

Because those had attention optimization (aotriton), while the new wheels don’t have any, yet.

**Comment by ScottTodd** [comment]
aotriton is coming soon - https://github.com/ROCm/TheRock/pull/1207 is getting close and I was able to reproduce the build on my local machine (after some trouble with unusual characters in file names confusing ccache, as well as numpy issues...)

I did run into these `torch.distributed` issues in my testing on Python 3.13, and I couldn't downgrade `transformers` due to https://github.com/huggingface/tokenizers/issues/1639 🫠

Well, good progress anyways, and thanks for all the debugging + notes here. I think I see the path forward but we'll have a few more things to grind through.

**Comment by 0xDELUXA** [comment]
@ScottTodd making this kind of announcement here for us is really promising. We’re eager to see any progress towards aotriton support on Windows next week and beyond.

P.S.: We also have devs like @jammm who work even on weekends to ensure we get aotriton Windows support asap: https://github.com/ROCm/TheRock/pull/1207. Really appreciate it 🚀

**Comment by 0xDELUXA** [comment]
What about this one: https://github.com/huggingface/transformers/pull/40038

**Comment by ScottTodd** [comment]
Oh, that will help too, thanks @m-gallus ! Maybe we can call this fixed once that makes its way into a release.

**Comment by 0xDELUXA** [comment]
Seems like `pip install git+https://github.com/huggingface/transformers` solves this issue now, because it installs transformers version 4.56.0.dev0, which includes https://github.com/huggingface/transformers/pull/40038

**Comment by ScottTodd** [comment]
I'm seeing more reports of this issue. While we wait for the fixes to make their way to stable release packages, I've added a summary and the known workarounds up top.

**Comment by subunder** [comment]
> I'm seeing more reports of this issue. While we wait for the fixes to make their way to stable release packages, I've added a summary and the known workarounds up top.

It should land this week, based on: https://github.com/huggingface/transformers/pull/40038#issuecomment-3220133663

**Comment by RSabbagh52** [comment]
Any idea when we will be able to run video workflows in comfyui on windows, for gfx_1151? Cannot run without hip out of memory errors.
Also, are their nightly builds of the pytorch wheels?

**Comment by subunder** [comment]
Nightly wheels are installed with `python -m pip install --index-url https://d2awnip2yjpvqn.cloudfront.net/v2/gfx1151` and dont include attention optimization yet, apart from the default math, which is kinda primitive. That's why we get OOM errors, it can't utilize the available memory efficiently. Video generation is quite resource-hungry. So we need AOTriton to solve these issues. Look at what AOTrition's dev replied to a case like yours: https://github.com/ROCm/TheRock/issues/1040#issuecomment-3185857980

**Comment by RSabbagh52** [comment]
Thank you for the reply! That url is where I have been going but I wasn't sure if they were stable builds of nightly builds. Ever since I first installed from there about 3 weeks ago, nothing has changed. Each time I do an install it states that I'm up to date. That's why I wasn't sure if they were nightly builds or stable. I'm still trying to figure out how all of the pieces fit together. At some point it would be great to contribute.

**Comment by subunder** [comment]
We have nightly and dev builds, see: https://github.com/ROCm/TheRock/tree/main/external-builds/pytorch#other-ways-to-install-the-rocm-packages
> From therock-nightly-python
> 
> OR from therock-dev-python
> ...

No such thing as "stable"

**Comment by subunder** [comment]
> I'm seeing more reports of this issue. While we wait for the fixes to make their way to stable release packages, I've added a summary and the known workarounds up top.

So we have https://github.com/huggingface/transformers/releases/tag/v4.56.0 now:

> # Bugfixes and improvements:
> * Fix error on importing unavailable torch.distributed by @m-gallus in https://github.com/huggingface/transformers/pull/40038

Yay🚀

**Comment by subunder** [comment]
Can't we close this now?

**Comment by ScottTodd** [comment]
Yes, I think this is resolved now.
