### ISSUE TITLE
[Issue]: [ROCm] Multiple Issues on Ubuntu 24.04 LTS with ComfyUI: Latest Nightly Crashes, Attention Status Question, and Memory Overflow

### ISSUE THREAD

**Issue by mykite** [ROCm/TheRock#1378]
### Problem Description

Hello,

I'm encountering several issues while running ComfyUI with ROCm on Ubuntu 24.04 LTS and would appreciate your help.

**System Environment:**
*   **OS:** Ubuntu 24.04 LTS
*   **GPU:** `[Please add your GPU model here, e.g., AMD Radeon RX 7900 XTX]`
*   **PyTorch (Latest Nightly):** `2.7.1+rocm7.0.0rc20250901`
*   **PyTorch (Working Nightly):** `2.9.0a0+rocm7.0.0rc20250826`
*   **ROCm Version (inferred from PyTorch build):** 7.0 / 7.1

---

### Issue 1: Latest nightly build causes `std::bad_alloc` crash

When I install the latest ROCm nightly build for PyTorch, ComfyUI crashes immediately upon launch with a `std::bad_alloc` error.

**Steps to Reproduce (Installation):**
```bash
python -m pip install \
  --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/ \
  torch torchaudio torchvision
```

**Error Log:**
```log
venv) ubuntu@ubuntu:/media/ubuntu/7C8284B882847882/linux/comfyui-workspace/test/ComfyUI$ python3 main.py 
Checkpoint files will always be loaded safely.
Total VRAM 16304 MB, total RAM 47543 MB
pytorch version: 2.7.1+rocm7.0.0rc20250901
AMD arch: gfx1201
ROCm version: (7, 1)
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon Graphics : native
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```
This error appears related to memory allocation, as discussed in other contexts [here](https://github.com/comfyanonymous/ComfyUI/issues/9604#issuecomment-3248840320).

**Working Solution (Downgrade):**
Downgrading `torch` and `torchaudio` to the **`20250826`** build resolves the crash. This suggests a potential regression in the builds released after this date.

**Functional Downgrade Command:**
```bash
python -m pip install \
  --force-reinstall \
  torch-2.9.0a0+rocm7.0.0rc20250826-cp312-cp312-linux_x86_64.whl \
  torchaudio-2.8.0a0+rocm7.0.0rc20250826-cp312-cp312-linux_x86_64.whl \
  torchvision-0.24.0a0+rocm7.0.0rc20250901-cp312-cp312-linux_x86_64.whl \
  --extra-index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/
```

---

### Issue 2: Discrepancy in reported Attention mechanism status

When using the functional older build, the ComfyUI startup log reports the attention mechanism as `attention_sub_quad`, which typically implies that optimized attention backends (like flash-attention) are not active.

**Log Snippet:**
```log
(venv) kite@kite:/media/kite/7C8284B882847882/linux/test2/ComfyUI$ python3 main.py 
...
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
...
[ComfyUI Attention日志] Attention机制选择为: attention_sub_quad```
**Question:** This is contrary to the expectation that recent ROCm releases should support optimized attention. Could you confirm if a more efficient attention implementation is expected to be enabled by default on the Linux + ROCm platform?

---

### Issue 3: More frequent Out-of-Memory errors on Linux vs. Windows

I have observed that identical workflows in ComfyUI are more prone to VRAM-related errors on Linux than on Windows.

**Typical Error Message:**
```log
HIP error: an illegal memory access was encountered
Search for hipErrorIllegalAddress' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__HIPRT__TYPES.html for more information. HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing AMD_SERIALIZE_KERNEL=3 Compile with TORCH_USE_HIP_DSA` to enable device-side assertions.
```
On Windows, this issue can often be mitigated with launch arguments like `--disable-smart-memory --reserve-vram 8`. These arguments seem less effective on Linux, suggesting that the root cause may be different or that memory management is under more pressure on this platform.

I hope this feedback is helpful for the continued improvement of ROCm. Thank you.

[std::bad_alloc](https://github.com/comfyanonymous/ComfyUI/issues/9604#issuecomment-3248840320)

### Operating System

ubuntu 24.4.3 lts

### CPU

U7 265k

### GPU

9070

### ROCm Version

ROCM 7

**Comment by mykite** [comment]
<img width="1091" height="499" alt="Image" src="https://github.com/user-attachments/assets/e99ef8b1-c380-475b-9549-5878c129c404" />

**Comment by schung-amd** [comment]
Hi @mykite, have you tried the nightly torch 2.9 wheels (e.g. https://rocm.nightlies.amd.com/v2/gfx120X-all/torch-2.9.0a0%2Brocm7.0.0rc20250902-cp312-cp312-linux_x86_64.whl)? Your reproducer shows torch 2.7.1 installed but your previous working version is using 2.9.

**Comment by harakiru** [comment]
I have the same issue with my gfx12, using the 0826 build works however i get constant "Memory access fault by GPU node-1 (Agent handle: 0x55b2c37b58d0) on address 0x7f078fdaa000. Reason: Page not present or supervisor privilege." errors which makes using comfyui impossible. It's also slower than the latest nightly packages from the pytorch website.

OS: arch
kernel: 6.16.4-arch1-1

**Comment by schung-amd** [comment]
@mykite I can repro the bad_alloc, investigating. Regarding the sub-quadratic attention, you can enable this by `TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1 python main.py --use-pytorch-cross-attention` (see https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#amd-rocm-tips). While the docs state that this should be enabled by default, it doesn't appear to be the case for older pytorch wheels and this might be linked to the regression you're observing with the nightly wheels (as it is enabled by default for those).

@harakiru That error is frustratingly generic but usually indicates an OOM issue in my experience. How big is the model you're using?

**Comment by digitaltopo** [comment]
@mykite  & @schung-amd if you uninstall `torchaudio` then the `bad_alloc` goes away.

So if you installed PyTorch from the nightlies:
`python -m pip install --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/  torch torchaudio torchvision`

Uninstall: `pip uninstall torchaudio`

Not sure why, but may help @schung-amd chase down the root of this issue.

For the OOM issue, this happens even with `TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1 python main.py --use-pytorch-cross-attention` and it appears to be quite random, very frustrating. Anecdotally the build from 2005/08/29 seemed to be better (but hard to confirm this).

**Comment by schung-amd** [comment]
As a workaround for now, the nightly torch 2.9.0 wheels don't have the bad_alloc issue; you can install by `pip install torch==2.9.0a0 torchvision==0.24.0a0 torchaudio==2.8.0a0 --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/`. This torch wheel does have the efficient attention enabled by default so you don't have to set the environment variable explicitly. Your previous working configuration is using these versions to begin with, not sure why your system had those but is now pulling in the 2.7.1 wheels.

e: Per @digitaltopo's comment this may be an issue with the `torchaudio` wheel specifically, so if you don't need `torchaudio` you can just uninstall that instead, but if `torchaudio` is needed then the above wheels should work. 

e2: Ok I think I see the problem, the nightly install command is pulling in torch 2.7.1 and torchaudio 2.8.0a0 which I'm not sure are compatible. Downgrading to torchaudio 2.7.1a0 also solves the issue.

**Comment by digitaltopo** [comment]
So looks like https://github.com/pytorch/pytorch/pull/161754 merged, does this make any difference atm?

**Comment by harakiru** [comment]
> pip install torch==2.9.0a0 torchvision==0.24.0a0 torchaudio==2.8.0a0 --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/

The "pip install torch==2.9.0a0 torchvision==0.24.0a0 torchaudio==2.8.0a0 --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/" packages you mentioned "works" however it produces black images 9/10 of the time. It also produces a cudagraphs related error when using the torchCompileVAE node however that might be the custom node im using. So in the end latest nightly packages from pytorch.org are the only ones that can run my specific workflow.

**Comment by mykite** [comment]
> Hi [@mykite](https://github.com/mykite), have you tried the nightly torch 2.9 wheels (e.g. https://rocm.nightlies.amd.com/v2/gfx120X-all/torch-2.9.0a0%2Brocm7.0.0rc20250902-cp312-cp312-linux_x86_64.whl)? Your reproducer shows torch 2.7.1 installed but your previous working version is using 2.9.

I initially used Python - m pip install\
--index-url  https://rocm.nightlies.amd.com/v2/gfx120X-all/  \
torch torchaudio torchvision

But there was an error when it started, it couldn't be used, and then it was downgraded

**Comment by mykite** [comment]
> [@mykite](https://github.com/mykite) I can repro the bad_alloc, investigating. Regarding the sub-quadratic attention, you can enable this by (see https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#amd-rocm-tips). While the docs state that this should be enabled by default, it doesn't appear to be the case for older pytorch wheels and this might be linked to the regression you're observing with the nightly wheels (as it is enabled by default for those).`TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1 python main.py --use-pytorch-cross-attention`
> 
> [@harakiru](https://github.com/harakiru) That error is frustratingly generic but usually indicates an OOM issue in my experience. How big is the model you're using?

Install with Python - m pip
--index-url  https://rocm.nightlies.amd.com/v2/gfx120X-all/
Torch torchauudio torchvision was installed with version 2.90 but encountered an error, or I need to manually download it. Which file are you using? Perhaps I can try it out

**Comment by mykite** [comment]
> As a workaround for now, the nightly torch 2.9.0 wheels don't have the bad_alloc issue; you can install by . This torch wheel does have the efficient attention enabled by default so you don't have to set the environment variable explicitly. Your previous working configuration is using these versions to begin with, not sure why your system had those but is now pulling in the 2.7.1 wheels.`pip install torch==2.9.0a0 torchvision==0.24.0a0 torchaudio==2.8.0a0 --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/`
> 
> e: Per [@digitaltopo](https://github.com/digitaltopo)'s comment this may be an issue with the wheel specifically, so if you don't need you can just uninstall that instead, but if is needed then the above wheels should work.`torchaudio``torchaudio``torchaudio`
> 
> e2: Ok I think I see the problem, the nightly install command is pulling in torch 2.7.1 and torchaudio 2.8.0a0 which I'm not sure are compatible. Downgrading to torchaudio 2.7.1a0 also solves the issue.

I saw pip install torch==2.9.0a0 torchvision==0.24.0a0 torchaudio==2.8.0a0 --index-url  https://rocm.nightlies.amd.com/v2/gfx120X-all/ I will try using this first in the future

**Comment by mykite** [comment]
> [@mykite](https://github.com/mykite) I can repro the bad_alloc, investigating. Regarding the sub-quadratic attention, you can enable this by (see https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#amd-rocm-tips). While the docs state that this should be enabled by default, it doesn't appear to be the case for older pytorch wheels and this might be linked to the regression you're observing with the nightly wheels (as it is enabled by default for those).`TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1 python main.py --use-pytorch-cross-attention`
> 
> [@harakiru](https://github.com/harakiru) That error is frustratingly generic but usually indicates an OOM issue in my experience. How big is the model you're using?

I can run it through -- disable smart memory -- reserve vram 8 on Windows, but adding it on Ubuntu doesn't work

**Comment by mykite** [comment]
> [@mykite](https://github.com/mykite) & [@schung-amd](https://github.com/schung-amd) if you uninstall `torchaudio` then the `bad_alloc` goes away.
> 
> So if you installed PyTorch from the nightlies: `python -m pip install --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/ torch torchaudio torchvision`
> 
> Uninstall: `pip uninstall torchaudio`
> 
> Not sure why, but may help [@schung-amd](https://github.com/schung-amd) chase down the root of this issue.
> 
> For the OOM issue, this happens even with `TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1 python main.py --use-pytorch-cross-attention` and it appears to be quite random, very frustrating. Anecdotally the build from 2005/08/29 seemed to be better (but hard to confirm this).

I can run it through -- disable smart memory -- reserve vram 8 on Windows, but adding it on Ubuntu doesn't work

**Comment by mykite** [comment]
@schung-amd 
I tried using Python pip  install torch==2.9.0a0 torchvision==0.24.0a0 torchaudio==2.8.0a0 --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/
torch torchaudio after torchvision can boot comfyui
But still loaded attention_sub_quad
When I use TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1 python main.py --use-pytorch-cross-attention
Can be recognized correctly, but graphics/memory overflow faster, I'm sure there's no problem on windows 11
So I'm currently giving up on Linux and waiting for Windows to finally release the available attention.

Below is the complete build and error file contents
[a.txt](https://github.com/user-attachments/files/22138091/a.txt)

**Comment by schung-amd** [comment]
@harakiru Thanks for trying, I'll try to repro the black images on my end to see if this is workflow-specific. You can also try `pip install torch==2.7.1 torchaudio==2.7.1a0 torchvision==0.22.1 --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/`, that might work better.

@mykite Interesting, the ComfyUI docs do state that the efficient attention is enabled by default on RDNA3 specifically so I guess this might still be experimental for gfx1201.

**Comment by mykite** [comment]
> [@harakiru](https://github.com/harakiru) Thanks for trying, I'll try to repro the black images on my end to see if this is workflow-specific. You can also try , that might work better.`pip install torch==2.7.1 torchaudio==2.7.1a0 torchvision==0.22.1 --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/`
> 
> [@mykite](https://github.com/mykite) Interesting, the ComfyUI docs do state that the efficient attention is enabled by default on RDNA3 specifically so I guess this might still be experimental for gfx1201.

I am currently back on Windows 11 and in a basic usable state. Personally, I think it is better than on Ubuntu. Perhaps it is because I am not proficient in Ubuntu?

**Comment by xinyazhang** [comment]
> So looks like [pytorch/pytorch#161754](https://github.com/pytorch/pytorch/pull/161754) merged, does this make any difference atm?

This PR moves Navi31(RX 7900 XTX) back to experimental state for ME/FA backend of SDPA operator.

**Comment by harakiru** [comment]
> torch==2.7.1 torchaudio==2.7.1a0 torchvision==0.22.1 --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/

I just tried it and it still produces black images and spits out a memory access fault. Also tried a default sdxl template to see if its some custom node but no dice unfortunately. I can upload the gpu coredump but its 7.2 gigs....

**Comment by schung-amd** [comment]
Thanks again for trying, I'll let you know if we need those logs.

**Comment by schung-amd** [comment]
For future users with the bad_alloc issue, another workaround is to add `--pre` to the `pip install` command, which will expose the prerelease wheels. By default `pip` is preferring the non-prerelease 2.7.1 `torch` wheel on Linux but there is no corresponding non-prerelease `torchaudio` wheel. With `--pre`, `pip` will pull in the latest prerelease wheels which should be compatible with each other (at the time of writing this is the `torch` 2.9.0a0 `torchaudio` 2.8.0a0 `torchvision` 0.24.0a0 combination). There's ongoing discussion about how we'll handle this moving forward, but for now I have a PR in to note this in the docs.

@harakiru Do you have another issue open for your black image problems? If not I'll continue looking into that here.

**Comment by harakiru** [comment]
No i havent opened an issue yet, ill let you know when i do, thanks for the help

**Comment by alshdavid** [comment]
I'm getting this every time 

<details>
<summary>Error Message</summary>

```
/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/segment_anything/modeling/image_encoder.py:231: UserWarning: HIP warning: an illegal memory access was encountered (Triggered internally at /__w/TheRock/TheRock/external-builds/pytorch/pytorch/aten/src/ATen/hip/impl/HIPGuardImplMasqueradingAsCUDA.h:83.)
  attn = (q * self.scale) @ k.transpose(-2, -1)
!!! Exception during processing !!! HIP error: an illegal memory access was encountered
Search for `hipErrorIllegalAddress' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__HIPRT__TYPES.html for more information.
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 883, in make_sam_mask
    detected_masks = sam_obj.predict(image, points, plabs, dilated_bbox, threshold)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 633, in predict
    predictor.set_image(image, "RGB")
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/segment_anything/predictor.py", line 60, in set_image
    self.set_torch_image(input_image_torch, image.shape[:2])
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/segment_anything/predictor.py", line 89, in set_torch_image
    self.features = self.model.image_encoder(input_image)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/segment_anything/modeling/image_encoder.py", line 112, in forward
    x = blk(x)
        ^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/segment_anything/modeling/image_encoder.py", line 174, in forward
    x = self.attn(x)
        ^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/segment_anything/modeling/image_encoder.py", line 231, in forward
    attn = (q * self.scale) @ k.transpose(-2, -1)
           ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
torch.AcceleratorError: HIP error: an illegal memory access was encountered
Search for `hipErrorIllegalAddress' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__HIPRT__TYPES.html for more information.
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/MachineLearning/ComfyUI/execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/ComfyUI/execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/ComfyUI/execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/mnt/data/MachineLearning/ComfyUI/execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "/mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 876, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 813, in enhance_face
    sam_mask = core.make_sam_mask(sam_model_opt, segs, image, sam_detection_hint, sam_dilation,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 890, in make_sam_mask
    sam_obj.release_device()
  File "/mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 629, in release_device
    self.model.to(device="cpu")
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1371, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/torch/nn/modules/module.py", line 930, in _apply
    module._apply(fn)
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/torch/nn/modules/module.py", line 930, in _apply
    module._apply(fn)
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/torch/nn/modules/module.py", line 930, in _apply
    module._apply(fn)
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/torch/nn/modules/module.py", line 957, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1357, in convert
    return t.to(
           ^^^^^
torch.AcceleratorError: HIP error: an illegal memory access was encountered
Search for `hipErrorIllegalAddress' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__HIPRT__TYPES.html for more information.
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.


Exception in thread Thread-3 (prompt_worker):
Traceback (most recent call last):
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/data/MachineLearning/ComfyUI/main.py", line 193, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "/mnt/data/MachineLearning/ComfyUI/execution.py", line 649, in execute
    asyncio.run(self.execute_async(prompt, prompt_id, extra_data, execute_outputs))
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/ComfyUI/execution.py", line 722, in execute_async
    comfy.model_management.unload_all_models()
  File "/mnt/data/MachineLearning/ComfyUI/comfy/model_management.py", line 1400, in unload_all_models
    free_memory(1e30, get_torch_device())
                      ^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/ComfyUI/comfy/model_management.py", line 187, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.12/site-packages/torch/cuda/__init__.py", line 1070, in current_device
    return torch._C._cuda_getDevice()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.AcceleratorError: HIP error: an illegal memory access was encountered
Search for `hipErrorIllegalAddress' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__HIPRT__TYPES.html for more information.
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

```

</details>

```
[START] Security scan
[ComfyUI-Manager] Using uv as Python module for pip operations.
Using Python 3.12.11 environment at: .local/python-comfyui
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-09-24 17:05:21.591
** Platform: Linux
** Python version: 3.12.11 (main, Sep 18 2025, 19:47:19) [Clang 20.1.4 ]
** Python executable: /mnt/data/MachineLearning/.local/python-comfyui/bin/python
** ComfyUI Path: /mnt/data/MachineLearning/ComfyUI
** ComfyUI Base Folder Path: /mnt/data/MachineLearning/ComfyUI
** User directory: /mnt/data/MachineLearning/ComfyUI/user
** ComfyUI-Manager config path: /mnt/data/MachineLearning/ComfyUI/user/default/ComfyUI-Manager/config.ini
** Log path: /mnt/data/MachineLearning/ComfyUI/user/comfyui.log
Using Python 3.12.11 environment at: .local/python-comfyui
Using Python 3.12.11 environment at: .local/python-comfyui

Prestartup times for custom nodes:
   0.0 seconds: /mnt/data/MachineLearning/ComfyUI/custom_nodes/rgthree-comfy
   0.2 seconds: /mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Manager

Checkpoint files will always be loaded safely.
Total VRAM 16304 MB, total RAM 96208 MB
pytorch version: 2.9.0a0+rocm7.0.0rc20250903
AMD arch: gfx1201
ROCm version: (7, 1)
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 AMD Radeon Graphics : native
Using split optimization for attention
Python version: 3.12.11 (main, Sep 18 2025, 19:47:19) [Clang 20.1.4 ]
ComfyUI version: 0.3.60
ComfyUI frontend version: 1.26.13
```

**Comment by alshdavid** [comment]
And using the latest (I think) results in a 

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[1]    42681 IOT instruction (core dumped)  comfyui
```

```
[START] Security scan
[ComfyUI-Manager] Using uv as Python module for pip operations.
Using Python 3.13.7 environment at: python-comfyui
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-09-24 17:17:20.340
** Platform: Linux
** Python version: 3.13.7 (main, Sep 18 2025, 19:47:49) [Clang 20.1.4 ]
** Python executable: /mnt/data/MachineLearning/.local/python-comfyui/bin/python
** ComfyUI Path: /mnt/data/MachineLearning/ComfyUI
** ComfyUI Base Folder Path: /mnt/data/MachineLearning/ComfyUI
** User directory: /mnt/data/MachineLearning/ComfyUI/user
** ComfyUI-Manager config path: /mnt/data/MachineLearning/ComfyUI/user/default/ComfyUI-Manager/config.ini
** Log path: /mnt/data/MachineLearning/ComfyUI/user/comfyui.log
Using Python 3.13.7 environment at: python-comfyui
Using Python 3.13.7 environment at: python-comfyui

Prestartup times for custom nodes:
   0.0 seconds: /mnt/data/MachineLearning/ComfyUI/custom_nodes/rgthree-comfy
   0.2 seconds: /mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Manager

Checkpoint files will always be loaded safely.
Total VRAM 16304 MB, total RAM 96208 MB
pytorch version: 2.7.1+rocm7.9.0rc20250923
AMD arch: gfx1201
ROCm version: (7, 1)
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 AMD Radeon Graphics : native
Using split optimization for attention
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[1]    42681 IOT instruction (core dumped)  comfyui
```

This version "works" on Windows but fails on Ubuntu. On Windows it crashes with OOM errors, but with smaller image sizes that fit on the GPU it is okay. A little slower than Linux but it works.

**Comment by schung-amd** [comment]
@alshdavid Thanks for reporting, your first comment looks similar to an issue we're investigating at the moment. Not the same issue as the original issue here though, can you submit a separate issue for it?

> And using the latest (I think) results in a

This one just looks like incompatible wheels; for our nightlies, with `torch` 2.7.1 make sure you're using `torchaudio` 2.7.1a0 or 2.7.0a0.

**Comment by alshdavid** [comment]
Thanks @schung-amd, I was able to fix it with:

```bash
python -m pip install torchaudio==2.7.1a0+rocm7.9.0rc20250923 --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/
```

Now I am getting the original error again. This happens 100% of the time with FaceDetailer when I have this setting enabled

```bash
export PYTORCH_TUNABLEOP_ENABLED=1
```

<details>
<summary>Error Message</summary>

```
$ comfyui
[START] Security scan
[ComfyUI-Manager] Using uv as Python module for pip operations.
Using Python 3.13.7 environment at: /mnt/data/MachineLearning/.local/python-comfyui
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-09-25 07:26:44.413
** Platform: Linux
** Python version: 3.13.7 (main, Sep 18 2025, 19:47:49) [Clang 20.1.4 ]
** Python executable: /mnt/data/MachineLearning/.local/python-comfyui/bin/python
** ComfyUI Path: /mnt/data/MachineLearning/ComfyUI
** ComfyUI Base Folder Path: /mnt/data/MachineLearning/ComfyUI
** User directory: /mnt/data/MachineLearning/ComfyUI/user
** ComfyUI-Manager config path: /mnt/data/MachineLearning/ComfyUI/user/default/ComfyUI-Manager/config.ini
** Log path: /mnt/data/MachineLearning/ComfyUI/user/comfyui.log
Using Python 3.13.7 environment at: /mnt/data/MachineLearning/.local/python-comfyui
Using Python 3.13.7 environment at: /mnt/data/MachineLearning/.local/python-comfyui

Prestartup times for custom nodes:
   0.0 seconds: /mnt/data/MachineLearning/ComfyUI/custom_nodes/rgthree-comfy
   0.3 seconds: /mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Manager

Checkpoint files will always be loaded safely.
Total VRAM 16304 MB, total RAM 96208 MB
pytorch version: 2.7.1+rocm7.9.0rc20250923
AMD arch: gfx1201
ROCm version: (7, 1)
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 AMD Radeon Graphics : native
Using split optimization for attention
Python version: 3.13.7 (main, Sep 18 2025, 19:47:49) [Clang 20.1.4 ]
ComfyUI version: 0.3.60
ComfyUI frontend version: 1.26.13
[Prompt Server] web root: /mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/comfyui_frontend_package/static
### Loading: ComfyUI-Manager (V3.37)
[ComfyUI-Manager] network_mode: public
### ComfyUI Version: v0.3.60 | Released on '2025-09-23'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `/mnt/data/MachineLearning/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 220 nodes successfully.

        "Art is the daughter of freedom." - Friedrich Schiller


[rgthree-comfy] Loaded 48 magnificent nodes. 🎉

### Loading: ComfyUI-Impact-Pack (V8.22.2)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Impact-Subpack (V1.3.5)
[Impact Pack/Subpack] Using folder_paths to determine whitelist path: /mnt/data/MachineLearning/ComfyUI/user/default/ComfyUI-Impact-Subpack/model-whitelist.txt
[Impact Pack/Subpack] Ensured whitelist directory exists: /mnt/data/MachineLearning/ComfyUI/user/default/ComfyUI-Impact-Subpack
[Impact Pack/Subpack] Loaded 0 model(s) from whitelist: /mnt/data/MachineLearning/ComfyUI/user/default/ComfyUI-Impact-Subpack/model-whitelist.txt
[Impact Subpack] ultralytics_bbox: /mnt/data/MachineLearning/ComfyUI/models/ultralytics/bbox
[Impact Subpack] ultralytics_segm: /mnt/data/MachineLearning/ComfyUI/models/ultralytics/segm

Import times for custom nodes:
   0.0 seconds: /mnt/data/MachineLearning/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /mnt/data/MachineLearning/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Impact-Subpack
   0.1 seconds: /mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Manager
   0.1 seconds: /mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   0.9 seconds: /mnt/data/MachineLearning/ComfyUI/custom_nodes/was-node-suite-comfyui

Context impl SQLiteImpl.
Will assume non-transactional DDL.
No target revision found.
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH ComfyRegistry Data: 5/98
FETCH ComfyRegistry Data: 10/98
FETCH ComfyRegistry Data: 15/98
FETCH ComfyRegistry Data: 20/98
got prompt
Failed to validate prompt for output 15:
* (prompt):
  - Return type mismatch between linked nodes: images, received_type(VAE) mismatch input_type(IMAGE)
* PreviewImage 15:
  - Return type mismatch between linked nodes: images, received_type(VAE) mismatch input_type(IMAGE)
Output will be ignored
Loads SAM model: /mnt/data/MachineLearning/ComfyUI/models/sams/sam_vit_b_01ec64.pth (device:AUTO)
FETCH ComfyRegistry Data: 25/98
model weight dtype torch.float16, manual cast: None
model_type EPS
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load SDXLClipModel
loaded completely 14532.8 1560.802734375 True
FETCH ComfyRegistry Data: 30/98

0: 640x448 1 face, 39.5ms
Speed: 3.5ms preprocess, 39.5ms inference, 192.4ms postprocess per image at shape (1, 3, 640, 448)
FETCH ComfyRegistry Data: 35/98
/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/segment_anything/modeling/image_encoder.py:231: UserWarning: HIP warning: an illegal memory access was encountered (Triggered internally at /__w/TheRock/TheRock/external-builds/pytorch/pytorch/aten/src/ATen/hip/impl/HIPGuardImplMasqueradingAsCUDA.h:83.)
  attn = (q * self.scale) @ k.transpose(-2, -1)
!!! Exception during processing !!! HIP error: an illegal memory access was encountered
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 883, in make_sam_mask
    detected_masks = sam_obj.predict(image, points, plabs, dilated_bbox, threshold)
  File "/mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 633, in predict
    predictor.set_image(image, "RGB")
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/segment_anything/predictor.py", line 60, in set_image
    self.set_torch_image(input_image_torch, image.shape[:2])
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/segment_anything/predictor.py", line 89, in set_torch_image
    self.features = self.model.image_encoder(input_image)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/segment_anything/modeling/image_encoder.py", line 112, in forward
    x = blk(x)
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/segment_anything/modeling/image_encoder.py", line 174, in forward
    x = self.attn(x)
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/segment_anything/modeling/image_encoder.py", line 231, in forward
    attn = (q * self.scale) @ k.transpose(-2, -1)
           ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
RuntimeError: HIP error: an illegal memory access was encountered
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/MachineLearning/ComfyUI/execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/ComfyUI/execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/ComfyUI/execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/mnt/data/MachineLearning/ComfyUI/execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "/mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 876, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~^
        single_image.unsqueeze(0), model, clip, vae, guide_size, guide_size_for, max_size, seed + i, steps, cfg, sampler_name, scheduler,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        cycle=cycle, inpaint_model=inpaint_model, noise_mask_feather=noise_mask_feather, scheduler_func_opt=scheduler_func_opt,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        tiled_encode=tiled_encode, tiled_decode=tiled_decode)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 813, in enhance_face
    sam_mask = core.make_sam_mask(sam_model_opt, segs, image, sam_detection_hint, sam_dilation,
                                  sam_threshold, sam_bbox_expansion, sam_mask_hint_threshold,
                                  sam_mask_hint_use_negative, )
  File "/mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 890, in make_sam_mask
    sam_obj.release_device()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/mnt/data/MachineLearning/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 629, in release_device
    self.model.to(device="cpu")
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1355, in to
    return self._apply(convert)
           ~~~~~~~~~~~^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
    ~~~~~~~~~~~~~^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
    ~~~~~~~~~~~~~^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
    ~~~~~~~~~~~~~^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/torch/nn/modules/module.py", line 942, in _apply
    param_applied = fn(param)
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1341, in convert
    return t.to(
           ~~~~^
        device,
        ^^^^^^^
        dtype if t.is_floating_point() or t.is_complex() else None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        non_blocking,
        ^^^^^^^^^^^^^
    )
    ^
RuntimeError: HIP error: an illegal memory access was encountered
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.


Exception in thread Thread-3 (prompt_worker):
Traceback (most recent call last):
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/ComfyUI/main.py", line 193, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/ComfyUI/execution.py", line 649, in execute
    asyncio.run(self.execute_async(prompt, prompt_id, extra_data, execute_outputs))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/mnt/data/MachineLearning/ComfyUI/execution.py", line 722, in execute_async
    comfy.model_management.unload_all_models()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/mnt/data/MachineLearning/ComfyUI/comfy/model_management.py", line 1400, in unload_all_models
    free_memory(1e30, get_torch_device())
                      ~~~~~~~~~~~~~~~~^^
  File "/mnt/data/MachineLearning/ComfyUI/comfy/model_management.py", line 187, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/mnt/data/MachineLearning/.local/python-comfyui/lib/python3.13/site-packages/torch/cuda/__init__.py", line 1030, in current_device
    return torch._C._cuda_getDevice()
           ~~~~~~~~~~~~~~~~~~~~~~~~^^
RuntimeError: HIP error: an illegal memory access was encountered
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
```

</details>

Launch command:

```bash
export PYTHONPATH="/opt/rocm/lib:$PYTHONPATH"
export PYTORCH_TUNABLEOP_ENABLED=1                  # <---- THIS CAUSES CRASH
export PYTORCH_HIP_ALLOC_CONF="garbage_collection_threshold:0.8,max_split_size_mb:256"
export PYTORCH_ENABLE_MPS_FALLBACK=1                # Avoid some FP16 fallback issues
export TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1    # Enable ROCm AOT Triton kernels
export MIGRAPHX_MLIR_USE_SPECIFIC_OPS="attention"   # Use optimized attention kernels
export MIOPEN_FIND_MODE=2                           # Performance tuning mode
export HIP_DISABLE_GRAPH_CAPTURE=1                  # Prevent graph capture OOM spikes

python main.py \
    --use-pytorch-cross-attention \
    --disable-smart-memory
```
