### ISSUE TITLE
[Issue]: rocm7rc crashes (OOM) on Windows due to lack of vram management and recycling mechanism

### ISSUE THREAD

**Issue by fangwengit04** [ROCm/TheRock#1494]
### Problem Description

On Windows 10 22h2, using comfyui, I installed the latest TheRock rocm+torch precompiled package as of September 16, 2025, using Python 12. After installing only rocm and torch without any parameters, I ran python main.py directly, loaded any example workflow, and clicked run. The first run was usually fine, but if you change the model or even the imported image, it will directly cause vram overflow, lag, and then the driver to drop (OOM).

### Operating System

Windows 10 19045.6332

### CPU

14600kf

### GPU

9070xt

### ROCm Version

torch-2.9.0a0+rocm7.0.0rc20250909

### Steps to Reproduce

python -m pip install --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/ --pre torch torchaudio torchvision
Use this command to install Torch and Rocm.

git clone https://github.com/comfyanonymous/ComfyUI.git
cd comfyui
pip install -r requirements.txt

python main.py
Load any official example workflow, flux dev is recommended, click Generate. Then, select a model in the workflow and switch to another one (from fp16 to fp8, or fp8 to fp16). Click Run again and observe the vram usage. It overflows immediately, and then there's a lag in the sampler stage. The driver then drops, and ComfyUI reports an OutOfMemory Error.

**Comment by fangwengit04** [comment]
Example video https://youtu.be/0j9zENuqxAA
The situations I encountered during use, flux change prompts, sdxl ControlNet change pictures and models

**Comment by Kademo15** [comment]
I have encountered the same issue. I believe it happens because comfy doesnt free vram and just stacks the model on top of the clips resulting in insane memory requirements. I have raised the [issue](https://github.com/comfyanonymous/ComfyUI/issues/8745) in the comfy repo but to no success. For the time being try to run the clip on the cpu that should help but make generation time longer. I hope the folks here at theRock could find out if its an amd side or a comfy side issue.

**Comment by alexsarmiento** [comment]
Try running comfyui with "--disable-smart-memory"

**Comment by fangwengit04** [comment]
> Try running comfyui with "--disable-smart-memory"

I tried it, but it didn't work. I also tried --lowvram, --use-quad-cross-attention, --use-split-cross-attention, but it crashed.

Using --disable-smart-memory is much better, but sometimes it will use shared vram when only 12g vram is used, which will cause crashes. ComfyUI seems to always try to use shared vram instead of using only dedicated vram.

**Comment by alexsarmiento** [comment]
> > Try running comfyui with "--disable-smart-memory"
> 
> I tried it, but it didn't work. I also tried --lowvram, --use-quad-cross-attention, --use-split-cross-attention, but it crashed.
> 
> Using --disable-smart-memory is much better, but sometimes it will use shared vram when only 12g vram is used, which will cause crashes. ComfyUI seems to always try to use shared vram instead of using only dedicated vram.

I've been observing this kind of memory mismanagement in comfyui with rocm for a while,  even on linux. In the meanwhile, try to load the models in fp8 e5m2 format. You can also test with these options : " --cache-classic" or "--cache-none", "--fp8_e5m2-unet". Another 'trick' that helps to reduce memory usage is torch.compile with the inductor backend. But torch inductor requires Triton, and I've not been able to make it work with these wheels. You might have better luck.

**Comment by garvin-mardens** [comment]
I think there is an issue beyond just comfy memory management. When I run comfyui workflows with ROCm on Linux or WSL2, I can overflow VRAM but for most nodes if it is only a relatively small excess, it can continue running seamlessly, swapping data to and from VRAM. (I observe this as short pauses in between bursts of GPU compute activity, which only happens when I exceed the dedicated VRAM limit -- normally the GPU activity is steady). You might not even notice anything happened.

When doing the exact same thing with Windows ROCm 7, the moment it overtops VRAM by any amount at all, the whole thing just hangs.

**Comment by jammm** [comment]
Can you try again with the latest nightly from september 17th?
Try upgrading your wheels with the `pip install --upgrade ...` command with the same args as the one you used earlier, and if that doesn't work, uninstall torch, vision, audio and try again.

The wheels I'm referring to specifically are (depending on your python version):

[torch-2.10.0a0+rocm7.0.0rc20250917-cp311-cp311-win_amd64.whl](https://rocm.nightlies.amd.com/v2/gfx120X-all/torch-2.10.0a0%2Brocm7.0.0rc20250917-cp311-cp311-win_amd64.whl)
[torch-2.10.0a0+rocm7.0.0rc20250917-cp312-cp312-win_amd64.whl](https://rocm.nightlies.amd.com/v2/gfx120X-all/torch-2.10.0a0%2Brocm7.0.0rc20250917-cp312-cp312-win_amd64.whl)
[torch-2.10.0a0+rocm7.0.0rc20250917-cp313-cp313-win_amd64.whl](https://rocm.nightlies.amd.com/v2/gfx120X-all/torch-2.10.0a0%2Brocm7.0.0rc20250917-cp313-cp313-win_amd64.whl)

The issue is most likely the lack of aotriton in the september 9 wheels. Without aotriton, comfyui isn't able to use flash attention and falls back to another implementation (likely the MATH backend or something similar) which eats up a lot of VRAM.

The reason why you didn't see this OOM on Linux/WSL2 is because the Linux wheels there have had aotriton built in by default. We've only enabled aotriton on Windows wheels recently https://github.com/ROCm/TheRock/pull/1437 which was after the sept 9th nightly.

**Comment by fangwengit04** [comment]
> Can you try again with the latest nightly from september 17th? Try upgrading your wheels with the `pip install --upgrade ...` command with the same args as the one you used earlier, and if that doesn't work, uninstall torch, vision, audio and try again.
> 
> The wheels I'm referring to specifically are (depending on your python version):
> 
> [torch-2.10.0a0+rocm7.0.0rc20250917-cp311-cp311-win_amd64.whl](https://rocm.nightlies.amd.com/v2/gfx120X-all/torch-2.10.0a0%2Brocm7.0.0rc20250917-cp311-cp311-win_amd64.whl) [torch-2.10.0a0+rocm7.0.0rc20250917-cp312-cp312-win_amd64.whl](https://rocm.nightlies.amd.com/v2/gfx120X-all/torch-2.10.0a0%2Brocm7.0.0rc20250917-cp312-cp312-win_amd64.whl) [torch-2.10.0a0+rocm7.0.0rc20250917-cp313-cp313-win_amd64.whl](https://rocm.nightlies.amd.com/v2/gfx120X-all/torch-2.10.0a0%2Brocm7.0.0rc20250917-cp313-cp313-win_amd64.whl)
> 
> The issue is most likely the lack of aotriton in the september 9 wheels. Without aotriton, comfyui isn't able to use flash attention and falls back to another implementation (likely the MATH backend or something similar) which eats up a lot of VRAM.
> 
> The reason why you didn't see this OOM on Linux/WSL2 is because the Linux wheels there have had aotriton built in by default. We've only enabled aotriton on Windows wheels recently [#1437](https://github.com/ROCm/TheRock/pull/1437) which was after the sept 9th nightly.

I installed
torch-2.10.0a0+rocm7.0.0rc20250917-cp312-cp312-win_amd64.whl
But the problem persists, with no change. Do I need to disable Resizable BAR? I still trigger the crash after 5 rounds of changes using sdxl+contrnet. The VRAM is used more and more without being released. ComfyUI will still use the shared vram.

**Comment by jammm** [comment]
Can you try with:
`python main.py --use-pytorch-cross-attention` ?

**Comment by fangwengit04** [comment]
> --use-pytorch-cross-attention

--use-pytorch-cross-attention is even more unfeasible, and vram overflows in the first round

<img width="1107" height="1009" alt="Image" src="https://github.com/user-attachments/assets/f5530d70-5c94-44c4-8ab3-bc7b814c8e3c" />

**Comment by jammm** [comment]
What's your baseline VRAM usage (before starting ComfyUI) ?

**Comment by jammm** [comment]
> The VRAM is used more and more without being released

~I don't see any evidence that this is a ROCm Windows specific issue yet.~ Memory management is something comfyui is responsible for, and on Windows the baseline VRAM usage is generally higher than linux due to background processes.

EDIT: I may have spoken too early. The TDR's that happen before OOM is likely a ROCm specific problem, though the VRAM management is still ComfyUI's responsibility.

What might help gather evidence for a ROCm issue is if you can share screenshots showing the VRAM usage with WSL and then again with these sept. 17th wheels after your first round of runs, and share the OOM error you're facing. Make sure to follow the exact same sequence of runs on both WSL and Windows.

If you encounter any TDR's (driver drops) again while doing this, please try to reproduce them again with the following environment variables set:

```
export MIOPEN_ENABLE_LOGGING=1
export MIOPEN_ENABLE_LOGGING_CMD=1
export MIOPEN_LOG_LEVEL=6
```

And share the logs here. It will help with narrowing down the issue.

**Comment by fangwengit04** [comment]
> What's your baseline VRAM usage (before starting ComfyUI) ?

As the video shows, my computer takes up 0.4G vram when it starts up.
I don't plan to install wsl, it's too troublesome to copy the model. and I don't know much about using pure command line Linux
But I have used rocm 6.4.1/6.4.3+torch 2.8 on linux ubuntu, I don't know how to see vram usage, but it was the same situation at that time.
In July, someone raised a similar issue on comfyui's github, but it was not resolved.
https://github.com/comfyanonymous/ComfyUI/issues/8745

**Comment by jammm** [comment]
I tried to reproduce this and was able to repro it. A few comments:

* The issue is not OOM, but it's just "stuck". Driver isn't crashing or going down either.
* It seems that comfyui uses its own "sub quadratic attention" as default, which seems to have better performance than `--use-pytorch-cross-attention` in flux.
* It's not clear what's causing comfyui to be "stuck" during the second run after switching the CLIP model.

So this issue is not OOM but a stuck/freeze issue within ComfyUI. I would rename the issue title to avoid confusion.

**Comment by jammm** [comment]
Hmm interesting. I'm not able to reproduce this anymore.
Are you able to consistently reproduce this issue ?

**Comment by fangwengit04** [comment]
> Hmm interesting. I'm not able to reproduce this anymore. Are you able to consistently reproduce this issue ?

Generally, the system will freeze after using shared VRAM because the shared VRAM is not uninstalled. Although the VRAM is reduced from 15GB to 13GB, the shared VRAM still has an abnormal 1GB usage.

In a similar situation, if the shared VRAM is never used, there will be no freeze.

<img width="1107" height="1009" alt="Image" src="https://github.com/user-attachments/assets/21d1f6cc-51c9-4ffa-8240-b096ae2ea9db" />

It should not be renamed because VRAM is always stacked. In the case of sdxl+contrnet, all VRAM is occupied after 5 rounds, thus using additional shared VRAM, which will cause comfyui to freeze. In flux, switching the clip model will cause all VRAM to be occupied, thus using additional shared VRAM, causing freezes. If it is never switched, flux will always use 13GB VRAM to keep running.

**Comment by Kademo15** [comment]
> Hmm interesting. I'm not able to reproduce this anymore. Are you able to consistently reproduce this issue ?

This issue exists for some time now and I am still running the early AIO wheels from may and have this issue since January I also linked the Comfy issue i opened further up in this issue. I am 99% sure it is a Comfy issue because it happens with Comfy base nodes only. Running smth big like flux or gwen is super slow like 70sec/it due to vram overflow, but then wan2.1 with full bf16 clip which should be bigger than flux + clip it runs perfectly. That is because the wan2.1 custom nodes have their own vram management code which offloads the clips perfectly and manage ram and vram limits to the max without overflowing or slowing down.

**Comment by fangwengit04** [comment]
> > Hmm interesting. I'm not able to reproduce this anymore. Are you able to consistently reproduce this issue ?
> 
> This issue exists for some time now and I am still running the early AIO wheels from may and have this issue since January I also linked the Comfy issue i opened further up in this issue. I am 99% sure it is a Comfy issue because it happens with Comfy base nodes only. Running smth big like flux or gwen is super slow like 70sec/it due to vram overflow, but then wan2.1 with full bf16 clip which should be bigger than flux + clip it runs perfectly. That is because the wan2.1 custom nodes have their own vram management code which offloads the clips perfectly and manage ram and vram limits to the max without overflowing or slowing down.

I can't use wan2.1 wan2.2 because of VRAM overflow

**Comment by Kademo15** [comment]
> I can't use wan2.1 wan2.2 because of VRAM overflow

Try using fp8 clip and fp8 model that should maybe work. I can fit the full fp16 clip and fp8 model onto 24gb vram with 32gb ram so maybe the fp8 clip could reduce it enough for 16gb of vram. I wrote the message to give context that it is probably a comfy error due to the fact that a custom with its own memory management works better than comfy core.

**Comment by alexsarmiento** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/d1d9eb94b1096c9b3f963bf152bd6b9cd330c3a4

The latest comfyui pull comes with some memory tweaks. Now I am able to do consecutive wan.2.2 runs without spilling into RAM. (barely). I still recomend using "--disable-smart-memory"

**Comment by fangwengit04** [comment]
> [comfyanonymous/ComfyUI@d1d9eb9](https://github.com/comfyanonymous/ComfyUI/commit/d1d9eb94b1096c9b3f963bf152bd6b9cd330c3a4)
> 
> The latest comfyui pull comes with some memory tweaks. Now I am able to do consecutive wan.2.2 runs without spilling into RAM. (barely). I still recomend using "--disable-smart-memory"

What resolution, what fp?

**Comment by fangwengit04** [comment]
> [comfyanonymous/ComfyUI@d1d9eb9](https://github.com/comfyanonymous/ComfyUI/commit/d1d9eb94b1096c9b3f963bf152bd6b9cd330c3a4)
> 
> The latest comfyui pull comes with some memory tweaks. Now I am able to do consecutive wan.2.2 runs without spilling into RAM. (barely). I still recomend using "--disable-smart-memory"

What model?
I use 
wan2.2_i2v_high_noise_14B_fp8_scaled,
I have to completely exit comfyui to do a new round of generation, otherwise the VRAM overflows

**Comment by RobertAgee** [comment]
I recommend using the nodes 'clear vram' or even better 'vram debug' which the latter is even better because you can hold arbitrary # of objects in memory while flushing the rest. placed within a loop, you can get endlessly extend generations for whatever purposes without hitting OOM

**Comment by Kademo15** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/c8d2117f02bcad6d8316ffd8273bdc27adf83b44

Probably not directly causing this but maybe ?

**Comment by fangwengit04** [comment]
> [comfyanonymous/ComfyUI@c8d2117](https://github.com/comfyanonymous/ComfyUI/commit/c8d2117f02bcad6d8316ffd8273bdc27adf83b44)
> 
> Probably not directly causing this but maybe ?

Until today, in version 20250926, when changing models, changing prompt words, or changing loading images, it still causes the shared VRAM to be used and thus stuck.

**Comment by skillmaker-dev** [comment]
Same issue, even after using `--disable-smart-memory` and also without even changing the model, in the 3rd 4th generation it crashes and I have to restart Comfyui again, I'm using the wheels from 1st October. ROCm 7

**Comment by jammm** [comment]
> Same issue, even after using `--disable-smart-memory` and also without even changing the model, in the 3rd 4th generation it crashes and I have to restart Comfyui again, I'm using the wheels from 1st October. ROCm 7

Can you create a new GH issue and share error logs? It doesn't seem related to the issue OP is facing here. The issue OP is facing is more of a soft hang rather than OOM/Crash.

**Comment by jammm** [comment]
> > [comfyanonymous/ComfyUI@c8d2117](https://github.com/comfyanonymous/ComfyUI/commit/c8d2117f02bcad6d8316ffd8273bdc27adf83b44)
> > Probably not directly causing this but maybe ?
> 
> Until today, in version 20250926, when changing models, changing prompt words, or changing loading images, it still causes the shared VRAM to be used and thus stuck.

Have you tried the latest ComfyUI as of today?

**Comment by jammm** [comment]
This issue appears to be more and more related to ComfyUI itself rather than ROCm. Unless there's a way to consistently reproduce this soft-hang/slowdown with concrete evidence that this is not related to ComfyUI itself, I recommend closing this and reporting this to ComfyUI for optimizing VRAM allocations to prevent it from hitting shared memory.

**Comment by alexsarmiento** [comment]
> This issue appears to be more and more related to ComfyUI itself rather than ROCm. Unless there's a way to consistently reproduce this soft-hang/slowdown with concrete evidence that this is not related to ComfyUI itself, I recommend closing this and reporting this to ComfyUI for optimizing VRAM allocations to prevent it from hitting shared memory.

Yeah, memory management in ComfyUI seems to focus on Nvidia idiosyncrasies. The fact that memory management behaves differently when using zluda is probably a symptom of this.

**Comment by Kademo15** [comment]
> Yeah, memory management in ComfyUI seems to focus on Nvidia idiosyncrasies. The fact that memory management behaves differently when using zluda is probably a symptom of this. 

Well the comfy team doesn't seem to care about AMD. I have opened 2 issues on the comfy github already reporting that vram managment on amd just seems off and gpt nothing.

**Comment by huanrwan-amd** [comment]
From ComfyUI issue report: https://github.com/Comfy-Org/ComfyUI/issues/9922 . This VRAM issue fixed since ROCM 7.1
> I have tested the latest released driver for ROCm 7.1 on Windows, with the latest version of ComfyUI, all generations are working without stack overflow, without using `--disable-smart-memory` and using PyTorch cross attention on RX 9070 XT.
> 
> For Z-Image FP8, I can generate images 1024x1024 at 1.4it/s. For SDXL, I can generate images 1024x1024 using Euler normal at 5it/s.

**Comment by huanrwan-amd** [comment]
close as fixed since ROCm7.1

**Comment by NoThanksGoAway** [comment]
Still happens. It's not Comfy specific. Only backend I've found I couldn't trigger it with was sd.cpp vulkan. Invoke for example cries it's OOM with >10gb reported free. Loading models rapid fire/switching makes it easier to set off. Can do it with large LLM too on a full model load. Vram fine under normal, non-rocm use. I.e 15gb+ vram use under a modded Skyrim. Very rarely it can recover, usually brings the whole system down and requires a full reboot. (Linux obv)

**Comment by jammm** [comment]
> Still happens. It's not Comfy specific. Only backend I've found I couldn't trigger it with was sd.cpp vulkan. Invoke for example cries it's OOM with >10gb reported free. Loading models rapid fire/switching makes it easier to set off. Can do it with large LLM too on a full model load. Vram fine under normal, non-rocm use. I.e 15gb+ vram use under a modded Skyrim. Very rarely it can recover, usually brings the whole system down and requires a full reboot. (Linux obv)

As this issue was closed months ago, you might want to create a separate issue for this. Steps to reproduce it would be helpful as well.
