### ISSUE TITLE
[Issue]: [MIOpen - gfx1200/Windows] First SD generation at VAE stage is extremely slow and crashes GPU driver - even with AOTriton enabled

### ISSUE THREAD

**Issue by Nem404** [ROCm/TheRock#1542]
> Note
> Also reported at https://github.com/ROCm/rocm-libraries/issues/1860

### Problem Description

Using a gfx1200 GPU, the first image generation in Stable Diffusion goes quickly - I get like 2.5 it/s - but at the end, during the VAE decode stage, it crashes the GPU driver, occasionally giving OOM errors in the console.

I’m using average/default generation parameters - basically every UI’s base values (1024×1024 resolution, 20 steps, Euler a or DPM++ 2M karras, etc.).

I’ve tried the well-known UIs:
[ComfyUI](https://github.com/comfyanonymous/ComfyUI), [SD.Next](https://github.com/vladmandic/automatic), [Stable Diffusion WebUI reForge](https://github.com/Panchovix/stable-diffusion-webui-reForge), etc., and they all behave the same.

Subsequent generations usually work, but if I change the resolution to anything else, the problem repeats.  
For example, using the [krita-ai-diffusion](https://github.com/Acly/krita-ai-diffusion) plugin with [Krita](https://github.com/KDE/krita) triggers the same issue every single time, because there the resolution and other parameters often change. This doesn’t seem reasonable.

I’ve tried every flag I could think of, for example in Comfy:
`--use-pytorch-cross-attention`, `--disable-smart-memory`, `--reserve-vram 8`, `--fp16-vae`, `--bf16-vae`,  tiled VAE node, etc., but nothing helps.

/ I figured out, along with other users, that disabling MIOpen entirely by hard-coding `torch.backends.cudnn.enabled = False` in the script generally prevents driver crashes and OOM issues, but it’s just a workaround, not a real solution. /

### Operating System

Windows 11

### CPU

Intel Core i5

### GPU

AMD Radeon RX 9060 XT 16 GB

### ROCm Version

7.0.0rc20250917

### Steps to Reproduce

Install the latest wheels:
`python -m pip install --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/ torch torchvision torchaudio`

Then open any SD UI, and generate an image.

(I'm using the `TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1` environment variable every time to enable AOTriton on the gfx1200.)

### Additional Information

I’ve seen other AMD users mention this VAE issue in several other places online.

**Comment by Cyxaruk** [comment]
`--bf16-vae` makes it work for me.

**Comment by subunder** [comment]
> `--bf16-vae` makes it work for me.

Are you using a gfx1200? I've tried `--bf16-vae` too, but it does the exact same thing

**Comment by subunder** [comment]
ComfyUI is also mentioning a similar issue in its script:
https://github.com/comfyanonymous/ComfyUI/blob/27bc181c49249f11da2d8a14f84f3bdb58a0615f/comfy/model_management.py#L926-L929
> also a problem on RDNA4 except fp32 is also slow there

So everything is slow. How nice

In my case, driver crash is also inevitable. Tried rolling back the driver, installing everything from 0, but nothing works

**Comment by Cyxaruk** [comment]
My exact setup is as follows.
I have 9060 XT 16 GB, Windows 11 Pro, in my comfyui venv there are torch and rocm wheels installed thier versions being:
```
rocm 7.0.0rc20250917
rocm-sdk-core 7.0.0rc20250917
rocm-sdk-libraries-gfx120X-all 7.0.0rc20250917
torch 2.10.0a0+rocm7.0.0rc20250917
torchaudio 2.8.0a0+rocm7.0.0rc20250917
torchsde 0.2.6
torchvision 0.25.0a0+rocm7.0.0rc20250917
```
I run comfyui with `TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1`
Launch arguments are `--use-pytorch-cross-attention --bf16-vae`
I use tiled vae decode in my workflow with parameters:
```
tile_size 512
overlap 64
temporal_size 64
temporal_overlap 8
```
It is stable on my machine but only with certain image resolutions (832x1216, 1024x1024). Any other sizes (mostly larger) make my whole system grind to a halt with no progress on the gen itself.
Nonetheless, when everything works, performance is reasonable (≈2.7 it/s, single image gen finishes in around 11 seconds).

**Comment by subunder** [comment]
@Cyxaruk So `--bf16-vae` + tiled vae node? This is very specific. For example we can't use tiled vae for video generation at all

**Comment by subunder** [comment]
> Adding
> 
> import torch torch.backends.cudnn.enabled = False
> 
> to ComfyUI/main.py

This disables MIOpen. I don't see this as a solution

**Comment by Cyxaruk** [comment]
> [@Cyxaruk](https://github.com/Cyxaruk) So `--bf16-vae` + tiled vae node? This is very specific. For example we can't use tiled vae for video generation at all

I am sorry my directions were of no help. I myself do not do video gens - never managed to set it up properly.

Seeing the great dedication of TheRock team I am sure this all will be resolved in no time.

**Comment by subunder** [comment]
@Cyxaruk Thanks for your suggestions, this way other users who have the same issues can experiment on their own

**Comment by subunder** [comment]
Just found out that:
`set MIOPEN_FIND_MODE=2`
makes VAE more stable.

Still, this is more like a workaround, not a solution for this issue

**Comment by jammm** [comment]
Hey @Nem404 , this is definitely a recurring issue that needs to be fixed, especially the TDR's which I've also observed. To gather more evidence, can you reproduce the TDR's by:
* Deleting the `.miopen` folder from your home directory? Should be the `C:\Users\<username>\.miopen` folder, something like that.
* Set the following environment variables, then try the VAE decode again, then share the output logs here:
```bash
export MIOPEN_ENABLE_LOGGING=1
export MIOPEN_ENABLE_LOGGING_CMD=1
export MIOPEN_LOG_LEVEL=6
```
(for windows you might want to use `set` or `$env:..` depending on cmd or powershell)

**Comment by jammm** [comment]
A similar issue was reported in https://github.com/ROCm/TheRock/discussions/1477#discussioncomment-14390314 on a gfx1100.

**Comment by jammm** [comment]
> Seeing the great dedication of TheRock team I am sure this all will be resolved in no time.

We're definitely aware of the issue, but it's a more complicated one, so it's not clear how long it'll take to fix. Creating issues like these will definitely help push this further.

**Comment by subunder** [comment]
> Hey [@Nem404](https://github.com/Nem404) , this is definitely a recurring issue that needs to be fixed, especially the TDR's which I've also observed. To gather more evidence, can you reproduce the TDR's by:
> 
> * Deleting the `.miopen` folder from your home directory? Should be the `C:\Users\<username>\.miopen` folder, something like that.
> * Set the following environment variables, then try the VAE decode again, then share the output logs here:
> 
> export MIOPEN_ENABLE_LOGGING=1
> export MIOPEN_ENABLE_LOGGING_CMD=1
> export MIOPEN_LOG_LEVEL=6
> (for windows you might want to use `set` or `$env:..` depending on cmd or powershell)

@jammm thanks for the reply, I'll try these things

**Comment by subunder** [comment]
I’m not sure why, but enabling MIOpen logging caused the system to freeze and lose display output. Even the Num Lock key cannot be toggled.
I had no choice but to hold the power button down until it turned off. After restarting, I had to reinstall AMD Adrenalin. This issue is starting to become quite serious.

**Comment by subunder** [comment]
> * Set the following environment variables, then try the VAE decode again, then share the output logs here:
> 
Got 250 pages of logs, but I think the most important part is at the end:
https://gist.github.com/Nem404/24b5c364ab3fde71a0bf457211617650

Can you pls evaluate these logs @jammm? Do they reveal anything significant?

**Comment by subunder** [comment]
> torch.OutOfMemoryError: HIP out of memory. Tried to allocate 1.12 GiB. GPU 0 has a total capacity of 15.92 GiB of which 9.18 GiB is free. Of the allocated memory 4.87 GiB is allocated by PyTorch, and 1.31 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

So 9.18 GiB is free, yet it can't allocate 1.12. ?_?
Btw I'm also using `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`

**Comment by jammm** [comment]
> > * Set the following environment variables, then try the VAE decode again, then share the output logs here:
> 
> Got 250 pages of logs, but I think the most important part is at the end: https://gist.github.com/Nem404/24b5c364ab3fde71a0bf457211617650
> 
> Can you pls evaluate these logs [@jammm](https://github.com/jammm)? Do they reveal anything significant?

Thanks! i've shared this internally and we're investigating.

> So 9.18 GiB is free, yet it can't allocate 1.12. ?_?
> Btw I'm also using PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

Not sure about this one. I'm guessing the env var may have affected it?

**Comment by subunder** [comment]
Should I retry without using `set PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`?

**Comment by jammm** [comment]
Yeah sure, worth a try!

**Comment by subunder** [comment]
I was going with:
```
set COMMANDLINE_ARGS=--auto-launch --use-pytorch-cross-attention --bf16-vae

set TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.80,max_split_size_mb:512
set PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

set MIOPEN_ENABLE_LOGGING=1
set MIOPEN_ENABLE_LOGGING_CMD=1
set MIOPEN_LOG_LEVEL=6
```
Idk if I should remove `--use-pytorch-cross-attention` or `--bf16-vae` together with the `PYTORCH_CUDA_ALLOC_CONF` things

**Comment by subunder** [comment]
The system freeze is kind of scary tho, at first I thought smth happened with my gpu as Windows couldnt use its driver after the forced shutdown and restart

**Comment by Cyxaruk** [comment]
Some testing later I have discovered the following.

`TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1` + `MIOPEN_FIND_MODE=2` + `--use-pytorch-cross-attention` + (`--bf16-vae` OR `--fp16-vae`) makes it work with regular VAE decode (not tiled). And `--fp16-vae` is a bit faster but inconsistent (sometimes it takes 5-8 seconds more than usual).
Comfyui seems to default to FP32 VAE when not specified, which does work with regular VAE, but takes around 40 seconds to decode and nearly halts my whole system.

**Comment by subunder** [comment]
@Cyxaruk I think MIOpen should automatically choose the optimal "find mode". Requiring users to manually configure this is not a practical solution in my op

**Comment by subunder** [comment]
> Some testing later I have discovered the following.
> 
> `TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1` + `MIOPEN_FIND_MODE=2` + `--use-pytorch-cross-attention` + (`--bf16-vae` OR `--fp16-vae`) makes it work with regular VAE decode (not tiled). And `--fp16-vae` is a bit faster but inconsistent (sometimes it takes 5-8 seconds more than usual). Comfyui seems to default to FP32 VAE when not specified, which does work with regular VAE, but takes around 40 seconds to decode and nearly halts my whole system.

I'll try these things here on my end too.
Which type of vae attention mechanism did you use? The default `split` one?

**Comment by Cyxaruk** [comment]
> I'll try these things here on my end too. Which type of vae attention mechanism did you use? The default `split` one?

Yes, the `split` one. Although I do not know how to change it. I recon comfyui defaults to it.

`Using split attention in VAE`

**Comment by Cyxaruk** [comment]
> [@Cyxaruk](https://github.com/Cyxaruk) I think MIOpen should automatically choose the optimal "find mode". Requiring users to manually configure this is not a practical solution in my op

[Using the find APIs and immediate mode](https://rocmdocs.amd.com/projects/MIOpen/en/latest/how-to/find-and-immediate.html#using-the-find-apis-and-immediate-mode) says: 

> Find modes
> MIOpen provides a set of find modes that are used to accelerate find API calls. Set the different modes by using the MIOPEN_FIND_MODE environment variable with one of these values:
> 
> - NORMAL/1 (normal find): This is the full find mode call, which benchmarks all the solvers and returns a list.
> - FAST/2 (fast find): Checks [FindDb](https://rocmdocs.amd.com/projects/MIOpen/en/latest/conceptual/finddb.html) for an entry. If there’s a FindDb hit, it uses that entry. If there’s a miss, it uses the immediate mode fallback. This mode offers fast start-up times at the cost of GPU performance.
> - HYBRID/3 or unset MIOPEN_FIND_MODE (hybrid find): Checks [FindDb](https://rocmdocs.amd.com/projects/MIOpen/en/latest/conceptual/finddb.html) for an entry. If there’s a FindDb hit, it uses that entry. If there’s a miss, it uses the existing find machinery. This mode offers slower start-up times than fast find without the GPU performance drop.
> - 4: This value is reserved and should not be used.
> - DYNAMIC_HYBRID/5 (dynamic hybrid find): Checks [FindDb](https://rocmdocs.amd.com/projects/MIOpen/en/latest/conceptual/finddb.html) for an entry. If there’s a FindDb hit, it uses that entry. If there’s a miss, it uses the existing find machinery, skipping non-dynamic kernels. It offers faster start-up times than hybrid find, but GPU performance might decrease.
> 
> The default find mode is DYNAMIC_HYBRID. To run the full NORMAL find mode, use export MIOPEN_FIND_MODE=NORMAL or export MIOPEN_FIND_MODE=1.


Many online resources suggest manually setting the `MIOPEN_FIND_MODE` variable. And, for example, [ComfyUI-ZLUDA](https://github.com/mrkoykang/ComfyUI-Zluda/tree/master) does that automatically during startup:
```
echo *** Starting the Comfyui-ZLUDA for the first time, please be patient...
echo.
set FLASH_ATTENTION_TRITON_AMD_ENABLE=TRUE
set MIOPEN_FIND_MODE=2
set MIOPEN_LOG_LEVEL=3
.\zluda\zluda.exe -- python main.py --auto-launch --use-pytorch-cross-attention
```

Making a custom startup script would be a viable solution.

**Comment by wasd-tech** [comment]
Hi, I also have strange behavior with VAE and also with the first run of ksampler. I think that the process of finding kernels is really slow. For me the variable that changes everything  is this:
`export MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_FWD=0`
@jammm I don't like to mention people directly but I hope this helps you find the bug.

On my rx 9070 xt with ROCm 7.0 it will make the autotuning almost instantaneous and the speed is really great (especially after the massive performance upgrade with ROCm 7.0)

I am referring exclusively to Linux.

**Comment by subunder** [comment]
@wasd-tech I'll try with `set MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_FWD=0` too

**Comment by subunder** [comment]
> 
> Making a custom startup script would be a viable solution.

I've made a custom script with AI to try the same image generation workflow with every MIOpen find mode and record the time taken by each. Who would've thought Fast mode is the fastest of all XD

But then what's even the point of Normal and Hybrid modes? So they're slower but they have better memory management or smth?

**Comment by subunder** [comment]
> > I'll try these things here on my end too. Which type of vae attention mechanism did you use? The default `split` one?
> 
> Yes, the `split` one. Although I do not know how to change it. I recon comfyui defaults to it.
> 
> `Using split attention in VAE`

I just thought that, given that using the `--use-pytorch-cross-attention` flag is better for us TheRock users on Windows, we should try using PyTorch attention in the VAE too. There’s a recent PR that hasn’t been merged yet (Idk if it ever will) that makes this possible for rdna4 if we merge it locally. I've tried it and now I get:

`Using pytorch attention in VAE`

Doesn't make that much of a difference tho. At least based on my testing

**Comment by wasd-tech** [comment]
@Nem404 let me know if it works!

**Comment by subunder** [comment]
> Yeah sure, worth a try!

Here's my 2nd run without the `PYTORCH_CUDA_ALLOC_CONF` things, so:
```
set COMMANDLINE_ARGS=--auto-launch --use-pytorch-cross-attention

set TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1

set MIOPEN_ENABLE_LOGGING=1
set MIOPEN_ENABLE_LOGGING_CMD=1
set MIOPEN_LOG_LEVEL=6
```

https://gist.github.com/Nem404/25a45a43d75a958be3733c27fc0f5928

> 
> > So 9.18 GiB is free, yet it can't allocate 1.12. ?_?
> > Btw I'm also using PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
> 
> Not sure about this one. I'm guessing the env var may have affected it?

Got a similar thing again: 9.12 GiB is free, yet it cant allocate 1.12 GiB

**Comment by subunder** [comment]
> [@Nem404](https://github.com/Nem404) let me know if it works!

Using the `set MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_FWD=0` env var I've got an error:

```
MIOpen Error: C:/home/runner/_work/TheRock/TheRock/rocm-libraries/projects/miopen/src/ocl/convolutionocl.cpp:584: No suitable algorithm was found to execute the required convolution
!!! Exception during processing !!! miopenStatusUnknownError
Traceback (most recent call last):
  File "C:\Users\nem404\New_folder\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Users\nem404\New_folder\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\custom_nodes\comfyui-inpaint-nodes\nodes.py", line 219, in encode
    positive, negative, latent = nodes.InpaintModelConditioning().encode(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\nodes.py", line 439, in encode
    concat_latent = vae.encode(pixels)
                    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\comfy\sd.py", line 714, in encode
    out = self.first_stage_model.encode(pixels_in).to(self.output_device).float()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\comfy\ldm\models\autoencoder.py", line 190, in encode
    z = self.encoder(x)
        ^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 591, in forward
    h = self.conv_in(x)
        ^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\comfy\ops.py", line 143, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\venv\Lib\site-packages\torch\nn\modules\conv.py", line 548, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\venv\Lib\site-packages\torch\nn\modules\conv.py", line 543, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
RuntimeError: miopenStatusUnknownError
```

**Comment by wasd-tech** [comment]
@Nem404 I am very sorry, I didn't understand that you are on Windows. I use Linux. But this means that the bugged kernels that miopen uses on Linux are the main used on Windows?

**Comment by subunder** [comment]
> [@Nem404](https://github.com/Nem404) I am very sorry, I didn't understand that you are on Windows. I use Linux.

No problem, thanks for your suggestion! You were just trying to help me. :)

**Comment by subunder** [comment]
> 
> But this means that the bugged kernels that miopen uses on Linux are the main used on Windows?

Yes, I think so too, there's smth about MIOpen on Windows that isn't right

**Comment by subunder** [comment]
Waaaaaaaaaait a minute


As  @ouco1986 suggested:
> 
> Adding
> 
> import torch 
> torch.backends.cudnn.enabled = False
> 
> to ComfyUI/main.py

This way, it avoids any OOMs and provides about the same speed as using MIOpen.

Confirmed that `torch.backends.cudnn.enabled = False` works, as I've left:
> 
> set MIOPEN_ENABLE_LOGGING=1
> set MIOPEN_ENABLE_LOGGING_CMD=1
> set MIOPEN_LOG_LEVEL=6

In the starting script, and it didn't give any MIOpen-related logs. So MIOpen was disabled as a whole.

**Comment by subunder** [comment]
> 
> Yes, I think so too, there's smth about MIOpen on Windows that isn't right

So this is kinda confirmed now

**Comment by wasd-tech** [comment]
@Nem404 Can you try a new combination? You can try `--cache-none` and also not set ` TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1`, but leave it disabled. I managed to create the image and also to decode it with the tiled VAE. The first run will be slow (exactly as on Linux), but after that it will be as fast as on Linux. I tried it on my 9070 xt.
I used `--use-pytorch-cross-attention --cache-none --disable-smart-memory --bf16-vae` with ComfyUI.

**Comment by subunder** [comment]
@wasd-tech The env var `set TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1` makes AOTriton work (on the gfx1200). Without it, I cant use flash or mem-eff attention at all. It's like a 50% decrease in performance. Not worth avoiding it in my op.

> I managed to create the image and also to decode it with the tiled VAE.

Tiled VAE also isn’t an option in my workflow.

**Comment by wasd-tech** [comment]
@Nem404 I don't want to contradict you but if it is necessary for attention why I have the exact same speed on Linux and on Windows? It's really strange. I actually use that env var on Linux so I'm speechless.

(For reference: 4.5 it/s)

**Comment by subunder** [comment]
> [@Nem404](https://github.com/Nem404) I don't want to contradict you but if it is necessary for attention why I have the exact same speed on Linux and on Windows? It's really strange. I actually use that env var on Linux so I'm speechless.

I’m not too confident about these things either, but I know someone who is: @jammm

Edit: Oh, so `TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1` is needed on the gfx1200, because it’s in the experimental support stage.

**Comment by subunder** [comment]
@wasd-tech
Which gpu do you have?

**Comment by wasd-tech** [comment]
> Which gpu do you have?

@Nem404 
rx 9070 xt

**Comment by subunder** [comment]
Still, disabling MIOpen by hardcoding `torch.backends.cudnn.enabled = False` in the script doesn’t feel right. It should be better for us to use MIOpen in my op.

**Comment by subunder** [comment]
> rx 9070 xt

I thought the gfx1201 is fully supported by AOTriton and doesn’t need the `experimental` flag. I could be wrong tho

Do you use the latest nightly wheels? I think there are still people using Jam's old wheels, which are not the same.

**Comment by wasd-tech** [comment]
> Do you use the latest nightly wheels? I think there are still people using Jam's old wheels, which are not the same.

Of course, I use the ones from: https://rocm.nightlies.amd.com/v2/gfx120X-all/

**Comment by subunder** [comment]
> 
> Of course, I use the ones from: https://rocm.nightlies.amd.com/v2/gfx120X-all/

Then Idk. But this is not a problem, I'm just saying that without the `TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1` env var, I can't use flash or mem-eff attention on my gfx1200 at all. I'm 100% sure

**Comment by subunder** [comment]
> 
> Thanks! i've shared this internally and we're investigating.

I hope the devs can make MIOpen work better, because based on my testing, disabling it helps me avoid OOMs while giving about the same performance. This isn’t how it should be. For me, every single MIOpen find mode gives OOMs. I've tried other wheels, deleting the ".miopen" folder, and all I could think of, but leaving MIOpen enabled gives the same outcome everytime.

**Comment by RandomGitUser321** [comment]
Are you guys making sure to clear your `%userprofile%/.miopen` folder between tests?

**Comment by subunder** [comment]
> Are you guys making sure to clear your `%userprofile%/.miopen` folder between tests?

Yes.

**Comment by RandomGitUser321** [comment]
Try the 2.10.0a0+rocm7.9.0rc20250923 build. It seems to work a lot better than the builds prior to it. I'm on a 7900xt though, so it may be different. I've had zero issues with slow vae encode/decoding now.

```
torch                           2.10.0a0+rocm7.9.0rc20250923
torchaudio                      2.8.0a0+rocm7.9.0rc20250923
torchsde                        0.2.6
torchvision                     0.25.0a0+rocm7.9.0rc20250923
```

Also, make sure your .bat that launches ComfyUI has set TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1 before running python main.py

For instance, this is what my run.bat looks like:
```
set TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
set MIOPEN_FIND_MODE=FAST
set MIOPEN_LOG_LEVEL=3
.\venv\scripts\python.exe -s ComfyUI\main.py --disable-smart-memory --use-pytorch-cross-attention
pause
```

I'd have to test the differences with MIOPEN being set to default vs fast though. Fast works well enough for me at the moment.

Using a simple workflow where I load the Wan2.1 VAE, set an EmptyHunyuanLatentVideo to 720x480x49, decode it and then preview it (to be able to run the workflow, there has to be an output), here is my ComfyUI log:
```
got prompt
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.float16
Requested to load WanVAE
loaded completely 15000.3671875 242.02829551696777 True
Prompt executed in 14.06 seconds
```

Here's a 1024x1024 Flux output (used KJNodes load VAE to set it to fp32, otherwise, it will give a black image. You can also add the --fp32-vae flag to the run.bat, but then things like WAN will use a ton more memory, so the node makes it easy to set it to whatever you want, without having to restart):
```
got prompt
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
Requested to load AutoencodingEngine
loaded completely 10766.875 319.7467155456543 True
Prompt executed in 1.79 seconds
```
Keep in mind that the split attention in VAE part is a ComfyUI thing, they changed it a while back for AMD cards, to prevent some crashes.

**Comment by wasd-tech** [comment]
@RandomGitUser321 @Nem404 I know this is off topic, but do you use the multigpu extension? I am having a hard time making it work consistently.

**Comment by subunder** [comment]
> [@RandomGitUser321](https://github.com/RandomGitUser321) [@Nem404](https://github.com/Nem404) I know this is off topic, but do you use the multigpu extension? I am having a hard time making it work consistently.

No, Im using a single gpu. It's really alone tho XD

**Comment by subunder** [comment]
> 
> Try the 2.10.0a0+rocm7.9.0rc20250923 build. It seems to work a lot better than the builds prior to it. I'm on a 7900xt though, so it may be different. I've had zero issues with slow vae encode/decoding now.

So you mean you had issues with the wheels before 20250923, but they’re gone now?

> 
> Also, make sure your .bat that launches ComfyUI has set TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1 before running python main.py

Yes, I'm using `TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1`, without it, no flash or mem-eff atten on my gfx1200.

> 
> For instance, this is what my run.bat looks like:
> 
> ```
> set TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
> set MIOPEN_FIND_MODE=FAST
> set MIOPEN_LOG_LEVEL=3
> .\venv\scripts\python.exe -s ComfyUI\main.py --disable-smart-memory --use-pytorch-cross-attention
> pause
> ```

Do we actually need `--disable-smart-memory`? Based on my runs, leaving it enabled makes things a bit better, not worse.

> 
> Keep in mind that the split attention in VAE part is a ComfyUI thing, they changed it a while back for AMD cards, to prevent some crashes.

Yes, I know. But given that `--use-pytorch-cross-attention` works better for us, it would make sense to use `pytorch attention` in the VAE as well. I’ve tried it, and it doesn’t cause any more crashes than `split attention` (for me, locally).

**Comment by RandomGitUser321** [comment]
> So you mean you had issues with the wheels before 20250923, but they’re gone now?

Yeah, I'd get slow VAE encodes/decodes on the first run with a new resolution or frame count. Now, I don't seem to have that issue anymore.

> Do we actually need `--disable-smart-memory`

Probably not, but I don't like running the risk of random OOMs when Comfy fails to shuffle the models back to RAM before moving another model to VRAM. I don't want anything lingering in VRAM between steps. Also, if you use GGUFs, they have their own nuances in how they handle memory management and Comfy's default systems don't work with them the same way. So if the VRAM is already filled with a GGUF model like WAN, Comfy may or may not correctly offload it first, before attempting to load the VAE and then decode. If it doesn't offload correctly or at all, then you're going to OOM.

> Yes, I know. But given that `--use-pytorch-cross-attention` works better for us, it would make sense to use `pytorch attention` in the VAE as well. I’ve tried it, and it doesn’t cause any more crashes than `split attention` (for me, locally).

There's a discussion over in a PR on the Comfy repo about this topic: https://github.com/comfyanonymous/ComfyUI/pull/9956
I've tested it both ways and have had issues with OOMing, but I will test with the newer wheels, since they seem to be functioning better than the older ones I was using before.

Using the 0923 wheels:
Using split-attention on a 2048x2048 Flux empty latent->decode:
Prompt executed in 55.61 seconds

Editing out that part in model_management.py to bypass the AMD workaround and use pytorch attention:
scaled_dot_product_attention OOMed: switched to slice attention
Prompt executed in 60.79 seconds

And my memory peaked through the roof when it OOMed. It used up all my VRAM+Shared sysmem(extra 16gb to work with, so 20+16=36gb)

**Comment by subunder** [comment]
Looks like I need to try the 20250923 wheels

**Comment by RandomGitUser321** [comment]
> Looks like I need to try the 20250923 wheels

Just run `python.exe -m pip install -U --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/ --pre torch torchaudio torchvision` from your venv directory where the python.exe is.

If you ever want to rollback, it's pretty easy to pick the versions you want with a similar command.

But again, make sure your run.bat that launches ComfyUI has those
```
set TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
set MIOPEN_FIND_MODE=FAST
```
before launching main.py. You can't inline them with set XXXX && set YYYY && python.exe -s main.py etc etc etc because they won't actually apply to the session correctly.

**Comment by subunder** [comment]
What are the `-U`, and the `--pre` in it? I've used: `python -m pip install --index-url=https://rocm.nightlies.amd.com/v2/gfx120X-all/ torch torchvision torchaudio`. This also installs the wheels for me

**Comment by RandomGitUser321** [comment]
-U == --upgrade and --pre usually means prerelease/nightly. I'd recommend using both since this branch of pytorch is already a nightly thing anyways and I'm not sure how they flag them under the hood. Pre should make sure to use the absolute latest complete build of the wheels. Sometimes, things won't upgrade if you don't include the -U or --upgrade part. You could also use --force-reinstall as well, if you wanted to play it safe.

**Comment by subunder** [comment]
Uninstalled the old wheels first

**Comment by subunder** [comment]
Now I'm trying with:

> 
> ```
> set TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
> set MIOPEN_FIND_MODE=FAST
> set MIOPEN_LOG_LEVEL=3
> .\venv\scripts\python.exe -s ComfyUI\main.py --disable-smart-memory --use-pytorch-cross-attention
> pause
> ```
> 
Using the latest wheels from: `python.exe -m pip install -U --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/ --pre torch torchaudio torchvision`, which are:

> 
> torch                           2.10.0a0+rocm7.9.0rc20250923
> torchaudio                      2.8.0a0+rocm7.9.0rc20250923
> torchsde                        0.2.6
> torchvision                     0.25.0a0+rocm7.9.0rc20250923

**Comment by RandomGitUser321** [comment]
Good, that's usually what I do as well. But anyways, give them a try and report back if anything changes. Also, make sure to clear your .miopen folder to make sure testing is more accurate.

Since we are both on different generations of cards, you may or may not have the same results as I did, when upgrading.

**Comment by subunder** [comment]
I haven’t had that `.miopen` folder generated again since yesterday. I deleted it and, in the meantime, used Comfy without MIOpen - it’s way better for me.

**Comment by RandomGitUser321** [comment]
Then you probably aren't using AOTriton.

**Comment by subunder** [comment]
> Then you probably aren't using AOTriton.

Yes, I am (at least I think I'm using it)

**Comment by RandomGitUser321** [comment]
By using torch.backends.cudnn.enabled = False that was brought up earlier in this issue thread? If so, then that indirectly disables triton optimizations afaik.

**Comment by subunder** [comment]
> By using torch.backends.cudnn.enabled = False that was brought up earlier in this issue thread? If so, then that indirectly disables triton optimizations afaik.

Then shouldn't it be way slower?

**Comment by subunder** [comment]
> Now I'm trying with:
> 
> > ```
> > set TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
> > set MIOPEN_FIND_MODE=FAST
> > set MIOPEN_LOG_LEVEL=3
> > .\venv\scripts\python.exe -s ComfyUI\main.py --disable-smart-memory --use-pytorch-cross-attention
> > pause
> > ```
> 
> Using the latest wheels from: `python.exe -m pip install -U --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/ --pre torch torchaudio torchvision`, which are:
> 
> > torch                           2.10.0a0+rocm7.9.0rc20250923
> > torchaudio                      2.8.0a0+rocm7.9.0rc20250923
> > torchsde                        0.2.6
> > torchvision                     0.25.0a0+rocm7.9.0rc20250923

Got two OOMs in a row with this setup. The first when it loads the model, the last one at VAE stage. Flickering black screen too

Edit: I meant driver timeout, not an actual OOM based on what the console prints

**Comment by RandomGitUser321** [comment]
> Then shouldn't it be way slower?

Not always. It depends on what you're doing. In things like sampling a WAN model, a good chunk of the it/s time is all the back and forth between CPU<>GPU, so the gains might be far lower than a raw benchmark.

> Got two OOMs in a row with this setup.

What and how are you testing?

Actually, what card do you have, what model are you trying to use(including quantization options), and what resolution/batch/frame count are you trying to generate?

**Comment by subunder** [comment]
> What and how are you testing?
> 
> Actually, what card do you have, what model are you trying to use(including quantization options), and what resolution/batch/frame count are you trying to generate?

gpu: gfx1200 16 GB
model: [Juggernaut XL](https://civitai.com/models/133005/juggernaut-xl)
Any parameters like resolution/batch/etc. are managed solely by the [krita-ai-diffusion](https://github.com/Acly/krita-ai-diffusion) plugin in [ComfyUI](https://github.com/comfyanonymous/ComfyUI). It doesn't use any quantization, because it's an just average SDXL model.
But I’m using the exact same image without changing anything, and leaving MIOpen enabled I get either a driver timeout or an OOM every time. Setting `torch.backends.cudnn.enabled = False` avoids all issues for me.

**Comment by subunder** [comment]
I know that this isn’t the best way to test these things, but the only reason I need generative AI on my PC is [Krita](https://github.com/KDE/krita). That’s all.

**Comment by subunder** [comment]
Got a different kind of error, probably because now I started using the default `split attention in VAE` suggested by @RandomGitUser321. I didn’t get this error when I was using `pytorch attention in VAE` at all.

```
...
MIOpen(HIP): Info [get_device_name] Raw device name: gfx1200
MIOpen(HIP): Info [SetStream] stream: 0000000000000000, device_id: 0
MIOpen(HIP): Command [LogCmdConvolution] MIOpenDriver.exe convbfp16 -n 1 -c 512 -H 147 -W 112 -k 512 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Info [ConvolutionForward] algo = 0, workspace = 0
MIOpen(HIP): Info2 [GetInvoker] Returning an invoker for problem 512x147x112x1x1x512x147x112x1xNCHWxBF16x0x0x1x1x1x1x1xFxDefault and algorithm miopenConvolutionFwdAlgoGEMM
MIOpen(HIP): Info2 [CallGemmStridedBatched] gemm_desc: {isColMajor 0, transA 0, transB 0, m 512, n 16464, k 512, lda 512, ldb 16464, ldc 16464, batch_count 1, strideA 0, strideB 8429568, strideC 8429568, alpha 1, beta 0, dataType bfloat16, a_cast_type bfloat16, b_cast_type bfloat16}
MIOpen(HIP): Info2 [CallGemmStridedBatched] rocBLAS
MIOpen(HIP): Info [get_device_name] Raw device name: gfx1200
MIOpen(HIP): Info [SetStream] stream: 0000000000000000, device_id: 0
MIOpen(HIP): Command [LogCmdConvolution] MIOpenDriver.exe convbfp16 -n 1 -c 512 -H 147 -W 112 -k 512 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Info [ConvolutionForward] algo = 0, workspace = 0
MIOpen(HIP): Info2 [GetInvoker] Returning an invoker for problem 512x147x112x1x1x512x147x112x1xNCHWxBF16x0x0x1x1x1x1x1xFxDefault and algorithm miopenConvolutionFwdAlgoGEMM
MIOpen(HIP): Info2 [CallGemmStridedBatched] gemm_desc: {isColMajor 0, transA 0, transB 0, m 512, n 16464, k 512, lda 512, ldb 16464, ldc 16464, batch_count 1, strideA 0, strideB 8429568, strideC 8429568, alpha 1, beta 0, dataType bfloat16, a_cast_type bfloat16, b_cast_type bfloat16}
MIOpen(HIP): Info2 [CallGemmStridedBatched] rocBLAS
C:\Users\nem404\New_folder\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py:227: UserWarning: bgemm_internal_cublaslt error: HIPBLAS_STATUS_INTERNAL_ERROR when calling hipblasLtMatmul with transpose_mat1 0 transpose_mat2 1 m 16464 n 16464 k 512 lda 16464 ldb 16464 ldc 16464 abType 14 cType 14 computeType 2 scaleType 0. Will attempt to recover by calling cublas instead. (Triggered internally at B:\src\torch\aten\src\ATen\hip\HIPBlas.cpp:560.)
  s1 = torch.bmm(q[:, i:end], k) * scale
!!! Exception during processing !!! CUDA error: HIPBLAS_STATUS_ALLOC_FAILED when calling `hipblasCreate(handle)`
Traceback (most recent call last):
  File "C:\Users\nem404\New_folder\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "C:\Users\nem404\New_folder\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\custom_nodes\comfyui-inpaint-nodes\nodes.py", line 219, in encode
    positive, negative, latent = nodes.InpaintModelConditioning().encode(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\nodes.py", line 439, in encode
    concat_latent = vae.encode(pixels)
                    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\comfy\sd.py", line 714, in encode
    out = self.first_stage_model.encode(pixels_in).to(self.output_device).float()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\comfy\ldm\models\autoencoder.py", line 190, in encode
    z = self.encoder(x)
        ^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1777, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1788, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 602, in forward
    h = self.mid.attn_1(h)
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1777, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1788, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 343, in forward
    h_ = self.optimized_attention(q, k, v)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 255, in normal_attention
    r1 = slice_attention(q, k, v)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nem404\New_folder\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 227, in slice_attention
    s1 = torch.bmm(q[:, i:end], k) * scale
         ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: HIPBLAS_STATUS_ALLOC_FAILED when calling `hipblasCreate(handle)`

```

Doesn’t `slice_attention` in the logs refer to `split attention`, which I’ve started using in the VAE? Or is it a completely different thing?

**Comment by mordekai2025** [comment]
I had to combine --disable-smart-memory and torch.backends.cudnn.enabled = False
to sort out all issues at once and it ran perfectly in ComfyUI with fast VAE Decode (Not tiled!) and KSampler, even at higher image resolution.  For the workarounds at least. With --pytorch-cross-attention on startup by default.

No more OOM, no need for VAE Decode (tiled) etc. Fast and smooth as heavy stuttering and extreme slowdowns was gone as well through KSampler (smaller or larger than 1024x1024 px).

Pure out of the box experience with zero special flags. No third party nodes. No miopen, pytorch, ... flags etc. Basic workflows. Affected both on Windows and Linux.
Even with the latest pytorch ROCm 7.0.0 wheel (23 September 2025) for Windows automaticially provided via ComfyUI (v.0.3.60) / Stability Matrix.
For Fedora WS 42 it was pytorch ROCm 6.4 Nightly (via official pytorch website).

GPU: Radeon RX 9070 16GB. 
ComfyUI ROCm installed via Stability Matrix on Windows and Linux.


Just telling from my experience.

**Comment by subunder** [comment]
Thx @mordekai2025 for sharing your findings, so we have one more person with the same MIOpen issue as me. Disabling it entirely works much better.

**Comment by mordekai2025** [comment]
I'll test enabled Smart Memory Management and torch.backends.cudnn.enabled = False in ComfyUI to see if it behaves the same or different.

**Comment by subunder** [comment]
>
> Doesn’t slice_attention in the logs refer to split attention, which I’ve started using in the VAE? Or is it a completely different thing?

Still not sure about this, but the only thing I changed was going back to using `Using pytorch attention in VAE`, and now I don't get the same error.

**Comment by subunder** [comment]
> I'll test enabled Smart Memory Management and torch.backends.cudnn.enabled = False in ComfyUI to see if it behaves the same or different.

For me, it’s the same, except that if I leave smart memory enabled, the console prints `Unloaded 1 model`, or sometimes 0. I think this is useful in some workflows tho, unloading models to free up more vram

**Comment by subunder** [comment]
Updating the title to reflect that this is now clearly a MIOpen-related issue.
I’m wondering whether TheRock folks will forward it, or if I should file an issue over there myself.

**Comment by RandomGitUser321** [comment]
It definitely seems like a MIOpen issue, but you guys might be onto something with the torch.backends.cudnn.enabled = False. I ran some tests and the sampling times were roughly identical, but the overall execution time was much lower (accounting for the loading of models, clip encoding and vae decoding). These are first run times:

**Without modification**
```
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [01:20<00:00,  2.69s/it]
Requested to load AutoencodingEngine
loaded completely 11921.9375 319.7467155456543 True
Prompt executed in 119.49 seconds
```

**With torch.backends.cudnn.enabled = False added to main.py**
```
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [01:21<00:00,  2.73s/it]
Requested to load AutoencodingEngine
loaded completely 11953.9375 319.7467155456543 True
Prompt executed in 99.46 seconds
```

Here is the result of the most basic Flux test with an empty 2048x2048->vae decode->preview image:
```
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
Requested to load AutoencodingEngine
loaded partially 128.0 127.99951171875 0
Warning: Ran out of memory when regular VAE decoding, retrying with tiled VAE decoding.
Prompt executed in 30.60 seconds
```

So 30 seconds vs 55 seconds in one of my earlier posts, but it didn't pop up the scaled_dot_product_attention OOMed: switched to slice attention thing either.

**Comment by subunder** [comment]
Idk but I've never in my whole life seen anything like that "scaled_dot_product_attention OOMed: switched to slice attention" thing in Comfy.

**Comment by RandomGitUser321** [comment]
> Idk but I've never in my whole life seen anything like that "scaled_dot_product_attention OOMed: switched to slice attention" thing in Comfy.

Oops, my bad:

> Using the 0923 wheels:
> Using split-attention on a 2048x2048 Flux empty latent->decode:
> Prompt executed in 55.61 seconds
> 
> Editing out that part in model_management.py to bypass the AMD workaround and use pytorch attention:
> scaled_dot_product_attention OOMed: switched to slice attention
> Prompt executed in 60.79 seconds

From my earlier post. That message came from me forcing Comfy to use pytorch attention on VAE decode. But even without that edit, it was still ~56 seconds for a VAE decode of the same latent size vs the ~31 just now with the torch.backends.cudnn.enabled = False.

**Comment by subunder** [comment]
I see

**Comment by subunder** [comment]
So it's really great: MIOpen does everything except what it's supposed to.

**Comment by RandomGitUser321** [comment]
I have little clue as to how MIOpen interacts with things like AOTriton. As far as I know, MIOpen is supposed to find optimizations to speed things up during subsequent runs and maybe make things use less VRAM? Not sure. All I know is that these wheels from the past couple weeks where they enabled AOTriton are still way faster than the older Scott wheels from earlier this year. Heavy hitters like WAN seems to work 1.5-2x as fast.

I suppose I should actually run some tests to see how much VRAM is being used with the different methods.

**Comment by rwfsmith** [comment]
I've had the same problem on my gfx1151 since I started testing TheRock's releases. Just took me 500 seconds to get through a 20 step Flux.1-Dev workflow at 1024x1024, only 72 seconds of that was for the sampling step, the rest of that was VAE decode. Ran it again immediately afterward and it was only 77 seconds total.

**Comment by subunder** [comment]
> I've had the same problem on my gfx1151 since I started testing TheRock's releases. Just took me 500 seconds to get through a 20 step Flux.1-Dev workflow at 1024x1024, only 72 seconds of that was for the sampling step, the rest of that was VAE decode. Ran it again immediately afterward and it was only 77 seconds total.

Another user with the same issue.

Btw what do you mean by "afterward", did you disable MIOpen as we did?

**Comment by rwfsmith** [comment]
> Another user with the same issue.
> 
> Btw what do you mean by "afterward", did you disable MIOpen as we did?

I didn't disable anything, only enabled AOTriton. I meant if I generate another image immediately after the first one, without it needing to reload the models, it completes the VAE step in just a few seconds instead of several minutes. 

edit:

Seems like disabling MIOpen just prevents crashing and OOMs? I don't hit those problems, but it probably helps that I have 110gb of available VRAM, so it's hard to OOM it. It used to crash on the VAE step for me sometimes on older builds, especially when running at higher resolutions, though I don't know why it did or why it's fine now.

**Comment by wasd-tech** [comment]
I want to emphasize that these problems are identical to the ones in Linux. For example, I experience the same behavior as @rwfsmith with an rx 9070 xt. After reading about this issue, I think the bad kernels used by Miopen are related to this environment variable:
`export MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_FWD=0`
Disabling these resolves the issue on Linux, but it seems that these are the only ones used on Windows. I am not a developer, so I could be wrong, but when @Nem404 used the filter, nothing was generated.

**Comment by rwfsmith** [comment]
I'm suddenly not able to reproduce it today. The first run is slightly slower, but that's likely due to just loading the models.

**Comment by subunder** [comment]
> I want to emphasize that these problems are identical to the ones in Linux. For example, I experience the same behavior as [@rwfsmith](https://github.com/rwfsmith) with an rx 9070 xt. After reading about this issue, I think the bad kernels used by Miopen are related to this environment variable: `export MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_FWD=0` Disabling these resolves the issue on Linux, but it seems that these are the only ones used on Windows. I am not a developer, so I could be wrong, but when [@Nem404](https://github.com/Nem404) used the filter, nothing was generated.

Yeah, setting `MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_FWD=0` on Windows doesn’t seem to improve anything (at least for me). AFAIK this prevents MIOpen from using the "naive direct convolution" algorithm, and forces it to use other ones.

**Comment by subunder** [comment]
> 
> Seems like disabling MIOpen just prevents crashing and OOMs? 

Yes. This issue wasn’t opened for AOTriton itself, but for driver timeouts and crashes at the VAE stage, which are caused by MIOpen.

**Comment by rwfsmith** [comment]
I tested some larger models (wan2.2) and started getting some OOMs. adding --disable-smart-memory and --reserve-vram 0.9 seems to have fixed my issues there, but I have to make sure to not add any of the other vram parameters like --highvram or --gpu-only or it breaks it.

**Comment by subunder** [comment]
@rwfsmith I'm curious what will happen in the same WAN 2.2 workflow if you don't use `--disable-smart-memory`, `--reserve-vram 0.9` or any other flags, but you disable MIOpen in ComfyUI's main.py, adding: 

```
import torch
torch.backends.cudnn.enabled = False
```

Can your try this pls?

**Comment by subunder** [comment]
Oh, so we got `PyTorch on Windows Preview with ROCm support` wheels from a company named AMD. XD

https://repo.radeon.com/rocm/windows/rocm-rel-6.4.4/torch-2.8.0a0%2Bgitfc14c65-cp312-cp312-win_amd64.whl

But I don’t understand. These wheels weren’t built with AOTriton, so there’s no flash or memory-efficient attention. I thought TheRock wheels would be integrated into the official PyTorch repo, but then why did AMD give the aforementioned wheels? They’re even behind TheRock ones in development in my opinion if there’s no SDPA at all.

**Comment by ScottTodd** [comment]
> These wheels weren’t built with AOTriton, so there’s no flash or memory-efficient attention.

I thought the 6.4 release would include aotriton but indeed, I don't see the lib/ files in those wheels. I can check on that.

> I thought TheRock wheels would be integrated into the official PyTorch repo, but then why did AMD give the aforementioned wheels?

That is still the plan, but it will take more time to fully roll out. We're catching up.

**Comment by subunder** [comment]
> 
> I thought the 6.4 release would include aotriton but indeed, I don't see the lib/ files in those wheels. I can check on that.

I can confirm there's no AOTriton at all, my test script says:

```
PyTorch version: 2.8.0a0+gitfc14c65
PyTorch ROCm version: 6.4.50101-9a6572ae7
CUDA available: True
Device count: 1
Device name: AMD Radeon RX 9060 XT
```

```
D:\Users\nem404\Documents\PyTorch_gfx1200\aotriton_test.py:107: UserWarning: Memory efficient kernel not used because: (Triggered internally at C:\develop\pytorch-test\aten\src\ATen\native\transformers\hip\sdp_utils.cpp:859.)
  output = torch.nn.functional.scaled_dot_product_attention(q, k, v)
D:\Users\nem404\Documents\PyTorch_gfx1200\aotriton_test.py:107: UserWarning: Flash attention kernel not used because: (Triggered internally at C:\develop\pytorch-test\aten\src\ATen\native\transformers\hip\sdp_utils.cpp:861.)
  output = torch.nn.functional.scaled_dot_product_attention(q, k, v)
D:\Users\nem404\Documents\PyTorch_gfx1200\aotriton_test.py:107: UserWarning: Torch was not compiled with flash attention. (Triggered internally at C:\develop\pytorch-test\aten\src\ATen\native\transformers\hip\sdp_utils.cpp:675.)
  output = torch.nn.functional.scaled_dot_product_attention(q, k, v)
D:\Users\nem404\Documents\PyTorch_gfx1200\aotriton_test.py:107: UserWarning: CuDNN attention kernel not used because: (Triggered internally at C:\develop\pytorch-test\aten\src\ATen\native\transformers\hip\sdp_utils.cpp:863.)
  output = torch.nn.functional.scaled_dot_product_attention(q, k, v)
D:\Users\nem404\Documents\PyTorch_gfx1200\aotriton_test.py:107: UserWarning: Torch was not compiled with cuDNN attention. (Triggered internally at C:\develop\pytorch-test\aten\src\ATen\native\transformers\hip\sdp_utils.cpp:618.)
  output = torch.nn.functional.scaled_dot_product_attention(q, k, v)

```

While TheRock wheels don’t give any errors to this script, they can use flash and mem-eff atten.


> 
> That is still the plan, but it will take more time to fully roll out. We're catching up.

Looking forward to seeing the progress!

I just don’t see the point of rolling out those "preview" wheels while we have The Rock wheels that work much better.

**Comment by ScottTodd** [comment]
Confirmed that aotriton is not there in the 6.4 release. It's planned but I can't comment on the timeline. We'll be working to keep it enabled in the nightly builds produced here so that it can continue to mature and reach stable releases when they are ready.

**Comment by rwfsmith** [comment]
> [@rwfsmith](https://github.com/rwfsmith) I'm curious what will happen in the same WAN 2.2 workflow if you don't use `--disable-smart-memory`, `--reserve-vram 0.9` or any other flags, but you disable MIOpen in ComfyUI's main.py, adding:
> 
> ```
> import torch
> torch.backends.cudnn.enabled = False
> ```
> 
> Can your try this pls?

I added it to the start of main.py  and just ran main.py by itself without any flags. I still had the AOTriton flag enabled, and it completed successfully, but the video was just a gray box. Disabled the Triton flag, restarted, and it gets an OOM almost immediately after starting the workflow.

torch.OutOfMemoryError: HIP out of memory. Tried to allocate 59.88 GiB. GPU 0 has a total capacity of 107.87 GiB of which 87.93 GiB is free. Of the allocated memory 15.38 GiB is allocated by PyTorch, and 3.09 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by subunder** [comment]
@rwfsmith I see. So your case isn't exactly like mine.

**Comment by CS1o** [comment]
Can confirm this too for gfx1100.

**Comment by subunder** [comment]
> Can confirm this too for gfx1100.

Looks like we have more and more users with the same issue. The devs really need to do smth abt this

**Comment by RandomGitUser321** [comment]
> The devs really need to do smth abt this

Definitely sliding into the realm of sounding demanding and impatient. That's not a nice tone to have... We aren't entitled to anything here and I'd rather them take their time working on things, than rush through stuff, which usually results in more problems. If you really want to have all the bells and whistles now, dual-boot your PC with a Linux installation.

**Comment by subunder** [comment]
> 
> Definitely sliding into the realm of sounding demanding and impatient. That's not a nice tone to have... We aren't entitled to anything here and I'd rather them take their time working on things, than rush through stuff, which usually results in more problems. If you really want to have all the bells and whistles now, dual-boot your PC with a Linux installation.

What I meant is that they should start by looking at the errors affecting the majority of users. That's it. 
I've waited here at the TheRock repo for gfx1200 support for two whole months. I’m nowhere near being impatient.

**Comment by Kademo15** [comment]
> What I meant is that they should start by looking at the errors affecting the majority of users. That's it. I've waited here at the TheRock repo for gfx1200 support for two whole months. I’m nowhere near being impatient.

Look the thing is I have been waiting for rocm on windows since 2 years now, amd has been neglecting their rdna cards when it comes to AI for a long time and now have a lot of catching up to do. They split their architectures so stuff that gets developed for their cdna architecture doesn't work on rdna gpus because rdna gpus weren't build to run ai stuff. AMD has been silent the past 2 years and then "theRock" came. When I look at what these guys here have achieved in months what wasn't done for years I think you are being impatient. "theRock" is a small team so you could blame cooperate AMD for not attributing more resources to this but not the "theRock" team. Furthermore you talk about "majority of users", you have no idea how small our majority of users is when talking in the scale of AMD.

TLDR. Cut the guys from "theRock" some slack they are doing gods work.

**Comment by RandomGitUser321** [comment]
> TLDR. Cut the guys from "theRock" some slack they are doing gods work.

Exactly, I'm just glad we've got some wheels working well enough to handle some of the more taxing models like WAN without OOMing or constant errors.

> I've waited here at the TheRock repo for gfx1200 support for two whole months.

And you could have easily dual-boot installed Linux within that two whole months, if it were that big of an urgent issue. Also, if all you do is stuff with models like SDXL or Flux, you can probably just stick to the older Scott wheels from earlier this year.

**Comment by subunder** [comment]
You guys just come here to tell others what to do.
Have I badmouthed AMD? No.
Have I said anything bad about The Rock? No.
If I were that annoying, then just ban me and close this issue as if it never happened. I'll never come back.
Sorry I was born.

**Comment by Kademo15** [comment]
> You guys just come here to tell others what to do.
> Have I badmouthed AMD? No.
> Have I said anything bad about The Rock? No.
> If I were that annoying, then just ban me and close this issue as if it never happened. I'll never come back.
> Sorry I was born.

No one is mad at you and I didn't bad mouth you either all I was saying is that it was way worse in the past and the "theRock" team is working a lot and have achieved a lot. So we should be patient they are getting there. 
I understand the frustration I've been there.

**Comment by subunder** [comment]
> all I was saying is that it was way worse in the past and the "theRock" team is working a lot and have achieved a lot. So we should be patient they are getting there.

I agree.

**Comment by subunder** [comment]
Oh, so we have `status: assessed` now. Good to know the devs have identified the root cause :)

**Comment by subunder** [comment]
Could https://github.com/ROCm/rocm-libraries/pull/3414 theoretically help with this issue?
Or should I wait for a build that includes this commit and then try?

**Comment by CS1o** [comment]
The Problem with VAE Decode (when upscaling by 2) using insane amount of VRAM and dropping into shared vram (and sometimes crashing the gpu driver) is still present, with the recent TheRock builds and even with the new released ROCm 7.2 :/

It got better on ComfyUI, but there after running a VAE Decode once successfully, the Gens it/s after that are slowed by half for normal sampling steps and hires. So Tiled VAE Decode is still mandatory to mitigate this issue.

For Forge Neo it still fills the whole VRAM + Shared VRAM and then crashes the GPU Driver while Freezing the PC. Tiled VAE setting fixes it.
Very Strange behaviour on ReForge, there the first run fills boath vram and shared vram to 98% and then sits there for 10 minutes. Then after its done, every new hires fix gen doesnt drop into shared memory that much and it gens very fast.

**Comment by Apophis3158** [comment]
btw check this out Comfy-Org/ComfyUI#12685

**Comment by pinea00** [comment]
I fixed it ，Vae takes only 7 seconds
only for Forge Neo
https://github.com/pinea00/ROCM-7-VAE-BUG-FIX-for-forge-neo
The preset parameters are for 1024*1024.
comfyui also overcomes this in the same way.

**Comment by subunder** [comment]
No longer appears to be an issue with the current nightlies. Closing.
