### ISSUE TITLE
[Issue]: Comfyui Ksampler error(HIP error: an illegal memory access was encountered)

### ISSUE THREAD

**Issue by aigengen5-ship-it** [ROCm/TheRock#1795]
### Problem Description

Hi, thank you for your help as always.

Lastest ROCK has a great performance improvement(x2 or more?) than ROCM 6.4.4. 
But there is a problem during Comfyui processing as below. **An illegal memory access was encountered.** 
Some users may have same issue but I can't find there is any clue or solution to avoid this issue.

Here is my log from Comfyui. Tiled VAE does not help to avoid this issue since it is generated from Ksampler itself. Resolution is 1536x1536. 

*

If there is no error, speed is super fast.
VAE load device: cuda:0, offload device: cuda:0, dtype: torch.float16
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:19<00:00,  1.50it/s]
Requested to load AutoencoderKL
0 models unloaded.
loaded completely 9.5367431640625e+25 159.55708122253418 True

After some images were generated, there was an error as below...

/home/TTTTT/AI/ComfyUI/comfy/k_diffusion/sampling.py:70: UserWarning: HIP warning: an illegal memory access was encountered (Triggered internally at /__w/TheRock/TheRock/external-builds/pytorch/pytorch/aten/src/ATen/hip/impl/HIPGuardImplMasqueradingAsCUDA.h:83.)
  sigma_up = min(sigma_to, eta * (sigma_to ** 2 * (sigma_from ** 2 - sigma_to ** 2) / sigma_from ** 2) ** 0.5)
 47%|████████████████████████████████████████████████████████████████████████████▌                                                                                       | 14/30 [00:09<00:10,  1.49it/s]
Exception in thread Thread-3 (prompt_worker):
Traceback (most recent call last):
  File "/home/TTTTT/AI/ComfyUI/execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/home/TTTTT/AI/ComfyUI/execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 741, in sample
    samples, images, gifs, preview = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler,
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 559, in process_latent_image
    samples = KSampler().sample(model, seed, steps, cfg, sampler_name, scheduler, positive, negative,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/nodes.py", line 1525, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/nodes.py", line 1492, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/comfy/sample.py", line 45, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/comfy/samplers.py", line 1161, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/comfy/samplers.py", line 1051, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/comfy/samplers.py", line 1036, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/comfy/samplers.py", line 1004, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/comfy/samplers.py", line 987, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/comfy/samplers.py", line 759, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/comfy/k_diffusion/sampling.py", line 220, in sample_euler_ancestral
    sigma_down, sigma_up = get_ancestral_step(sigmas[i], sigmas[i + 1], eta=eta)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TTTTT/AI/ComfyUI/comfy/k_diffusion/sampling.py", line 70, in get_ancestral_step
    sigma_up = min(sigma_to, eta * (sigma_to ** 2 * (sigma_from ** 2 - sigma_to ** 2) / sigma_from ** 2) ** 0.5)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.AcceleratorError: HIP error: an illegal memory access was encountered
Search for `hipErrorIllegalAddress' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__HIPRT__TYPES.html for more information.
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

### Operating System

24.04.2 LTS (Noble Numbat)

### CPU

AMD Ryzen 9 7950X3D 16-Core Processor

### GPU

AMD Radeon AI PRO R9700

### ROCm Version

ROCM Rock(Nightly)

**Comment by harakiru** [comment]
I have the exact same issue, the only pytorch version that doesn't give me this error is the stable 6.4 build from pytorch.org

**Comment by tcgu-amd** [comment]
@harakiru, @aigengen5-ship-it, Thanks for reaching out! How did you install ROCm and Pytorch? @harakiru are you also using 9070/9700? Thanks!

**Comment by aigengen5-ship-it** [comment]
Hi @tcgu-amd , thank you for your help. I installed official ROCM 7.0.2 and install latest(nightly) pytorch by using this command. 

python -m pip install \
  --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/ \
  --pre torch torchaudio torchvision

**Comment by harakiru** [comment]
> [@harakiru](https://github.com/harakiru), [@aigengen5-ship-it](https://github.com/aigengen5-ship-it), Thanks for reaching out! How did you install ROCm and Pytorch? [@harakiru](https://github.com/harakiru) are you also using 9070/9700? Thanks!

I installed pytorch by following the instructions on the releases page just like @aigengen5-ship-it. I've also made new virtual enviorments just to make sure there are no leftover packages. Im using a  9070xt. Currently all rocm 7.0 builds cause the same error whether its from the pytorch page or from https://rocm.nightlies.amd.com/v2/gfx120X-all/. I've also tried different combinations of pytorch 2.7/2.8/2.9 etc.

**Comment by aigengen5-ship-it** [comment]
https://github.com/comfyanonymous/ComfyUI/issues/10369

Same issue was reported in Comfyui github also.

**Comment by tcgu-amd** [comment]
@aigengen5-ship-it, yes, there appears to have been several reports on this issue. We are actively working on investigating it internally. Thank you for your patience!

**Comment by aigengen5-ship-it** [comment]
Hi @tcgu-amd , thank you for your help as always.

Since ROCM 7.1 does not resolve this issue, but there is a hint for 'reducing' Comfyui HIP error.
(Maybe it is acceptable for R9700 since it has enough VRAM)

Observation)
Errors were generated on those functions in 'comfy/model_management.py'.
get_free_memory(device)
soft_empty_cache

What I did)
If I comment out some functions related on 'free memory' or 'empty cache', it will help to prevent a Comfyui crash(not 100%).
Maybe there is a confliction between memory(cache) cleanup and normal operation. I hope it may help to resolve this issue.

Note) Even if I comment out those, there was a normal function HIP illegal memory access. Especially in 'face detailer' custom node.

**Comment by tcgu-amd** [comment]
@aigengen5-ship-it thanks for the hint. Yes I think the error certain occurs at a the edge between memory free/allocation. Right now I'm suspecting some subtle race condition, which might be why reducing the free memory operation can reduce the chance of the error. Great intuition.

**Comment by rsnel** [comment]
Partial workaround: since it appears to be a race condition, rather than disabling the functions, I added a delay to the start of 

```
def soft_empty_cache(force=False):
    time.sleep(1./1000.)
```

and

```
def get_free_memory(dev=None, torch_free_too=False):
    time.sleep(1./1000.)
```

With `import time` above the first instance.

It seems to be at least an order of magnitude more stable this way (haven't seen a crash yet).

**Comment by tcgu-amd** [comment]
> Partial workaround: since it appears to be a race condition, rather than disabling the functions, I added a delay to the start of
> 
> ```
> def soft_empty_cache(force=False):
>     time.sleep(1./1000.)
> ```
> 
> and
> 
> ```
> def get_free_memory(dev=None, torch_free_too=False):
>     time.sleep(1./1000.)
> ```
> 
> With `import time` above the first instance.
> 
> It seems to be at least an order of magnitude more stable this way (haven't seen a crash yet).

That's neat! Thanks for the hack!

**Comment by aigengen5-ship-it** [comment]
Hi @rsnel , thank you for your hack. I did some tests adding more sleep options.
1) HIP error issue may be resolved. 
2) Comfyui is hang during image generation, no error is occurred and just it is stalled. 
3) @tcgu-amd Is there any way to resolve this issue? Thank you!

**Comment by rsnel** [comment]
@aigengen5-ship-it : Sometimes the GPU becomes very slow, and it takes a while to pick up the pace, but not very often. Where did you put your other sleeps? I had to increase the delay from 0.001 s to 0.01 s to keep generation stable.

The bug is very weird, it looks like a 'free before allocate' as if the allocation of memory is queued and the freeing is immediate.

Edit: Well, since I haven't specified AMD_SERIALIZE_KERNEL=3 the bug could also appear elsewhere and be a use after free. Will use AMD_SERIALIZE_KERNEL=3 to see where te problem actually is.

Edit2: 
- I see the 'hang' also. In nvtop GPU is at 100%, but the power usage (W) is at 25%-33%. Nothing usefil seems to happen.
- Also with AMD_SERIALIZE_KERNEL=3 crashes are reported to happen in empty cache

**Comment by harakiru** [comment]
Tried out with the latest therock release but it still crashes immediately, also adding delays didn't make any difference.

**Comment by rsnel** [comment]
@harakiru: It's pity that the delays don't help. Maybe try the kernel boot arguments of @mikealanni (edited, wrong tag previously) in presumably related bug  https://github.com/ROCm/ROCm/issues/5245#issuecomment-3505632266  (haven't tried it myself).

I'll stick with the version I have, which at least somewhat works, until @tcgu-amd encourages us here to try a new version.

**Comment by tcgu-amd** [comment]
Hi @harakiru sorry to hear that.. do you have the logs for the crash? What's the last thing displayed?

**Comment by harakiru** [comment]
> Hi [@harakiru](https://github.com/harakiru) sorry to hear that.. do you have the logs for the crash? What's the last thing displayed?

This happened while using the regular KSampler node, around the 2nd or 3rd step. The error message was:

“Memory access fault by GPU node-1 (Agent handle: 0x5de975b3cc80) on address 0x799bfc063000”
(the address may vary)

I didn’t have logging enabled at the time, so I don’t have logs right now. I can produce detailed logs and dumps this weekend if that would help. The crash blocked my current project, so I had to roll back to the stable PyTorch 6.4 release from pytorch.org to keep working.

**Comment by aigengen5-ship-it** [comment]
Hi @tcgu-amd , is there any possible test version after 7.0? Can we use ROCM 7.9 or nightly 7.1? Thank you!

**Comment by CSFFlame** [comment]
> [@harakiru](https://github.com/harakiru): It's pity that the delays don't help. Maybe try the kernel boot arguments of [@mikealanni](https://github.com/mikealanni) (edited, wrong tag previously) in presumably related bug [ROCm/ROCm#5245 (comment)](https://github.com/ROCm/ROCm/issues/5245#issuecomment-3505632266) (haven't tried it myself).
> 
> I'll stick with the version I have, which at least somewhat works, until [@tcgu-amd](https://github.com/tcgu-amd) encourages us here to try a new version.

Those kernel boot arguments stopped the crashing for me.  It's completely stable.  I'll try to isolate which argument is the one that matters (or if multiple do).

For reference:
> amdgpu.mcbp=0 amdgpu.cwsr_enable=0 amdgpu.queue_preemption_timeout_ms=1

As kernel boot args, for ubuntu/kubuntu that's adding them to /etc/default/grub, and then running update-grub, then rebooting.

Edit:
> amdgpu.cwsr_enable=0 

Appears to be the only one necessary and the one that stops crashing.

**Comment by Baake77** [comment]
> > [@harakiru](https://github.com/harakiru): It's pity that the delays don't help. Maybe try the kernel boot arguments of [@mikealanni](https://github.com/mikealanni) (edited, wrong tag previously) in presumably related bug [ROCm/ROCm#5245 (comment)](https://github.com/ROCm/ROCm/issues/5245#issuecomment-3505632266) (haven't tried it myself).
> > I'll stick with the version I have, which at least somewhat works, until [@tcgu-amd](https://github.com/tcgu-amd) encourages us here to try a new version.
> 
> Those kernel boot arguments stopped the crashing for me. It's completely stable. I'll try to isolate which argument is the one that matters (or if multiple do).
> 
> For reference:
> 
> > amdgpu.mcbp=0 amdgpu.cwsr_enable=0 amdgpu.queue_preemption_timeout_ms=1
> 
> As kernel boot args, for ubuntu/kubuntu that's adding them to /etc/default/grub, and then running update-grub, then rebooting.

Same. Adding those parameters as kernel boot args fixed it for me, too.
Before I tried every solution I could find (every driver, torch, rocm ...) with a lot of starting parameter combinations. Some things helped for a few image generations, but nothing was stable.

**Comment by harakiru** [comment]
I recently tried using the kernel boot options, and while they did allow ROCm 7.10 to work with my setup, the workflow took considerably longer than expected. I have not yet run detailed benchmarks, but it already appears to perform more slowly than version 6.4.

Additionally, it does not seem ideal for end users to have to modify kernel boot parameters in order to get RDNA4 cards working with the latest ROCm release.

I would appreciate it if you guys could look into this issue and work toward a solution that maintains performance. Please keep this issue open until it has been fully resolved.

Thank you for your time and effort.

**Comment by mikealanni** [comment]
> I recently tried using the kernel boot options, and while they did allow ROCm 7.10 to work with my setup, the workflow took considerably longer than expected. I have not yet run detailed benchmarks, but it already appears to perform more slowly than version 6.4.
> 
> Additionally, it does not seem ideal for end users to have to modify kernel boot parameters in order to get RDNA4 cards working with the latest ROCm release.
> 
> I would appreciate it if you guys could look into this issue and work toward a solution that maintains performance. Please keep this issue open until it has been fully resolved.
> 
> Thank you for your time and effort.

I didn’t experience any slowness in my workflow — in fact, it’s even faster now. For example, the default ComfyUI workflow that used to run in 3.80 seconds now runs in 3.25 seconds with flash-attention and some other flags enabled in ComfyUI. I’m still in the process of fine-tuning and cleaning up the flags to find the optimal setup for now, and we’ll wait for AMD to fix the ROCm/AMDGPU driver issue.

**Comment by aigengen5-ship-it** [comment]
From my side, there is no side effect. And latest ROCK(10/15)...works well without any hang or HIP error. Thank you! @CSFFlame

**Comment by CSFFlame** [comment]
After testing, it seems to be "amdgpu.cwsr_enable=0" that stops the crashing.  I removed the other 2 arguments without issues.

**Comment by harakiru** [comment]
Update: it seems that the newer torch version was causing the regression, installed torch 2.7+rocm7.1 and now its much faster. (of course i wouldn't say no to even further performance improvements but that's not relevant to this issue)

**Comment by int13h82** [comment]
> "amdgpu.cwsr_enable=0"

Thanks! Can confirm it works for my system either. Just added it to kernel command line - Comfy is stable now with the same PyTorch, venv and model which had the issue.

**Comment by mikealanni** [comment]
I’m really happy to help people resolve this issue. It took two weeks of trying every flag in ComfyUI, ROCm, and the AMDGPU driver.

**Comment by Blackfish95** [comment]
I'm running ComfyUI on ROCm 7.1 (amdgpu installer) amdgpu.cwsr_enable=0 worked for me too. 
I think I can probably edit my startup script a bit now to improve performance since its stable. I just ran 40+ images back to back with no errors!
Thanks!
Partial Startup log:
Total VRAM 16304 MB, total RAM 31749 MB
pytorch version: 2.8.0+rocm7.1.0.git7a520360
Set: torch.backends.cudnn.enabled = False for better AMD performance.
AMD arch: gfx1201
ROCm version: (7, 1)
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 AMD Radeon RX 9070 XT : native
Using pytorch attention
Python version: 3.12.3 (main, Aug 14 2025, 17:47:21) [GCC 13.3.0]
ComfyUI version: 0.3.68
ComfyUI frontend version: 1.28.8

launch script:
#!/usr/bin/env bash
# ============================================================
# ComfyUI ROCm 7.1 Optimized Launcher for RDNA4 (RX 9070 XT / gfx1201)
# Last Updated: 2025-11-03
#
# REVISION: Focused on stability for first-render crashes.
# - Re-enabled AMD_SERIALIZE_KERNEL=3 for testing.
# - Added TORCH_USE_ROCM_DSA=1 for HIP debugging.
# - Removed deprecated HSA_ENABLE_SDMA=0 and PYTORCH_NO_CUDNN=1.
# ============================================================
# === Environment setup ===
export ROCM_PATH=/opt/rocm
export AMD_SERIALIZE_KERNEL=1 # For illegal memory access debugging; hurts perf, remove if no help.
export TORCH_BLAS_PREFER_HIPBLASLT=0 # Avoid matrix op errors.
export COMFYUI_TORCH_COMPILE=0
export COMFYUI_DISABLE_METAL=1
export COMFYUI_FAST_LOAD=1
export TORCH_MPS_FALLBACK=0
export TORCH_USE_HIP_DSA=1 # Deeper HIP error tracing for crashes. changed from _RCOM_DSA
export HSA_ENABLE_SDMA=0

# Use HIP-specific allocator
export PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:512
# Change to ComfyUI directory
cd /home/<user>/ComfyUI
# === Activate venv ===
source venv/bin/activate
# === Print summary ===
echo "============================================================"
echo "Launching ComfyUI optimized for AMD RDNA4 (gfx1201) with ROCm 7.1"
echo "Python: $(python --version)"
echo "PyTorch: $(python -c 'import torch; print(torch.__version__)')"
echo "GPU: $(rocminfo | grep -m1 'Name:' | awk '{print $2}')"
echo "============================================================"
# === Launch parameters ===
python main.py \
    --normalvram \
    --use-pytorch-cross-attention \
    --disable-xformers \
    --preview-method auto \
    --cache-lru 1 \
    --reserve-vram 1024 \
    --disable-smart-memory \
    --verbose INFO \
    --listen 127.0.0.1 \
    --port 8188 \
    "$@"

**Comment by tcgu-amd** [comment]
Hi all, just a quick update, the official patch did not make it to 7.1.1. We are currently looking at a ROCm 7.2. 

For easier tracking purposes, I will be closing this issue since it has the same root cause as https://github.com/ROCm/ROCm/issues/5245. Please use that ticket for future updates. In the meantime, feel free to continue to use this issue as a forum for discussions. 

Thanks!

**Comment by crosson** [comment]
Can anyone comment on the perf differences with the amdgpu.cwsr_enable=0 fix, and moving to 7.1 as compared to rocm 6.4? Any improvements?

**Comment by mikealanni** [comment]
> Can anyone comment on the perf differences with the amdgpu.cwsr_enable=0 fix, and moving to 7.1 as compared to rocm 6.4? Any improvements?

I didn't notice anything. Now I don't know for very complex workflow

**Comment by codeliger** [comment]
7.1.1 is completely broken on 9070 XT for wan2.2. GGUF does not work anymore.

**Comment by crosson** [comment]
FYI I am running ROCM 7.2 right now and this appears fixed. Also the performance is FANTASTIC.

**Comment by codeliger** [comment]
> FYI I am running ROCM 7.2 right now and this appears fixed. Also the performance is FANTASTIC.

Which platform are you on? Did you build it from scratch?

**Comment by crosson** [comment]
Linux Mint following the official documentation released today. Im coming from ROCM 6.4. It's over a 100% perf boost. I ran a few test WAN renders at 5s (81 frames). 3 samplers at 6 steps used to take me 10 minutes. It's now down to ~175 seconds. An insane bump.


[ROCM](https://rocm.docs.amd.com/projects/radeon-ryzen/en/latest/docs/install/installrad/native_linux/install-radeon.html)


[Torch](https://rocm.docs.amd.com/projects/radeon-ryzen/en/latest/docs/install/installrad/native_linux/install-pytorch.html)
