### ISSUE TITLE
[Issue]: No GPU detected in simple Torch C++ example on Windows

### ISSUE THREAD

**Issue by charest** [ROCm/TheRock#1825]
### Problem Description

I am unable to detect a GPU with Torch's C++ frontend on Windows.  Example is built with clang-cl via CMake.

Build compiles and links successfully, but `torch::cuda::is_available()` returns `false`. Executing a call to a device function, like `torch::zeros(..., torch::Device(torch::kHIP))` throws an exception.

### Operating System

Windows 11 Pro 24H2 10/‎14/‎2025

### CPU

AMD EPYC 9V64 32-Core Processor

### GPU

AMD Radeon V710

### ROCm Version

7.0.0rc20250908

### Steps to Reproduce

Initialize python virtual environment:
```
python -m venv .venv
.venv\Scripts\Activate.bat
```
Install rocm and torch:
```
python -m pip install --index-url https://rocm.nightlies.amd.com/v2/gfx110X-dgpu/ "rocm[libraries,devel]==7.0.0rc20250908"
python -m pip install --index-url https://rocm.nightlies.amd.com/v2/gfx110X-dgpu/ --pre torch==2.9.0a0+rocm7.0.0rc20250908 torchaudio==2.8.0a0+rocm7.0.0rc20250908 torchvision==0.24.0a0+rocm7.0.0rc20250908
```
Load the rocm_sdk module to kick off init scripts:
```
python -m rocm_sdk path --root
```
Clone repo and build
```
git clone git@github.com:charest/torch-cpp-example

cd torch-cpp-example

cmake -B build -GNinja . -DCMAKE_PREFIX_PATH=.venv\Lib\site-packages\_rocm_sdk_devel;.venv\Lib\site-packages\torch -DCMAKE_HIP_PLATFORM=amd -DCMAKE_HIP_ARCHITECTURES=gfx1101 -DCMAKE_CXX_COMPILER=clang-cl.exe -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_FLAGS="--offload-arch=gfx1101"

cmake --build build
```
Run test:
```
build\torch_test.exe
```
Expected output:
```
GPU is available: Yes
Creating tensor...
Created data tensor
```
Actual output:
```
GPU is available: No
Creating tensor...
```

### Additional Information

`cdb.exe build\torch_test.exe` gives:

```
Processing 4 threads, please wait
*** WARNING: Unable to verify checksum for C:\Users\azureuser\sources\torch-cpp-example\build\torch_cpu.dll
*** WARNING: Unable to verify checksum for torch_test.exe

.  0  Id: 20d8.1784 Suspend: 1 Teb: 000000d7`fda26000 Unfrozen
      Start: torch_test!c10::ivalue::Object::~Object+0x62c0 (00007ff7`a375d0c0)
      Priority: 0  Priority class: 32  Affinity: ffffff
Child-SP          RetAddr           Call Site
000000d7`fdcfed40 00007fff`d9ab52c7 KERNELBASE!RaiseException+0x8a
000000d7`fdcfee40 00007fff`627d4eda VCRUNTIME140!_CxxThrowException+0x97
000000d7`fdcfeea0 00007fff`624246cc torch_cpu!c10::impl::OperatorEntry::reportError+0x57a
000000d7`fdcff220 00007fff`6382c185 torch_cpu!c10::impl::OperatorEntry::lookup+0xbc
000000d7`fdcff270 00007fff`6382c035 torch_cpu!at::_ops::empty_memory_format::redispatch+0x245
000000d7`fdcff350 00007fff`63cf96e7 torch_cpu!at::_ops::empty_memory_format::redispatch+0xf5
000000d7`fdcff410 00007fff`6382ab2f torch_cpu!at::_ops::_foobar_out::redispatch+0xb9d7
000000d7`fdcff4d0 00007fff`6269dff8 torch_cpu!at::_ops::empty_memory_format::call+0x1bf
000000d7`fdcff630 00007fff`62d74302 torch_cpu!at::functorch::reshape_dim_outof_symint+0x4a428
000000d7`fdcff6d0 00007fff`63de5862 torch_cpu!at::native::zeros_symint+0x382
000000d7`fdcff8d0 00007fff`6343da10 torch_cpu!at::compositeexplicitautograd::_efficientzerotensor_symint_outf+0x322
000000d7`fdcff930 00007fff`634714ba torch_cpu!at::_ops::randn::redispatch+0x330
000000d7`fdcffa10 00007fff`63d1007d torch_cpu!at::_ops::zeros::redispatch+0xea
000000d7`fdcffad0 00007fff`63470f09 torch_cpu!at::_ops::_foobar_out::redispatch+0x2236d
000000d7`fdcffb80 00007ff7`a3757143 torch_cpu!at::_ops::zeros::call+0x1a9
000000d7`fdcffce0 00007ff7`a3756fd4 torch_test!c10::ivalue::Object::~Object+0x343
000000d7`fdcffdb0 00007ff7`a375d050 torch_test!c10::ivalue::Object::~Object+0x1d4
000000d7`fdcffe40 00007ff8`0f9de8d7 torch_test!c10::ivalue::Object::~Object+0x6250
000000d7`fdcffe80 00007ff8`1096c53c KERNEL32!BaseThreadInitThunk+0x17
000000d7`fdcffeb0 00000000`00000000 ntdll!RtlUserThreadStart+0x2c

.  1  Id: 20d8.c90 Suspend: 1 Teb: 000000d7`fda28000 Unfrozen
      Start: ntdll!TppWorkerThread (00007ff8`10955bc0)
      Priority: 0  Priority class: 32  Affinity: ffffff
Child-SP          RetAddr           Call Site
000000d7`fddff808 00007ff8`10955f3e ntdll!NtWaitForWorkViaWorkerFactory+0x14
000000d7`fddff810 00007ff8`0f9de8d7 ntdll!TppWorkerThread+0x37e
000000d7`fddffb70 00007ff8`1096c53c KERNEL32!BaseThreadInitThunk+0x17
000000d7`fddffba0 00000000`00000000 ntdll!RtlUserThreadStart+0x2c

Total threads: 4
Duplicate callstacks: 2 (windbg thread #s follow):
2, 3
````

DependencyExplorer shows:
<img width="1906" height="1016" alt="Image" src="https://github.com/user-attachments/assets/a33dc0fb-4c85-4f32-9b0c-2cabad68c861" />

**Comment by schung-amd** [comment]
Thanks for the report and reproducer, was able to repro this and will look into it.

**Comment by charest** [comment]
Some progress.  Now the GPU is detected, but `torch::zeros` doesn't seem to complete properly:
```
GPU is available: Yes
Creating tensor...
```

To reproduce:
*  Added `/WHOLEARCHIVE` to force adding all object files in the library to the executable.  This seems to be for static libraries, but `torch_hip` is a DLL.  In my example's `CMakeLists.txt` I added the following:
    ```
    find_library(TORCH_HIP_LIBRARY torch_hip PATHS "${TORCH_INSTALL_PREFIX}/lib")
    target_link_libraries(torch_test PRIVATE "-Xlinker /WHOLEARCHIVE:${TORCH_HIP_LIBRARY}")
    ```
* Added `/FORCE:MULTIPLE` to `CMAKE_EXE_LINKER_FLAGS` to deal with duplicate references as a result of `/WHOLEARCHIVE`

**Comment by charest** [comment]
Was able to resolve what looks like two separate issues (without the need for `/WHOLEARCHIVE`.
* Adding `LoadLibraryA("torch_hip.dll")` resolves GPU detection, i.e. `torch::cuda::is_available()` now returns `true`.
* Using `torch::Device(torch::kCUDA)` instead of `torch::Device(torch::kHIP)`.  This lets me call torch functions like `torch::empty` and `torch::zeros`.

**Comment by schung-amd** [comment]
Great, glad to see you've made progress on this. Sorry for the delay on my end, my attention was pulled away to a priority issue. Is there anything still broken for you here or is everything working now?

**Comment by jammm** [comment]
PyTorch isn't linking with torch_hip.lib/dll on ROCm in its libtorch cmake configs. I would look into the cmake here https://github.com/pytorch/pytorch/blob/main/cmake/TorchConfig.cmake.in#L128-L144 to check if it's properly including torch_hip.lib/libtorch_hip.so.

From discord by @scottt  https://discord.com/channels/1239631572886491286/1429848558307377242/1430479687213387929
:
```
for  issue/1825, from the dependency walker screenshot[1], torch_test.exe is linked with c10.dll and toch_cpu.dll but not torch_hip.dll. I suspect that's the problem just like your observation with when comparing with ldd output from Linux.

I'd double check the  value of the TORCH_LIBRARIES variable in CMakeLists.txt[2]


[1]: https://private-user-images.githubusercontent.com/17015378/502755785-a33dc0fb-4c85-4f32-9b0c-2cabad68c861.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjExMTgwODgsIm5iZiI6MTc2MTExNzc4OCwicGF0aCI6Ii8xNzAxNTM3OC81MDI3NTU3ODUtYTMzZGMwZmItNGM4NS00ZjMyLTliMGMtMmNhYmFkNjhjODYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDIyVDA3MjMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNWE3NTJmYzFmN2VkOWExMzFjNWNhZGU3NTRhMDhlMjYzZGIyNGZhMTE4NWI5Y2JjYWYwMjE3ZWVkNjY1MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lq_LcnEXFwLWZ6oqxJeMIh-ZNH5VPLrA38JgKf4vsLE

[2]: https://github.com/charest/torch-cpp-example/blob/main/CMakeLists.txt#L79 
```

**Comment by charest** [comment]
@schung-amd everything appears to be working now.  Thanks!
