### ISSUE TITLE
[issue] gfx-120X-all pytorch TestNN.test_cudnn_rnn_dropout_states_device failing on python 3.12 torch 2.7

### ISSUE THREAD

**Issue by JeniferC99** [ROCm/TheRock#2120]
job link: https://github.com/ROCm/TheRock/actions/runs/19292043000/job/55254964764

```
external-builds/pytorch/pytorch/test/test_nn.py::TestNN::test_cross_entropy_loss_precision PASSED [1.3554s] [  1%]
external-builds/pytorch/pytorch/test/test_nn.py::TestNN::test_cross_entropy_loss_zero_div PASSED [0.0006s] [  1%]
external-builds/pytorch/pytorch/test/test_nn.py::TestNN::test_cudnn_forward_exception PASSED [0.0011s] [  1%]
MIOpen(HIP): Error [Compile] 'hiprtcCompileProgram(prog.get(), c_options.size(), c_options.data())' MIOpenDropoutHIP.cpp: HIPRTC_ERROR_COMPILATION (6)
MIOpen(HIP): Error [BuildHip] HIPRTC status = HIPRTC_ERROR_COMPILATION (6), source file: MIOpenDropoutHIP.cpp
MIOpen(HIP): Warning [BuildHip] In file included from /tmp/comgr-3465-340-5f598f/input/MIOpenDropoutHIP.cpp:32:
/tmp/comgr-3465-340-5f598f/include/miopen_rocrand.hpp:45:10: fatal error: 'rocrand/rocrand_xorwow.h' file not found
   45 | #include <rocrand/rocrand_xorwow.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated when compiling for gfx1201.
MIOpen Error: 23facf3bf076:/therock/src/rocm-libraries/projects/miopen/src/hipoc/hipoc_program.cpp:299: Code object build failed. Source: MIOpenDropoutHIP.cpp
external-builds/pytorch/pytorch/test/test_nn.py::TestNN::test_cudnn_rnn_dropout_states_device FAILED [0.0242s] [  1%]
external-builds/pytorch/pytorch/test/test_nn.py::TestNN::test_cudnn_weight_format PASSED [4.3189s] [  1%]

...

 =================================== FAILURES ===================================
_________________ TestNN.test_cudnn_rnn_dropout_states_device __________________
Traceback (most recent call last):
  File "/__w/_tool/Python/3.12.11/x64/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/__w/_tool/Python/3.12.11/x64/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "/__w/_tool/Python/3.12.11/x64/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/__w/TheRock/TheRock/external-builds/pytorch/pytorch/test/test_nn.py", line 3484, in test_cudnn_rnn_dropout_states_device
    output = rnn(input, hx)
             ^^^^^^^^^^^^^^
  File "/__w/TheRock/TheRock/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/__w/TheRock/TheRock/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/__w/TheRock/TheRock/.venv/lib/python3.12/site-packages/torch/nn/modules/rnn.py", line 716, in forward
    result = _VF.rnn_tanh(
             ^^^^^^^^^^^^^
RuntimeError: miopenStatusUnknownError
=========================== short test summary info ============================
FAILED [0.0242s] external-builds/pytorch/pytorch/test/test_nn.py::TestNN::test_cudnn_rnn_dropout_states_device - RuntimeError: miopenStatusUnknownError
= 1 failed, 37841 passed, 2376 skipped, 81 deselected, 53 xfailed in 728.87s (0:12:08) =
```

**Comment by amd-chiranjeevi** [comment]
effecting gfx-120X pytorch2.8 also
https://github.com/ROCm/TheRock/actions/runs/19357783472/job/55384725143

**Comment by ScottTodd** [comment]
This error:
```
MIOpen(HIP): Error [Compile] 'hiprtcCompileProgram(prog.get(), c_options.size(), c_options.data())' MIOpenDropoutHIP.cpp: HIPRTC_ERROR_COMPILATION (6)
MIOpen(HIP): Error [BuildHip] HIPRTC status = HIPRTC_ERROR_COMPILATION (6), source file: MIOpenDropoutHIP.cpp
MIOpen(HIP): Warning [BuildHip] In file included from /tmp/comgr-3465-340-5f598f/input/MIOpenDropoutHIP.cpp:32:
/tmp/comgr-3465-340-5f598f/include/miopen_rocrand.hpp:45:10: fatal error: 'rocrand/rocrand_xorwow.h' file not found
   45 | #include <rocrand/rocrand_xorwow.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated when compiling for gfx1201.
MIOpen Error: 23facf3bf076:/therock/src/rocm-libraries/projects/miopen/src/hipoc/hipoc_program.cpp:299: Code object build failed. Source: MIOpenDropoutHIP.cpp
external-builds/pytorch/pytorch/test/test_nn.py::TestNN::test_cudnn_rnn_dropout_states_device FAILED [0.0242s] [  1%]
```

matches part of the issue report at https://github.com/ROCm/rocm-libraries/issues/2617 too

We have a dep on rocRAND in MIOpen: https://github.com/ROCm/TheRock/blob/880a76c98117c256096cae8ac6fd0756ba7b55cf/ml-libs/CMakeLists.txt#L131-L138

This is at _test time in pytorch_ though, so not setting include paths properly for JIT compilation or something...?

**Comment by ScottTodd** [comment]
This has a similar root cause as https://github.com/ROCm/TheRock/issues/2152 and also https://github.com/ROCm/TheRock/issues/2118. The path to the error is different though.

This code in MIOpen (not pytorch) is JIT compiling: https://github.com/ROCm/rocm-libraries/blob/2b7a409ab0975829b515d4280967c335391c0efd/projects/miopen/src/hipoc/hipoc_program.cpp#L264-L301

That is depending on `#include <rocrand/rocrand_xorwow.h>` here: https://github.com/ROCm/rocm-libraries/blob/2b7a409ab0975829b515d4280967c335391c0efd/projects/miopen/src/kernels/miopen_rocrand.hpp#L43-L45

We do not currently distribute that header in `rocm[libraries]`. It only comes through via `rocm[devel]`.

cc @stellaraccident @jeffdaily

**Comment by k-artem** [comment]
* Checked with `registry-sc-harbor.amd.com/framework/compute-rocm-rel-7.1:34_ubuntu24.04_py3.12_pytorch_release-2.9_62316079` docker and `rm -rf  /root/.cache/miopen/ && AMD_COMGR_EMIT_VERBOSE_LOGS=1 MIOPEN_LOG_LEVEL=6 MIOPEN_ENABLE_LOGGING_CMD=1 MIOPEN_ENABLE_LOGGING=1 PYTORCH_TEST_WITH_ROCM=1 python test/test_nn.py TestNN.test_cudnn_rnn_dropout_states_device`
confirmed that `"-I/opt/rocm/include"` passes as compiler option and compilation by [comgr](https://github.com/ROCm/llvm-project/blob/amd-staging/amd/comgr/README.md) and test itself works as expected, see log below.
```
MIOpen(HIP): Info2 [LoadBinary] Unable to load binary for: "MIOpenDropoutHIP.cpp.o"; args: -DRUN_FORWARD=0  -DRUN_INIT_PRNG=1 -mcpu=gfx1201
MIOpen(HIP): Info [PrintVersion] HIPRTC v.9.0
MIOpen(HIP): Info [Compile] amd_comgr_do_action:
          ActionKind: AMD_COMGR_ACTION_COMPILE_SOURCE_TO_RELOCATABLE
             IsaName: amdgcn-amd-amdhsa--gfx1201
             Options: "-O3" "--hip-version=7.2.53220" "-DHIP_VERSION_MAJOR=7" "-DHIP_VERSION_MINOR=2" "-DHIP_VERSION_PATCH=53220" "-Wno-gnu-line-marker" "-Wno-missing-prototypes" "-D__HIPCC_RTC__" "-nogpuinc" "-include" "hiprtc_runtime.h" "-DRUN_FORWARD=0" "-DRUN_INIT_PRNG=1" "-Wno-everything" "-D__HIP_PLATFORM_AMD__=1" "-DHIP_PACKAGE_VERSION_FLAT=7002053210" "-DMIOPEN_DONT_USE_HIP_RUNTIME_HEADERS" "-Wno-newline-eof" "-Wno-reserved-identifier" "-Wno-old-style-cast" "-Wno-extra-semi-stmt" "-Wno-gnu-line-marker" "-Wno-pass-failed" "-Wno-cuda-compat" "-fno-gpu-rdc" "-O3" "-fno-offload-uniform-block" "-std=c++17" "-I/opt/rocm/include"
                Path:
            Language: AMD_COMGR_LANGUAGE_HIP
 Comgr Branch-Commit: undefined-65bd3cfc5b42
         LLVM Commit: 8e85e3138dd485c4221cc12aff9eb60ab48ed3b5+PATCHED:371bd8145f7e4d1d481987d05427c94e17708b91
    File System: VFS
    Compilation Args:  "--offload-arch=gfx1201" "-c" "-fhip-emit-relocatable" "-mllvm" "-amdgpu-internalize-symbols" "-I" "/tmp/comgr-1623709-8-b8fc6c/include" "-no-integrated-cpp" "-dD" "-O3" "-x" "hip" "--offload-device-only" "-cuid=AE1EC8E1AEBD725ED9AEF2C1350370E411723E96A0A6BC9E804C73BDF175C5E6" "--rocm-path=/tmp/comgr-1623709-8-b8fc6c/rocm" "-O3" "--hip-version=7.2.53220" "-DHIP_VERSION_MAJOR=7" "-DHIP_VERSION_MINOR=2" "-DHIP_VERSION_PATCH=53220" "-Wno-gnu-line-marker" "-Wno-missing-prototypes" "-D__HIPCC_RTC__" "-nogpuinc" "-include" "hiprtc_runtime.h" "-DRUN_FORWARD=0" "-DRUN_INIT_PRNG=1" "-Wno-everything" "-D__HIP_PLATFORM_AMD__=1" "-DHIP_PACKAGE_VERSION_FLAT=7002053210" "-DMIOPEN_DONT_USE_HIP_RUNTIME_HEADERS" "-Wno-newline-eof" "-Wno-reserved-identifier" "-Wno-old-style-cast" "-Wno-extra-semi-stmt" "-Wno-gnu-line-marker" "-Wno-pass-failed" "-Wno-cuda-compat" "-fno-gpu-rdc" "-O3" "-fno-offload-uniform-block" "-std=c++17" "-I/opt/rocm/include" "-Xclang" "-no-disable-free" "/tmp/comgr-1623709-8-b8fc6c/input/MIOpenDropoutHIP.cpp" "-o" "/tmp/comgr-1623709-8-b8fc6c/output/MIOpenDropoutHIP.o"
     Driver Job Args: clang "-cc1" "-triple" "amdgcn-amd-amdhsa" "-aux-triple" "x86_64-unknown-linux-gnu" "-O3" "-Werror=atomic-alignment" "-E" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "MIOpenDropoutHIP.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-fhalf-no-semantic-interposition" "-mframe-pointer=none" "-fno-rounding-math" "-mconstructor-aliases" "-aux-target-cpu" "x86-64" "-fcuda-is-device" "-fno-threadsafe-statics" "-mllvm" "-amdgpu-internalize-symbols" "-fcuda-allow-variadic-functions" "-fvisibility=hidden" "-fapply-global-visibility-to-externs" "-mlink-builtin-bitcode" "/tmp/comgr-1623709-8-b8fc6c/rocm/amdgcn/bitcode/ocml.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623709-8-b8fc6c/rocm/amdgcn/bitcode/ockl.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623709-8-b8fc6c/rocm/amdgcn/bitcode/oclc_daz_opt_off.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623709-8-b8fc6c/rocm/amdgcn/bitcode/oclc_unsafe_math_off.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623709-8-b8fc6c/rocm/amdgcn/bitcode/oclc_finite_only_off.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623709-8-b8fc6c/rocm/amdgcn/bitcode/oclc_correctly_rounded_sqrt_on.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623709-8-b8fc6c/rocm/amdgcn/bitcode/oclc_wavefrontsize64_off.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623709-8-b8fc6c/rocm/amdgcn/bitcode/oclc_isa_version_1201.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623709-8-b8fc6c/rocm/amdgcn/bitcode/oclc_abi_version_600.bc" "-target-cpu" "gfx1201" "-debugger-tuning=gdb" "-fdebug-compilation-dir=/var/lib/jenkins/pytorch" "-fcoverage-compilation-dir=/var/lib/jenkins/pytorch" "-resource-dir" "/lib/clang/22" "-internal-isystem" "/lib/clang/22/include/cuda_wrappers" "-include" "hiprtc_runtime.h" "-I" "/tmp/comgr-1623709-8-b8fc6c/include" "-D" "HIP_VERSION_MAJOR=7" "-D" "HIP_VERSION_MINOR=2" "-D" "HIP_VERSION_PATCH=53220" "-D" "__HIPCC_RTC__" "-D" "RUN_FORWARD=0" "-D" "RUN_INIT_PRNG=1" "-D" "__HIP_PLATFORM_AMD__=1" "-D" "HIP_PACKAGE_VERSION_FLAT=7002053210" "-D" "MIOPEN_DONT_USE_HIP_RUNTIME_HEADERS" "-I" "/opt/rocm/include" "-internal-isystem" "/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14" "-internal-isystem" "/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/x86_64-linux-gnu/c++/14" "-internal-isystem" "/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/backward" "-internal-isystem" "/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14" "-internal-isystem" "/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/x86_64-linux-gnu/c++/14" "-internal-isystem" "/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/backward" "-internal-isystem" "/lib/clang/22/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../x86_64-linux-gnu/include" "-internal-externc-isystem" "/usr/include/x86_64-linux-gnu" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-internal-isystem" "/lib/clang/22/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../x86_64-linux-gnu/include" "-internal-externc-isystem" "/usr/include/x86_64-linux-gnu" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-Wno-gnu-line-marker" "-Wno-missing-prototypes" "-Wno-everything" "-Wno-newline-eof" "-Wno-reserved-identifier" "-Wno-old-style-cast" "-Wno-extra-semi-stmt" "-Wno-gnu-line-marker" "-Wno-pass-failed" "-Wno-cuda-compat" "-std=c++17" "-fdeprecated-macro" "-fno-autolink" "-ferror-limit" "19" "-fmessage-length=209" "-fhip-new-launch-api" "-fgnuc-version=4.2.1" "-fskip-odr-check-in-gmf" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-vectorize-loops" "-vectorize-slp" "-dD" "-no-disable-free" "-mllvm" "-amdgpu-internalize-symbols" "-cuid=AE1EC8E1AEBD725ED9AEF2C1350370E411723E96A0A6BC9E804C73BDF175C5E6" "-fcuda-allow-variadic-functions" "-fno-offload-uniform-block" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-o" "/tmp/MIOpenDropoutHIP-gfx1201-4be72c.hipi" "-x" "hip" "/tmp/comgr-1623709-8-b8fc6c/input/MIOpenDropoutHIP.cpp"
     Driver Job Args: clang "-cc1" "-triple" "amdgcn-amd-amdhsa" "-aux-triple" "x86_64-unknown-linux-gnu" "-O3" "-Werror=atomic-alignment" "-emit-obj" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "MIOpenDropoutHIP.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-fhalf-no-semantic-interposition" "-mframe-pointer=none" "-fno-rounding-math" "-mconstructor-aliases" "-aux-target-cpu" "x86-64" "-fcuda-is-device" "-fno-threadsafe-statics" "-mllvm" "-amdgpu-internalize-symbols" "-fcuda-allow-variadic-functions" "-fvisibility=hidden" "-fapply-global-visibility-to-externs" "-mlink-builtin-bitcode" "/tmp/comgr-1623253-8-3829e1/rocm/amdgcn/bitcode/ocml.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623253-8-3829e1/rocm/amdgcn/bitcode/ockl.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623253-8-3829e1/rocm/amdgcn/bitcode/oclc_daz_opt_off.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623253-8-3829e1/rocm/amdgcn/bitcode/oclc_unsafe_math_off.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623253-8-3829e1/rocm/amdgcn/bitcode/oclc_finite_only_off.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623253-8-3829e1/rocm/amdgcn/bitcode/oclc_correctly_rounded_sqrt_on.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623253-8-3829e1/rocm/amdgcn/bitcode/oclc_wavefrontsize64_off.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623253-8-3829e1/rocm/amdgcn/bitcode/oclc_isa_version_1201.bc" "-mlink-builtin-bitcode" "/tmp/comgr-1623253-8-3829e1/rocm/amdgcn/bitcode/oclc_abi_version_600.bc" "-target-cpu" "gfx1201" "-debugger-tuning=gdb" "-fdebug-compilation-dir=/var/lib/jenkins/pytorch" "-fcoverage-compilation-dir=/var/lib/jenkins/pytorch" "-resource-dir" "/lib/clang/22" "-Wno-gnu-line-marker" "-Wno-missing-prototypes" "-Wno-everything" "-Wno-newline-eof" "-Wno-reserved-identifier" "-Wno-old-style-cast" "-Wno-extra-semi-stmt" "-Wno-gnu-line-marker" "-Wno-pass-failed" "-Wno-cuda-compat" "-std=c++17" "-fdeprecated-macro" "-fno-autolink" "-ferror-limit" "19" "-fmessage-length=209" "-fhip-new-launch-api" "-fgnuc-version=4.2.1" "-fskip-odr-check-in-gmf" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-vectorize-loops" "-vectorize-slp" "-dD" "-no-disable-free" "-mllvm" "-amdgpu-internalize-symbols" "-cuid=AE1EC8E1AEBD725ED9AEF2C1350370E411723E96A0A6BC9E804C73BDF175C5E6" "-fcuda-allow-variadic-functions" "-fno-offload-uniform-block" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-o" "/tmp/comgr-1623253-8-3829e1/output/MIOpenDropoutHIP.o" "-x" "hip-cpp-output" "/tmp/MIOpenDropoutHIP-gfx1201-1d7aff.hipi"
Comgr cache: found entry 442665cb454150de1fe7278acdc1224a6193c2d4ff5e7b483fcb6e8a9a4043c6 in cache.
        ReturnStatus: AMD_COMGR_STATUS_SUCCESS
``` 
* ~`opt/rocm/include` is default option of comgr (i.e. no code in MIOpen that add it before run a comgr job)~ can be overriden via env var see comment below, so please @ScottTodd could you please check that you have this path in TheRock env.

**Comment by ScottTodd** [comment]
The new packages support installing into a python environment on Linux and WIndows, **not** `/opt/rocm/`. We prefer the python-based packages for python projects like pytorch, not system-wide installs. (We also provide "tarball" releases and "native Linux packages" which do support system-wide installation but that is not what python projects should expect)

Additionally, the packages are now split into "core" and "devel", with PyTorch currently only depending on "core". C++ source files are CMake files are in "devel". See
* https://github.com/ROCm/TheRock/blob/main/docs/packaging/python_packaging.md#general-design
* https://github.com/ROCm/TheRock/blob/main/docs/packaging/python_packaging.md#using-packages-from-frameworks.

**Comment by k-artem** [comment]
>do support system-wide installation 

I think this is the root cause of the issue, need to check how pass local include paths to comgr

EDIT:
And I suppose that **not** gfx12x specific issue.

**Comment by k-artem** [comment]
@ScottTodd, comgr has [functionality ](https://github.com/ROCm/rocm-libraries/blob/a2f7c3551160e8ac5470366157bd1e93940b906e/projects/miopen/src/comgr.cpp#L970)to read ROCM_PATH in order to create path for -I directive,  I suggest to use this env var to point to rocm include inside venv (e.g. `export ROCM_PATH=/root/therock/.venv/lib/python3.12/site-packages/_rocm_sdk_devel/`), because for Radeon (in compare with MI) there is no database with precompiled kernels and kernels compiles and store to internal db at first run. I've tested it works as expected.

**Comment by ScottTodd** [comment]
Python packages shouldn't depend (only) on any global system state like environment variables. They should have access to everything they need to function from within the python environment, including binary tools and files.

Looking at https://github.com/ROCm/TheRock/issues/1880, if the devel packages are installed (and that issue is fixed) automatic discovery of "ROCM_PATH" via `hipconfig --rocmpath` may be sufficient to find these header files.

I see that https://github.com/ROCm/rocm-libraries/pull/2510 is changing how `--rocm-path=` is used in that linked code. Tagging @DarylHawkinsAMD @JonathanLichtnerAMD @BrianHarrisonAMD here too. We've discussed other aspects of this on https://github.com/ROCm/rocm-libraries/issues/2617.

I think with these PRs the tests may be able to pass when devel packages are installed:
* https://github.com/ROCm/rocm-libraries/pull/2510
* https://github.com/ROCm/TheRock/pull/2428

To remove the "devel packages must be installed" requirement, we could bundle the rocrand headers (and any other required headers) in the core package. The decision of which packages include which files is handled by https://github.com/ROCm/TheRock/blob/main/build_tools/build_python_packages.py

**Comment by BrianHarrisonAMD** [comment]
> Python packages shouldn't depend (only) on any global system state like environment variables. They should have access to everything they need to function from within the python environment, including binary tools and files.
> 
> Looking at [#1880](https://github.com/ROCm/TheRock/issues/1880), if the devel packages are installed (and that issue is fixed) automatic discovery of "ROCM_PATH" via `hipconfig --rocmpath` may be sufficient to find these header files.
> 
> I see that [ROCm/rocm-libraries#2510](https://github.com/ROCm/rocm-libraries/pull/2510) is changing how `--rocm-path=` is used in that linked code. Tagging [@DarylHawkinsAMD](https://github.com/DarylHawkinsAMD) [@JonathanLichtnerAMD](https://github.com/JonathanLichtnerAMD) [@BrianHarrisonAMD](https://github.com/BrianHarrisonAMD) here too. We've discussed other aspects of this on [ROCm/rocm-libraries#2617](https://github.com/ROCm/rocm-libraries/issues/2617).
> 
> I think with these PRs the tests may be able to pass when devel packages are installed:
> 
> * [[MIOpen] Fix runtime kernel compilation issues rocm-libraries#2510](https://github.com/ROCm/rocm-libraries/pull/2510)
> * [Redirect base exec path for Python CLI scripts if `rocm[devel]` is installed #2428](https://github.com/ROCm/TheRock/pull/2428)
> 
> To remove the "devel packages must be installed" requirement, we could bundle the rocrand headers (and any other required headers) in the core package. The decision of which packages include which files is handled by https://github.com/ROCm/TheRock/blob/main/build_tools/build_python_packages.py

Agreed.
I think we need to land https://github.com/ROCm/rocm-libraries/pull/2510, and also bundle any necessary headers in the core package for this to be resolved properly. 

I believe @DarylHawkinsAMD is working towards this solution.

**Comment by JonathanLichtnerAMD** [comment]
This has been fixed in the rock via https://github.com/ROCm/rocm-libraries/pull/4007

**Comment by ScottTodd** [comment]
Nice! Let's remove the skip test code?

* https://github.com/ROCm/TheRock/blob/9811cae44ebab37d8c0db71a16fb8eb935fbbd18/external-builds/pytorch/skip_tests/generic.py#L52-L60
* https://github.com/ROCm/TheRock/blob/9811cae44ebab37d8c0db71a16fb8eb935fbbd18/external-builds/pytorch/skip_tests/pytorch_2.9.py#L109-L117
* https://github.com/ROCm/TheRock/blob/9811cae44ebab37d8c0db71a16fb8eb935fbbd18/external-builds/pytorch/skip_tests/pytorch_2.10.py#L104-L112

**Comment by k-artem** [comment]
>  Let's remove the skip test code?

https://github.com/ROCm/TheRock/pull/3367
