### ISSUE TITLE
[Issue]: MIOpen(HIP): Error on latest gfx1151 Pytorch

### ISSUE THREAD

**Issue by jrhip** [ROCm/TheRock#2488]
### Problem Description

```
  Marketing Name:          AMD RYZEN AI MAX+ 395 w/ Radeon 8060S
  Name:                    gfx1151                            
  Marketing Name:          Radeon 8060S Graphics              
      Name:                    amdgcn-amd-amdhsa--gfx1151         
      Name:                    amdgcn-amd-amdhsa--gfx11-generic   
  Name:                    aie2                               
  Marketing Name:          AIE-ML 
```

```
pytorch-triton-rocm==3.5.0+gitb0cf18f2.rocm7.10.0a20251015
rocm==7.10.0a20251015
rocm-sdk-core==7.10.0a20251015
rocm-sdk-libraries-gfx1151==7.10.0a20251015
torch==2.10.0a0+rocm7.10.0a20251015
torchaudio==2.8.0a0+rocm7.10.0a20251015
torchvision==0.25.0a0+rocm7.10.0a20251015
```

When calling torch.nn.functional.instance_norm I get `RuntimeError: miopenStatusUnknownError`

And the following message:

```
MIOpen(HIP): Error [Compile] 'hiprtcCompileProgram(prog.get(), c_options.size(), c_options.data())' MIOpenBatchNormFwdTrainSpatialHIP.cpp: HIPRTC_ERROR_COMPILATION (6)
MIOpen(HIP): Error [BuildHip] HIPRTC status = HIPRTC_ERROR_COMPILATION (6), source file: MIOpenBatchNormFwdTrainSpatialHIP.cpp
MIOpen(HIP): Warning [BuildHip] In file included from /tmp/comgr-f79515/input/MIOpenBatchNormFwdTrainSpatialHIP.cpp:34:
/tmp/comgr-f79515/include/reduction_functions.hpp:83:23: error: not a valid operand.
   83 |                      "v_add_f32 %0 %0 %0 row_bcast:15 row_mask:0xa\n"
      |                       ^
<inline asm>:14:20: note: instantiated into assembly here
   14 | v_add_f32 v1 v1 v1 row_bcast:15 row_mask:0xa
      |                    ^
In file included from /tmp/comgr-f79515/input/MIOpenBatchNormFwdTrainSpatialHIP.cpp:34:
/tmp/comgr-f79515/include/reduction_functions.hpp:84:23: error: not a valid operand.
   84 |                      "v_add_f32 %1 %1 %1 row_bcast:15 row_mask:0xa\n"
      |                       ^
<inline asm>:15:23: note: instantiated into assembly here
   15 | v_add_f32 v59 v59 v59 row_bcast:15 row_mask:0xa
      |                       ^
In file included from /tmp/comgr-f79515/input/MIOpenBatchNormFwdTrainSpatialHIP.cpp:34:
/tmp/comgr-f79515/include/reduction_functions.hpp:86:23: error: not a valid operand.
   86 |                      "v_add_f32 %0 %0 %0 row_bcast:31 row_mask:0xc\n"
      |                       ^
<inline asm>:17:20: note: instantiated into assembly here
   17 | v_add_f32 v1 v1 v1 row_bcast:31 row_mask:0xc
      |                    ^
In file included from /tmp/comgr-f79515/input/MIOpenBatchNormFwdTrainSpatialHIP.cpp:34:
/tmp/comgr-f79515/include/reduction_functions.hpp:87:23: error: not a valid operand.
   87 |                      "v_add_f32 %1 %1 %1 row_bcast:31 row_mask:0xc\n"
      |                       ^
<inline asm>:18:23: note: instantiated into assembly here
   18 | v_add_f32 v59 v59 v59 row_bcast:31 row_mask:0xc
      |                       ^
4 errors generated when compiling for gfx1151.
MIOpen Error: /therock/src/rocm-libraries/projects/miopen/src/hipoc/hipoc_program.cpp:299: Code object build failed. Source: MIOpenBatchNormFwdTrainSpatialHIP.cpp
```

### Operating System

Fedora 43

### CPU

AMD RYZEN AI MAX+ 395

### GPU

Radeon 8060S

### ROCm Version

7.10.0a20251015

### Steps to Reproduce

Run torch.nn.functional.instance_norm while using torch.device('cuda')

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

ROCk module version 6.16.6 is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.18
Runtime Ext Version:     1.14
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
XNACK enabled:           NO
DMAbuf Support:          YES
VMM Support:             YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD RYZEN AI MAX+ 395 w/ Radeon 8060S
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD RYZEN AI MAX+ 395 w/ Radeon 8060S
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      49152(0xc000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   5187                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Memory Properties:       
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    131151708(0x7d1375c) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    131151708(0x7d1375c) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    131151708(0x7d1375c) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 4                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    131151708(0x7d1375c) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1151                            
  Uuid:                    GPU-XX                             
  Marketing Name:          Radeon 8060S Graphics              
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      2048(0x800) KB                     
    L3:                      32768(0x8000) KB                   
  Chip ID:                 5510(0x1586)                       
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          128(0x80)                          
  Max Clock Freq. (MHz):   2900                               
  BDFID:                   49664                              
  Internal Node ID:        1                                  
  Compute Unit:            40                                 
  SIMDs per CU:            2                                  
  Shader Engines:          2                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Memory Properties:       APU
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        2147483647(0x7fffffff)             
    y                        65535(0xffff)                      
    z                        65535(0xffff)                      
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 32                                 
  SDMA engine uCode::      17                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65575852(0x3e89bac) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    65575852(0x3e89bac) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1151         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        2147483647(0x7fffffff)             
        y                        65535(0xffff)                      
        z                        65535(0xffff)                      
      FBarrier Max Size:       32                                 
    ISA 2                    
      Name:                    amdgcn-amd-amdhsa--gfx11-generic   
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        2147483647(0x7fffffff)             
        y                        65535(0xffff)                      
        z                        65535(0xffff)                      
      FBarrier Max Size:       32                                 
*******                  
Agent 3                  
*******                  
  Name:                    aie2                               
  Uuid:                    AIE-XX                             
  Marketing Name:          AIE-ML                             
  Vendor Name:             AMD                                
  Feature:                 AGENT_DISPATCH                     
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        1(0x1)                             
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          64(0x40)                           
  Queue Type:              SINGLE                             
  Node:                    0                                  
  Device Type:             DSP                                
  Cache Info:              
    L2:                      2048(0x800) KB                     
    L3:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          0(0x0)                             
  Max Clock Freq. (MHz):   0                                  
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            0                                  
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:0                                  
  Memory Properties:       
  Features:                AGENT_DISPATCH
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, COARSE GRAINED
      Size:                    131151708(0x7d1375c) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65536(0x10000) KB                  
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    131151708(0x7d1375c) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:

**Comment by huanrwan-amd** [comment]
similar as https://github.com/ROCm/TheRock/issues/2489

**Comment by k-artem** [comment]
`row_bcast` ddp is gcn specific and no support on rdna, please see it for details -> https://github.com/ROCm/rocm-libraries/pull/909#issuecomment-3631922378

CC @ScottTodd

**Comment by stellaraccident** [comment]
@ROCm/rocm-genies for attention

**Comment by astrelsky** [comment]
It looks like this one is actually not the same as #2489 as I am no longer encountering it.

**Comment by k-artem** [comment]
@jrhip kindly ask you to add args of `instance_norm` that you use in the description, i.e. short script for repro.

**Comment by jrhip** [comment]
> [@jrhip](https://github.com/jrhip) kindly ask you to add args of `instance_norm` that you use in the description, i.e. short script for repro.

Will post something later today. Thanks

**Comment by k-artem** [comment]
> > [@jrhip](https://github.com/jrhip) kindly ask you to add args of `instance_norm` that you use in the description, i.e. short script for repro.
> 
> Will post something later today. Thanks

another option just run your python with `AMD_COMGR_EMIT_VERBOSE_LOGS=1 MIOPEN_LOG_LEVEL=6 MIOPEN_ENABLE_LOGGING_CMD=1 MIOPEN_ENABLE_LOGGING=1` and share the ouput.

**Comment by jrhip** [comment]
Try this:

```
import torch
import os 

os.environ["AMD_COMGR_EMIT_VERBOSE_LOGS"]="1" 
os.environ["MIOPEN_LOG_LEVEL"]="6" 
os.environ["MIOPEN_ENABLE_LOGGING_CMD"]="1" 
os.environ["MIOPEN_ENABLE_LOGGING"]="1" 

device = 'cuda'

N = torch.tensor(2,device=device)
x = torch.rand((N,N,N,N),device=device)
norm = torch.nn.InstanceNorm3d(int(N), affine=True).to(device=device)
norm(x)
```

Which produces a vast quantity of information:

```
MIOpen(HIP): Info [get_device_name] Raw device name: gfx1151
MIOpen(HIP): Info [SetStream] stream: 0, device_id: 0
MIOpen(HIP): miopenStatus_t miopenCreateTensorDescriptor(miopenTensorDescriptor_t *){
MIOpen(HIP): 	tensorDesc = 0
MIOpen(HIP): }
MIOpen(HIP): miopenStatus_t miopenSetTensorDescriptor(miopenTensorDescriptor_t, miopenDataType_t, int, const int *, const int *){
MIOpen(HIP): 	tensorDesc = {}, {}, packed, 
MIOpen(HIP): 	dataType = 1
MIOpen(HIP): 	nbDims = 5
MIOpen(HIP): 	dim.values = { 1 2 2 2 2 }
MIOpen(HIP): 	stride.values = { 16 8 4 2 1 }
MIOpen(HIP): }
MIOpen(HIP): miopenStatus_t miopenCreateTensorDescriptor(miopenTensorDescriptor_t *){
MIOpen(HIP): 	tensorDesc = 0
MIOpen(HIP): }
MIOpen(HIP): miopenStatus_t miopenSetTensorDescriptor(miopenTensorDescriptor_t, miopenDataType_t, int, const int *, const int *){
MIOpen(HIP): 	tensorDesc = {}, {}, packed, 
MIOpen(HIP): 	dataType = 1
MIOpen(HIP): 	nbDims = 5
MIOpen(HIP): 	dim.values = { 1 2 1 1 1 }
MIOpen(HIP): 	stride.values = { 2 1 1 1 1 }
MIOpen(HIP): }
MIOpen(HIP): miopenStatus_t miopenBatchNormForwardTrainingActivation(miopenHandle_t, miopenBatchNormMode_t, void *, void *, const miopenTensorDescriptor_t, const void *, const miopenTensorDescriptor_t, void *, const miopenTensorDescriptor_t, const miopenTensorDescriptor_t, const miopenTensorDescriptor_t, const miopenTensorDescriptor_t, void *, void *, double, void *, void *, double, void *, void *, const miopenActivationDescriptor_t){
MIOpen(HIP): 	handle = stream: 0, device_id: 0
MIOpen(HIP): 	bn_mode = 1
MIOpen(HIP): 	xDesc = {1, 2, 2, 2, 2}, {16, 8, 4, 2, 1}, packed, 
MIOpen(HIP): 	x = 0x7f9333c01a00
MIOpen(HIP): 	yDesc = {1, 2, 2, 2, 2}, {16, 8, 4, 2, 1}, packed, 
MIOpen(HIP): 	y = 0x7f9333c02400
MIOpen(HIP): 	scaleDesc = {1, 2, 1, 1, 1}, {2, 1, 1, 1, 1}, packed, 
MIOpen(HIP): 	biasDesc = {1, 2, 1, 1, 1}, {2, 1, 1, 1, 1}, packed, 
MIOpen(HIP): 	savedMeanDesc = {1, 2, 1, 1, 1}, {2, 1, 1, 1, 1}, packed, 
MIOpen(HIP): 	savedVarianceDesc = {1, 2, 1, 1, 1}, {2, 1, 1, 1, 1}, packed, 
MIOpen(HIP): 	bnScale = 0x7f9333c02000
MIOpen(HIP): 	bnBias = 0x7f9333c02200
MIOpen(HIP): 	expAvgFactor = 0.1
MIOpen(HIP): 	resultRunningMean = nullptr
MIOpen(HIP): 	resultRunningVariance = nullptr
MIOpen(HIP): 	epsilon = 1e-05
MIOpen(HIP): }
MIOpen(HIP): miopenStatus_t miopenGetTensorDescriptorSize(miopenTensorDescriptor_t, int *){
MIOpen(HIP): 	tensorDesc = {1, 2, 2, 2, 2}, {16, 8, 4, 2, 1}, packed, 
MIOpen(HIP): }
MIOpen(HIP): Command [LogCmdBNorm] ./bin/MIOpenDriver bnorm -n 1 -c 2 -D 2 -H 2 -W 2 -m 1 --forw 1 -b 0 -s 1 --layout NCDHW
MIOpen(HIP): miopenStatus_t miopenGetTensorDescriptorSize(miopenTensorDescriptor_t, int *){
MIOpen(HIP): 	tensorDesc = {1, 2, 2, 2, 2}, {16, 8, 4, 2, 1}, packed, 
MIOpen(HIP): }
MIOpen(HIP): Info2 [GetInvoker] Returning an invoker for problem 2x1x4x2x1xNCHWxNCHWxFP32xFP32xFP32xFP32xFP32xFP32x0xTrnx1x0x1x0 and algorithm miopenBatchNormForwardTrainingSpatial
MIOpen(HIP): Info2 [GetFound1_0] No invokers found for 2x1x4x2x1xNCHWxNCHWxFP32xFP32xFP32xFP32xFP32xFP32x0xTrnx1x0x1x0
MIOpen(HIP): Info [FindSolutionImpl] BnFwdTrainingSpatial
MIOpen(HIP): Info2 [FindRecordUnsafe] Looking for key 2x1x2x4x2x1x1x0x0xNCHWxTrnxFP32x1 in cache for file "/home/james/.config/miopen/batchnorm_gfx1151_20.HIP.3_5_1_10cc739c23.udb.txt"
MIOpen(HIP): Info2 [FindRecord] Looking for key 2x1x4x2x1xNCHWxNCHWxFP32xFP32xFP32xFP32xFP32xFP32x0xTrnx1x0x1x0 in file ""
MIOpen(HIP): Info2 [Measure] Db::Load time: 0.020348 ms
MIOpen(HIP): Info [FindSolutionImpl] Perf Db: record not found for: BnFwdTrainingSpatial
MIOpen(HIP): Info [GetDefaultPerformanceConfig] Variant0-1
MIOpen(HIP): Info2 [SearchForSolutions] BnFwdTrainingSpatial: Success.
MIOpen(HIP): Info2 [PrepareInvoker] Preparing kernel: MIOpenBatchNormFwdTrainSpatial
MIOpen(HIP): Info2 [SQLiteBase] Initializing system database file ""
MIOpen(HIP): Info [KernDb] database not present
MIOpen(HIP): Info2 [SQLiteBase] Initializing user database file "/home/james/.cache/miopen/3.5.1.10cc739c23/gfx1151_20.ukdb"
MIOpen(HIP): Info2 [KernDb] Database created successfully
MIOpen(HIP): Info2 [LoadBinary] Loading binary for: "MIOpenBatchNormFwdTrainSpatial.cl.o"; args: -DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP32=1 -DMIOPEN_USE_FPMIX=0 -DMIOPEN_USE_BFPMIX=0 -DMIO_SAVE_MEAN_VARIANCE=1 -DMIO_RUNNING_RESULT=0 -DMIO_BN_VARIANT=0 -DMIO_BN_LDS_SIZE=256 -DMIO_BN_LDSGCN_SIZE=4 -DMIO_BN_N=1 -DMIO_BN_NGRPS=1 -DMIO_BN_NGRPS2=1 -DMIO_BN_N_ELEMENTS=85899345921 -DMIO_BN_GRP0=256 -DMIO_BN_GRP1=1 -DMIO_BN_GRP2=1 -DMIO_BN_GRP0_FINAL=0 -DMIO_BN_GRP1_FINAL=1 -DMIO_BN_GRP2_FINAL=1 -DMIO_BN_GFX103X=0 -DMIO_BN_GFX110X=0 -DMIO_BN_GFX120X=0 -DMIO_LAYOUT_NHWC=0 -DMIO_BN_VECTORIZE=0 -DMIO_BN_VEC_SIZE=1 -DMIO_BN_STASH_METHOD=0 -DMIOPEN_NRN_OP_ID=0 -DMIO_BN_C=2 -DMIO_BN_HW=8 -DMIO_BN_NHW=8 -DMIO_BN_CHW=16 -DMIO_BN_NCHW=16 -mcpu=gfx1151
MIOpen(HIP): Info2 [Prepare] SELECT kernel_blob, kernel_hash, uncompressed_size FROM kern_db WHERE (kernel_name = 'MIOpenBatchNormFwdTrainSpatial.cl.o') AND (kernel_args = '-DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP32=1 -DMIOPEN_USE_FPMIX=0 -DMIOPEN_USE_BFPMIX=0 -DMIO_SAVE_MEAN_VARIANCE=1 -DMIO_RUNNING_RESULT=0 -DMIO_BN_VARIANT=0 -DMIO_BN_LDS_SIZE=256 -DMIO_BN_LDSGCN_SIZE=4 -DMIO_BN_N=1 -DMIO_BN_NGRPS=1 -DMIO_BN_NGRPS2=1 -DMIO_BN_N_ELEMENTS=85899345921 -DMIO_BN_GRP0=256 -DMIO_BN_GRP1=1 -DMIO_BN_GRP2=1 -DMIO_BN_GRP0_FINAL=0 -DMIO_BN_GRP1_FINAL=1 -DMIO_BN_GRP2_FINAL=1 -DMIO_BN_GFX103X=0 -DMIO_BN_GFX110X=0 -DMIO_BN_GFX120X=0 -DMIO_LAYOUT_NHWC=0 -DMIO_BN_VECTORIZE=0 -DMIO_BN_VEC_SIZE=1 -DMIO_BN_STASH_METHOD=0 -DMIOPEN_NRN_OP_ID=0 -DMIO_BN_C=2 -DMIO_BN_HW=8 -DMIO_BN_NHW=8 -DMIO_BN_CHW=16 -DMIO_BN_NCHW=16 -mcpu=gfx1151');
MIOpen(HIP): Info2 [Measure] Db::FindRecord time: 0.023144 ms
MIOpen(HIP): Info2 [LoadBinary] Unable to load binary for: "MIOpenBatchNormFwdTrainSpatial.cl.o"; args: -DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP32=1 -DMIOPEN_USE_FPMIX=0 -DMIOPEN_USE_BFPMIX=0 -DMIO_SAVE_MEAN_VARIANCE=1 -DMIO_RUNNING_RESULT=0 -DMIO_BN_VARIANT=0 -DMIO_BN_LDS_SIZE=256 -DMIO_BN_LDSGCN_SIZE=4 -DMIO_BN_N=1 -DMIO_BN_NGRPS=1 -DMIO_BN_NGRPS2=1 -DMIO_BN_N_ELEMENTS=85899345921 -DMIO_BN_GRP0=256 -DMIO_BN_GRP1=1 -DMIO_BN_GRP2=1 -DMIO_BN_GRP0_FINAL=0 -DMIO_BN_GRP1_FINAL=1 -DMIO_BN_GRP2_FINAL=1 -DMIO_BN_GFX103X=0 -DMIO_BN_GFX110X=0 -DMIO_BN_GFX120X=0 -DMIO_LAYOUT_NHWC=0 -DMIO_BN_VECTORIZE=0 -DMIO_BN_VEC_SIZE=1 -DMIO_BN_STASH_METHOD=0 -DMIOPEN_NRN_OP_ID=0 -DMIO_BN_C=2 -DMIO_BN_HW=8 -DMIO_BN_NHW=8 -DMIO_BN_CHW=16 -DMIO_BN_NCHW=16 -mcpu=gfx1151
MIOpen(HIP): Info2 [SetIsaName] amdgcn-amd-amdhsa--gfx1151
MIOpen(HIP): Info [Do] AMD_COMGR_ACTION_ADD_PRECOMPILED_HEADERS: amd_comgr_do_action:
	  ActionKind: AMD_COMGR_ACTION_ADD_PRECOMPILED_HEADERS
	     IsaName: amdgcn-amd-amdhsa--gfx1151
	     Options: "-DMIOPEN_USE_FP16=0" "-DMIOPEN_USE_FP32=1" "-DMIOPEN_USE_FPMIX=0" "-DMIOPEN_USE_BFPMIX=0" "-DMIO_SAVE_MEAN_VARIANCE=1" "-DMIO_RUNNING_RESULT=0" "-DMIO_BN_VARIANT=0" "-DMIO_BN_LDS_SIZE=256" "-DMIO_BN_LDSGCN_SIZE=4" "-DMIO_BN_N=1" "-DMIO_BN_NGRPS=1" "-DMIO_BN_NGRPS2=1" "-DMIO_BN_N_ELEMENTS=85899345921" "-DMIO_BN_GRP0=256" "-DMIO_BN_GRP1=1" "-DMIO_BN_GRP2=1" "-DMIO_BN_GRP0_FINAL=0" "-DMIO_BN_GRP1_FINAL=1" "-DMIO_BN_GRP2_FINAL=1" "-DMIO_BN_GFX103X=0" "-DMIO_BN_GFX110X=0" "-DMIO_BN_GFX120X=0" "-DMIO_LAYOUT_NHWC=0" "-DMIO_BN_VECTORIZE=0" "-DMIO_BN_VEC_SIZE=1" "-DMIO_BN_STASH_METHOD=0" "-DMIOPEN_NRN_OP_ID=0" "-DMIO_BN_C=2" "-DMIO_BN_HW=8" "-DMIO_BN_NHW=8" "-DMIO_BN_CHW=16" "-DMIO_BN_NCHW=16" "-Wno-everything" "-cl-std=CL2.0" "-cl-kernel-arg-info" "-D__IMAGE_SUPPORT__=1" "-D__OPENCL_VERSION__=200" "-mllvm" "-amdgpu-early-inline-all" "-mllvm" "-amdgpu-prelink" "-O3" "-mllvm" "-amdgpu-internalize-symbols"
	        Path: 
	    Language: AMD_COMGR_LANGUAGE_OPENCL_2_0
 Comgr Branch-Commit: HEAD-e130d9d39595
	 LLVM Commit: a7d47b26ca0ec0b3e9e4da83825cace5d761f4bc+PATCHED:1d3c56e3e837bfa87144aef73e9faad95492b591
	ReturnStatus: AMD_COMGR_STATUS_SUCCESS


MIOpen(HIP): Info [Do] AMD_COMGR_ACTION_COMPILE_SOURCE_WITH_DEVICE_LIBS_TO_BC: amd_comgr_do_action:
	  ActionKind: AMD_COMGR_ACTION_COMPILE_SOURCE_WITH_DEVICE_LIBS_TO_BC
	     IsaName: amdgcn-amd-amdhsa--gfx1151
	     Options: "-DMIOPEN_USE_FP16=0" "-DMIOPEN_USE_FP32=1" "-DMIOPEN_USE_FPMIX=0" "-DMIOPEN_USE_BFPMIX=0" "-DMIO_SAVE_MEAN_VARIANCE=1" "-DMIO_RUNNING_RESULT=0" "-DMIO_BN_VARIANT=0" "-DMIO_BN_LDS_SIZE=256" "-DMIO_BN_LDSGCN_SIZE=4" "-DMIO_BN_N=1" "-DMIO_BN_NGRPS=1" "-DMIO_BN_NGRPS2=1" "-DMIO_BN_N_ELEMENTS=85899345921" "-DMIO_BN_GRP0=256" "-DMIO_BN_GRP1=1" "-DMIO_BN_GRP2=1" "-DMIO_BN_GRP0_FINAL=0" "-DMIO_BN_GRP1_FINAL=1" "-DMIO_BN_GRP2_FINAL=1" "-DMIO_BN_GFX103X=0" "-DMIO_BN_GFX110X=0" "-DMIO_BN_GFX120X=0" "-DMIO_LAYOUT_NHWC=0" "-DMIO_BN_VECTORIZE=0" "-DMIO_BN_VEC_SIZE=1" "-DMIO_BN_STASH_METHOD=0" "-DMIOPEN_NRN_OP_ID=0" "-DMIO_BN_C=2" "-DMIO_BN_HW=8" "-DMIO_BN_NHW=8" "-DMIO_BN_CHW=16" "-DMIO_BN_NCHW=16" "-Wno-everything" "-cl-std=CL2.0" "-cl-kernel-arg-info" "-D__IMAGE_SUPPORT__=1" "-D__OPENCL_VERSION__=200" "-mllvm" "-amdgpu-early-inline-all" "-mllvm" "-amdgpu-prelink" "-O3" "-mllvm" "-amdgpu-internalize-symbols"
	        Path: 
	    Language: AMD_COMGR_LANGUAGE_OPENCL_2_0
 Comgr Branch-Commit: HEAD-e130d9d39595
	 LLVM Commit: a7d47b26ca0ec0b3e9e4da83825cace5d761f4bc+PATCHED:1d3c56e3e837bfa87144aef73e9faad95492b591
    File System: VFS
    Compilation Args:  "-target" "amdgcn-amd-amdhsa" "-mcpu=gfx1151" "-I" "/tmp/comgr-ff5509/include" "-include-pch" "/tmp/comgr-ff5509/include/opencl2.0-c.pch" "-Xclang" "-fno-validate-pch" "-O3" "-x" "cl" "-std=cl2.0" "-cl-no-stdinc" "-c" "-emit-llvm" "--rocm-path=/tmp/comgr-ff5509/rocm" "-Xclang" "-mlink-builtin-bitcode-postopt" "-DMIOPEN_USE_FP16=0" "-DMIOPEN_USE_FP32=1" "-DMIOPEN_USE_FPMIX=0" "-DMIOPEN_USE_BFPMIX=0" "-DMIO_SAVE_MEAN_VARIANCE=1" "-DMIO_RUNNING_RESULT=0" "-DMIO_BN_VARIANT=0" "-DMIO_BN_LDS_SIZE=256" "-DMIO_BN_LDSGCN_SIZE=4" "-DMIO_BN_N=1" "-DMIO_BN_NGRPS=1" "-DMIO_BN_NGRPS2=1" "-DMIO_BN_N_ELEMENTS=85899345921" "-DMIO_BN_GRP0=256" "-DMIO_BN_GRP1=1" "-DMIO_BN_GRP2=1" "-DMIO_BN_GRP0_FINAL=0" "-DMIO_BN_GRP1_FINAL=1" "-DMIO_BN_GRP2_FINAL=1" "-DMIO_BN_GFX103X=0" "-DMIO_BN_GFX110X=0" "-DMIO_BN_GFX120X=0" "-DMIO_LAYOUT_NHWC=0" "-DMIO_BN_VECTORIZE=0" "-DMIO_BN_VEC_SIZE=1" "-DMIO_BN_STASH_METHOD=0" "-DMIOPEN_NRN_OP_ID=0" "-DMIO_BN_C=2" "-DMIO_BN_HW=8" "-DMIO_BN_NHW=8" "-DMIO_BN_CHW=16" "-DMIO_BN_NCHW=16" "-Wno-everything" "-cl-std=CL2.0" "-cl-kernel-arg-info" "-D__IMAGE_SUPPORT__=1" "-D__OPENCL_VERSION__=200" "-mllvm" "-amdgpu-early-inline-all" "-mllvm" "-amdgpu-prelink" "-O3" "-mllvm" "-amdgpu-internalize-symbols" "/tmp/comgr-ff5509/input/MIOpenBatchNormFwdTrainSpatial.cl" "-o" "/tmp/comgr-ff5509/output/MIOpenBatchNormFwdTrainSpatial.cl.bc"
     Driver Job Args: clang "-cc1" "-triple" "amdgcn-amd-amdhsa" "-Werror=atomic-alignment" "-emit-llvm-bc" "-emit-llvm-uselists" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "MIOpenBatchNormFwdTrainSpatial.cl" "-mrelocation-model" "pic" "-pic-level" "2" "-fhalf-no-semantic-interposition" "-mframe-pointer=none" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-fvisibility=hidden" "-fapply-global-visibility-to-externs" "-mlink-builtin-bitcode" "/tmp/comgr-ff5509/rocm/amdgcn/bitcode/opencl.bc" "-mlink-builtin-bitcode" "/tmp/comgr-ff5509/rocm/amdgcn/bitcode/ocml.bc" "-mlink-builtin-bitcode" "/tmp/comgr-ff5509/rocm/amdgcn/bitcode/ockl.bc" "-mlink-builtin-bitcode" "/tmp/comgr-ff5509/rocm/amdgcn/bitcode/oclc_daz_opt_off.bc" "-mlink-builtin-bitcode" "/tmp/comgr-ff5509/rocm/amdgcn/bitcode/oclc_unsafe_math_off.bc" "-mlink-builtin-bitcode" "/tmp/comgr-ff5509/rocm/amdgcn/bitcode/oclc_finite_only_off.bc" "-mlink-builtin-bitcode" "/tmp/comgr-ff5509/rocm/amdgcn/bitcode/oclc_correctly_rounded_sqrt_off.bc" "-mlink-builtin-bitcode" "/tmp/comgr-ff5509/rocm/amdgcn/bitcode/oclc_wavefrontsize64_off.bc" "-mlink-builtin-bitcode" "/tmp/comgr-ff5509/rocm/amdgcn/bitcode/oclc_isa_version_1151.bc" "-mlink-builtin-bitcode" "/tmp/comgr-ff5509/rocm/amdgcn/bitcode/oclc_abi_version_600.bc" "-target-cpu" "gfx1151" "-debugger-tuning=gdb" "-fdebug-compilation-dir=/home/james/Documents/Python Bits" "-resource-dir" "/home/james/anaconda3/envs/pytorch/lib/python3.13/site-packages/_rocm_sdk_core/llvm/lib/clang/20" "-include-pch" "/tmp/comgr-ff5509/include/opencl2.0-c.pch" "-I" "/tmp/comgr-ff5509/include" "-D" "MIOPEN_USE_FP16=0" "-D" "MIOPEN_USE_FP32=1" "-D" "MIOPEN_USE_FPMIX=0" "-D" "MIOPEN_USE_BFPMIX=0" "-D" "MIO_SAVE_MEAN_VARIANCE=1" "-D" "MIO_RUNNING_RESULT=0" "-D" "MIO_BN_VARIANT=0" "-D" "MIO_BN_LDS_SIZE=256" "-D" "MIO_BN_LDSGCN_SIZE=4" "-D" "MIO_BN_N=1" "-D" "MIO_BN_NGRPS=1" "-D" "MIO_BN_NGRPS2=1" "-D" "MIO_BN_N_ELEMENTS=85899345921" "-D" "MIO_BN_GRP0=256" "-D" "MIO_BN_GRP1=1" "-D" "MIO_BN_GRP2=1" "-D" "MIO_BN_GRP0_FINAL=0" "-D" "MIO_BN_GRP1_FINAL=1" "-D" "MIO_BN_GRP2_FINAL=1" "-D" "MIO_BN_GFX103X=0" "-D" "MIO_BN_GFX110X=0" "-D" "MIO_BN_GFX120X=0" "-D" "MIO_LAYOUT_NHWC=0" "-D" "MIO_BN_VECTORIZE=0" "-D" "MIO_BN_VEC_SIZE=1" "-D" "MIO_BN_STASH_METHOD=0" "-D" "MIOPEN_NRN_OP_ID=0" "-D" "MIO_BN_C=2" "-D" "MIO_BN_HW=8" "-D" "MIO_BN_NHW=8" "-D" "MIO_BN_CHW=16" "-D" "MIO_BN_NCHW=16" "-D" "__IMAGE_SUPPORT__=1" "-D" "__OPENCL_VERSION__=200" "-internal-isystem" "/home/james/anaconda3/envs/pytorch/lib/python3.13/site-packages/_rocm_sdk_core/llvm/include/amdgcn-amd-amdhsa" "-O3" "-Wno-everything" "-std=cl2.0" "-ferror-limit" "19" "-cl-std=CL2.0" "-cl-kernel-arg-info" "-fno-threadsafe-statics" "-fskip-odr-check-in-gmf" "-vectorize-loops" "-vectorize-slp" "-fno-validate-pch" "-mlink-builtin-bitcode-postopt" "-mllvm" "-amdgpu-early-inline-all" "-mllvm" "-amdgpu-prelink" "-mllvm" "-amdgpu-internalize-symbols" "-faddrsig" "-o" "/tmp/comgr-ff5509/output/MIOpenBatchNormFwdTrainSpatial.cl.bc" "-x" "cl" "/tmp/comgr-ff5509/input/MIOpenBatchNormFwdTrainSpatial.cl"
	ReturnStatus: AMD_COMGR_STATUS_SUCCESS


<inline asm>:14:20: error: not a valid operand.
v_add_f32 v3 v3 v3 row_bcast:15 row_mask:0xa
                   ^
<inline asm>:15:20: error: not a valid operand.
v_add_f32 v2 v2 v2 row_bcast:15 row_mask:0xa
                   ^
<inline asm>:17:20: error: not a valid operand.
v_add_f32 v3 v3 v3 row_bcast:31 row_mask:0xc
                   ^
<inline asm>:18:20: error: not a valid operand.
v_add_f32 v2 v2 v2 row_bcast:31 row_mask:0xc
                   ^
MIOpen(HIP): Error [Do] 'amd_comgr_do_action(kind, handle, in.GetHandle(), out.GetHandle())' AMD_COMGR_ACTION_CODEGEN_BC_TO_RELOCATABLE: ERROR (1)
MIOpen(HIP): Error [BuildOcl] comgr status = ERROR (1)
MIOpen(HIP): Warning [BuildOcl] amd_comgr_do_action:
	  ActionKind: AMD_COMGR_ACTION_CODEGEN_BC_TO_RELOCATABLE
	     IsaName: amdgcn-amd-amdhsa--gfx1151
	     Options: "-DMIOPEN_USE_FP16=0" "-DMIOPEN_USE_FP32=1" "-DMIOPEN_USE_FPMIX=0" "-DMIOPEN_USE_BFPMIX=0" "-DMIO_SAVE_MEAN_VARIANCE=1" "-DMIO_RUNNING_RESULT=0" "-DMIO_BN_VARIANT=0" "-DMIO_BN_LDS_SIZE=256" "-DMIO_BN_LDSGCN_SIZE=4" "-DMIO_BN_N=1" "-DMIO_BN_NGRPS=1" "-DMIO_BN_NGRPS2=1" "-DMIO_BN_N_ELEMENTS=85899345921" "-DMIO_BN_GRP0=256" "-DMIO_BN_GRP1=1" "-DMIO_BN_GRP2=1" "-DMIO_BN_GRP0_FINAL=0" "-DMIO_BN_GRP1_FINAL=1" "-DMIO_BN_GRP2_FINAL=1" "-DMIO_BN_GFX103X=0" "-DMIO_BN_GFX110X=0" "-DMIO_BN_GFX120X=0" "-DMIO_LAYOUT_NHWC=0" "-DMIO_BN_VECTORIZE=0" "-DMIO_BN_VEC_SIZE=1" "-DMIO_BN_STASH_METHOD=0" "-DMIOPEN_NRN_OP_ID=0" "-DMIO_BN_C=2" "-DMIO_BN_HW=8" "-DMIO_BN_NHW=8" "-DMIO_BN_CHW=16" "-DMIO_BN_NCHW=16" "-Wno-everything" "-cl-std=CL2.0" "-cl-kernel-arg-info" "-D__IMAGE_SUPPORT__=1" "-D__OPENCL_VERSION__=200" "-mllvm" "-amdgpu-early-inline-all" "-mllvm" "-amdgpu-prelink" "-O3" "-mllvm" "-amdgpu-internalize-symbols"
	        Path: 
	    Language: AMD_COMGR_LANGUAGE_OPENCL_2_0
 Comgr Branch-Commit: HEAD-e130d9d39595
	 LLVM Commit: a7d47b26ca0ec0b3e9e4da83825cace5d761f4bc+PATCHED:1d3c56e3e837bfa87144aef73e9faad95492b591
    File System: VFS
    Compilation Args:  "-target" "amdgcn-amd-amdhsa" "-mcpu=gfx1151" "-c" "-mllvm" "-amdgpu-internalize-symbols" "-DMIOPEN_USE_FP16=0" "-DMIOPEN_USE_FP32=1" "-DMIOPEN_USE_FPMIX=0" "-DMIOPEN_USE_BFPMIX=0" "-DMIO_SAVE_MEAN_VARIANCE=1" "-DMIO_RUNNING_RESULT=0" "-DMIO_BN_VARIANT=0" "-DMIO_BN_LDS_SIZE=256" "-DMIO_BN_LDSGCN_SIZE=4" "-DMIO_BN_N=1" "-DMIO_BN_NGRPS=1" "-DMIO_BN_NGRPS2=1" "-DMIO_BN_N_ELEMENTS=85899345921" "-DMIO_BN_GRP0=256" "-DMIO_BN_GRP1=1" "-DMIO_BN_GRP2=1" "-DMIO_BN_GRP0_FINAL=0" "-DMIO_BN_GRP1_FINAL=1" "-DMIO_BN_GRP2_FINAL=1" "-DMIO_BN_GFX103X=0" "-DMIO_BN_GFX110X=0" "-DMIO_BN_GFX120X=0" "-DMIO_LAYOUT_NHWC=0" "-DMIO_BN_VECTORIZE=0" "-DMIO_BN_VEC_SIZE=1" "-DMIO_BN_STASH_METHOD=0" "-DMIOPEN_NRN_OP_ID=0" "-DMIO_BN_C=2" "-DMIO_BN_HW=8" "-DMIO_BN_NHW=8" "-DMIO_BN_CHW=16" "-DMIO_BN_NCHW=16" "-Wno-everything" "-cl-std=CL2.0" "-cl-kernel-arg-info" "-D__IMAGE_SUPPORT__=1" "-D__OPENCL_VERSION__=200" "-mllvm" "-amdgpu-early-inline-all" "-mllvm" "-amdgpu-prelink" "-O3" "-mllvm" "-amdgpu-internalize-symbols" "-nogpulib" "/tmp/comgr-b6856a/input/MIOpenBatchNormFwdTrainSpatial.cl.bc" "-o" "/tmp/comgr-b6856a/output/MIOpenBatchNormFwdTrainSpatial.cl.bc.o"
     Driver Job Args: clang "-cc1" "-triple" "amdgcn-amd-amdhsa" "-Werror=atomic-alignment" "-emit-obj" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "MIOpenBatchNormFwdTrainSpatial.cl.bc" "-mrelocation-model" "pic" "-pic-level" "2" "-fhalf-no-semantic-interposition" "-mframe-pointer=none" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-fvisibility=hidden" "-fapply-global-visibility-to-externs" "-target-cpu" "gfx1151" "-debugger-tuning=gdb" "-fdebug-compilation-dir=/home/james/Documents/Python Bits" "-resource-dir" "/home/james/anaconda3/envs/pytorch/lib/python3.13/site-packages/_rocm_sdk_core/llvm/lib/clang/20" "-O3" "-Wno-everything" "-ferror-limit" "19" "-cl-std=CL2.0" "-cl-kernel-arg-info" "-nogpulib" "-fskip-odr-check-in-gmf" "-vectorize-loops" "-vectorize-slp" "-mllvm" "-amdgpu-internalize-symbols" "-mllvm" "-amdgpu-early-inline-all" "-mllvm" "-amdgpu-prelink" "-mllvm" "-amdgpu-internalize-symbols" "-faddrsig" "-o" "/tmp/comgr-b6856a/output/MIOpenBatchNormFwdTrainSpatial.cl.bc.o" "-x" "ir" "/tmp/comgr-b6856a/input/MIOpenBatchNormFwdTrainSpatial.cl.bc"
error: cannot compile inline asm
error: cannot compile inline asm
error: cannot compile inline asm
error: cannot compile inline asm
4 errors generated.
	ReturnStatus: AMD_COMGR_STATUS_ERROR


MIOpen Error: /therock/src/rocm-libraries/projects/miopen/src/hipoc/hipoc_program.cpp:299: Code object build failed. Source: MIOpenBatchNormFwdTrainSpatial.cl
MIOpen(HIP): miopenStatus_t miopenDestroyTensorDescriptor(miopenTensorDescriptor_t){
MIOpen(HIP): 	tensorDesc = {1, 2, 1, 1, 1}, {2, 1, 1, 1, 1}, packed, 
MIOpen(HIP): }
MIOpen(HIP): miopenStatus_t miopenDestroyTensorDescriptor(miopenTensorDescriptor_t){
MIOpen(HIP): 	tensorDesc = {1, 2, 2, 2, 2}, {16, 8, 4, 2, 1}, packed, 
MIOpen(HIP): }
```

**Comment by k-artem** [comment]
@jrhip thanks, 
root cause that in build build args
> "-DMIO_BN_GFX103X=0" "-DMIO_BN_GFX110X=0" "-DMIO_BN_GFX120X=0"

`"-DMIO_BN_GFX115X=1"` is absent,  we will check internally with TheRock team and back.

**Comment by k-artem** [comment]
@jrhip please try latest nightly, works properly on my side

```pip install --index-url=https://rocm.nightlies.amd.com/v2-staging/gfx1151/ torch==2.11.0a0+rocm7.11.0a20251217```

```
...
Options: "-DMIOPEN_USE_FP16=0" "-DMIOPEN_USE_FP32=1" "-DMIOPEN_USE_FPMIX=0" "-DMIOPEN_USE_BFPMIX=0" "-DMIO_SAVE_MEAN_VARIANCE=1" "-DMIO_RUNNING_RESULT=0" "-DMIO_BN_VARIANT=0" "-DMIO_BN_LDS_SIZE=256" "-DMIO_BN_LDSGCN_SIZE=4" "-DMIO_BN_N=1" "-DMIO_BN_NGRPS=1" "-DMIO_BN_NGRPS2=1" "-DMIO_BN_N_ELEMENTS=140735107842448" "-DMIO_BN_GRP0=256" "-DMIO_BN_GRP1=1" "-DMIO_BN_GRP2=1" "-DMIO_BN_GRP0_FINAL=124734557534291" "-DMIO_BN_GRP1_FINAL=1" "-DMIO_BN_GRP2_FINAL=1" "-DMIO_BN_GFX103X=0" "-DMIO_BN_GFX110X=0" "-DMIO_BN_GFX120X=0" "-DMIO_BN_GFX115X=1" "-DMIO_LAYOUT_NHWC=0" "-DMIO_BN_VECTORIZE=0" "-DMIO_BN_VEC_SIZE=1" "-DMIO_BN_STASH_METHOD=0" "-DMIOPEN_NRN_OP_ID=0" "-DMIO_BN_C=2" "-DMIO_BN_HW=8" "-DMIO_BN_NHW=8" "-DMIO_BN_CHW=16" "-DMIO_BN_NCHW=16" "-Wno-everything" "-cl-std=CL2.0" "-cl-kernel-arg-info" "-D__IMAGE_SUPPORT__=1" "-D__OPENCL_VERSION__=200" "-mllvm" "-amdgpu-early-inline-all" "-mllvm" "-amdgpu-prelink" "-O3" "-mllvm" "-amdgpu-internalize-symbols"
...
```

**Comment by jrhip** [comment]
Great! Will test later today and get back to you.

**Comment by jrhip** [comment]
Yes that works now, thanks!
