### ISSUE TITLE
[Issue]: ComfyUI vae stage using cudnn will get error on gfx1103

### ISSUE THREAD

**Issue by LuXuxue** [ROCm/TheRock#2524]
### Problem Description

i'm testing torch-2.10.0a0+rocm7.11.0a20251211-cp312-cp312-win_amd64.whl on gfx1103(780M)
using comfyui with torch.backends.cudnn.enabled(tweak by custom_nodes) will cause black screen
and if using rdp to login system, we can see error log like this:

```
MIOpen(HIP): Error [GenericSearch] Error: Exception encountered : DESKTOP-5V05ODG:C:/home/runner/_work/TheRock/TheRock/rocm-libraries/projects/miopen/src/hip/handlehip.cpp:161: Error setting device 0: unspecified launch failure

MIOpen(HIP): Error [GenericSearch] #11 (12)  Failed rc=1
MIOpen(HIP): Error [FindSolutionImpl] Search Failed: 2x640x48x32x1x3x3x1x1280x2x1x1x0x1x1x0x1x1x0x0x1xNCHWxFP16xFConvBinWinogradRxSf3x2: DESKTOP-5V05ODG:C:/home/runner/_work/TheRock/TheRock/rocm-libraries/projects/miopen/src/include\miopen/generic_search.hpp:718: Search failed
MIOpen(HIP): Warning [Find] DESKTOP-5V05ODG:C:/home/runner/_work/TheRock/TheRock/rocm-libraries/projects/miopen/src/hip/handlehip.cpp:735: : unspecified launch failure
MIOpen(HIP): Error [EvaluateInvokers] DESKTOP-5V05ODG:C:/home/runner/_work/TheRock/TheRock/rocm-libraries/projects/miopen/src/hipoc/hipoc_program.cpp:368: Empty code object path.
MIOpen Error: DESKTOP-5V05ODG:C:/home/runner/_work/TheRock/TheRock/rocm-libraries/projects/miopen/src/hipoc/hipoc_program.cpp:368: Empty code object path.
C:\Portable\python_embeded-new\Lib\site-packages\torch\nn\modules\conv.py:548: UserWarning: HIP warning: unspecified launch failure (Triggered internally at B:/src/torch/aten/src\ATen/hip/impl/HIPGuardImplMasqueradingAsCUDA.h:83.)
  return F.conv2d(
```
without cudnn, speed of sdxl@1024x1536 is about 6s/it
and with cudnn, speed of sdxl@1024x1536 is about 3.7s/it(scottt‘s build)
maybe fix conv2d issue can speedup comfy

### Operating System

Windows 11 24H2

### CPU

AMD Ryzen 7 8845HS

### GPU

Radeon 780M Graphics

### ROCm Version

rocm7.11.0a20251211

### ROCm Component

MIOpen

### Steps to Reproduce

1. pip install rocm-7.11.0a20251211.tar.gz rocm_sdk_core-7.11.0a20251211-py3-none-win_amd64.whl rocm_sdk_devel-7.11.0a20251211-py3-none-win_amd64.whl rocm_sdk_libraries_gfx110x_all-7.11.0a20251211-py3-none-win_amd64.whl torch-2.10.0a0+rocm7.11.0a20251211-cp312-cp312-win_amd64.whl torchvision-0.25.0a0+rocm7.11.0a20251211-cp312-cp312-win_amd64.whl torchaudio-2.10.0a0+rocm7.11.0a20251211-cp312-cp312-win_amd64.whl
2. install comfy
3. install https://github.com/patientx/ComfyUI-Zluda/blob/master/cfz/nodes/cfz_cudnn.toggle.py
4. turn on enable_cudnn and cudnn_benchmark
5. error

**Comment by ScottTodd** [comment]
Does this reproduce on torch 2.9.1? I'm setting up pytorch unit test coverage on Windows (https://github.com/ROCm/TheRock/issues/2258) and I see similar `HIP error: unspecified launch failure` on torch 2.10.0a but _not_ on torch 2.9.1, at least on gfx1151.

**Comment by astrelsky** [comment]
I think this might be the same as #2488 and #2489. For which I get the problem using 2.9.1+rocm7.11.0a20251211

**Comment by LuXuxue** [comment]
> Does this reproduce on torch 2.9.1? I'm setting up pytorch unit test coverage on Windows ([#2258](https://github.com/ROCm/TheRock/issues/2258)) and I see similar `HIP error: unspecified launch failure` on torch 2.10.0a but _not_ on torch 2.9.1, at least on gfx1151.

same error, and 2.9.1 have not enabled aotriton, will get worse speed, about 7.5s/it

**Comment by astrelsky** [comment]
> > Does this reproduce on torch 2.9.1? I'm setting up pytorch unit test coverage on Windows ([#2258](https://github.com/ROCm/TheRock/issues/2258)) and I see similar `HIP error: unspecified launch failure` on torch 2.10.0a but _not_ on torch 2.9.1, at least on gfx1151.
> 
> same error, and 2.9.1 have not enabled aotriton, will get worse speed, about 7.5it/s

7.5it/s is really good. Perhaps you meant 7.5s/it?.

**Comment by LuXuxue** [comment]
test report on torch-2.10.0a0+rocm7.11.0a20251213-cp312-cp312-win_amd64.whl:
after i upgrade torch, i run comfy directly with cudnn. after a `warning: xnack 'Off' was requested for a processor that does not support it!` log and a long time(about 11min) benchmark(or something else), it generated a blank image.
a normal image was generated on the second run, at speed of about 5.3s/it, which is a bit faster than the speed without cudnn, but is slower than scottt‘s build.
maybe it is the backend difference, so i closed comfy, and run a test script([validate_pytorch_vroom.py](https://github.com/user-attachments/files/24142385/validate_pytorch_vroom.py)), everything passed and it said backend is Cublas, while scottt‘s build's backend is Cublaslt.
i run comfy again, and i meet the black screen and the error log. delete .miopen folder and reboot system can not solve this problem.
comfy dead, but the test script is still alive, showing a better performance number in theory.

**Comment by astrelsky** [comment]
@LuXuxue your symptoms are suspiciously similar to behavior I was seeing and hopefully https://github.com/ROCm/rocm-libraries/pull/3364 will fix it.

**Comment by LuXuxue** [comment]
test on torch-2.9.1+rocm7.11.0a20251219-cp312-cp312-win_amd64.whl: fixed, speed is about 5.2s/it with or without cudnn(with cudnn is a little faster, but it takes a long time before the first run)
there is no torch 2.10a whl today, i will test on 2.10 when new whl released

**Comment by ScottTodd** [comment]
> there is no torch 2.10a whl today, i will test on 2.10 when new whl released

FYI torch updated the latest version to 2.11.0a0, so we'll be switching to advertising "2.10 stable/final" and "2.11 alpha" at https://github.com/ROCm/TheRock/tree/main/external-builds/pytorch#supported-pytorch-versions soon. Builds since 2025-12-14 have been using the newer version.

But yes, today and yesterday we did not have successful builds of "nightly" pytorch due to https://github.com/ROCm/TheRock/issues/2628

**Comment by LuXuxue** [comment]
> [@LuXuxue](https://github.com/LuXuxue) your symptoms are suspiciously similar to behavior I was seeing and hopefully [ROCm/rocm-libraries#3364](https://github.com/ROCm/rocm-libraries/pull/3364) will fix it.

issue is fixed on sampling steps. but when i try to enable cudnn on vae step, black screen with error like this:

```
MIOpen(HIP): Error [EvaluateInvokers] DESKTOP-5V05ODG:C:/home/runner/_work/TheRock/TheRock/rocm-libraries/projects/miopen/src/hip/handlehip.cpp:161: Error setting device 0: unspecified launch failure
C:\Portable\python_embeded-new\Lib\site-packages\torch\nn\modules\conv.py:543: UserWarning: HIP warning: unspecified launch failure (Triggered internally at B:/src/torch/aten/src\ATen/hip/impl/HIPGuardImplMasqueradingAsCUDA.h:83.)
  return F.conv2d(
!!! Exception during processing !!! HIP error: unspecified launch failure
```

**Comment by LuXuxue** [comment]
test on torch-2.11.0a0+rocm7.11.0a20260106-cp313-cp313-win_amd64.whl:

With triton-windows and sageattention, speed on gfx1103 got a boost. Now we can get the speed almost as fast as scottt‘s build. --use-pytorch-cross-attention is still 10% slower than scottt‘s build.
Tiled vae with cudnn can run without error. 

[HQ.json](https://github.com/user-attachments/files/24454403/HQ.json) 

From the second run, this test workflow(768x1280 with 1.5xHiRes) use about 185s with --use-sage-attention, and about 204s with --use-pytorch-cross-attention.
We still need to disable cudnn if we don't want to use tiled vae, or we will get error like this:

[error log.txt](https://github.com/user-attachments/files/24454435/error.log.txt)

During test, i found a interesting bug in scottt‘s build:
Normally, i set cudnn on before sampler stage and vae stage, it takes about 181s per run.  But if i turn cudnn off and on again before every sampler stage and vae stage, i can get a speed boost, about 166s per run, almost 8% speed up.
This bug does not exist in torch-2.11.0a0+rocm7.11.0a20260106-cp313-cp313-win_amd64.whl.

following https://github.com/ROCm/TheRock/issues/2591#issuecomment-3715412951 by setting PYTORCH_TUNABLEOP_ENABLED=1, rocm7 can get the speed of 165s per run now, and this does not need to toggle cudnn off and on.

**Comment by LuXuxue** [comment]
Tested on torch-2.11.0a0+rocm7.12.0a20260129-cp313-cp313-win_amd64.whl, black screen problem have been solved, but I still get error on vae stage if i'm not using tiled vae or set MIOPEN_FIND_MODE=2. The default MIOPEN_FIND_MODE is 3, and it will cause error.
Maybe there is a problem with certain solver that can not deal with big data size on gfx1103, and miopen benchmark wrongly use it.

**Comment by LuXuxue** [comment]
Local build and using patch in https://github.com/ROCm/rocm-libraries/issues/3509, error fixed. The default MIOPEN_FIND_MODE=3 no more report error. Maybe naive solver have some problem in it.

**Comment by LuXuxue** [comment]
In https://github.com/ROCm/rocm-libraries/pull/4212, johannes-graner try to solve direct solver issue by setting a max size. ComfyUI does not need direct solver at all as we have many other solers, so I just try to set `MIOPEN_DEBUG_CONV_DIRECT=0`, everything works perfect on torch-2.11.0a0+rocm7.12.0a20260205-cp313-cp313-win_amd64.whl. No need to disable cudnn on vae stage, No need to set MIOPEN_FIND_MODE for quick benchmark, No need to local build rocm using skip naive solver patch.
I locally build gfx1035(680M), it works well with sage attention.

**Comment by qnxsgwy** [comment]
> In [ROCm/rocm-libraries#4212](https://github.com/ROCm/rocm-libraries/pull/4212), johannes-graner try to solve direct solver issue by setting a max size. ComfyUI does not need direct solver at all as we have many other solers, so I just try to set `MIOPEN_DEBUG_CONV_DIRECT=0`, everything works perfect on torch-2.11.0a0+rocm7.12.0a20260205-cp313-cp313-win_amd64.whl. No need to disable cudnn on vae stage, No need to set MIOPEN_FIND_MODE for quick benchmark, No need to local build rocm using skip naive solver patch. I locally build gfx1035(680M), it works well with sage attention.

Hello, could you share the latest ROCm wheels and PyTorch wheels you built for gfx1035 (680M), or share the build instructions? Thank you very much.

**Comment by LuXuxue** [comment]
> Hello, could you share the latest ROCm wheels and PyTorch wheels you built for gfx1035 (680M), or share the build instructions? Thank you very much.

I did nothing special, just follow https://github.com/ROCm/TheRock/blob/main/docs/development/windows_support.md and use -DTHEROCK_AMDGPU_FAMILIES=gfx103X-igpu for rocm build, and https://github.com/ROCm/TheRock/blob/main/external-builds/pytorch/README.md for pytorch build
wheels are too big to upload, there are 5.30GB total. I have no idea about why they are so big.
