### ISSUE TITLE
[Issue]: Cannot find the function: ...

### ISSUE THREAD

**Issue by astrelsky** [ROCm/TheRock#2978]
### Problem Description

Win11 10.0.26200

### Operating System

10.0.26200

### CPU

AMD Ryzen AI 9 HX 370 w/ Radeon 890M

### GPU

Radeon 890M (gfx1150)

### ROCm Version

rocm7.11.0a20260114, rocm7.11.0a20260115, rocm7.11.0a20260116

### Steps to Reproduce

Run inference with SD.Next. Comfyui seems to work ok, at least when I tried yesterday. Didn't bother today.

### Additional Information

There doesn't appear to be enough information provided by logs with max verbosity.

[logs.zip](https://github.com/user-attachments/files/24682778/logs.zip)

```
16:49:06-824629 WARNING  Decode: type="taesd" variant="TAESD 1.3 Mocha Croissant": decode: miopenStatusInternalError
Progress  3.10s/it █████████████████████████████████ 100% 20/20 01:01 00:00 Base
16:50:04-091366 INFO     Processing modifiers: unapply
16:50:04-278864 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}
16:50:04-295003 ERROR    Control: type=controlnet units=0 HIP error: named symbol not found
                         Search for `hipErrorNotFound' in
                         https://docs.nvidia.com/cuda/cuda-runtime-api/group__HIPRT__TYPES.html for more information.
                         HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace
                         below might be incorrect.
                         For debugging consider passing AMD_SERIALIZE_KERNEL=3
                         Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

16:50:04-295003 ERROR    Control: AcceleratorError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│C:\Users\astre\Documents\StabilityMatrix-win-x64\Data\Packages\SD.Next\modules\control\run.py:614 in control_run      │
│                                                                                                                      │
│  613 │   │   │   │   │   │   if processed is None:                                                                   │
│❱ 614 │   │   │   │   │   │   │   processed: processing.Processed = processing.process_images(p) # run actual pipelin │
│  615 │   │   │   │   │   │   else:                                                                                   │
│                                                                                                                      │
│C:\Users\astre\Documents\StabilityMatrix-win-x64\Data\Packages\SD.Next\modules\processing.py:222 in process_images    │
│                                                                                                                      │
│  221 │   │   │   with context_hypertile_vae(p), context_hypertile_unet(p):                                           │
│❱ 222 │   │   │   │   results = process_images_inner(p)                                                               │
│  223                                                                                                                 │
│                                                                                                                      │
│C:\Users\astre\Documents\StabilityMatrix-win-x64\Data\Packages\SD.Next\modules\processing.py:455 in process_images_in │
│                                                                                                                      │
│  454 │   │   │   │   from modules.processing_diffusers import process_diffusers                                      │
│❱ 455 │   │   │   │   samples = process_diffusers(p)                                                                  │
│  456 │   │   │   timer.process.record('process')                                                                     │
│                                                                                                                      │
│C:\Users\astre\Documents\StabilityMatrix-win-x64\Data\Packages\SD.Next\modules\processing_diffusers.py:606 in process │
│                                                                                                                      │
│  605 │                                                                                                               │
│❱ 606 │   results = process_decode(p, output)                                                                         │
│  607 │   timer.process.record('decode')                                                                              │
│                                                                                                                      │
│C:\Users\astre\Documents\StabilityMatrix-win-x64\Data\Packages\SD.Next\modules\processing_diffusers.py:474 in process │
│                                                                                                                      │
│  473 │   │   │   else:                                                                                               │
│❱ 474 │   │   │   │   results = processing_vae.vae_decode(                                                            │
│  475 │   │   │   │   │   latents = output.images,                                                                    │
│                                                                                                                      │
│C:\Users\astre\Documents\StabilityMatrix-win-x64\Data\Packages\SD.Next\modules\processing_vae.py:314 in vae_decode    │
│                                                                                                                      │
│  313 │   elif vae_type == 'Full' and hasattr(model, "vae"):                                                          │
│❱ 314 │   │   decoded = full_vae_decode(latents=latents, model=model)                                                 │
│  315 │   elif hasattr(model, "vqgan"):                                                                               │
│                                                                                                                      │
│C:\Users\astre\Documents\StabilityMatrix-win-x64\Data\Packages\SD.Next\modules\processing_vae.py:126 in full_vae_deco │
│                                                                                                                      │
│  125 │   else:                                                                                                       │
│❱ 126 │   │   latents = latents / scaling_factor                                                                      │
│  127 │   if shift_factor:                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AcceleratorError: HIP error: named symbol not found
Search for `hipErrorNotFound' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__HIPRT__TYPES.html for more information.
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
```

**Comment by astrelsky** [comment]
Here are logs with the commgr logs enabled, as well as the temporary files generated. It's hard to remember to get everything since there are so many different environment variables.


[logs.zip](https://github.com/user-attachments/files/24682918/logs.zip)

[commgr.zip](https://github.com/user-attachments/files/24682906/commgr.zip)

[miopen.zip](https://github.com/user-attachments/files/24689407/miopen.zip)

**Comment by astrelsky** [comment]
Well, now I get it running comfyui too, but this time more information.

```
warning: xnack 'Off' was requested for a processor that does not support it!
MIOpen(HIP): Error [Do] 'amd_comgr_do_action(kind, handle, in.GetHandle(), out.GetHandle())' : ERROR (1)
MIOpen(HIP): Error [BuildAsm] comgr status = ERROR (1)
MIOpen(HIP): Warning [BuildAsm] amd_comgr_do_action:
          ActionKind: AMD_COMGR_ACTION_ASSEMBLE_SOURCE_TO_RELOCATABLE
             IsaName: amdgcn-amd-amdhsa--gfx1150
             Options: "-Wa,-defsym,ROCM_METADATA_VERSION=5" "-mcumode" "-mwavefrontsize64" "-mno-xnack"
                Path:
            Language: AMD_COMGR_LANGUAGE_NONE
 Comgr Branch-Commit: undefined-c051b301d1c2
         LLVM Commit: 08a72fce79ea9208f36b7845aa37aedfbaac39ee+PATCHED:093518e8e59892fbc4b55b6652dec090672d32ff
    File System: Real
    Compilation Args:  "-target" "amdgcn-amd-amdhsa" "-mcpu=gfx1150" "-I" "C:\Users\astre\AppData\Local\Temp\comgr-20380-37-e2efd4\include" "-no-integrated-cpp" "-dD" "-c" "-x" "assembler" "-Wa,-defsym,ROCM_METADATA_VERSION=5" "-mcumode" "-mwavefrontsize64" "-mno-xnack" "-Xclang" "-no-disable-free" "C:\Users\astre\AppData\Local\Temp\comgr-20380-37-e2efd4\input\Conv_Winograd_Fury_v2_4_1_fp16_fp16acc_f2x3_c32_stride1.s" "-o" "C:\Users\astre\AppData\Local\Temp\comgr-20380-37-e2efd4\output\Conv_Winograd_Fury_v2_4_1_fp16_fp16acc_f2x3_c32_stride1.o"
warning: argument unused during compilation: '-dD' [-Wunused-command-line-argument]
warning: argument unused during compilation: '-Xclang -no-disable-free' [-Wunused-command-line-argument]
     Driver Job Args: clang "-cc1as" "-triple" "amdgcn-amd-amdhsa" "-filetype" "obj" "-main-file-name" "Conv_Winograd_Fury_v2_4_1_fp16_fp16acc_f2x3_c32_stride1.s" "-target-cpu" "gfx1150" "-target-feature" "+wavefrontsize64" "-target-feature" "+cumode" "-target-feature" "-xnack" "-I" "C:\Users\astre\AppData\Local\Temp\comgr-20380-37-e2efd4\include" "-fdebug-compilation-dir=C:\Users\astre\Documents\StabilityMatrix-win-x64\Data\Packages\ComfyUI" "-dwarf-debug-producer" "AMD clang version 22.0.0git (https://github.com/ROCm/llvm-project.git 08a72fce79ea9208f36b7845aa37aedfbaac39ee+PATCHED:093518e8e59892fbc4b55b6652dec090672d32ff)" "-I" "C:\Users\astre\AppData\Local\Temp\comgr-20380-37-e2efd4\include" "-dwarf-version=5" "-mrelocation-model" "pic" "--defsym" "ROCM_METADATA_VERSION=5" "-o" "C:\Users\astre\AppData\Local\Temp\comgr-20380-37-e2efd4\output\Conv_Winograd_Fury_v2_4_1_fp16_fp16acc_f2x3_c32_stride1.o" "C:\Users\astre\AppData\Local\Temp\comgr-20380-37-e2efd4\input\Conv_Winograd_Fury_v2_4_1_fp16_fp16acc_f2x3_c32_stride1.s"
C:\Users\astre\AppData\Local\Temp\comgr-20380-37-e2efd4\input\Conv_Winograd_Fury_v2_4_1_fp16_fp16acc_f2x3_c32_stride1.s:5407:9: error: Unsupported gpu
        .error "Unsupported gpu"
        ^
        ReturnStatus: AMD_COMGR_STATUS_ERROR


MIOpen Error: geekom:D:/TheRock/rocm-libraries/projects/miopen/src/hipoc/hipoc_program.cpp:299: Code object build failed. Source: Conv_Winograd_Fury_v2_4_1_fp16_fp16acc_f2x3_c32_stride1.s
```

[Conv_Winograd_Fury_v2_4_1_fp16_fp16acc_f2x3_c32_stride1.s](https://github.com/user-attachments/files/24692222/Conv_Winograd_Fury_v2_4_1_fp16_fp16acc_f2x3_c32_stride1.s.txt)

~~This doesn't appear to be the same as the file here https://github.com/ROCm/rocm-libraries/blob/e80c412f2e6f44a2c16c11c1006d189f8216740e/projects/miopen/src/kernels/winograd/Conv_Winograd_Fury_v2_4_1_fp16_fp16acc_f2x3_c32_stride1.s and I don't understand why.~~ It had been pre-processed with the `.inc` file already.

**Comment by astrelsky** [comment]
Regarding the `warning: xnack 'Off' was requested for a processor that does not support it!`, does this mean that the gfx1150 doesn't support xnack, or it doesn't support turning it off?

**Comment by astrelsky** [comment]
Temporary workaround is to use `MIOPEN_DEBUG_AMD_WINOGRAD_FURY_RXS_F2X3=0`

**Comment by k-artem** [comment]
@astrelsky , root cause is next:
here 

<img width="794" height="168" alt="Image" src="https://github.com/user-attachments/assets/dd4419b2-1042-4fa2-8738-e6e73de1898c" />
gfx1150 mentioned as full vgpr arch and it leads to run internal perf model for selection kernel

<img width="730" height="125" alt="Image" src="https://github.com/user-attachments/assets/7fa6490d-9f4a-49f2-bd68-667bf8b27716" />

, for your testcase `Conv_Winograd_Fury_v2_4_1_fp16_fp16acc_f2x3_c32_stride1.s` has been selected but this kernel doesn't support  on this arch

<img width="1068" height="303" alt="Image" src="https://github.com/user-attachments/assets/d21faeaa-3502-4498-9fbf-077e863cf65d" />

so need to fix it inside `conv_wino_fury_RxS.cpp` and prevent selection of this kernel.

**Comment by astrelsky** [comment]
Thank you @k-artem . I can probably temporarily patch that locally so at least the other Winograd kernels can be used.

**Comment by astrelsky** [comment]
> @astrelsky , root cause is next:
> here 
> 
> <img width="794" height="168" alt="Image" src="https://github.com/user-attachments/assets/dd4419b2-1042-4fa2-8738-e6e73de1898c" />
> gfx1150 mentioned as full vgpr arch and it leads to run internal perf model for selection kernel
> 
> <img width="730" height="125" alt="Image" src="https://github.com/user-attachments/assets/7fa6490d-9f4a-49f2-bd68-667bf8b27716" />
> 
> , for your testcase `Conv_Winograd_Fury_v2_4_1_fp16_fp16acc_f2x3_c32_stride1.s` has been selected but this kernel doesn't support  on this arch
> 
> <img width="1068" height="303" alt="Image" src="https://github.com/user-attachments/assets/d21faeaa-3502-4498-9fbf-077e863cf65d" />
> 
> so need to fix it inside `conv_wino_fury_RxS.cpp` and prevent selection of this kernel. 
> 

Out of curiosity, how come gfx1151 has reduced vgpr memory, but yet is supported by that kernel? Just trying to understand why that one is supported but gfx1150 isn't, or if the reduced vgpr memory is actually unrelated.


Oh, I read it inverted, it doesn't have reduced vgpr memory. Nevermind that then. I would still like to understand why the kernel supports gfx1151 but not gfx1150.

**Comment by k-artem** [comment]
@astrelsky please try https://github.com/ROCm/rocm-libraries/pull/4023

**Comment by astrelsky** [comment]
> [@astrelsky](https://github.com/astrelsky) please try [ROCm/rocm-libraries#4023](https://github.com/ROCm/rocm-libraries/pull/4023)

I won't be able to check until tonight, but I'll let you know as soon as I do.

**Comment by astrelsky** [comment]
> [@astrelsky](https://github.com/astrelsky) please try [ROCm/rocm-libraries#4023](https://github.com/ROCm/rocm-libraries/pull/4023)

@k-artem I just finished confirming it fixes the issue. I deleted the `.miopen` folder before testing and I checked my ufdb afterwards and found this, so winograd is being used again.
`384-152-104-3x3-4-152-104-2-1x1-1x1-1x1-0-NCHW-FP16-F=ConvWinoFuryRxS<2-3>:0.39654,0,miopenConvolutionFwdAlgoWinograd;ConvHipImplicitGemmGroupFwdXdlops:3.66305,24561664,miopenConvolutionFwdAlgoImplicitGEMM;GemmFwdRest:6.48271,109264896,miopenConvolutionFwdAlgoGEMM;ConvBinWinogradRxSf3x2:0.72878,0,miopenConvolutionFwdAlgoWinograd;ConvBinWinogradRxSf2x3g1:0.4844,0,miopenConvolutionFwdAlgoWinograd`
