### ISSUE TITLE
[Issue]: [gfx1103] HSA_ERROR_INVALID_ISA error occurred during calculation in FP16

### ISSUE THREAD

**Issue by libra-379125** [ROCm/TheRock#3044]
### Problem Description

When I tried benchmarking resnet50 using pytorch-micor-benchmarking, an error occurred in fp16 mode, but it ran without any problems in 32-bit mode.

output message: 

INFO: running forward and backward for warmup.
Kernel Name: miopenSp3AsmConvFury_v2_4_1_gfx11_1024vgprs_fp16_fp16acc_f2x3_c16_stride1
VGPU=0x493b4330 SWq=0x74b6496e0000, HWq=0x74b60c100000, id=1
	Dispatch Header =0xb02 (type=2, barrier=1, acquire=1, release=1), setup=0
	grid=[4608, 1, 1], workgroup=[384, 1, 1]
	private_seg_size=0, group_seg_size=65536
	kernel_obj=0x74b60e2a0f80, kernarg_address=0x0x74b4fe41fe80
	completion_signal=0x74b60fdf4780, correlation_id=0
	rptr=1111, wptr=1112
:0:rocdevice.cpp            :3756: 8633521827 us:  Callback: Queue 0x74b60c100000 aborting with error : HSA_STATUS_ERROR_INVALID_ISA: The instruction set architecture is invalid. code: 0x100f
Aborted (core dumped)

### Operating System

Ubuntu24.0.2 LTS(Noble Nubat)

### CPU

AMD Ryzen 9 7940HS w

### GPU

 Radeon 780M Graphics

### ROCm Version

7.11.0a20260121

### Steps to Reproduce

Run pytorch-micro-benchmarking in 16-bit mode.

git link: https://github.com/ROCm/pytorch-micro-benchmarking
execution command: "python3 micro_benchmarking_pytorch.py --network resnet50 --fp16 1"

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.18
Runtime Ext Version:     1.15
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
XNACK enabled:           NO
DMAbuf Support:          YES
VMM Support:             YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 9 7940HS w/ Radeon 780M Graphics
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen 9 7940HS w/ Radeon 780M Graphics
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   0                                  
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            16                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Memory Properties:       
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    32070452(0x1e95b34) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    32070452(0x1e95b34) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    32070452(0x1e95b34) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 4                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    32070452(0x1e95b34) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1103                            
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon 780M Graphics           
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      2048(0x800) KB                     
  Chip ID:                 5567(0x15bf)                       
  ASIC Revision:           7(0x7)                             
  Cacheline Size:          128(0x80)                          
  Max Clock Freq. (MHz):   2799                               
  BDFID:                   50176                              
  Internal Node ID:        1                                  
  Compute Unit:            12                                 
  SIMDs per CU:            2                                  
  Shader Engines:          1                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Memory Properties:       APU
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        2147483647(0x7fffffff)             
    y                        65535(0xffff)                      
    z                        65535(0xffff)                      
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 35                                 
  SDMA engine uCode::      16                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    29360128(0x1c00000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    29360128(0x1c00000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1103         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        2147483647(0x7fffffff)             
        y                        65535(0xffff)                      
        z                        65535(0xffff)                      
      FBarrier Max Size:       32                                 
    ISA 2                    
      Name:                    amdgcn-amd-amdhsa--gfx11-generic   
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        2147483647(0x7fffffff)             
        y                        65535(0xffff)                      
        z                        65535(0xffff)                      
      FBarrier Max Size:       32                                 
*** Done ***

**Comment by libra-379125** [comment]
After some experimentation, I found that setting the environment variable MIOPEN_FIND_MODE=2 worked well.

**Comment by k-artem** [comment]
EDIT
~Hi @libra-379125, probably similar to https://github.com/ROCm/TheRock/issues/2978 that was fixed.~
@adityas-amd if you able to repro it, please attach logs of running `python3 micro_benchmarking_pytorch.py --network resnet50 --fp16 1` with next env vars: `AMD_COMGR_EMIT_VERBOSE_LOGS=1 MIOPEN_LOG_LEVEL=6 MIOPEN_ENABLE_LOGGING_CMD=1 MIOPEN_ENABLE_LOGGING=1 `

**Comment by adityas-amd** [comment]
log files, even with different modes I get the same failures [out.log](https://github.com/user-attachments/files/25015147/out.log)

**Comment by k-artem** [comment]
@libra-379125 as temporary workaround please use `export MIOPEN_DEBUG_AMD_WINOGRAD_FURY_RXS_F2X3=0`

**Comment by k-artem** [comment]
Also repro on **gfx1152**, discussing with driver team in progress.

Cmd:
```
rm -rf ${HOME}/.cache/miopen && MIOPEN_FIND_MODE=HYBRID  MIOPEN_FIND_ENFORCE=3 MIOPEN_LOG_LEVEL=6 MIOPEN_ENABLE_LOGGING_CMD=1 MIOPEN_ENABLE_LOGGING=1 MIOpenDriver convfp16 -n 64 -c 64 -H 56 -W 56 -k 64 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
```

ROCm version:
```
pip install --index-url https://rocm.nightlies.amd.com/v2/gfx1152/ "rocm[libraries,devel]" --force-reinstall
```

Kernel info:
```
(.venv) amd@ctr-krkn-at48-2:~/therock$ uname -r
6.14.0-1020-oem
```

GPU info
```
*******
Agent 2
*******
  Name:                    gfx1152
  Uuid:                    GPU-XX
  Marketing Name:          AMD Radeon 840M Graphics
  Vendor Name:             AMD
  Feature:                 KERNEL_DISPATCH
  Profile:                 BASE_PROFILE
  Float Round Mode:        NEAR
  Max Queue Number:        128(0x80)
  Queue Min Size:          64(0x40)
  Queue Max Size:          131072(0x20000)
  Queue Type:              MULTI
  Node:                    1
  Device Type:             GPU
  Cache Info:
    L1:                      32(0x20) KB
    L2:                      1024(0x400) KB
  Chip ID:                 4372(0x1114)
  ASIC Revision:           0(0x0)
  Cacheline Size:          128(0x80)
  Max Clock Freq. (MHz):   2900
  BDFID:                   50176
  Internal Node ID:        1
  Compute Unit:            4
  SIMDs per CU:            2
  Shader Engines:          1
  Shader Arrs. per Eng.:   2
  WatchPts on Addr. Ranges:4
  Coherent Host Access:    FALSE
  Memory Properties:       APU
  Features:                KERNEL_DISPATCH
  Fast F16 Operation:      TRUE
  Wavefront Size:          32(0x20)
  Workgroup Max Size:      1024(0x400)
  Workgroup Max Size per Dimension:
    x                        1024(0x400)
    y                        1024(0x400)
    z                        1024(0x400)
  Max Waves Per CU:        32(0x20)
  Max Work-item Per CU:    1024(0x400)
  Grid Max Size:           4294967295(0xffffffff)
  Grid Max Size per Dimension:
    x                        2147483647(0x7fffffff)
    y                        65535(0xffff)
    z                        65535(0xffff)
  Max fbarriers/Workgrp:   32
  Packet Processor uCode:: 15
  SDMA engine uCode::      12
  IOMMU Support::          None
  Pool Info:
    Pool 1
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED
      Size:                    7855184(0x77dc50) KB
      Allocatable:             TRUE
      Alloc Granule:           4KB
      Alloc Recommended Granule:2048KB
      Alloc Alignment:         4KB
      Accessible by all:       FALSE
    Pool 2
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    7855184(0x77dc50) KB
      Allocatable:             TRUE
      Alloc Granule:           4KB
      Alloc Recommended Granule:2048KB
      Alloc Alignment:         4KB
      Accessible by all:       FALSE
    Pool 3
      Segment:                 GROUP
      Size:                    64(0x40) KB
      Allocatable:             FALSE
      Alloc Granule:           0KB
      Alloc Recommended Granule:0KB
      Alloc Alignment:         0KB
      Accessible by all:       FALSE
  ISA Info:
    ISA 1
      Name:                    amdgcn-amd-amdhsa--gfx1152
      Machine Models:          HSA_MACHINE_MODEL_LARGE
      Profiles:                HSA_PROFILE_BASE
      Default Rounding Mode:   NEAR
      Default Rounding Mode:   NEAR
      Fast f16:                TRUE
      Workgroup Max Size:      1024(0x400)
      Workgroup Max Size per Dimension:
        x                        1024(0x400)
        y                        1024(0x400)
        z                        1024(0x400)
      Grid Max Size:           4294967295(0xffffffff)
      Grid Max Size per Dimension:
        x                        2147483647(0x7fffffff)
        y                        65535(0xffff)
        z                        65535(0xffff)
      FBarrier Max Size:       32
    ISA 2
      Name:                    amdgcn-amd-amdhsa--gfx11-generic
      Machine Models:          HSA_MACHINE_MODEL_LARGE
      Profiles:                HSA_PROFILE_BASE
      Default Rounding Mode:   NEAR
      Default Rounding Mode:   NEAR
      Fast f16:                TRUE
      Workgroup Max Size:      1024(0x400)
      Workgroup Max Size per Dimension:
        x                        1024(0x400)
        y                        1024(0x400)
        z                        1024(0x400)
      Grid Max Size:           4294967295(0xffffffff)
      Grid Max Size per Dimension:
        x                        2147483647(0x7fffffff)
        y                        65535(0xffff)
        z                        65535(0xffff)
      FBarrier Max Size:       32
```

**Comment by libra-379125** [comment]
> 編集 ~こんにちは[@libra-379125](https://github.com/libra-379125)おそらく修正された[#2978と同様です。](https://github.com/ROCm/TheRock/issues/2978)~ [@adityas-amd](https://github.com/adityas-amd)再現できる場合は、`python3 micro_benchmarking_pytorch.py --network resnet50 --fp16 1`次の環境変数で実行したログを添付してください。`AMD_COMGR_EMIT_VERBOSE_LOGS=1 MIOPEN_LOG_LEVEL=6 MIOPEN_ENABLE_LOGGING_CMD=1 MIOPEN_ENABLE_LOGGING=1 `

Sorry for the late reply. I tried the latest daily build and was able to reproduce the issue. I've attached the logs.

MIOpen(HIP): Info [EvaluateInvokers] Evaluating Solver: miopenConvolutionFwdAlgoWinograd:ConvWinoFuryRxS<2-3>
MIOpen(HIP): Info2 [PrepareInvoker] Preparing kernel: miopenSp3AsmConvFury_v2_4_1_gfx11_1024vgprs_fp16_fp16acc_f2x3_c16_stride1
MIOpen(HIP): Info2 [MakeGcnAsmWinoV2InvokerFactory]  N=64 C=64 H=56 W=56 K=64 R=1 S=1 pad_H=0 pad_W=0 out_H=56 out_W=56 G=1 alpha=0 beta=0 act_mode=0 d_offset=0 f_offset=0 o_offset=0 b_offset=0 d_N_stride=200704 d_C_stride=3136 d_H_stride=56 d_G_stride=200704 f_K_stride=64 f_C_stride=1 f_R_stride=1 f_G_stride=4096 o_N_stride=200704 o_K_stride=3136 o_H_stride=56 o_G_stride=200704 n_groups=12 flags64=0xe200 sync_limit=0 sync_period=0
MIOpen(HIP): Info2 [run] kernel_name = miopenSp3AsmConvFury_v2_4_1_gfx11_1024vgprs_fp16_fp16acc_f2x3_c16_stride1, global_work_dim = { 4608, 1, 1 }, local_work_dim = { 384, 1, 1 }
Kernel Name: miopenSp3AsmConvFury_v2_4_1_gfx11_1024vgprs_fp16_fp16acc_f2x3_c16_stride1
VGPU=0x34c05de0 SWq=0x78e53afb3000, HWq=0x78e51c200000, id=1
	Dispatch Header =0xb02 (type=2, barrier=1, acquire=1, release=1), setup=0
	grid=[4608, 1, 1], workgroup=[384, 1, 1]
	private_seg_size=0, group_seg_size=65536
	kernel_obj=0x78e5243f0f80, kernarg_address=0x0x78e414c01800
	completion_signal=0x78e525df7000, correlation_id=0
	rptr=3720, wptr=3721
:0:rocdevice.cpp            :3868: 12680118200 us:  Callback: Queue 0x78e51c200000 aborting with error : HSA_STATUS_ERROR_INVALID_ISA: The instruction set architecture is invalid. code: 0x100f
Aborted (core dumped)

Thanks.

**Comment by libra-379125** [comment]
> [@libra-379125](https://github.com/libra-379125) as temporary workaround please use `export MIOPEN_DEBUG_AMD_WINOGRAD_FURY_RXS_F2X3=0`

The workaround works perfectly!

**Comment by hammmmy** [comment]
Fixed in https://github.com/ROCm/rocm-libraries/pull/4023

**Comment by k-artem** [comment]
@hammmmy This issue is not related with mentioned PR, so reopen, need to continue internal discussion with driver team.

**Comment by hammmmy** [comment]
@k-artem the APU used was 1152 and the issue was fixed in https://github.com/ROCm/rocm-libraries/pull/4023 as 1152 was also incorrectly added in the PR that was reverted by https://github.com/ROCm/rocm-libraries/pull/4023

@libra-379125 confirmed that using export MIOPEN_DEBUG_AMD_WINOGRAD_FURY_RXS_F2X3=0 fixed it too

**Comment by k-artem** [comment]
@hammmmy yes, but I tested with mentioned PR(I used nightly TheRock) and confirm that the issue presents and related with vgpr (the problem which we continue to discuss with driver team in email loop), in the log we can see that correct kernel selected for compiling with _1024vgprs_ (without [mentioned PR](https://github.com/ROCm/rocm-libraries/pull/4023) _1536vgprs_ would have been chosen, which is not correct and was fixed)
```
MIOpen(HIP): Info [EvaluateInvokers] Evaluating Solver: miopenConvolutionFwdAlgoWinograd:ConvWinoFuryRxS<2-3>
MIOpen(HIP): Info2 [PrepareInvoker] Preparing kernel: miopenSp3AsmConvFury_v2_4_1_gfx11_1024vgprs_fp16_fp16acc_f2x3_c16_stride1
MIOpen(HIP): Info2 [MakeGcnAsmWinoV2InvokerFactory]  N=64 C=64 H=56 W=56 K=64 R=1 S=1 pad_H=0 pad_W=0 out_H=56 out_W=56 G=1 alpha=0 beta=0 act_mode=0 d_offset=0 f_offset=0 o_offset=0 b_offset=0 d_N_stride=200704 d_C_stride=3136 d_H_stride=56 d_G_stride=200704 f_K_stride=64 f_C_stride=1 f_R_stride=1 f_G_stride=4096 o_N_stride=200704 o_K_stride=3136 o_H_stride=56 o_G_stride=200704 n_groups=4 flags64=0xe200 sync_limit=0 sync_period=0
MIOpen(HIP): Info2 [run] kernel_name = miopenSp3AsmConvFury_v2_4_1_gfx11_1024vgprs_fp16_fp16acc_f2x3_c16_stride1, global_work_dim = { 1536, 1, 1 }, local_work_dim = { 384, 1, 1 }
Kernel Name: miopenSp3AsmConvFury_v2_4_1_gfx11_1024vgprs_fp16_fp16acc_f2x3_c16_stride1
VGPU=0x5d3592d5d600 SWq=0x75bf8d316000, HWq=0x75bf71a00000, id=1
        Dispatch Header =0xb02 (type=2, barrier=1, acquire=1, release=1), setup=0
        grid=[1536, 1, 1], workgroup=[384, 1, 1]
        private_seg_size=0, group_seg_size=65536
        kernel_obj=0x75bf8ca78f80, kernarg_address=0x0x75bf71201400
        completion_signal=0x75bf74dfd900, correlation_id=0
        rptr=57, wptr=58
:0:rocdevice.cpp            :3868: 731545282104 us:  Callback: Queue 0x75bf71a00000 aborting with error : HSA_STATUS_ERROR_INVALID_ISA: The instruction set architecture is invalid. code: 0x100f
 MIOpen(HIP): Error [EvaluateInvokers] ctr-krkn-at48-2:/therock/src/rocm-libraries/projects/miopen/src/hip/handlehip.cpp:161: Error setting device 0: invalid kernel file
```
As conclusion, https://github.com/ROCm/rocm-libraries/pull/4023 for fixing another compilation problem (which is related with wrong selection of a kernel as per gpu arch), but this issue is another problem and seems it should be fixed in cooperation with driver team as it was for StrixHalo.

**Comment by k-artem** [comment]
with latest **gfx1152** firmware Fury works as expected: 
```
(.venv) amd@ctr-krkn-at48-2:~/therock$ sudo cat /sys/kernel/debug/dri/0000:c4:00.0/amdgpu_firmware_info
VCE feature version: 0, firmware version: 0x00000000
UVD feature version: 0, firmware version: 0x00000000
MC feature version: 0, firmware version: 0x00000000
ME feature version: 35, firmware version: 0x0000000d
PFP feature version: 35, firmware version: 0x00000011
CE feature version: 0, firmware version: 0x00000000
RLC feature version: 1, firmware version: 0x11520504
RLC SRLC feature version: 0, firmware version: 0x00000000
RLC SRLG feature version: 0, firmware version: 0x00000000
RLC SRLS feature version: 0, firmware version: 0x00000000
RLCP feature version: 1, firmware version: 0x11520504
RLCV feature version: 0, firmware version: 0x00000000
MEC feature version: 35, firmware version: 0x00000011
IMU feature version: 0, firmware version: 0x0b342000
SOS feature version: 0, firmware version: 0x00000000
ASD feature version: 553648378, firmware version: 0x210000fa
TA XGMI feature version: 0x00000000, firmware version: 0x00000000
TA RAS feature version: 0x00000000, firmware version: 0x00000000
TA HDCP feature version: 0x00000000, firmware version: 0x17000049
TA DTM feature version: 0x00000000, firmware version: 0x1200001a
TA RAP feature version: 0x00000000, firmware version: 0x00000000
TA SECUREDISPLAY feature version: 0x00000000, firmware version: 0x00000000
SMC feature version: 0, program: 11, firmware version: 0x0b650200 (101.2.0)
SDMA0 feature version: 60, firmware version: 0x0000000c
VCN feature version: 0, firmware version: 0x0911800d
DMCU feature version: 0, firmware version: 0x00000000
DMCUB feature version: 0, firmware version: 0x09002c01
TOC feature version: 0, firmware version: 0x0000000b
MES_KIQ feature version: 6, firmware version: 0x00000079
MES feature version: 1, firmware version: 0x00000075
VPE feature version: 60, firmware version: 0x0000000f
VBIOS version: 113-STRIXEMU-001

(.venv) amd@ctr-krkn-at48-2:~/therock$ uname -r
6.17.0-1012-oem

(.venv) amd@ctr-krkn-at48-2:~/therock$ rocminfo | grep gfx
  Name:                    gfx1152
      Name:                    amdgcn-amd-amdhsa--gfx1152
      Name:                    amdgcn-amd-amdhsa--gfx11-generic
```
waiting updates for gfx1103.

**Comment by libra-379125** [comment]
This error has been resolved in gfx1103 on latest V2 release. 
It works without environment variables now.

Can I close this ticket?

**Comment by k-artem** [comment]
> This error has been resolved in gfx1103 on latest V2 release. It works without environment variables now.
> 
> Can I close this ticket?

hi @libra-379125, it wasn't solved, applied workaround https://github.com/ROCm/rocm-libraries/pull/5763/changes , I propose to keep it open.
CC @adityas-amd

**Comment by astrelsky** [comment]
> > This error has been resolved in gfx1103 on latest V2 release. It works without environment variables now.
> > 
> > Can I close this ticket?
> 
> hi @libra-379125, it wasn't solved, applied workaround https://github.com/ROCm/rocm-libraries/pull/5763/changes , I propose to keep it open.
> CC @adityas-amd 

This only affects gfx1103 and therefore should not be a blocker for https://github.com/ROCm/rocm-libraries/issues/6178 correct?

**Comment by k-artem** [comment]
> > > This error has been resolved in gfx1103 on latest V2 release. It works without environment variables now.
> > > Can I close this ticket?
> > 
> > 
> > hi [@libra-379125](https://github.com/libra-379125), it wasn't solved, applied workaround https://github.com/ROCm/rocm-libraries/pull/5763/changes , I propose to keep it open.
> > CC [@adityas-amd](https://github.com/adityas-amd)
> 
> This only affects gfx1103 and therefore should not be a blocker for [ROCm/rocm-libraries#6178](https://github.com/ROCm/rocm-libraries/issues/6178) correct?

The issue affects gfx1152 and gfx1103. For gfx1152 it is fixed, gfx1103 in progress.

**Comment by astrelsky** [comment]
> > > > This error has been resolved in gfx1103 on latest V2 release. It works without environment variables now.
> > > > Can I close this ticket?
> > > 
> > > 
> > > hi [@libra-379125](https://github.com/libra-379125), it wasn't solved, applied workaround https://github.com/ROCm/rocm-libraries/pull/5763/changes , I propose to keep it open.
> > > CC [@adityas-amd](https://github.com/adityas-amd)
> > 
> > This only affects gfx1103 and therefore should not be a blocker for [ROCm/rocm-libraries#6178](https://github.com/ROCm/rocm-libraries/issues/6178) correct?
> 
> The issue affects gfx1152 and gfx1103. For gfx1152 it is fixed, gfx1103 in progress.

Ok so it did not effect gfx1150, gfx1152 is fixed and gfx1103 is in progress. Thank you for the clarification. Is there a reason for it to be a blocker to add the missing Winograd kernel? I'm assuming/hoping that missing kernel is the reason for the convolution bottleneck for gfx1150.

**Comment by k-artem** [comment]
Update: the issue is fixed&verified for gfx1103, need to wait to update of linux driver for reverting  https://github.com/ROCm/rocm-libraries/commit/938013db09c08027eafed374425a7a40f6acda66
CC @adityas-amd

**Comment by Mubelotix** [comment]
I can confirm that this fixes it:

```
MIOPEN_FIND_MODE=2
MIOPEN_DEBUG_AMD_WINOGRAD_FURY_RXS_F2X3=0
```

The issue is present in Rocm 7.2
