### ISSUE TITLE
[Issue]: AMD iGPU is cuda:0 when using ROCm wheels built by TheRock

### ISSUE THREAD

**Issue by FishYu-OWO** [ROCm/TheRock#3392]
### Problem Description

After installing the ROCm .whl packages built by TheRock, I noticed that my discrete RX 9000 series GPU is enumerated as cuda:1, while the integrated GPU (iGPU) from my AMD 9000 series CPU is enumerated as cuda:0.

The problem is that even if I explicitly select cuda:1, the RX 9000 still does not work correctly in practice.
Some error appear like this:
```
torch.AcceleratorError: HIP error: device kernel image is invalid
Search for `hipErrorInvalidImage' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__HIPRT__TYPES.html for more information.
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions
```

So currently, the only workaround I found is setting:
```
CUDA_VISIBLE_DEVICES=1
```

Is there any other recommended way to control or fix the device ordering, so that the discrete GPU is properly recognized as cuda:0, or at least to completely hide the AMD iGPU, without relying on CUDA_VISIBLE_DEVICES?

However, when using the ROCm version bundled with the official AMD GPU windows driver 26.1.1 AI bundle, this issue does not occur. In that setup, the AMD iGPU does not appear as a CUDA device at all, and only the discrete GPU is visible.

### Operating System

Windows11 25H2

### CPU

AMD 9600X

### GPU

AMD RX 9070

### ROCm Version

ROCm 7.11(TheRock whl)  ROCm 7.2

**Comment by schung-amd** [comment]
Hi @FishYu-OWO, thanks for the report. We're aware of this issue, particularly with torch, and are looking at a better prioritization for devices. Generally, though, we recommend disabling internal graphics altogether: https://rocm.docs.amd.com/projects/radeon-ryzen/en/latest/docs/prerequisites/prerequisitesrad.html#disable-igpu, https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/prerequisites.html#disable-integrated-graphics-igp. The alternative is to do what you're already doing and hide the integrated graphics with `CUDA_VISIBLE_DEVICES` and `HIP_VISIBLE_DEVICES`.

**Comment by schung-amd** [comment]
@FishYu-OWO Has this improved for you with the latest TheRock nightlies? We had a regression which was causing RDNA2 devices to not be properly enumerated in Windows, leading to issues when pairing iGPUs and dGPUs. This is now fixed, so you shouldn't need to mask any devices.

**Comment by FishYu-OWO** [comment]
> [@FishYu-OWO](https://github.com/FishYu-OWO) Has this improved for you with the latest TheRock nightlies? We had a regression which was causing RDNA2 devices to not be properly enumerated in Windows, leading to issues when pairing iGPUs and dGPUs. This is now fixed, so you shouldn't need to mask any devices.

@schung-amd 
I tested the 20260317 and 20260328 nightlies. If I don’t disable my 9600X iGPU (gfx1036), I still need to use `CUDA_VISIBLE_DEVICES=1` to select the 9070 (gfx1201).Also, this issue does not occur on Linux (Ubuntu 24.04).


There was a brief period (e.g., the 20260220 nightly build) where I could select it directly without needing to mask devices.

**Comment by schung-amd** [comment]
Thanks for the update. I'll check to see if this is still expected/known to be occurring.

**Comment by schung-amd** [comment]
Hi @FishYu-OWO, sorry for the delay on this. I'm not seeing this issue with Adrenalin 26.5.1 and the latest nightlies. Could you try on your end to verify?

**Comment by FishYu-OWO** [comment]
Hi @schung-amd,

Sorry for the late reply.
As a workaround for this issue, I had been running with the 9600X iGPU disabled in BIOS for quite some time. Recently I re-enabled the iGPU to test again.

I tested with the newer TheRock v2 nightly packages:

```bash
uv pip install --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/ torch torchaudio torchvision
```

This installed:

```text
rocm 7.13.0a20260416
```

Using the bundled `hipinfo`, device enumeration still shows:

```text
device 0 -> gfx1036 (Ryzen 9600X iGPU)
device 1 -> gfx1201 (RX 9070)
```

So the iGPU is still being enumerated as device 0.

I then ran a simple standalone PyTorch computation test.

Since this wheel does not contain any gfx1036 kernels, using `cuda:0` fails as expected. However, explicitly selecting `cuda:1` still does not work correctly and I encounter the same behavior as originally reported.

So for the gfx120X-only nightly build, the situation is still:

1. `cuda:0` is the iGPU (gfx1036).
2. Explicitly selecting `cuda:1` does not allow the RX 9070 to operate correctly.

I also tested the multi-arch nightly build:

```bash
pip install --index-url https://rocm.nightlies.amd.com/whl-multi-arch/ \
  "torch[device-gfx1201]" \
  "torchvision[device-gfx1201]" \
  torchaudio
```

With this build, attempting to use `cuda:1` results in a process crash with:

```text
Exception Code: 0xC0000005
```

Therefore, from my testing, the original issue still appears to be present when an iGPU (gfx1036) and RX 9070 (gfx1201) coexist on Windows.

**Comment by FishYu-OWO** [comment]
I performed some additional testing after noticing that newer TheRock nightlies now provide ROCm wheels for gfx1036 as well.

I installed a staging multi-arch build containing support for both my iGPU and dGPU:

```bash
pip install --index-url https://rocm.nightlies.amd.com/whl-staging-multi-arch/ \
  "torch[device-gfx1201,device-gfx1036]" \
  "torchvision[device-gfx1201,device-gfx1036]" \
  torchaudio
```

With this configuration, I found that the device enumerated as `cuda:0` (gfx1036) can successfully execute PyTorch operations.

However, attempting to run the same workload on `cuda:1` (gfx1201 / RX 9070) still fails.

From all of my testing so far, the behavior appears to be:

* When multiple AMD GPUs are present, device enumeration works and both devices are visible.
* The GPU assigned to `cuda:0` can execute PyTorch workloads successfully.
* The GPU assigned to `cuda:1` cannot be used correctly, even when explicitly selected through PyTorch.

At the moment, I still have to use `HIP_VISIBLE_DEVICES=1` or `CUDA_VISIBLE_DEVICES=1` to hide the iGPU and force the RX 9070 to become `cuda:0`.

While this workaround functions, it does not seem like the expected behavior. Explicitly selecting `cuda:1` should be sufficient to run workloads on the RX 9070 without having to mask other AMD devices.
