### ISSUE TITLE
[Issue] Linux Pytorch Build failure due to missing argument `--target_gpus` to `generate.py` - gfx906, gfx908

### ISSUE THREAD

**Issue by chiranjeevipattigidi** [ROCm/TheRock#3701]
**Platform:** `Linux`
**Pytorch Versions:** `2.8, 2.9, 2.10, nightly`
**Python Versions:** `3.10, 3.11, 3.12, 3.13`
**Effected Archs:** `gfx906, gfx908`

### Runs:
- https://github.com/ROCm/TheRock/actions/runs/22564835731
- https://github.com/ROCm/TheRock/actions/runs/22570332110

```
2026-03-02T07:03:33.0484685Z -- AOTRITON_OVERRIDE_TARGET_GPUS 
2026-03-02T07:03:33.0484986Z -- EFFECTIVE_TARGET_GPUS 
2026-03-02T07:03:34.1008335Z AOTRITON_COMPILER /__w/TheRock/TheRock/external-builds/pytorch/pytorch/build/aotriton/src/aotriton_runtime/v3python/compile.py
2026-03-02T07:03:34.7809277Z usage: generate.py [-h]
2026-03-02T07:03:34.7810704Z                    [--target_gpus {gfx90a_mod0,gfx942_mod0,gfx950_mod0,gfx1100_mod0,gfx1101_mod0,gfx1102_mod0,gfx1151_mod0,gfx1150_mod0,gfx1201_mod0,gfx1200_mod0,gfx1250_mod0} [{gfx90a_mod0,gfx942_mod0,gfx950_mod0,gfx1100_mod0,gfx1101_mod0,gfx1102_mod0,gfx1151_mod0,gfx1150_mod0,gfx1201_mod0,gfx1200_mod0,gfx1250_mod0} ...]]
2026-03-02T07:03:34.7812393Z                    [--build_dir BUILD_DIR] [--root_dir ROOT_DIR]
2026-03-02T07:03:34.7812836Z                    [--archive_only] [--library_suffix LIBRARY_SUFFIX]
2026-03-02T07:03:34.7813237Z                    [--noimage_mode] [--build_for_tuning]
2026-03-02T07:03:34.7813591Z                    [--build_for_tuning_second_pass]
2026-03-02T07:03:34.7814069Z                    [--build_for_tuning_but_skip_kernel [BUILD_FOR_TUNING_BUT_SKIP_KERNEL ...]]
2026-03-02T07:03:34.7814562Z                    [--verbose] [--lut_sanity_check]
2026-03-02T07:03:34.7815021Z generate.py: error: argument --target_gpus: expected at least one argument
2026-03-02T07:03:34.7818061Z '/opt/_internal/cpython-3.10.17/lib/python3.10/site-packages/cmake/data/bin/cmake' '-E' 'env' 'VIRTUAL_ENV=/__w/TheRock/TheRock/external-builds/pytorch/pytorch/build/aotriton/src/aotriton_runtime-build/venv' 'AOTRITON_ENABLE_FP32=1' '/__w/TheRock/TheRock/external-builds/pytorch/pytorch/build/aotriton/src/aotriton_runtime-build/venv/bin/python' '-X' 'utf8' '-m' 'v3python.generate' '--target_gpus' '--build_dir' '/__w/TheRock/TheRock/external-builds/pytorch/pytorch/build/aotriton/src/aotriton_runtime-build/v3src' '--noimage_mode'
2026-03-02T07:03:34.8853188Z CMake Error at v3src/CMakeLists.txt:71 (execute_process):
2026-03-02T07:03:34.8853658Z   execute_process failed command indexes:
2026-03-02T07:03:34.8853882Z 
2026-03-02T07:03:34.8853988Z     1: "Child return code: 2"
2026-03-02T07:03:34.8854164Z 
2026-03-02T07:03:34.8854168Z 
2026-03-02T07:03:34.8854171Z 
2026-03-02T07:03:34.8856220Z -- Configuring incomplete, errors occurred!
2026-03-02T07:03:34.8934930Z [5055/8022] Building HIPCC object third_party/gloo/gloo/CMakeFiles/gloo_hip.dir/__/__/__/build/third_party/gloo/hip/gloo/gloo_hip_generated_hip_allreduce_local.cc.o
2026-03-02T07:03:34.8936162Z In file included from /__w/TheRock/TheRock/external-builds/pytorch/pytorch/build/third_party/gloo/hip/gloo/hip_allreduce_local.cc:12:
2026-03-02T07:03:34.8937107Z In file included from /__w/TheRock/TheRock/external-builds/pytorch/pytorch/build/third_party/gloo/hip/gloo/hip_collectives_device.h:23:
2026-03-02T07:03:34.8938818Z /__w/TheRock/TheRock/external-builds/pytorch/pytorch/build/third_party/gloo/hip/gloo/hip_collectives_native.h:86:9: warning: ignoring return value of type 'hipError_t' declared with 'nodiscard' attribute [-Wunused-value]
```

**Comment by ScottTodd** [comment]
I suspect we could work around this by adding gfx906 and gfx908 to `AOTRITON_UNSUPPORTED_ARCHS` here: https://github.com/ROCm/TheRock/blob/4bef0f8774febc7f9e4a9f99eed201c0c39540ce/external-builds/pytorch/build_prod_wheels.py#L785-L791

**Comment by araravik-psd** [comment]
Test pytorch build run with gfx906 and gfx908 added to AOTRITON_UNSUPPORTED_ARCHS

https://github.com/ROCm/TheRock/actions/runs/22633229507

**Comment by araravik-psd** [comment]
Looks like the test build has gone through , fails during the post-install sanity check when importing torch.

Test run failed with the below error:

++ Exec [/tmp]$ /opt/python/cp310-cp310/bin/python -m pip install /__w/TheRock/TheRock/external-builds/pytorch/pytorch/dist/torch-2.8.0+devrocm7.12.0.dev0.bc907c4f2d394603ef2685b38bdf6b2ac0bbc9ae-cp310-cp310-linux_x86_64.whl
+++ Sanity checking installed torch (unavailable is okay on CPU machines):
Traceback (most recent call last):
++ Capture [/tmp]$ /opt/python/cp310-cp310/bin/python -c 'import torch; print(torch.cuda.is_available())'
  File "/__w/TheRock/TheRock/./external-builds/pytorch/build_prod_wheels.py", line 1262, in <module>
    main(sys.argv[1:])
  File "/__w/TheRock/TheRock/./external-builds/pytorch/build_prod_wheels.py", line 1258, in main
    args.func(args)
  File "/__w/TheRock/TheRock/./external-builds/pytorch/build_prod_wheels.py", line 622, in do_build
Error capturing output: Command '['/opt/python/cp310-cp310/bin/python', '-c', 'import torch; print(torch.cuda.is_available())']' returned non-zero exit status 1.
Output from the failed command:
Traceback (most recent call last):
  File "/opt/python/cp310-cp310/lib/python3.10/site-packages/rocm_sdk/__init__.py", line 34, in find_libraries
    lib_entry = _dist_info.ALL_LIBRARIES[shortname]
KeyError: 'hipdnn'


Suspecting that the below merged PR could be causing the hipdnn error:

https://github.com/ROCm/TheRock/commit/5b58daad513c94a06028b2d35ec6449ab2e0fdc8#diff-168d238c5eb0d9a21f018a1c54a8af0ec7fa089a5fa5c6fb87c09a08f523d5a3

**Comment by ScottTodd** [comment]
Ah... well, another option is to add `expect_pytorch_failure` to https://github.com/ROCm/TheRock/blob/main/build_tools/github_actions/amdgpu_family_matrix.py for these targets on Linux. It's already there on Windows.

**Comment by araravik-psd** [comment]
@ScottTodd  I added the expect_pytorch_failrue for both gfx906 and gfx908, I still see the post install sanity check is causing an exception for hipdnn, is there any other way to skip these checks for these 2 archs.

https://github.com/ROCm/TheRock/commit/1a8b59c8cf7341ca74a4f296c7fc163f17dca4f8

Test run with expect_pytorch_failure for gfx906

https://github.com/ROCm/TheRock/actions/runs/22643962281/job/65627036300#step:10:62215

**Comment by ScottTodd** [comment]
Manually triggering a release will fail. Setting `expect_pytorch_failure` will not change that.

What that option does control is here:
1. Skip triggering pytorch releases for that family: https://github.com/ROCm/TheRock/blob/604935ec9382e2a0170defce1e130fb4d8fce481/.github/workflows/release_portable_linux_packages.yml#L331-L335
2. Skip triggering pytorch CI builds for that family: https://github.com/ROCm/TheRock/blob/604935ec9382e2a0170defce1e130fb4d8fce481/build_tools/github_actions/configure_ci.py#L233

**Comment by araravik-psd** [comment]
Issue is resolved with this PR:

https://github.com/ROCm/TheRock/commit/4aa048f79078cfa63ed878c1ca13c3befc436280
