### ISSUE TITLE
[Issue]: Docker support for ROCm on gfx1151 (Radeon 8060S / Strix Halo APU) — community request

### ISSUE THREAD

**Issue by siavashhub** [ROCm/TheRock#4240]
### Problem Description

Hi,
I'm working on adding Docker support for llamacpp-rocm for a number of community members who want to run Lemonade Server (https://github.com/lemonade-sdk/lemonade) in containers on AMD ROCm hardware.

Hardware: Radeon 8060S (gfx1151, Ryzen AI MAX / Strix Halo APU, unified memory, VMM: no)
OS: Ubuntu 24.04, HSA Runtime 1.18
Binary: llama-b1170-ubuntu-rocm-gfx1151-x64.zip

Problem: The llama-server binary crashes on the first GPU kernel execution with `Memory access fault by GPU node-1 — Page not present or supervisor privilege` regardless of:

- Docker `--privileged` mode
- `HSA_ENABLE_SDMA=0`
- `HSA_OVERRIDE_GFX_VERSION=11.0.3`
- `-fit off`, `--no-mmap`
- `amdgpu.cwsr_enable=0`, `amd_iommu=off` kernel params

The same hardware runs Vulkan and CPU backends fine on Docker.

ROCm [docs notes ](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/prerequisites.html#additional-dev-packages:~:text=Manager%20(DRM)%20devices.-,Disable%20integrated%20graphics%20(IGP),-%23) mentioned currently integrated graphics is not supported, but gfx1151 (Strix Halo) has significant community interest.

Would you be able to provide guidance or a build that supports this configuration? Happy to test any suggestions.

Additional information:

```
Docker Image Base: rocm/dev-ubuntu-24.04

Docker Run Command:
docker run --name lemonade-server \
  -p 8000:8000 \
  -v lemonade-cache:/root/.cache/huggingface \
  -v lemonade-llama:/opt/lemonade/llama \
  -e LEMONADE_LLAMACPP=rocm \
  -e HSA_OVERRIDE_GFX_VERSION=11.0.3 \
  --security-opt label=type:container_runtime_t \
  --device=/dev/kfd \
  --device=/dev/dri \
  --group-add video \
  --group-add render \
  ghcr.io/siavashhub/lemonade/lemonade-rocm:latest
```
I followed all the steps within below links:
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/quick-start.html#rocm-install-quick
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/install-methods/package-manager/package-manager-ubuntu.html
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/post-install.html
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/docker.html

### Operating System

Ubuntu 24.04.4 LTS (Noble Numbat)

### CPU

AMD RYZEN AI MAX+ 395

### GPU

Radeon 8060S

### ROCm Version

7.2.1

### Steps to Reproduce

Run below on an Ubuntu 24.04 native Strix Halo linux machine with docker installed:
```
docker run --name lemonade-server \
  -p 8000:8000 \
  -v lemonade-cache:/root/.cache/huggingface \
  -v lemonade-llama:/opt/lemonade/llama \
  -e LEMONADE_LLAMACPP=rocm \
  -e HSA_OVERRIDE_GFX_VERSION=11.0.3 \
  --security-opt label=type:container_runtime_t \
  --device=/dev/kfd \
  --device=/dev/dri \
  --group-add video \
  --group-add render \
  ghcr.io/siavashhub/lemonade/lemonade-rocm:latest
```

Then run below command on a separate terminal against it:
```
curl -X POST http://localhost:8000/api/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer lemonade" \
  -d '{
    "model": "Qwen3-0.6B-GGUF",
    "messages": [{"role": "user", "content": "Hello, Lemonade!"}]
  }'
```

If logs are not visible in your terminal run below command:
`docker logs -f lemonade-server`

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

```
ROCk module version 6.16.13 is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.18
Runtime Ext Version:     1.15
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
XNACK enabled:           NO
DMAbuf Support:          YES
VMM Support:             YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD RYZEN AI MAX+ 395 w/ Radeon 8060S
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD RYZEN AI MAX+ 395 w/ Radeon 8060S
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      49152(0xc000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   5187                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Memory Properties:       
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    131163168(0x7d16420) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    131163168(0x7d16420) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    131163168(0x7d16420) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 4                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    131163168(0x7d16420) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1151                            
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon Graphics                
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      2048(0x800) KB                     
    L3:                      32768(0x8000) KB                   
  Chip ID:                 5510(0x1586)                       
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          128(0x80)                          
  Max Clock Freq. (MHz):   2900                               
  BDFID:                   49664                              
  Internal Node ID:        1                                  
  Compute Unit:            40                                 
  SIMDs per CU:            2                                  
  Shader Engines:          2                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Memory Properties:       APU
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        2147483647(0x7fffffff)             
    y                        65535(0xffff)                      
    z                        65535(0xffff)                      
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 32                                 
  SDMA engine uCode::      17                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65581584(0x3e8b210) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    65581584(0x3e8b210) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1151         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        2147483647(0x7fffffff)             
        y                        65535(0xffff)                      
        z                        65535(0xffff)                      
      FBarrier Max Size:       32                                 
    ISA 2                    
      Name:                    amdgcn-amd-amdhsa--gfx11-generic   
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        2147483647(0x7fffffff)             
        y                        65535(0xffff)                      
        z                        65535(0xffff)                      
      FBarrier Max Size:       32                                 
*******                  
Agent 3                  
*******                  
  Name:                    aie2p                              
  Uuid:                    AIE-XX                             
  Marketing Name:          RyzenAI-npu5                       
  Vendor Name:             AMD                                
  Feature:                 AGENT_DISPATCH                     
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        1(0x1)                             
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          64(0x40)                           
  Queue Type:              SINGLE                             
  Node:                    0                                  
  Device Type:             DSP                                
  Cache Info:              
    L2:                      2048(0x800) KB                     
    L3:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          0(0x0)                             
  Max Clock Freq. (MHz):   0                                  
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            0                                  
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:0                                  
  Memory Properties:       
  Features:                AGENT_DISPATCH
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, COARSE GRAINED
      Size:                    131163168(0x7d16420) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65536(0x10000) KB                  
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    131163168(0x7d16420) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*** Done *** 
```

**Comment by harkgill-amd** [comment]
Hey @siavashhub, I was able to get this working with `lemonade-server:latest` image + Strix Halo using the following command,
```
sudo docker run -d \
  --name lemonade-server \
  -p 8000:8000 \
  -v lemonade-cache:/root/.cache/huggingface \
  -v lemonade-llama:/opt/lemonade/llama \
  -e LEMONADE_LLAMACPP_BACKEND=rocm \
  --device=/dev/kfd \
  --device=/dev/dri \
  --group-add video \
  --group-add render \
  ghcr.io/lemonade-sdk/lemonade-server:latest
```
Couple key points here - you don't need the `HSA_OVERRIDE_GFX_VERSION` environment variable here as gfx1151 should work just fine natively.  Also, the environment variable for llama.cpp backend should be `LEMONADE_LLAMACPP_BACKEND`. With these changes, you should be good to get up and running. Let me know if you run into any further issues or have any questions.

**Comment by siavashhub** [comment]
Hey @harkgill-amd 

Thanks so much for testing this and following up, really appreciate it!

Just a few clarifications that might help explain what's going on:

1. I'm actually one of the maintainers of the lemonade-sdk repo and recently added Docker support. The current `ghcr.io/lemonade-sdk/lemonade-server:latest` image is built around the Vulkan backend, adding ROCm support is exactly what I'm working on, which is why I opened this issue.

2. The image that would reproduce the problem is in my fork: `ghcr.io/siavashhub/lemonade/lemonade-rocm:latest`. The main repo image won't hit the ROCm crash since it doesn't attempt to use ROCm.

3. Regarding the environment variable, `LEMONADE_LLAMACPP_BACKEND` was recently renamed to `LEMONADE_LLAMACPP` in the codebase. The docs haven't caught up yet (there's a PR in progress for that), so you may still see the old name referenced in places.

3. The reason your run appeared to succeed is that lemonade has a backend fallback mechanism, if ROCm initialization fails, it silently falls back to Vulkan. If you check `docker logs -f lemonade-server` you'll likely see it selected Vulkan, not ROCm. So everything runs, but the underlying issue I'm reporting is still there.

Would love to continue testing with the fork image if you're open to it, happy to share any additional logs or details that would help!

**Comment by harkgill-amd** [comment]
Ahh I see, thanks for the clarification @siavashhub!!

Just gave it another run, using `LEMONADE_LLAMACPP` this time, and ROCm is now being picked up correctly. For context, here's the complete docker command I ran,
```
sudo docker run -d \
  --name lemonade-server \
  -p 8000:8000 \
  -v lemonade-cache:/root/.cache/huggingface \
  -v lemonade-llama:/opt/lemonade/llama \
  -e LEMONADE_LLAMACPP=rocm \
  --device=/dev/kfd \
  --device=/dev/dri \
  --group-add video \
  ghcr.io/lemonade-sdk/lemonade-server:latest
```
And a quick snippet from the `docker logs`
```
2026-04-01 17:46:23.539 [Info] (Process) ggml_cuda_init: found 1 ROCm devices (Total VRAM: 49152 MiB):
2026-04-01 17:46:23.539 [Info] (Process)   Device 0: Radeon 8060S Graphics, gfx1151 (0x1151), VMM: no, Wave Size: 32, VRAM: 49152 MiB
....
026-04-01 17:46:23.987 [Info] (Process) load_tensors: offloaded 29/29 layers to GPU
2026-04-01 17:46:23.987 [Info] (Process) load_tensors:          CPU model buffer size =   121.71 MiB
2026-04-01 17:46:23.987 [Info] (Process) load_tensors:        ROCm0 model buffer size =   358.78 MiB
```
When I swap to using your forked image, `ghcr.io/siavashhub/lemonade/lemonade-rocm:latest`, I hit `"code":"model_load_error","message":"Failed to load model 'Qwen3-0.6B-GGUF` errors. Checking the `docker logs`, it looks like you're forcing an override to `gfx1103` which is causing device kernel image failures downstream.
```
ggml_cuda_init: found 1 ROCm devices:
  Device 0: Radeon 8060S Graphics, gfx1103 (0x1103), VMM: no, Wave Size: 32
....
ROCm error: device kernel image is invalid
  current device: 0, in function ggml_cuda_compute_forward at /home/runner/work/llamacpp-rocm/llamacpp-rocm/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2751
  err
```
Based on these two experiments, I'm thinking the original `Memory access fault` errors might have to do with a FW/ROCm mismatch (see our [compatibility matrix](https://rocm.docs.amd.com/en/latest/how-to/system-optimization/strixhalo.html#required-kernel-version)) rather than missing ROCm support in the upstream image. Open to your input here especially for the first case where ROCm seems to be working fine with the `lemonade-sdk/lemonade-server:latest` image, I might be missing something there.

**Comment by siavashhub** [comment]
> sudo docker run -d \
>   --name lemonade-server \
>   -p 8000:8000 \
>   -v lemonade-cache:/root/.cache/huggingface \
>   -v lemonade-llama:/opt/lemonade/llama \
>   -e LEMONADE_LLAMACPP=rocm \
>   --device=/dev/kfd \
>   --device=/dev/dri \
>   --group-add video \
>   ghcr.io/lemonade-sdk/lemonade-server:latest
> ```
> 
> And a quick snippet from the `docker logs`
> 
> ```
> 2026-04-01 17:46:23.539 [Info] (Process) ggml_cuda_init: found 1 ROCm devices (Total VRAM: 49152 MiB):
> 2026-04-01 17:46:23.539 [Info] (Process)   Device 0: Radeon 8060S Graphics, gfx1151 (0x1151), VMM: no, Wave Size: 32, VRAM: 49152 MiB
> ....
> 026-04-01 17:46:23.987 [Info] (Process) load_tensors: offloaded 29/29 layers to GPU
> 2026-04-01 17:46:23.987 [Info] (Process) load_tensors:          CPU model buffer size =   121.71 MiB
> 2026-04-01 17:46:23.987 [Info] (Process) load_tensors:        ROCm0 model buffer size =   358.78 MiB
> ```

Yeah I was trying to make it work in that package, but on yours with the main repo package does it process the request with 200? I'm thinking maybe the issue is with my device or kernel, cause I ran the same command that you did above for the main repo package but I still get the old error with it and it ends with 500:

```
2026-04-01 18:44:38.448 [Info] (LlamaCpp) Starting llama-server...
2026-04-01 18:44:38.448 [Info] (ProcessManager) Process started successfully, PID: 81
Waiting for llama-server to be ready (timeout: 600s)...
2026-04-01 18:44:38.535 [Info] (Process) ggml_cuda_init: found 1 ROCm devices (Total VRAM: 64044 MiB):
2026-04-01 18:44:38.535 [Info] (Process)   Device 0: Radeon 8060S Graphics, gfx1151 (0x1151), VMM: no, Wave Size: 32, VRAM: 64044 MiB
2026-04-01 18:44:38.549 [Info] (Process) main: n_parallel is set to auto, using n_parallel = 4 and kv_unified = true
2026-04-01 18:44:38.549 [Info] (Process) build: 1 (b1c70e2) with Clang 23.0.0 for Linux 
2026-04-01 18:44:38.549 [Info] (Process) system info: n_threads = 16, n_threads_batch = 16, total_threads = 32
2026-04-01 18:44:38.549 [Info] (Process) system_info: n_threads = 16 (n_threads_batch = 16) / 32 | ROCm : NO_VMM = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : LLAMAFILE = 1 | REPACK = 1 | 
2026-04-01 18:44:38.549 [Info] (Process) Running without SSL
2026-04-01 18:44:38.549 [Info] (Process) init: using 31 threads for HTTP server
2026-04-01 18:44:38.549 [Info] (Process) Web UI is disabled
2026-04-01 18:44:38.549 [Info] (Process) start: binding port with default address family
2026-04-01 18:44:38.551 [Info] (Process) main: loading model
2026-04-01 18:44:38.551 [Info] (Process) srv    load_model: loading model '/root/.cache/huggingface/hub/models--unsloth--Qwen3-0.6B-GGUF/snapshots/50968a4468ef4233ed78cd7c3de230dd1d61a56b/Qwen3-0.6B-Q4_0.gguf'
2026-04-01 18:44:38.551 [Info] (Process) common_init_result: fitting params to device memory, for bugs during this step try to reproduce them with -fit off, or provide --verbose logs if the bug only occurs with -fit on
2026-04-01 18:44:38.667 [Info] (Process) Memory access fault by GPU node-1 (Agent handle: 0x5a7004e44300) on address 0x7a06987bc000. Reason: Page not present or supervisor privilege.
2026-04-01 18:44:38.676 [Info] (Process) GPU coredump: execvp failed: No such file or directory
2026-04-01 18:44:38.678 [Info] (Process) Failed to write segment data to pipe: Success
2026-04-01 18:44:38.678 [Error] (Process) GPU coredump: handler exited with error (status: 1)
2026-04-01 18:44:38.678 [Info] (Process) GPU core dump failed
2026-04-01 18:44:38.857 [Error] (WrappedServer) llama-server process has terminated with exit code: -1
2026-04-01 18:44:38.857 [Error] (WrappedServer) This usually means:
2026-04-01 18:44:38.857 [Error] (WrappedServer)   - Missing required drivers or dependencies
2026-04-01 18:44:38.857 [Error] (WrappedServer)   - Incompatible model file
2026-04-01 18:44:38.857 [Error] (WrappedServer)   - Try running the server manually to see the actual error
2026-04-01 18:44:43.876 [Warn] (ProcessManager) Process did not respond to SIGTERM, using SIGKILL
2026-04-01 18:44:43.876 [Info] (ProcessManager) Process terminated, waiting for GPU driver cleanup...
2026-04-01 18:44:45.877 [Error] (Router) Backend load failed: llama-server failed to start
2026-04-01 18:44:45.877 [Warn] (Router) Load failed with non-file-not-found error, evicting all models and retrying...
2026-04-01 18:44:45.877 [Info] (Router) Evicting all models (0 total)
2026-04-01 18:44:45.877 [Info] (Router) All models evicted
2026-04-01 18:44:45.877 [Info] (LlamaCpp) Loading model: Qwen3-0.6B-GGUF
2026-04-01 18:44:45.878 [Info] (LlamaCpp) Starting llama-server...
2026-04-01 18:44:45.879 [Info] (ProcessManager) Process started successfully, PID: 122
Waiting for llama-server to be ready (timeout: 600s)...
2026-04-01 18:44:45.974 [Info] (Process) ggml_cuda_init: found 1 ROCm devices (Total VRAM: 64044 MiB):
2026-04-01 18:44:45.974 [Info] (Process)   Device 0: Radeon 8060S Graphics, gfx1151 (0x1151), VMM: no, Wave Size: 32, VRAM: 64044 MiB
2026-04-01 18:44:45.994 [Info] (Process) main: n_parallel is set to auto, using n_parallel = 4 and kv_unified = true
2026-04-01 18:44:45.995 [Info] (Process) build: 1 (b1c70e2) with Clang 23.0.0 for Linux 
2026-04-01 18:44:45.995 [Info] (Process) system info: n_threads = 16, n_threads_batch = 16, total_threads = 32
2026-04-01 18:44:45.995 [Info] (Process) system_info: n_threads = 16 (n_threads_batch = 16) / 32 | ROCm : NO_VMM = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : LLAMAFILE = 1 | REPACK = 1 | 
2026-04-01 18:44:45.995 [Info] (Process) Running without SSL
2026-04-01 18:44:45.995 [Info] (Process) init: using 31 threads for HTTP server
2026-04-01 18:44:45.995 [Info] (Process) Web UI is disabled
2026-04-01 18:44:45.995 [Info] (Process) start: binding port with default address family
2026-04-01 18:44:45.996 [Info] (Process) main: loading model
2026-04-01 18:44:45.996 [Info] (Process) srv    load_model: loading model '/root/.cache/huggingface/hub/models--unsloth--Qwen3-0.6B-GGUF/snapshots/50968a4468ef4233ed78cd7c3de230dd1d61a56b/Qwen3-0.6B-Q4_0.gguf'
2026-04-01 18:44:45.996 [Info] (Process) common_init_result: fitting params to device memory, for bugs during this step try to reproduce them with -fit off, or provide --verbose logs if the bug only occurs with -fit on
2026-04-01 18:44:46.158 [Info] (Process) Memory access fault by GPU node-1 (Agent handle: 0x586d755dd300) on address 0x720e72c0c000. Reason: Page not present or supervisor privilege.
2026-04-01 18:44:46.168 [Info] (Process) GPU coredump: execvp failed: No such file or directory
2026-04-01 18:44:46.170 [Info] (Process) Failed to write segment data to pipe: Success
2026-04-01 18:44:46.170 [Error] (Process) GPU coredump: handler exited with error (status: 1)
2026-04-01 18:44:46.170 [Info] (Process) GPU core dump failed
2026-04-01 18:44:46.370 [Error] (WrappedServer) llama-server process has terminated with exit code: -1
2026-04-01 18:44:46.370 [Error] (WrappedServer) This usually means:
2026-04-01 18:44:46.370 [Error] (WrappedServer)   - Missing required drivers or dependencies
2026-04-01 18:44:46.370 [Error] (WrappedServer)   - Incompatible model file
2026-04-01 18:44:46.370 [Error] (WrappedServer)   - Try running the server manually to see the actual error
2026-04-01 18:44:51.388 [Warn] (ProcessManager) Process did not respond to SIGTERM, using SIGKILL
2026-04-01 18:44:51.388 [Info] (ProcessManager) Process terminated, waiting for GPU driver cleanup...
2026-04-01 18:44:53.389 [Error] (Router) Retry also failed: llama-server failed to start
2026-04-01 18:44:53.389 [Info] (LlamaCpp) Unloading model...
2026-04-01 18:44:53.389 [Info] (LlamaCpp) Unloading model...
2026-04-01 18:44:53.389 [Error] (Router) Failed to load model: llama-server failed to start
2026-04-01 18:44:53.389 [Error] (Server) Failed to load model: llama-server failed to start
2026-04-01 18:44:53.389 [Error] (Server) Error 500: POST /api/v1/chat/completions
```
It recognizes ROCm but it fails with memory access fault saying Page not present or supervisor privilege. I followed the instructions as it was provided on the rocm.docs.amd.com:
```
2026-04-01 18:44:38.667 [Info] (Process) Memory access fault by GPU node-1 (Agent handle: 0x5a7004e44300) on address 0x7a06987bc000. Reason: Page not present or supervisor privilege.
2026-04-01 18:44:38.676 [Info] (Process) GPU coredump: execvp failed: No such file or directory
2026-04-01 18:44:38.678 [Info] (Process) Failed to write segment data to pipe: Success
2026-04-01 18:44:38.678 [Error] (Process) GPU coredump: handler exited with error (status: 1)
2026-04-01 18:44:38.678 [Info] (Process) GPU core dump failed
2026-04-01 18:44:38.857 [Error] (WrappedServer) llama-server process has terminated
```

**Comment by harkgill-amd** [comment]
>  on yours with the main repo package does it process the request with 200?

Yup, `(Server) POST /api/v1/chat/completions - 200 OK`

> It recognizes ROCm but it fails with memory access fault saying Page not present or supervisor privileg

What kernel version are you on? We had [similar reports](https://github.com/ROCm/ROCm/issues/5724) in the past that were caused by a kernel (FW)/ROCm conflict which has since been fixed. https://rocm.docs.amd.com/en/latest/how-to/system-optimization/strixhalo.html#required-kernel-version, for reference, all of my testing was done on the `6.14.0-1018-oem` kernel.

**Comment by siavashhub** [comment]
> What kernel version are you on? We had [similar reports](https://github.com/ROCm/ROCm/issues/5724) in the past that were caused by a kernel (FW)/ROCm conflict which has since been fixed. https://rocm.docs.amd.com/en/latest/how-to/system-optimization/strixhalo.html#required-kernel-version, for reference, all of my testing was done on the `6.14.0-1018-oem` kernel.

mine is 6.17.0-19-generic, I have also tested it with 6.8.0-106-generic and generic-hwe-24.04

Let me try yours...

**Comment by siavashhub** [comment]
> What kernel version are you on? We had [similar reports](https://github.com/ROCm/ROCm/issues/5724) in the past that were caused by a kernel (FW)/ROCm conflict which has since been fixed. https://rocm.docs.amd.com/en/latest/how-to/system-optimization/strixhalo.html#required-kernel-version, for reference, all of my testing was done on the `6.14.0-1018-oem` kernel.

Tried with `6.14.0-1018-oem` unfortunately it didn't work. I'm reeving the same memory access fault error.

**Comment by harkgill-amd** [comment]
Do you have `amdgpu-dkms` installed by any chance? I know https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/docker.html#prerequisites mentions that as a prerequisite but it's not recommended for Strix Halo and can actually cause these types of errors. 

If you do have it installed, try removing it with `sudo apt remove amdgpu-dkms amdgpu-dkms-firmware` then rebooting. After doing this, your `modinfo` output should look like this
```
modinfo amdgpu | grep filename
filename:       /lib/modules/6.14.0-1018-oem/kernel/drivers/gpu/drm/amd/amdgpu/amdgpu.ko.zst
```
at which point you can give lemonade-server another run and it should work.

**Comment by siavashhub** [comment]
> If you do have it installed, try removing it with `sudo apt remove amdgpu-dkms amdgpu-dkms-firmware` then rebooting.

Tried it, but unfortunately getting the same error.

Below is result of the command before `amdgpu-dkms` and `amdgpu-dkms-firmwware` removal:
```
modinfo amdgpu | grep filename
filename:       /lib/modules/6.14.0-1018-oem/updates/dkms/amdgpu.ko.zst
```

Below is the result after removal and reboot:
```
modinfo amdgpu | grep filename
filename:       /lib/modules/6.14.0-1018-oem/kernel/drivers/gpu/drm/amd/amdgpu/amdgpu.ko.zst
```

Error output:
```
2026-04-04 15:31:54.195 [Info] (Process) ggml_cuda_init: found 1 ROCm devices (Total VRAM: 64045 MiB):
2026-04-04 15:31:54.195 [Info] (Process)   Device 0: Radeon 8060S Graphics, gfx1151 (0x1151), VMM: no, Wave Size: 32, VRAM: 64045 MiB
2026-04-04 15:31:54.215 [Info] (Process) main: n_parallel is set to auto, using n_parallel = 4 and kv_unified = true
2026-04-04 15:31:54.215 [Info] (Process) build: 1 (b1c70e2) with Clang 23.0.0 for Linux 
2026-04-04 15:31:54.215 [Info] (Process) system info: n_threads = 16, n_threads_batch = 16, total_threads = 32
2026-04-04 15:31:54.215 [Info] (Process) system_info: n_threads = 16 (n_threads_batch = 16) / 32 | ROCm : NO_VMM = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : LLAMAFILE = 1 | REPACK = 1 | 
2026-04-04 15:31:54.215 [Info] (Process) Running without SSL
2026-04-04 15:31:54.215 [Info] (Process) init: using 31 threads for HTTP server
2026-04-04 15:31:54.215 [Info] (Process) Web UI is disabled
2026-04-04 15:31:54.215 [Info] (Process) start: binding port with default address family
2026-04-04 15:31:54.216 [Info] (Process) main: loading model
2026-04-04 15:31:54.216 [Info] (Process) srv    load_model: loading model '/root/.cache/huggingface/hub/models--unsloth--Qwen3-0.6B-GGUF/snapshots/50968a4468ef4233ed78cd7c3de230dd1d61a56b/Qwen3-0.6B-Q4_0.gguf'
2026-04-04 15:31:54.216 [Info] (Process) common_init_result: fitting params to device memory, for bugs during this step try to reproduce them with -fit off, or provide --verbose logs if the bug only occurs with -fit on
2026-04-04 15:31:54.380 [Info] (Process) Memory access fault by GPU node-1 (Agent handle: 0x5a7f783b3300) on address 0x715ebd1b4000. Reason: Page not present or supervisor privilege.
2026-04-04 15:31:54.392 [Info] (Process) GPU coredump: execvp failed: No such file or directory
2026-04-04 15:31:54.393 [Info] (Process) Failed to write segment data to pipe: Broken pipe
2026-04-04 15:31:54.393 [Error] (Process) GPU coredump: handler exited with error (status: 1)
2026-04-04 15:31:54.393 [Info] (Process) GPU core dump failed
2026-04-04 15:31:54.586 [Error] (WrappedServer) llama-server process has terminated with exit code: -1
2026-04-04 15:31:54.586 [Error] (WrappedServer) This usually means:
2026-04-04 15:31:54.586 [Error] (WrappedServer)   - Missing required drivers or dependencies
2026-04-04 15:31:54.586 [Error] (WrappedServer)   - Incompatible model file
2026-04-04 15:31:54.586 [Error] (WrappedServer)   - Try running the server manually to see the actual error
2026-04-04 15:31:59.607 [Warn] (ProcessManager) Process did not respond to SIGTERM, using SIGKILL
2026-04-04 15:31:59.607 [Info] (ProcessManager) Process terminated, waiting for GPU driver cleanup...
2026-04-04 15:32:01.608 [Error] (Router) Retry also failed: llama-server failed to start
2026-04-04 15:32:01.608 [Info] (LlamaCpp) Unloading model...

```

**Comment by harkgill-amd** [comment]
The amdgpu-dkms removal looks good, just want to double check that the correct firmware is being loaded too. Could you share the output of ` sudo cat /sys/kernel/debug/dri/1/amdgpu_firmware_info | grep MES` on your system after the reboot? We'd be expecting MES FW version 0x00000080 in this case.

**Comment by siavashhub** [comment]
> The amdgpu-dkms removal looks good, just want to double check that the correct firmware is being loaded too. Could you share the output of ` sudo cat /sys/kernel/debug/dri/1/amdgpu_firmware_info | grep MES` on your system after the reboot? We'd be expecting MES FW version 0x00000080 in this case.

Sure, here are the results:
```
sudo cat /sys/kernel/debug/dri/1/amdgpu_firmware_info | grep MES
MES_KIQ feature version: 6, firmware version: 0x0000006f
MES feature version: 1, firmware version: 0x00000083
```
Seems mine is different.

**Comment by harkgill-amd** [comment]
Ah that's likely the culprit, the `0x00000083` is coming from the `amdgpu-dkms-firmware` package (granted you're still on the `6.14.0-1018-oem` kernel`). The package might still be lingering on your system, a quick way to confirm is the output of,

- ` ls /lib/firmware/updates/amdgpu/*mes*` - files here -> `amdgpu-dkms-firmware` is loaded

**Comment by siavashhub** [comment]
> Ah that's likely the culprit, the `0x00000083` is coming from the `amdgpu-dkms-firmware` package (granted you're still on the `6.14.0-1018-oem` kernel`). The package might still be lingering on your system, a quick way to confirm is the output of,
> 
> * ` ls /lib/firmware/updates/amdgpu/*mes*` - files here -> `amdgpu-dkms-firmware` is loaded

Nice thank you so much that was the issue.

I ran below to remove the strain firmware files:
```
sudo rm /lib/firmware/amdgpu/gc_11_5_1_mes1.bin
sudo rm /lib/firmware/amdgpu/gc_11_5_1_mes_2.bin
sudo update-initramfs -u -k all
```

Now the result after reboot:
```
sudo cat /sys/kernel/debug/dri/1/amdgpu_firmware_info | grep MES
MES_KIQ feature version: 6, firmware version: 0x0000006f
MES feature version: 1, firmware version: 0x00000080
```
Now the docker images works fine using ROCm with this firmware :)

Thank you so much again, really appreciate your patience and help!

**Comment by harkgill-amd** [comment]
No problem, glad to hear it's working on your end!
