### ISSUE TITLE
[Issue]: CI Linux PyTorch Wheels test failures

### ISSUE THREAD

**Issue by stzu9000** [ROCm/TheRock#4476]
### Problem Description

The Linux PyTorch wheels release CI jobs failed with a few different failures.  (sorry for the long list, happy to split into multiple issues if needed)

I tried to cross check against "successful" tests but turned out the tests are simply skipped.  Any context on why they are skipped?   See here:   https://github.com/ROCm/TheRock/actions/runs/24277573869/job/70895428350

A few failed at the same place like this one:
[Release | gfx1151 | py 3.12 | torch release/2.11 / Test | gfx1151 | linux-gfx1151-gpu-rocm / Test PyTorch | gfx1151](https://github.com/ROCm/TheRock/actions/runs/24276870054/job/70893834068#logs)

```
external-builds/pytorch/pytorch/test/test_cuda.py::TestMemPool::test_mempool_expandable [1/2] c++ -MMD -MF main_hip.o.d -DTORCH_EXTENSION_NAME=dummy_allocator -DTORCH_API_INCLUDE_EXTENSION_H -isystem /__w/TheRock/TheRock/.venv/lib/python3.11/site-packages/torch/include -isystem /__w/TheRock/TheRock/.venv/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -isystem /__w/TheRock/TheRock/.venv/lib/python3.11/site-packages/torch/include/THH -isystem /__w/TheRock/TheRock/.venv/include -isystem /__w/_tool/Python/3.11.15/x64/include/python3.11 -fPIC -std=c++17 -c /github/home/.cache/torch_extensions/py311_rocm71360980/dummy_allocator/main_hip.cpp -o main_hip.o -D__HIP_PLATFORM_AMD__=1 -DUSE_ROCM=1 -DHIPBLAS_V2 -fPIC
FAILED: [code=1] main_hip.o 
c++ -MMD -MF main_hip.o.d -DTORCH_EXTENSION_NAME=dummy_allocator -DTORCH_API_INCLUDE_EXTENSION_H -isystem /__w/TheRock/TheRock/.venv/lib/python3.11/site-packages/torch/include -isystem /__w/TheRock/TheRock/.venv/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -isystem /__w/TheRock/TheRock/.venv/lib/python3.11/site-packages/torch/include/THH -isystem /__w/TheRock/TheRock/.venv/include -isystem /__w/_tool/Python/3.11.15/x64/include/python3.11 -fPIC -std=c++17 -c /github/home/.cache/torch_extensions/py311_rocm71360980/dummy_allocator/main_hip.cpp -o main_hip.o -D__HIP_PLATFORM_AMD__=1 -DUSE_ROCM=1 -DHIPBLAS_V2 -fPIC
In file included from /github/home/.cache/torch_extensions/py311_rocm71360980/dummy_allocator/main_hip.cpp:5:
/__w/TheRock/TheRock/.venv/lib/python3.11/site-packages/torch/include/ATen/hip/Exceptions.h:5:10: fatal error: 'hipblas/hipblas.h' file not found
    5 | #include <hipblas/hipblas.h>
      |          ^~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
FAILED [4.8334s] [  8%]
```

```
external-builds/pytorch/pytorch/test/test_cuda.py::TestMemPool::test_mempool_no_split FAILED [0.0111s] [  8%]
external-builds/pytorch/pytorch/test/test_cuda.py::TestMemPool::test_nested_mempool FAILED [0.0115s] [  8%]
terminate called after throwing an instance of 'c10::Error'
  what():  captures_underway.empty() INTERNAL ASSERT FAILED at "/__w/TheRock/TheRock/external-builds/pytorch/pytorch/c10/hip/HIPCachingAllocator.cpp":3781, please report a bug to PyTorch. 
Exception raised from synchronize_and_free_events at /__w/TheRock/TheRock/external-builds/pytorch/pytorch/c10/hip/HIPCachingAllocator.cpp:3781 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x9d (0x70b47c38605d in /__w/TheRock/TheRock/.venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x69 (0x70b47c31a7d3 in /__w/TheRock/TheRock/.venv/lib/python3.11/site-packages/torch/lib/libc10.so)
```

[Release | gfx1151 | py 3.13 | torch release/2.11 / Test | gfx1151 | linux-gfx1151-gpu-rocm / Test PyTorch | gfx1151](https://github.com/ROCm/TheRock/actions/runs/24276870054/job/70893853449#logs)

```
FAILED [0.0033s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_large__refs_special_spherical_bessel_j0_cuda_uint16 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0031s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_large__refs_special_spherical_bessel_j0_cuda_uint32 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0029s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_large__refs_special_spherical_bessel_j0_cuda_uint64 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0032s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_large_special_spherical_bessel_j0_cuda_uint16 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0030s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_large_special_spherical_bessel_j0_cuda_uint32 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0031s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_large_special_spherical_bessel_j0_cuda_uint64 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0032s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_uint16 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0023s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_uint32 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0025s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_uint64 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0031s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_normal_special_airy_ai_cuda_uint16 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0038s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_normal_special_airy_ai_cuda_uint32 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0032s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_normal_special_airy_ai_cuda_uint64 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0034s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_normal_special_spherical_bessel_j0_cuda_uint16 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0029s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_normal_special_spherical_bessel_j0_cuda_uint32 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0032s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_normal_special_spherical_bessel_j0_cuda_uint64 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0020s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_uint16 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0023s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_uint32 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0021s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_uint64 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0019s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_small_special_airy_ai_cuda_uint16 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0026s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_small_special_airy_ai_cuda_uint32 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0019s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_small_special_airy_ai_cuda_uint64 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0020s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_small_special_spherical_bessel_j0_cuda_uint16 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0020s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_small_special_spherical_bessel_j0_cuda_uint32 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.0022s] external-builds/pytorch/pytorch/test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_small_special_spherical_bessel_j0_cuda_uint64 - AttributeError: 'NoneType' object has no attribute 'dtype'
FAILED [0.4964s] external-builds/pytorch/pytorch/test/test_autograd.py::TestAutograd::test_checkpoint_compile_no_recompile - torch._dynamo.exc.BackendCompilerFailed: backend='aot_eager' raised:
```

[Release | gfx1151 | py 3.13 | torch nightly / Test | gfx1151 | linux-gfx1151-gpu-rocm / Test PyTorch | gfx1151](https://github.com/ROCm/TheRock/actions/runs/24276870054/job/70894027516#logs)

```
GPU coredump: execvp failed: No such file or directory
Failed to write segment data to pipe: Success
GPU coredump: handler exited with error (status: 1)
GPU core dump failed
:0:rocdevice.cpp            :3921: 235758982418 us:  Callback: Queue 0x74d65de00000 aborting with error : HSA_STATUS_ERROR_EXCEPTION: An HSAIL operation resulted in a hardware exception. code: 0x1016
```

```
terminate called after throwing an instance of 'c10::AcceleratorError'
  what():  CUDA error: operation not permitted when stream is capturing
Search for `hipErrorStreamCaptureUnsupported' in https://rocm.docs.amd.com/projects/HIP/en/latest/index.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Device-side assertion tracking was not enabled by user.
Exception raised from ~CUDAGraph at /__w/TheRock/TheRock/external-builds/pytorch/pytorch/aten/src/ATen/hip/HIPGraph.cpp:367 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x9d (0x79a591b7fe7d in /__w/TheRock/TheRock/.venv/lib/python3.13/site-packages/torch/lib/libc10.so)
```

[Release | gfx1151 | py 3.14 | torch release/2.9 / Test | gfx1151 | linux-gfx1151-gpu-rocm / Test PyTorch | gfx1151](https://github.com/ROCm/TheRock/actions/runs/24276870054/job/70893832768#logs)

```
2026-04-11T08:22:52.0030673Z Traceback (most recent call last):
2026-04-11T08:22:52.0042479Z   File "<string>", line 17, in <module>
2026-04-11T08:22:52.0043009Z     output = my_func(a, b, perm)
2026-04-11T08:22:52.0043455Z   File "<string>", line 7, in my_func
2026-04-11T08:22:52.0043908Z     a[0] *= b[idx]  # should raise an error during capture
2026-04-11T08:22:52.0044300Z             ~^^^^^
2026-04-11T08:22:52.0045021Z torch.AcceleratorError: HIP error: operation not permitted when stream is capturing
2026-04-11T08:22:52.0045430Z Search for `hipErrorStreamCaptureUnsupported' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__HIPRT__TYPES.html for more information.
2026-04-11T08:22:52.0045835Z HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
2026-04-11T08:22:52.0046111Z For debugging consider passing AMD_SERIALIZE_KERNEL=3
2026-04-11T08:22:52.0046293Z Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
2026-04-11T08:22:52.0046417Z 
2026-04-11T08:22:52.0046420Z 
2026-04-11T08:22:52.0046508Z During handling of the above exception, another exception occurred:
2026-04-11T08:22:52.0046631Z 
2026-04-11T08:22:52.0046679Z Traceback (most recent call last):
2026-04-11T08:22:52.0046827Z   File "<string>", line 16, in <module>
2026-04-11T08:22:52.0046957Z     with torch.cuda.graph(g):
2026-04-11T08:22:52.0047071Z          ~~~~~~~~~~~~~~~~^^^
2026-04-11T08:22:52.0047303Z   File "/__w/TheRock/TheRock/.venv/lib/python3.14/site-packages/torch/cuda/graphs.py", line 265, in __exit__
2026-04-11T08:22:52.0047526Z     self.cuda_graph.capture_end()
2026-04-11T08:22:52.0047641Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
2026-04-11T08:22:52.0047864Z   File "/__w/TheRock/TheRock/.venv/lib/python3.14/site-packages/torch/cuda/graphs.py", line 128, in capture_end
2026-04-11T08:22:52.0048085Z     super().capture_end()
2026-04-11T08:22:52.0048190Z     ~~~~~~~~~~~~~~~~~~~^^
2026-04-11T08:22:52.0048368Z torch.AcceleratorError: HIP error: operation failed due to a previous error during capture
2026-04-11T08:22:52.0048732Z Search for `hipErrorStreamCaptureInvalidated' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__HIPRT__TYPES.html for more information.
2026-04-11T08:22:52.0049128Z HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
2026-04-11T08:22:52.0049381Z For debugging consider passing AMD_SERIALIZE_KERNEL=3
2026-04-11T08:22:52.0049564Z Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
2026-04-11T08:22:52.0049682Z 
```

```
2026-04-11T08:23:31.0162326Z Traceback (most recent call last):
2026-04-11T08:23:31.0164505Z   File "<string>", line 35, in <module>
2026-04-11T08:23:31.0173391Z     ret = fork_and_check_is_pinned()
2026-04-11T08:23:31.0176910Z   File "<string>", line 22, in fork_and_check_is_pinned
2026-04-11T08:23:31.0177438Z     p.start()
2026-04-11T08:23:31.0177694Z     ~~~~~~~^^
2026-04-11T08:23:31.0178298Z   File "/__w/_tool/Python/3.14.4/x64/lib/python3.14/multiprocessing/process.py", line 121, in start
2026-04-11T08:23:31.0178929Z     self._popen = self._Popen(self)
2026-04-11T08:23:31.0179267Z                   ~~~~~~~~~~~^^^^^^
2026-04-11T08:23:31.0179866Z   File "/__w/_tool/Python/3.14.4/x64/lib/python3.14/multiprocessing/context.py", line 230, in _Popen
2026-04-11T08:23:31.0180575Z     return _default_context.get_context().Process._Popen(process_obj)
2026-04-11T08:23:31.0181098Z            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
2026-04-11T08:23:31.0181761Z   File "/__w/_tool/Python/3.14.4/x64/lib/python3.14/multiprocessing/context.py", line 306, in _Popen
2026-04-11T08:23:31.0182344Z     return Popen(process_obj)
2026-04-11T08:23:31.0183016Z   File "/__w/_tool/Python/3.14.4/x64/lib/python3.14/multiprocessing/popen_forkserver.py", line 35, in __init__
2026-04-11T08:23:31.0183648Z     super().__init__(process_obj)
2026-04-11T08:23:31.0183968Z     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
2026-04-11T08:23:31.0184545Z   File "/__w/_tool/Python/3.14.4/x64/lib/python3.14/multiprocessing/popen_fork.py", line 20, in __init__
2026-04-11T08:23:31.0185137Z     self._launch(process_obj)
2026-04-11T08:23:31.0185509Z     ~~~~~~~~~~~~^^^^^^^^^^^^^
2026-04-11T08:23:31.0186107Z   File "/__w/_tool/Python/3.14.4/x64/lib/python3.14/multiprocessing/popen_forkserver.py", line 47, in _launch
2026-04-11T08:23:31.0186730Z     reduction.dump(process_obj, buf)
2026-04-11T08:23:31.0187070Z     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2026-04-11T08:23:31.0187631Z   File "/__w/_tool/Python/3.14.4/x64/lib/python3.14/multiprocessing/reduction.py", line 60, in dump
2026-04-11T08:23:31.0187936Z     ForkingPickler(file, protocol).dump(obj)
2026-04-11T08:23:31.0188064Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
2026-04-11T08:23:31.0188303Z _pickle.PicklingError: Can't pickle local object <function fork_and_check_is_pinned.<locals>.worker at 0x707f76351c70>
2026-04-11T08:23:31.0188758Z when serializing dict item '_target'
2026-04-11T08:23:31.0188905Z when serializing multiprocessing.context.Process state
2026-04-11T08:23:31.0189080Z when serializing multiprocessing.context.Process object
2026-04-11T08:23:31.2425359Z external-builds/pytorch/pytorch/test/test_cuda.py::TestCuda::test_is_pinned_no_context FAILED [0.9759s] [  8%]
```

### Operating System

CI

### CPU

CI

### GPU

CI

### ROCm Version

7.13.0a20260411

**Comment by mgehre-amd** [comment]
The hipblas/hipblas.h issue is also reported in #2452

**Comment by mgehre-amd** [comment]
> I tried to cross check against "successful" tests but turned out the tests are simply skipped. Any context on why they are skipped? See here: [ROCm/TheRock/actions/runs/24277573869/job/70895428350](https://github.com/ROCm/TheRock/actions/runs/24277573869/job/70895428350)

gfx1152 doesn't have runners in CI yet, this is why the tests are skipped.

**Comment by ScottTodd** [comment]
> The Linux PyTorch wheels release CI jobs failed with a few different failures. (sorry for the long list, happy to split into multiple issues if needed)

See also the first pinned issue in this repository:
* https://github.com/ROCm/TheRock/issues/2156

Let's dup this against that issue and/or split into sub-issues? cc @sa-faizal who has been driving the effort to get these tests stable (there's an internal spreadsheet tracking issues too - please reflect that back to the github issues too)

**Comment by stzu9000** [comment]
> > I tried to cross check against "successful" tests but turned out the tests are simply skipped. Any context on why they are skipped? See here: [ROCm/TheRock/actions/runs/24277573869/job/70895428350](https://github.com/ROCm/TheRock/actions/runs/24277573869/job/70895428350)
> 
> gfx1152 doesn't have runners in CI yet, this is why the tests are skipped.

Got it. I just randomly picked one.  (BTW it seems like Radeon AI Pro R9700 (gfx1201) is skipped too.  See https://github.com/ROCm/TheRock/actions/runs/24387915163   should CI be set up for it?)

**Comment by zichguan-amd** [comment]
The header issue should be fixed by https://github.com/ROCm/TheRock/pull/4565, and that should clear the rest of the test failures. Working run https://github.com/ROCm/TheRock/actions/runs/24090877188

**Comment by sa-faizal** [comment]
### Adding some additional pointers to this issue

**Workflow:** Release portable Linux PyTorch Wheels  
**Workflow run:** https://github.com/ROCm/TheRock/actions/runs/24438647045  
**Matrix:** gfx94X-dcgpu | Python 3.11 | `pytorch_git_ref`: release/2.11  
**Wheel / ROCm:** `torch` 2.11.0+rocm7.13.0a20260415 

**Observed sequence:**
1. `TestMemPool::test_mempool_expandable` JIT build of `dummy_allocator` fails: `fatal error: 'hipblas/hipblas.h' file not found` (via `ATen/hip/Exceptions.h`). 
3. `TestMemPool::test_mempool_no_split`, `test_nested_mempool` FAILED.
4. Process abort: `captures_underway.empty() INTERNAL ASSERT FAILED` at `c10/hip/HIPCachingAllocator.cpp:3781` during `test_snapshot_include_traces` (GC / `MemPool` destructor), then **exit code 134**.
**Logs:** https://github.com/ROCm/TheRock/actions/runs/24438647045/job/71410178208

Also note `HSA_STATUS_ERROR_EXCEPTION` / `code: 0x1016` and GPU coredump handler noise after `test_events` which could be possible async GPU instability or compile-path failure.

Update:
* [PR 4565](https://github.com/ROCm/TheRock/pull/4565) should fix the test_mempool_expandable test failure (skipping the test)

**Comment by srinivamd** [comment]
## Root Cause Analysis

Five distinct failure clusters are present in this issue. The **primary blocker** (`test_mempool_expandable`) was introduced by **ROCm/pytorch PR#3106** (merged 2026-03-27, `release/2.11`), which enabled HIP VMM-based expandable segments (`hipMemAddressReserve`, `hipMemCreate`, `hipMemMap`) and un-skipped `test_mempool_expandable`. That test JIT-compiles a `dummy_allocator` C++ extension that includes `ATen/hip/Exceptions.h`, which transitively pulls in `hipblas/hipblas.h` — a header absent from wheel-only CI installs (runtime packages, no `rocm-devel`). This cascades into `HIPCachingAllocator.cpp:3781 captures_underway.empty() INTERNAL ASSERT FAILED`. **This blocker was fixed by TheRock PR#4565** (merged 2026-04-15), which re-adds `test_mempool_expandable` to the `pytorch_2.11.py` skip list. The test was never enabled on `release/2.10` or `release/2.9`, so those branches are unaffected.

The four remaining open failures are secondary: (2) `test_unary_ufuncs` for `spherical_bessel_j0`/`airy_ai` fails on uint16/uint32/uint64 with `AttributeError: 'NoneType' has no attribute 'dtype'` — missing numpy reference implementations for unsigned integer dtypes, not observed on MI300X where a different bool-dtype numpy error occurs; (3) `test_checkpoint_compile_no_recompile` fails with `BackendCompilerFailed: backend='aot_eager'`, possibly a wavefront-width-specific path for RDNA3.5; (4) `hipErrorStreamCaptureUnsupported` in the `HIPGraph.cpp` destructor followed by a GPU coredump (`HSA_STATUS_ERROR_EXCEPTION: 0x1016`), indicating incomplete HIP graph stream-capture support on gfx1151; (5) `test_is_pinned_no_context` fails with `PicklingError: Can't pickle local object` under Python 3.14's new `forkserver` default multiprocessing start method.

---

## GitHub Findings

### ROCm/TheRock

| PR/Issue | Title | Date | Relevance | Confidence |
|---|---|---|---|---|
| [#4565](https://github.com/ROCm/TheRock/pull/4565) | Skip `test_mempool_expandable` in `pytorch_2.11.py` | 2026-04-15 | **Fix — Cluster 1** | High |
| [#2452](https://github.com/ROCm/TheRock/issues/2452) | `hipblas/hipblas.h` not found after installing ROCm python wheel packages | 2024 | Related background — missing devel headers in wheels | High |

### ROCm/pytorch

| PR/Issue | Title | Date | Relevance | Confidence |
|---|---|---|---|---|
| [#3106](https://github.com/ROCm/pytorch/pull/3106) | Enable expandable segments for ROCm using HIP VMM APIs | 2026-03-27 | **Regression introducer — Cluster 1** (un-skipped `test_mempool_expandable` in `release/2.11`) | High |

### ROCm/rocm-libraries / ROCm/rocm-systems

No matches found for the gfx1151 test failures.

### pytorch/pytorch (upstream)

No upstream fixes found for Clusters 2–5 (`spherical_bessel_j0` uint NoneType, `aot_eager` checkpoint, HIP stream capture, Python 3.14 pickle).

---

## Cross-Architecture Comparison

MI300X (gfx942) metrics at ROCm 7.13.0 show **different** failures from gfx1151:
- `test_unary_ufuncs` (MI300X 2.9.x): `TypeError: numpy bool '-' not supported` for **bool** dtype — not the uint16/32/64 NoneType error seen on gfx1151
- `test_cuda.py` (MI300X 2.10.x): `test_device_count_not_cached_pre_init`, `test_host_memory_stats`, `test_mempool_ctx_multithread` — none of these appear in the gfx1151 failure list

`test_mempool_expandable` is **absent** from MI300X 2.10.x failures, confirming it was only triggered by the release/2.11 enablement. No MI350 (gfx950) metrics data is available locally.

---

## Recommended Action

- [x] **Cluster 1 (done):** TheRock#4565 merged 2026-04-15 — skips `test_mempool_expandable` in `pytorch_2.11.py`
- [ ] **Cluster 1 (proper fix):** Investigate why `ATen/hip/Exceptions.h` requires `hipblas/hipblas.h`; consider removing or guarding the include, or bundling headers in the wheel
- [ ] **Cluster 2:** Add numpy reference implementations for uint16/uint32/uint64 dtypes in `special_spherical_bessel_j0` and `special_airy_ai`, or explicitly exclude unsigned integer dtypes from these tests
- [ ] **Cluster 3:** Debug `aot_eager` backend failure on gfx1151 — check RDNA3.5 wavefront-width-specific compilation paths
- [ ] **Cluster 4:** Audit HIP graph stream-capture support completeness for gfx1151; coordinate with ROCm runtime team on `hipErrorStreamCaptureUnsupported`
- [ ] **Cluster 5:** Update `test_is_pinned_no_context` to use a top-level picklable callable for Python 3.14 `forkserver` compatibility

*Analysis generated with AI assistance.*

**Comment by stzu9000** [comment]
> **Observed sequence:**
> 
>     1. `TestMemPool::test_mempool_expandable` JIT build of `dummy_allocator` fails: `fatal error: 'hipblas/hipblas.h' file not found` (via `ATen/hip/Exceptions.h`).
> 
...
> Update:
> 
>     * [PR 4565](https://github.com/ROCm/TheRock/pull/4565) should fix the test_mempool_expandable test failure
Would there be a better fix than skipping the test?

> Also note `HSA_STATUS_ERROR_EXCEPTION` / `code: 0x1016` and GPU coredump handler noise after `test_events` which could be possible async GPU instability or compile-path failure.

I think it's the expected output from the `external-builds/pytorch/pytorch/test/test_cuda.py::TestCuda::test_fixed_cuda_assert_async`  test?

**Comment by srinivamd** [comment]
> ### Adding some additional pointers to this issue
> **Workflow:** Release portable Linux PyTorch Wheels **Workflow run:** https://github.com/ROCm/TheRock/actions/runs/24438647045 **Matrix:** gfx94X-dcgpu | Python 3.11 | `pytorch_git_ref`: release/2.11 **Wheel / ROCm:** `torch` 2.11.0+rocm7.13.0a20260415
> 
> **Observed sequence:**
> 
> 1. `TestMemPool::test_mempool_expandable` JIT build of `dummy_allocator` fails: `fatal error: 'hipblas/hipblas.h' file not found` (via `ATen/hip/Exceptions.h`).
> 2. `TestMemPool::test_mempool_no_split`, `test_nested_mempool` FAILED.
> 3. Process abort: `captures_underway.empty() INTERNAL ASSERT FAILED` at `c10/hip/HIPCachingAllocator.cpp:3781` during `test_snapshot_include_traces` (GC / `MemPool` destructor), then **exit code 134**.
>    **Logs:** https://github.com/ROCm/TheRock/actions/runs/24438647045/job/71410178208
> 
> Also note `HSA_STATUS_ERROR_EXCEPTION` / `code: 0x1016` and GPU coredump handler noise after `test_events` which could be possible async GPU instability or compile-path failure.
> 
> Update:
> 
> * [PR 4565](https://github.com/ROCm/TheRock/pull/4565) should fix the test_mempool_expandable test failure

The above tests are passing with ROCm 7.2.2 on gfx942 arch. Are you able to reproduce the failure on ROCm 7.2.2?

**Comment by stzu9000** [comment]
The test hit on other failures. See here https://github.com/ROCm/TheRock/issues/4598

**Comment by srinivamd** [comment]
> ### Adding some additional pointers to this issue
> **Workflow:** Release portable Linux PyTorch Wheels **Workflow run:** https://github.com/ROCm/TheRock/actions/runs/24438647045 **Matrix:** gfx94X-dcgpu | Python 3.11 | `pytorch_git_ref`: release/2.11 **Wheel / ROCm:** `torch` 2.11.0+rocm7.13.0a20260415
> 
> **Observed sequence:**
> 
> 1. `TestMemPool::test_mempool_expandable` JIT build of `dummy_allocator` fails: `fatal error: 'hipblas/hipblas.h' file not found` (via `ATen/hip/Exceptions.h`).
> 2. `TestMemPool::test_mempool_no_split`, `test_nested_mempool` FAILED.
> 3. Process abort: `captures_underway.empty() INTERNAL ASSERT FAILED` at `c10/hip/HIPCachingAllocator.cpp:3781` during `test_snapshot_include_traces` (GC / `MemPool` destructor), then **exit code 134**.
>    **Logs:** https://github.com/ROCm/TheRock/actions/runs/24438647045/job/71410178208
> 
> Also note `HSA_STATUS_ERROR_EXCEPTION` / `code: 0x1016` and GPU coredump handler noise after `test_events` which could be possible async GPU instability or compile-path failure.
> 
> Update:
> 
> * [PR 4565](https://github.com/ROCm/TheRock/pull/4565) should fix the test_mempool_expandable test failure (skipping the test)

The issue could be related to `amdsmi` failing or not detecting gpus.
The log for test run https://github.com/ROCm/TheRock/actions/runs/24438647045/job/71410178208 shows:
```
2026-04-15T07:57:31.5416087Z external-builds/pytorch/pytorch/test/test_cuda.py::TestCudaMallocAsync::test_raw_amdsmi_device_count SKIPPED [0.0001s] [  8%]
2026-04-15T07:57:31.5420933Z external-builds/pytorch/pytorch/test/test_cuda.py::TestCudaMallocAsync::test_raw_amdsmi_device_uuids SKIPPED [0.0001s] [  8%]
```
which gets skipped only when `amdsmi` is not detected or if not `rocm` test.
CC: @pragupta @jithunnair-amd @CSkmd

**Comment by srinivamd** [comment]
## gfx94X Focus: Root Cause Analysis

**Workflow run:** https://github.com/ROCm/TheRock/actions/runs/24438647045/job/71410178208  
**Matrix:** gfx94X-dcgpu | Python 3.11 | `pytorch_git_ref`: release/2.11 | `torch 2.11.0+rocm7.13.0a20260415`

### Failure Sequence

The gfx94X job shows the same mempool cascade as gfx1151. **ROCm/pytorch PR#3106** (merged 2026-03-27, `release/2.11`) enabled HIP VMM-based expandable segments and un-skipped `test_mempool_expandable`. That test JIT-compiles a `dummy_allocator` extension which includes `ATen/hip/Exceptions.h` → transitively requires `hipblas/hipblas.h` — absent in wheel-only CI installs (no `rocm-devel`). This causes process exit code 134 and leaves `HIPCachingAllocator` in a broken state (`captures_underway.empty() INTERNAL ASSERT FAILED` at `HIPCachingAllocator.cpp:3781`), cascading into `test_mempool_no_split` and `test_nested_mempool` failures.

**This is fixed by TheRock PR#4565** (merged 2026-04-15), which re-adds `test_mempool_expandable` to the `pytorch_2.11.py` skip list.

---

### amdsmi Tests Skipped — Why?

The log shows:
```
test_cuda.py::TestCudaMallocAsync::test_raw_amdsmi_device_count  SKIPPED [0.0001s]
test_cuda.py::TestCudaMallocAsync::test_raw_amdsmi_device_uuids  SKIPPED [0.0001s]
```

The skip is **not** `TEST_WITH_ROCM` (which is True on gfx94X). The actual guard is `TEST_PYNVML`:

```python
@unittest.skipIf(not TEST_PYNVML, "pynvml/amdsmi is not available")  # ← this fires
@unittest.skipIf(not TEST_WITH_ROCM, "amdsmi specific test")
def test_raw_amdsmi_device_count(self): ...
```

`TEST_PYNVML = torch.cuda._HAS_PYNVML`, which is set to `True` only if `import amdsmi` succeeds during `torch/cuda/__init__.py` initialization. On ROCm, this import raises `ModuleNotFoundError` silently — the `amdsmi` Python package is **not bundled in the TheRock wheel** and not installed in the CI environment. The 0.0001s skip time confirms the skip fires at decorator evaluation before any test body runs.

**Evidence from the log:** Skip reason is "pynvml/amdsmi is not available" — the exact `TEST_PYNVML` message. No explicit import error is shown because `torch/cuda/__init__.py` catches `ModuleNotFoundError` silently.

**CI fix required:** Add `pip install /opt/rocm/share/amd_smi/` to the gfx94X test setup step, or bundle the amdsmi Python package in the test environment.

---

### Bisect: `7a10d22b` (pass) → `0446f7ba` (fail)

Five commits separate the two SHAs. The key one is:

| SHA | Merged | Title |
|---|---|---|
| `4e323059` | 2026-04-08 | [ROCm] Require rocm_smi package (#175648) |

This modifies `cmake/Dependencies.cmake` and `cmake/public/LoadHIP.cmake` to hard-link `librocm_smi64.so.1` into `libtorch_hip.so`. However, the actual test failures are driven by the earlier PR#3106 (merged 2026-03-27) which un-skipped `test_mempool_expandable` — this was already in the wheel built for the failing commit range. The 04/01 build passed because `test_mempool_expandable` was still in the skip list at that point.

---

### amdsmi Runtime Dependency Change (libnl3) — Possible import failure cause

**TheRock PR#4061** (merged 2026-04-06) added `libnl3`, `libnl-genl-3`, and `libmnl` as amdsmi runtime shared library dependencies (bundled as `librocm_sysdeps_nl_3.so.200`). On a CI container without these system packages, `import amdsmi` will fail at the `.so` loading stage even if the Python package is installed. This is a possible reason the amdsmi tests were importable on the 04/02 runner but not on the 04/15 runner.

---

## GitHub Findings

### ROCm/TheRock

| PR/Issue | Title | Date | Relevance | Confidence |
|---|---|---|---|---|
| [#4565](https://github.com/ROCm/TheRock/pull/4565) | Skip `test_mempool_expandable` in `pytorch_2.11.py` | 2026-04-15 | **Fix — mempool cascade** | High |
| [#4061](https://github.com/ROCm/TheRock/pull/4061) | [AMD-SMI] Add libnl/libnml to RUNTIME_DEPS | 2026-04-06 | **Possible amdsmi import failure** if libnl3 absent from CI container | High |
| [#4222](https://github.com/ROCm/TheRock/pull/4222) | Revert rocm-systems bump (broke amdsmi on gfx94x/gfx950) | 2026-03-28 | Precedent — amdsmi instability on gfx94X | Medium |
| [#2452](https://github.com/ROCm/TheRock/issues/2452) | `hipblas/hipblas.h` not found after installing wheel | 2024 | Background — pre-existing header gap | High |

### ROCm/pytorch

| PR/Issue | Title | Date | Relevance | Confidence |
|---|---|---|---|---|
| [#3106](https://github.com/ROCm/pytorch/pull/3106) | Enable expandable segments for ROCm using HIP VMM APIs | 2026-03-27 | **Regression introducer** — un-skipped `test_mempool_expandable` | High |
| [`4e323059`](https://github.com/ROCm/pytorch/commit/4e323059) | [ROCm] Require rocm_smi package (#175648) | 2026-04-08 | **Key bisect commit** — hard-links librocm_smi64 into libtorch_hip.so | High |

### ROCm/rocm-systems

| Commit | Title | Date | Relevance | Confidence |
|---|---|---|---|---|
| `8a49af6e` | Fix py-interface: `sys.getsizeof` → `ctypes.sizeof` in amdsmi bindings | 2026-03-02 | Wrong buffer sizes passed to `libamd_smi.so` — incorrect GPU enumeration | Medium |
| `67d9db06` | Fix `stoi`→`stoull` for 64-bit GPU IDs | 2026-04-15 | ID truncation on large GPU counts | Medium |
| `197543fd` | Fix cmake: amdsmi CLI Python files not updated on incremental builds | 2026-04-17 | Stale amdsmi Python in installed packages | Medium |

---

## Recommended Action

- [x] **Mempool cascade (done):** TheRock#4565 merged 2026-04-15 — re-skips `test_mempool_expandable` in `pytorch_2.11.py`
- [ ] **Proper hipblas.h fix:** Remove or guard the `hipblas/hipblas.h` transitive include in `ATen/hip/Exceptions.h`, or bundle dev headers in the wheel (tracked in TheRock#2452)
- [ ] **Install amdsmi Python package in CI:** Add `pip install /opt/rocm/share/amd_smi/` to the gfx94X test setup so `test_raw_amdsmi_device_count` and `test_raw_amdsmi_device_uuids` run instead of silently skipping
- [ ] **Verify libnl3 in CI container:** Run `ldconfig -p | grep libnl` on the gfx94X runner — if absent, `import amdsmi` will fail post-TheRock#4061 even with the Python package installed
- [ ] **Validate `4e323059` librocm_smi64 bundling:** Confirm `librocm_smi64.so.1` is bundled in the wheel now that cmake hard-requires it (same pattern as PR#4440)

*Analysis generated with AI assistance.*

**Comment by srinivamd** [comment]
> > ### Adding some additional pointers to this issue
> > **Workflow:** Release portable Linux PyTorch Wheels **Workflow run:** https://github.com/ROCm/TheRock/actions/runs/24438647045 **Matrix:** gfx94X-dcgpu | Python 3.11 | `pytorch_git_ref`: release/2.11 **Wheel / ROCm:** `torch` 2.11.0+rocm7.13.0a20260415
> > **Observed sequence:**
> > 
> > 1. `TestMemPool::test_mempool_expandable` JIT build of `dummy_allocator` fails: `fatal error: 'hipblas/hipblas.h' file not found` (via `ATen/hip/Exceptions.h`).
> > 2. `TestMemPool::test_mempool_no_split`, `test_nested_mempool` FAILED.
> > 3. Process abort: `captures_underway.empty() INTERNAL ASSERT FAILED` at `c10/hip/HIPCachingAllocator.cpp:3781` during `test_snapshot_include_traces` (GC / `MemPool` destructor), then **exit code 134**.
> >    **Logs:** https://github.com/ROCm/TheRock/actions/runs/24438647045/job/71410178208
> > 
> > Also note `HSA_STATUS_ERROR_EXCEPTION` / `code: 0x1016` and GPU coredump handler noise after `test_events` which could be possible async GPU instability or compile-path failure.
> > Update:
> > 
> > * [PR 4565](https://github.com/ROCm/TheRock/pull/4565) should fix the test_mempool_expandable test failure (skipping the test)
> 
> The issue could be related to `amdsmi` failing or not detecting gpus. The log for test run https://github.com/ROCm/TheRock/actions/runs/24438647045/job/71410178208 shows:
> 
> ```
> 2026-04-15T07:57:31.5416087Z external-builds/pytorch/pytorch/test/test_cuda.py::TestCudaMallocAsync::test_raw_amdsmi_device_count SKIPPED [0.0001s] [  8%]
> 2026-04-15T07:57:31.5420933Z external-builds/pytorch/pytorch/test/test_cuda.py::TestCudaMallocAsync::test_raw_amdsmi_device_uuids SKIPPED [0.0001s] [  8%]
> ```
> 
> which gets skipped only when `amdsmi` is not detected or if not `rocm` test. CC: [@pragupta](https://github.com/pragupta) [@jithunnair-amd](https://github.com/jithunnair-amd) [@CSkmd](https://github.com/CSkmd)

On ROCm 7.2.2 installation with pytorch 2.11 the test results are:
```
pytorch/test/test_cuda.py::TestCudaMallocAsync::test_raw_amdsmi_device_count PASSED [0.3118s]
pytorch/test/test_cuda.py::TestCudaMallocAsync::test_raw_amdsmi_device_uuids FAILED [0.4561s]
```
Torch version:
```
pip3 list|grep torch
torch                   2.11.0+git0446f7b
torchvision             0.26.0+336d36e
```

**Comment by srinivamd** [comment]
## Analysis: `import torch` before `import amdsmi` causes `amdsmi_get_processor_handles()` to return 0 GPUs

### The Key Commit

One commit in the `ROCm/pytorch` `release/2.11` range `7a10d22`→`8543095` is responsible:

**Commit `4e323059`** — *"[ROCm] Require rocm_smi package (#175648)"* — cherry-picked to `release/2.11` on 2026-04-08.

It adds two cmake changes:
- `cmake/public/LoadHIP.cmake`: `find_package_and_print_version(rocm_smi REQUIRED)`
- `cmake/Dependencies.cmake`: links `rocm_smi64` as a public HIP dependency for distributed builds

This makes `librocm_smi64.so` (and thus `lib/libamd_smi.so`) **always** loaded when `import torch` executes — turning a previously environment-dependent race into a deterministic failure.

---

### Root Cause: Two Physical Copies of `libamd_smi.so`

Two distinct physical copies exist in a ROCm installation:

| Copy | Path | Loaded by |
|---|---|---|
| **System copy** | `$ROCM_PATH/lib/libamd_smi.so` | `libtorch` via rpath (after commit `4e323059`) |
| **Python copy** | `$ROCM_PATH/share/amd_smi/amdsmi/libamd_smi.so` | `amdsmi` Python package via `ctypes.CDLL` |

### Why `import torch` First Breaks Things

1. `import torch` → loads `librocm_smi64.so` → pulls in `lib/libamd_smi.so`, initializing its global state
2. `import amdsmi` → `amdsmi_wrapper.py` calls `ctypes.CDLL("...share/.../libamd_smi.so")` → loads the **second** copy with fresh/empty state
3. `amdsmi_init()` now operates on the second copy's isolated state
4. `amdsmi_get_processor_handles()` → returns **0** (second copy never received GPU enumeration data from HIP)

```python
>>> import torch
>>> import amdsmi
>>> amdsmi.amdsmi_init()
>>> len(amdsmi.amdsmi_get_processor_handles())
0   # ← second libamd_smi.so copy, no GPU state
```

### Why `import amdsmi` First Works

1. `import amdsmi` → loads `share/.../libamd_smi.so`, initializes correctly against HIP
2. `import torch` → `_amdsmi_cdll_hook` in `torch/cuda/__init__.py` intercepts torch's own internal `import amdsmi` and routes it to the already-loaded `lib/` copy — but Python's module cache returns the already-imported `amdsmi` module which still points to the `share/` copy that was initialized successfully

### PyTorch's Hook Only Protects Its Own Imports

`torch/cuda/__init__.py` has `_amdsmi_cdll_hook` that patches `ctypes.CDLL` during torch's internal `import amdsmi` to prefer `lib/libamd_smi.so`. This hook only fires during `import torch` itself — it does not protect user-level `import amdsmi` calls.

---

### The Fix

**The correct fix is in `ROCm/rocm-systems` (amdsmi packaging)**: replace the physical copy of `libamd_smi.so` in the Python package directory with a symlink to the versioned system library:

```bash
# Current state (wrong): two independent physical copies
$ROCM_PATH/lib/libamd_smi.so          # system copy
$ROCM_PATH/share/amd_smi/amdsmi/libamd_smi.so  # full physical copy

# Fix: replace the Python package copy with a symlink
ln -sf $ROCM_PATH/lib/libamd_smi.so.26 \
       $ROCM_PATH/share/amd_smi/amdsmi/libamd_smi.so
```

When `amdsmi_wrapper.py` calls `ctypes.CDLL("...share/.../libamd_smi.so")`, the dynamic linker resolves the symlink to the same inode as `$ROCM_PATH/lib/libamd_smi.so.26`. The OS-level `dlopen` deduplication (keyed on real path / inode) then ensures only **one** copy of the library is ever mapped into the process regardless of import order. Both `import torch` and `import amdsmi` share the same global state.

**Short-term workarounds** while the packaging fix lands:
- Always do `import amdsmi` before `import torch` in test code
- Or: `LD_PRELOAD=$ROCM_PATH/lib/libamd_smi.so` to force the system copy loaded first so `dlopen` deduplicates on the second load

### Related

- Upstream pytorch PR: https://github.com/pytorch/pytorch/pull/175648
- TheRock cmake breakage (prior revert): https://github.com/ROCm/TheRock/issues/3702
- rocm-systems cmake fix (unblocked re-land): https://github.com/ROCm/rocm-systems/pull/3979

**Comment by srinivamd** [comment]
The report generated with AI tool posted above.
The fix tested:
```
rm /root/venv/rocm-venv/lib/python3.12/site-packages/_rocm_sdk_devel/lib/libamd_smi.so

ln -sf /root/venv/rocm-venv/lib/python3.12/site-packages/_rocm_sdk_devel/lib/libamd_smi.so.26 /root/venv/rocm-venv/lib/python3.12/site-packages/_rocm_sdk_devel/lib/libamd_smi.so

```
With the above fix, the order of `import torch` and `import amdsmi` does not matter.

**Comment by srinivamd** [comment]
**The OS-level dlopen deduplication (keyed on real path / inode) then ensures only one copy of the library is ever mapped into the process regardless of import order.**

It is important for the therock installation to NOT create multiple copies of shared libraries - the above should explain why that it not ok and why "it works" should not be the criteria to continue with duplicate shared objects.

CC: @jithunnair-amd @pragupta @pruthvistony @jeffdaily

**Comment by pruthvistony** [comment]
@Melantha-S ,
Can we assign this ticket to amdsmi team. 
cc @rraminen

**Comment by Melantha-S** [comment]
> [@Melantha-S](https://github.com/Melantha-S) , Can we assign this ticket to amdsmi team. cc [@rraminen](https://github.com/rraminen)

@sekhatir , @bill-shuzhou-liu , could your team please look into this issue. Thanks

**Comment by fjankovi** [comment]
There is a similar internal ticket already reported to amdsmi: ROCM-21373
