### ISSUE TITLE
Triton HIP: invalid device ordinal on gfx1151 (Strix Halo) in forked subprocess

### ISSUE THREAD

**Issue by stampby** [ROCm/TheRock#4552]
## Environment

- **GPU:** AMD Radeon 8060S (Strix Halo, gfx1151)
- **ROCm:** 7.12.0 (bundled in vllm-rocm portable package from lemonade-sdk/vllm-rocm)
- **Triton:** 3.6.0
- **PyTorch HIP:** 7.12.60610
- **Kernel:** Linux 7.0.0-1-mainline (CachyOS / Arch)
- **RAM:** 128GB unified

## Bug

Triton's AMD HIP driver crashes with `invalid device ordinal` when executing kernels in a **forked/spawned child process** on gfx1151 (Strix Halo iGPU).

```
RuntimeError: Triton Error [HIP]: Code: 101, Messsage: invalid device ordinal
```

The error comes from `triton/backends/amd/driver.py` during kernel launch in vLLM's EngineCore subprocess.

## Key Observation

**Main process:** PyTorch HIP works perfectly.
```python
import torch
print(torch.cuda.device_count())   # 1
print(torch.cuda.get_device_name(0))  # Radeon 8060S Graphics
x = torch.randn(100, 100, device="cuda:0", dtype=torch.float16)
y = torch.matmul(x, x)  # OK
```

**Child process (fork/spawn):** Triton kernel launch fails. The HIP device ordinal becomes invalid after the process fork. Both `ROCM_ATTN` and `TRITON_ATTN` backends crash the same way since both use Triton kernels.

## Reproduction

```bash
# Raw vLLM launch — crashes
python -m vllm.entrypoints.openai.api_server \
  --model any-model \
  --dtype float16 \
  --enforce-eager \
  --port 8000
```

Tried: `HIP_VISIBLE_DEVICES=0`, `VLLM_USE_TRITON_FLASH_ATTN=0`, `VLLM_WORKER_MULTIPROC_METHOD=spawn`, `--enforce-eager`, `--disable-custom-all-reduce`. All fail with the same Triton error.

## Workaround

Lemonade SDK's wrapped server backend (lemonade-sdk/lemonade#1537) launches vLLM through a `ProcessManager` that sets up the environment correctly (`PYTHONNOUSERSITE=1`, `FLASH_ATTENTION_TRITON_AMD_ENABLE=TRUE`, proper `LD_LIBRARY_PATH` via a launcher script). Through this path, **all 14 tested models work including a 72B dense model**.

Benchmark results through the Lemonade wrapper:
```
Qwen3-0.6B          116.7 tok/s
Llama-3.2-1B-AWQ    110.4 tok/s
Llama-3.2-3B-AWQ     50.5 tok/s
Qwen3-4B-AWQ         42.8 tok/s
Qwen3-8B-AWQ         22.8 tok/s
Qwen2.5-72B-AWQ       2.3 tok/s (72B dense on 128GB unified)
```

## Root Cause Hypothesis

The gfx1151 iGPU uses unified memory (no discrete VRAM). The HIP device ordinal may not propagate correctly through process fork/spawn when the GPU is an integrated device rather than a discrete PCIe card. The Lemonade workaround suggests the issue is in environment setup (LD_LIBRARY_PATH, device visibility) rather than a fundamental HIP limitation.

## Impact

gfx1151 (Strix Halo) has 128GB unified memory — it's an ideal target for large model inference. The workaround exists but standalone Triton/vLLM users on gfx1151 cannot use the HIP backend without it.

## References

- lemonade-sdk/vllm-rocm#3 (original bug report)
- lemonade-sdk/lemonade#1537 (PR with working wrapper)

**Comment by tcgu-amd** [comment]
Hi @stampby, thanks for raising the issue.  This does indeed seem like an issue with environment propagation. While the error message says invalid device ordinal, it is probably only saying that because there's a user library mismatch which causes an error when trying to load the device ordinal. 

In your raw vllm test, were you also using the lemonde vllm? How did you install pytorch? Did you install it from the official pytorch site, from AMD's release, or through TheRock? I think if installation was done through lemonade, then setting up the proper environment variables as lemonade does is necessary, because pytorch usually bundles its own ROCm libraries which can conflict with the lemonade ones if not configured properly.

**Comment by stampby** [comment]
@tcgu-amd Thanks for looking into this.

**PyTorch install:** `pip install torch==2.11.0+rocm7.2` from the official PyTorch nightly index (`--index-url https://download.pytorch.org/whl/nightly/rocm7.2`). Not through TheRock, not through lemonade. Direct pip install.

**vLLM:** Used lemonade's vllm-rocm portable package from `lemonade-sdk/vllm-rocm`. This bundles its own ROCm 7.12 libraries. So yes — there's a version mismatch: PyTorch has ROCm 7.2 libs, vllm-rocm has ROCm 7.12 libs, and system is ROCm 7.2.1. Three different ROCm versions in the same process.

**Raw vLLM test:** Same lemonade vllm-rocm package. The Triton crash happens specifically when vLLM's worker subprocess tries to initialize the HIP device — the parent process works fine, but the forked child gets `invalid device ordinal`.

**Environment vars we set:**
```bash
export HSA_OVERRIDE_GFX_VERSION=11.5.1
export HSA_ENABLE_SDMA=0
export HIP_VISIBLE_DEVICES=0
```

Your theory about library mismatch causing the device ordinal error makes sense. The forked subprocess might be picking up a different set of ROCm libs than the parent depending on how `LD_LIBRARY_PATH` propagates through the fork.

**Since then** we've built TheRock 7.13 from source for gfx1151 (`-DTHEROCK_AMDGPU_TARGETS=gfx1151 -DTHEROCK_ENABLE_BLAS=ON`). Would using TheRock-built PyTorch + Triton avoid this mismatch entirely?

**Comment by stampby** [comment]
**Update: FIXED with TheRock-built libs.**

Rebuilt ROCm 7.13 from source with TheRock (`-DTHEROCK_AMDGPU_TARGETS=gfx1151 -DTHEROCK_ENABLE_BLAS=ON`) and loaded the libs via `LD_LIBRARY_PATH`. The Triton subprocess test now passes:

```
[PARENT] Testing GPU in parent process...
[PARENT] GPU OK: Radeon 8060S Graphics
[PARENT] Starting child process...
[CHILD] GPU matmul OK: torch.Size([64, 64])
[CHILD] Triton kernel OK (max_err=0.000000)
[PARENT] Child exit code: 0
PASS — Triton works in subprocess
```

@tcgu-amd you were right — it was a library mismatch. The previous setup had three conflicting ROCm versions:
- PyTorch 2.11.0+rocm7.2 (bundled ROCm 7.2 libs)
- lemonade vllm-rocm (bundled ROCm 7.12 libs)  
- System ROCm 7.2.1

With TheRock-built libs loaded uniformly via `LD_LIBRARY_PATH`, the parent and child processes use the same libraries and the device ordinal resolves correctly.

Test script: https://github.com/stampby/rocm-cpp/blob/main/tools/test_triton_fork.py

**Comment by tcgu-amd** [comment]
@stampby Great! Glad you hear that you were able to get the issue fixed! I will be closing this ticket them. Please feel free to follow up if you need any additional help from our side! :D
