### ISSUE TITLE
[Issue]: `gfx1151 (Strix Halo): Multiple GPU kernels crash with HSA_STATUS_ERROR_EXCEPTION during neural network inference — multinomial, gather, scatter_gather_elementwise`

### ISSUE THREAD

**Issue by EvilSquirrels** [ROCm/TheRock#5259]
### Problem Description

Several GPU kernels produce fatal hardware exceptions (HSA_STATUS_ERROR_EXCEPTION, code 0x1016) on gfx1151 during neural network inference using PyTorch/ROCm. The crashes occur in torch.multinomial, torch.gather/index_select, and scatter_gather_elementwise_kernel. These operations are triggered during autoregressive token generation in XTTS (Coqui TTS v2), but the crashes are in core PyTorch GPU operations and are not specific to XTTS.

The three kernel names that crash:
- `_ZN2at6native25_assert_async_cuda_kernelIbEEvPKT_NS0_3MsgE` (multinomial)
- `_ZN2at6native24vectorized_gather_kernelILi16ElEEvPcS2_PT0_illllb` (gather / index_select)
- `_ZN2at6native34_scatter_gather_elementwise_kernelILi256ELi4EZNS0_36_cuda_scatter_gather_internal_kernelILb0ENS0_10OpaqueTypeILi4EEElEclINS0_12TensorAssignEEEvRNS_14TensorIteratorElllRKT_EUliE_EEviT1_` (scatter_gather_elementwise)

Moving torch.multinomial and torch.nn.functional.embedding to CPU via monkey-patching prevents the hard crashes for shorter input sequences, but for longer sequences (~20+ words of input text) the GPU still produces inf/nan values in probability tensors, indicating upstream numerical corruption in the GPU computation even when individual operations do not crash.

Setting MIOPEN_CONV_PRECISE_ROCBLAS_FLOWS=1 and MIOPEN_DEBUG_CONV_GEMM=0 improved convolution correctness and resolved some crashes, but the kernel crashes listed above persist regardless.

This is related to a previously filed issue regarding missing gfx1151 MIOpen files (gfx1151_20.HIP.fdb.txt and libMIOpenCKGroupedConv_gfx1151.so). Even with workarounds for those missing files in place, these kernel crashes occur independently.

> **Update:** The crashes were traced to a missing timeout in the reverse proxy layer. The proxy's `requests.post()` call to AllTalk had no timeout set. For long generations (30-60+ seconds), Flask's default connection timeout killed the proxy's connection to AllTalk while the GPU was still mid-inference. AllTalk's GPU kernels crashed when the connection they were reporting back through was abruptly dropped.
>
> Adding `timeout=300` to the proxy's POST request resolved the crashes. Direct calls to AllTalk (port 7851) never exhibited the crashes — only requests routed through the proxy. This suggests the kernel crashes are triggered by an interrupted in-flight GPU computation rather than by the operations themselves being intrinsically broken.
>
> This may be relevant to other users running AllTalk or similar TTS models behind any reverse proxy or load balancer without adequate timeout configuration. The underlying question of whether these kernels handle interrupted computations gracefully on gfx1151 remains open.

### Operating System

Ubuntu 26.04 LTS (Resolute Raccoon), Linux kernel 7.0

### CPU

AMD Ryzen AI Max+ 395 (Strix Halo, 16-core Zen 5)

### GPU

AMD Radeon 8060S — gfx1151 (integrated, Strix Halo), 128GB unified memory (shared between CPU and GPU), GTT size unlocked via GRUB: amdgpu.gttsize=122880

### ROCm Version

ROCm 7.2.2 (system) / torch 2.11.0+rocm7.13.0a20260425 (TheRock nightly)

### Steps to Reproduce

**Steps to Reproduce:**
1. Hardware: AMD Ryzen AI Max+ 395 (gfx1151 / Strix Halo), 128GB unified memory, Ubuntu 26.04 LTS, ROCm 7.2.2, torch 2.11.0+rocm7.13.0a20260425
2. Install AllTalk TTS V2 with XTTS v2 model (Coqui TTS 0.22.0)
3. Set HSA_OVERRIDE_GFX_VERSION=11.5.1, HSA_ENABLE_SDMA=0, MIOPEN_CONV_PRECISE_ROCBLAS_FLOWS=1, MIOPEN_DEBUG_CONV_GEMM=0
4. Run XTTS inference with any input text of approximately 15+ words
5. The multinomial crash occurs on virtually all inputs. The gather/scatter crashes occur on medium to long inputs.

Minimal reproduction without XTTS — run this directly in Python to confirm the multinomial crash in isolation:

```python
import torch
# Simulate the probability tensor shape XTTS produces during token generation
probs = torch.softmax(torch.randn(1, 8194, device='cuda'), dim=-1)
# This crashes with HSA_STATUS_ERROR_EXCEPTION on gfx1151
result = torch.multinomial(probs, num_samples=1)
print(result)
```
> **Reliable reproduction path (updated):** Route TTS requests through a reverse proxy that has a shorter timeout than the generation time. With a proxy timeout shorter than the GPU computation time, the connection drops mid-inference and the kernel crashes reliably. Direct calls to AllTalk with no proxy do not reproduce the crashes.

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.18
Runtime Ext Version:     1.15
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
XNACK enabled:           NO
DMAbuf Support:          YES
VMM Support:             YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD RYZEN AI MAX+ 395 w/ Radeon 8060S
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD RYZEN AI MAX+ 395 w/ Radeon 8060S
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      49152(0xc000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   5187                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Memory Properties:       
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    128130724(0x7a31ea4) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    128130724(0x7a31ea4) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    128130724(0x7a31ea4) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 4                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    128130724(0x7a31ea4) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1151                            
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon Graphics                
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      2048(0x800) KB                     
    L3:                      32768(0x8000) KB                   
  Chip ID:                 5510(0x1586)                       
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          128(0x80)                          
  Max Clock Freq. (MHz):   2900                               
  BDFID:                   50432                              
  Internal Node ID:        1                                  
  Compute Unit:            40                                 
  SIMDs per CU:            2                                  
  Shader Engines:          2                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Memory Properties:       APU
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        2147483647(0x7fffffff)             
    y                        65535(0xffff)                      
    z                        65535(0xffff)                      
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 34                                 
  SDMA engine uCode::      18                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    64065360(0x3d18f50) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    64065360(0x3d18f50) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1151         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        2147483647(0x7fffffff)             
        y                        65535(0xffff)                      
        z                        65535(0xffff)                      
      FBarrier Max Size:       32                                 
    ISA 2                    
      Name:                    amdgcn-amd-amdhsa--gfx11-generic   
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        2147483647(0x7fffffff)             
        y                        65535(0xffff)                      
        z                        65535(0xffff)                      
      FBarrier Max Size:       32                                 
*******                  
Agent 3                  
*******                  
  Name:                    aie2p                              
  Uuid:                    AIE-XX                             
  Marketing Name:          RyzenAI-npu5                       
  Vendor Name:             AMD                                
  Feature:                 AGENT_DISPATCH                     
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        1(0x1)                             
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          64(0x40)                           
  Queue Type:              SINGLE                             
  Node:                    0                                  
  Device Type:             DSP                                
  Cache Info:              
    L2:                      2048(0x800) KB                     
    L3:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          0(0x0)                             
  Max Clock Freq. (MHz):   0                                  
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            0                                  
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:0                                  
  Memory Properties:       
  Features:                AGENT_DISPATCH
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, COARSE GRAINED
      Size:                    128130724(0x7a31ea4) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65536(0x10000) KB                  
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    128130724(0x7a31ea4) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*** Done *** 

### Additional Information

**Additional Information:**
- The crashes occur in the GPU kernels themselves, not in Python. The HSA queue abort message appears in stderr from rocdevice.cpp line 3966.
- HSA_SERIALIZE_KERNEL=3 was suggested by the error output but does not prevent the crashes — it only changes the reporting timing.
- Workaround currently in use: monkey-patching torch.multinomial and torch.nn.functional.embedding to run on CPU. This prevents the hard crashes but does not resolve the underlying numerical corruption for longer sequences.
- The inf/nan values appearing in probability tensors for longer inputs suggest that upstream GPU convolution operations (likely in the GPT attention layers) are producing incorrect results, causing the probability distributions to become degenerate before multinomial is even called. This points to the MIOpen workspace allocation failures (GemmFwdRest returning zero-size workspace) as the root cause of the numerical corruption, even when the missing fdb/CK library issues are worked around.
- Previous related issue: [https://github.com/ROCm/TheRock/issues/5105]

> **Update:** The CPU fallback patches for multinomial, embedding, and torchaudio.load, and the additional MIOpen environment variables (MIOPEN_FIND_ENFORCE, MIOPEN_DEBUG_CONV_GEMM, MIOPEN_CONV_PRECISE_ROCBLAS_FLOWS) were all removed after the root cause was identified. AllTalk operates correctly on gfx1151 with standard configuration when requests are not interrupted mid-computation.

**Comment by EvilSquirrels** [comment]
Update — regression in 2.10.0+rocm7.13.0a20260513 (the build that fixed the 
symlink from #5340):

The 0513 build ships libMIOpenCKGroupedConv_gfx1151.so as a real compiled 
library (284MB) rather than the missing symlink from 0425. However, when 
MIOpen attempts to use the CK kernels during MuseTalk inference (grouped 
convolution in a UNet architecture), the system experiences a complete hard 
lockup requiring a physical power cycle.

The kernel writes zero crash information — the journal stops cleanly several 
minutes before the lockup with no ring timeout, OOM, panic, watchdog fire, or 
any GPU error. NMI watchdog with kernel.hung_task_panic=1 and 
kernel.softlockup_panic=1 does not fire. Reproduced twice from both GNOME 
session and TTY (Ctrl+Alt+F3), ruling out compositor involvement.

Hypothesis: one or more CK kernels in the 0513 build generates an invalid GPU 
instruction or illegal memory access for a specific grouped convolution tensor 
shape that MuseTalk hits early in inference (batch 1 of 20, approximately 
6-7 minutes in), causing the GPU command processor to hang with no recovery.

The 0425 build with manually created symlinks remains stable but slow (~42x 
slower than real-time for MuseTalk) due to MIOpen falling back to unoptimised 
solvers. The 0513 build has been reverted.

Hardware: same as above (gfx1151, Strix Halo, 128GB unified, Ubuntu 26.04)
Torch: 2.10.0+rocm7.13.0a20260513
Related: #5340 (symlink packaging fix that introduced this regression)

**Comment by EvilSquirrels** [comment]
[gfx1151_20.HIP.3_5_2_5b3f4b7474-dirty.ufdb.txt](https://github.com/user-attachments/files/28314014/gfx1151_20.HIP.3_5_2_5b3f4b7474-dirty.ufdb.txt)

Additional finding: MIOpen 3.5.2 built from source (develop branch, 
commit 5b3f4b7474) with CK enabled for gfx1151 produces the same hard 
GPU lockup during MuseTalk inference. The MIOpen solver database 
(gfx1151_20.HIP.3_5_2_5b3f4b7474-dirty.ufdb.txt, 20KB) was partially 
populated before the crash, indicating some CK kernels execute correctly 
on gfx1151 while at least one specific grouped convolution kernel shape 
triggers the lockup. This confirms the bug is in the CK kernel source 
for gfx1151, not in the packaging or build configuration.

**Comment by EvilSquirrels** [comment]
@mapatel-amd 

Thanks for the staging endpoint pointer in #5340. I tested it just now with a fresh conda env using the exact command you provided. Unfortunately, the crash is still present.

**Setup:**
```bash
conda create -n staging_test python=3.11 -y
conda activate staging_test
pip install torch rocm-sdk-libraries-gfx1151 \
    --index-url https://rocm.nightlies.amd.com/v2-staging/gfx1151/ \
    --extra-index-url https://pypi.org/simple/
```

**Versions installed:**
- `torch==2.12.0+rocm7.14.0a20260529`
- `torchvision==0.27.0+rocm7.14.0a20260529`
- `libMIOpen.so.1` — 456MB
- `libMIOpenCKGroupedConv_gfx1151.so` — 304MB

**Reproduction:** Running MuseTalk v1.5 inference. Hard GPU lockup at batch 0/20 of UNet inference (requires power cycle, no kernel logs written).

**Last logged shape before crash:**
```
conv -n 8 -c 640 -H 32 -W 32 -k 320 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
```
With `exhaustiveSearch = 1`.

Note: I cannot confirm this is the actual crashing shape — the hard lockup prevents further logs from being written. When I run MIOpenDriver standalone with this exact shape (exhaustive search enabled), it completes successfully and selects `ConvBinWinogradRxSf2x3g1` at ~0.95ms. So the crash may be in a code path specific to PyTorch's MIOpen integration, or in the next shape MuseTalk attempts which never gets logged.

**Environment variables set:**
```
HSA_OVERRIDE_GFX_VERSION=11.5.1
ROCR_VISIBLE_DEVICES=0
HSA_ENABLE_SDMA=0
MIOPEN_FIND_ENFORCE=3
MIOPEN_DEBUG_CONV_GEMM=0
```

The crash is reproducible across multiple ROCm versions on my gfx1151 (Strix Halo, Radeon 8060S). I previously tested with the 0425 nightly (where MIOpenDriver can work around the issue by pre-populating the user database with a safe Winograd solver), the 0513 nightly, the 7.14.0a20260527 SDK libraries, and now the 7.14.0a20260529 staging build. All exhibit the same hard lockup during MuseTalk inference.

For reference, the workaround I'm currently using is forcing Winograd for the last-logged shape via MIOpenDriver before launching MuseTalk:
```bash
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM=0
export MIOPEN_DEBUG_CONV_DIRECT=0
export MIOPEN_DEBUG_CONV_FFT=0
export MIOPEN_DEBUG_CONV_WINOGRAD=1
export MIOPEN_FIND_ENFORCE=1
./MIOpenDriver conv -n 8 -c 640 -H 32 -W 32 -k 320 -y 3 -x 3 \
    -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
```
This writes a `ConvBinWinogradRxSf2x3g1` entry to the user database. MuseTalk then runs at ~1.1x real-time using the cached entry, presumably because whichever shape actually crashes either hits the cached safe path or never gets reached.

Can you reproduce MuseTalk v1.5 inference on your gfx1151 system, or was the testing you mentioned with a different workload? Happy to provide additional diagnostics (rocprofv3 traces, MIOpen verbose logs at level 5, MuseTalk reproduction steps) if useful.

**Comment by EvilSquirrels** [comment]
Closing this issue as the original problem (AllTalk HSA_STATUS_ERROR_EXCEPTION crashes on gfx1151) was resolved — it was caused by a missing timeout in a reverse proxy layer, not by a GPU kernel defect. The fix (`timeout=300` on the proxy's `requests.post()`) is documented in the issue body's update.

I want to apologize for subsequently appending the MuseTalk hard-lockup report as a comment on this thread. That was a different bug and I should have filed it separately from the start. Mixing the two made this ticket harder to triage and may have contributed to it sitting longer than it should have.

The MuseTalk lockup has now been properly diagnosed and filed as a standalone issue: #5581. The root cause turned out to be completely different from what was assumed here — it is a compute-unit hang in the MIOpen Winograd Sp3 gfx11 assembly solvers (`miopenSp3AsmConv_v30_3_1_gfx11_fp32_f3x2`), not a CK grouped-convolution problem. Full details, a minimal reproducer, and a systematic elimination matrix are in the new issue.

Thank you for your patience, and apologies again for the confusion.

**Comment by mapatel-amd** [comment]
@EvilSquirrels, Thanks for letting me know, I will also close #5340 and see if I can take on #5581 since I already have background knowledge from these issues. 

Edit: Thanks for closing #5340 just saw that.
