### ISSUE TITLE
[Issue]: No suitable algorithm was found to execute the required convolution

### ISSUE THREAD

**Issue by rishkhandelwal** [ROCm/TheRock#798]
### Problem Description

Requested to load HunyuanVideoClipModel_
loaded completely 9.5367431640625e+25 7894.8529052734375 True
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
Requested to load HunyuanVideo
loaded completely 31296.33470703125 24454.140747070312 True
100%|███████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.63it/s]
Requested to load AutoencoderKL
0 models unloaded.
loaded completely 16244.432812500001 470.1210079193115 True
MIOpen Error: D:/jam/TheRock/ml-libs/MIOpen/src/ocl/convolutionocl.cpp:275: No suitable algorithm was found to execute the required convolution
!!! Exception during processing !!! miopenStatusUnknownError
Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI\ComfyUI\execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\nodes.py", line 323, in decode
    images = vae.decode_tiled(samples["samples"], tile_x=tile_size // compression, tile_y=tile_size // compression, overlap=overlap // compression, tile_t=temporal_size, overlap_t=temporal_overlap)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\sd.py", line 621, in decode_tiled
    output = self.decode_tiled_3d(samples, **args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\sd.py", line 526, in decode_tiled_3d
    return self.process_output(comfy.utils.tiled_scale_multidim(samples, decode_fn, tile=(tile_t, tile_x, tile_y), overlap=overlap, upscale_amount=self.upscale_ratio, out_channels=self.output_channels, index_formulas=self.upscale_index_formula, output_device=self.output_device))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\utils.py", line 959, in tiled_scale_multidim
    ps = function(s_in).to(output_device)
         ^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\sd.py", line 525, in <lambda>
    decode_fn = lambda a: self.first_stage_model.decode(a.to(self.vae_dtype).to(self.device)).float()        
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\ldm\models\autoencoder.py", line 209, in decode
    dec = self.decoder(dec, **decoder_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl     
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 723, in forward
    h = self.up[i_level].upsample(h)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl     
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 114, in forward
    x = self.conv(x)
        ^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl     
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 62, in forward
    return self.conv(x)
           ^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl     
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\ops.py", line 128, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\conv.py", line 725, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\conv.py", line 720, in _conv_forward     
    return F.conv3d(
           ^^^^^^^^^
RuntimeError: miopenStatusUnknownError

### Operating System

Windows 11 Pro 10.0.26100

### CPU

AMD RYZEN AI MAX+ 395 w/ Radeon 8060S

### GPU

AMD Radeon(TM) 8060S Graphics

### ROCm Version

TheRock Latest

### ROCm Component

MIOpen

### Steps to Reproduce

Install ComfyUI
Install requirements.txt
Install pre-built windows Python wheels from TheRock(for python 3.11)
Download Hunyaun(text to video) template and required files
Click Start

After going to text encoder it gives error.

### Additional Information

I am using wheel - https://github.com/scottt/rocm-TheRock/releases/tag/v6.5.0rc-pytorch-gfx110x (with cp311 name)
using Python 3.11

In Dual clip loader - 
Using clip_I.safetensors was giving an issue - clip missing: ['text_projection.weight']
So I replaced it with ViT-L-14-BEST-smooth-GmP-TE-only-HF-format.safetensors to resolve the issue.

I tried changing MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_FWD=1, but it's taking more than an hour to load.
sample -
```
Requested to load HunyuanVideoClipModel_
loaded completely 9.5367431640625e+25 7894.8529052734375 True
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
Requested to load HunyuanVideo
loaded completely 31296.33470703125 24454.140747070312 True
 20%|█████████████▊                                                       | 4/20 [18:30<1:25:12, 319.54s/it]

**Comment by jammm** [comment]
Which hunyuan model did you try to run? Is the workflow from https://comfyanonymous.github.io/ComfyUI_examples/hunyuan_video/ ?

**Comment by jammm** [comment]
If by load you mean inference time, If you're using the 720p bf16 model, it's expected to take an hour to finish. The 8060S isn't powerful enough to run large video models fast enough.

**Comment by rishkhandelwal** [comment]
Thanks for letting me know about the inference time.
Yes, i used https://comfyanonymous.github.io/ComfyUI_examples/hunyuan_video/ Text to video.

However, as mentioned here, adding clip_l.safetensors and llava_llama3_fp8_scaled.safetensors to ComfyUI/models/text_encoders throws an error: 'clip missing: ['text_projection.weight']'.

To fix this, I moved clip_l.safetensors to the clip folder and further replaced it with ViT-L-14-BEST-smooth-GmP-TE-only-HF-format.safetensors into the clip folder only.

Still, after running for about two hours, it gave me the same error - RuntimeError: miopenStatusUnknownError

**Comment by jammm** [comment]
I see. Is the error happening even after `MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_FWD=1` ? To quickly check this, set the number of samples to 1 instead of 20.

**Comment by jammm** [comment]
I tried with `MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_FWD=1` and I get OOM. Perhaps try reducing the tile_size and overlap to 64/32 to see if it helps. Expect some TDR's with this env var set, but subsequent inferences should hopefully reduce those TDR's.

**Comment by rishkhandelwal** [comment]
I tried it with  MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_FWD=1, and still got the original error, not the OOM you mentioned. I will now try with the tile and overlap configuration you suggested.

**Comment by jammm** [comment]
Hmm I wasn't seeing that error. Reproducing it would require the exact workflow you're using.
It'll porbably be easier if you set the following env vars:
```
MIOPEN_ENABLE_LOGGING=1
MIOPEN_ENABLE_LOGGING_CMD=1
```

Then share the output logs (set step count to 1).

It'll provide MIOpen driver commands which can be used to quickly repro the issue without requiring comfyui usage.

**Comment by jammm** [comment]
I've seen this issue before though. For some large block sizes during VAE decode, MIOpen fails to find a suitable solution, and ends up having to run the nave convolution. Or sometimes it just gives up despite the naive convolution being enabled. It's a more MIOpen specific issue which needs to be investigated. The output logs will be useful evidence for that.

**Comment by rishkhandelwal** [comment]
```
got prompt
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.float16
model weight dtype torch.bfloat16, manual cast: None
model_type FLOW
Using scaled fp8: fp8 matrix mult: False, scale input: False
Requested to load HunyuanVideoClipModel_
loaded completely 9.5367431640625e+25 7894.8529052734375 True
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
Requested to load HunyuanVideo
loaded completely 31296.33470703125 24454.140747070312 True
100%|█████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.59s/it]
Requested to load AutoencoderKL
0 models unloaded.
loaded completely 16251.182812500001 470.1210079193115 True
MIOpen Error: D:/jam/TheRock/ml-libs/MIOpen/src/ocl/convolutionocl.cpp:275: No suitable algorithm was found to execute the required convolution
!!! Exception during processing !!! miopenStatusUnknownError
Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI\ComfyUI\execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\nodes.py", line 323, in decode
    images = vae.decode_tiled(samples["samples"], tile_x=tile_size // compression, tile_y=tile_size // compression, overlap=overlap // compression, tile_t=temporal_size, overlap_t=temporal_overlap)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\sd.py", line 621, in decode_tiled
    output = self.decode_tiled_3d(samples, **args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\sd.py", line 526, in decode_tiled_3d
    return self.process_output(comfy.utils.tiled_scale_multidim(samples, decode_fn, tile=(tile_t, tile_x, tile_y), overlap=overlap, upscale_amount=self.upscale_ratio, out_channels=self.output_channels, index_formulas=self.upscale_index_formula, output_device=self.output_device))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\utils.py", line 959, in tiled_scale_multidim
    ps = function(s_in).to(output_device)
         ^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\sd.py", line 525, in <lambda>
    decode_fn = lambda a: self.first_stage_model.decode(a.to(self.vae_dtype).to(self.device)).float()        
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\ldm\models\autoencoder.py", line 209, in decode
    dec = self.decoder(dec, **decoder_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl     
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 723, in forward
    h = self.up[i_level].upsample(h)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl     
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 114, in forward
    x = self.conv(x)
        ^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl     
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 62, in forward
    return self.conv(x)
           ^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl     
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\ops.py", line 128, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\conv.py", line 725, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\conv.py", line 720, in _conv_forward     
    return F.conv3d(
           ^^^^^^^^^
RuntimeError: miopenStatusUnknownError

Prompt executed in 649.29 seconds

**Comment by jammm** [comment]
Looks like the env vars weren't set properly. Are you running from powershell? if so, run the following commands:
```
$env:MIOPEN_ENABLE_LOGGING=1
$env:MIOPEN_ENABLE_LOGGING_CMD=1
```

**Comment by rishkhandelwal** [comment]
Its working but not more than tile size 64.
I am getting this error.

```
Prompt executed in 115.70 seconds
got prompt
Requested to load HunyuanVideo
loaded completely 36482.1751953125 24454.140747070312 True
  0%|                                                                                 | 0/1 [00:00<?, ?it/s]MIOpen(HIP): Command [LogCmdConvolution] MIOpenDriver.exe convbfp16 -n 1 -c 16 --in_d 19 -H 60 -W 60 -k 3072 --fil_d 1 -y 2 -x 2 --pad_d 0 -p 0 -q 0 --conv_stride_d 1 -u 2 -v 2 --dilation_d 1 -l 1 -j 1 --spatial_dim 3 -m conv -g 1 -F 1 -t 1
100%|█████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.19s/it]
0 models unloaded.
MIOpen(HIP): Command [LogCmdFindConvolution] MIOpenDriver.exe convfp16 -n 1 -c 16 --in_d 16 -H 12 -W 12 -k 16 --fil_d 1 -y 1 -x 1 --pad_d 0 -p 0 -q 0 --conv_stride_d 1 -u 1 -v 1 --dilation_d 1 -l 1 -j 1 --spatial_dim 3 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] MIOpenDriver.exe convfp16 -n 1 -c 16 --in_d 16 -H 12 -W 12 -k 16 --fil_d 1 -y 1 -x 1 --pad_d 0 -p 0 -q 0 --conv_stride_d 1 -u 1 -v 1 --dilation_d 1 -l 1 -j 1 --spatial_dim 3 -m conv -g 1 -F 1 -t 1

MIOpen(HIP): Command [LogCmdConvolution] MIOpenDriver.exe convfp16 -n 1 -c 256 --in_d 33 -H 50 -W 50 -k 256 --fil_d 3 -y 3 -x 3 --pad_d 0 -p 0 -q 0 --conv_stride_d 1 -u 1 -v 1 --dilation_d 1 -l 1 -j 1 --spatial_dim 3 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] MIOpenDriver.exe convfp16 -n 1 -c 256 --in_d 33 -H 50 -W 50 -k 256 --fil_d 3 -y 3 -x 3 --pad_d 0 -p 0 -q 0 --conv_stride_d 1 -u 1 -v 1 --dilation_d 1 -l 1 -j 1 --spatial_dim 3 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] MIOpenDriver.exe convfp16 -n 1 -c 256 --in_d 33 -H 50 -W 50 -k 256 --fil_d 3 -y 3 -x 3 --pad_d 0 -p 0 -q 0 --conv_stride_d 1 -u 1 -v 1 --dilation_d 1 -l 1 -j 1 --spatial_dim 3 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] MIOpenDriver.exe convfp16 -n 1 -c 256 --in_d 33 -H 50 -W 50 -k 256 --fil_d 3 -y 3 -x 3 --pad_d 0 -p 0 -q 0 --conv_stride_d 1 -u 1 -v 1 --dilation_d 1 -l 1 -j 1 --spatial_dim 3 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdFindConvolution] MIOpenDriver.exe convfp16 -n 1 -c 256 --in_d 63 -H 98 -W 98 -k 256 --fil_d 3 -y 3 -x 3 --pad_d 0 -p 0 -q 0 --conv_stride_d 1 -u 1 -v 1 --dilation_d 1 -l 1 -j 1 --spatial_dim 3 -m conv -g 1 -F 1 -t 1
MIOpen Error: D:/jam/TheRock/ml-libs/MIOpen/src/ocl/convolutionocl.cpp:275: No suitable algorithm was found to execute the required convolution
!!! Exception during processing !!! miopenStatusUnknownError
Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI\ComfyUI\execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\nodes.py", line 323, in decode
    images = vae.decode_tiled(samples["samples"], tile_x=tile_size // compression, tile_y=tile_size // compression, overlap=overlap // compression, tile_t=temporal_size, overlap_t=temporal_overlap)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\sd.py", line 621, in decode_tiled
    output = self.decode_tiled_3d(samples, **args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\sd.py", line 526, in decode_tiled_3d
    return self.process_output(comfy.utils.tiled_scale_multidim(samples, decode_fn, tile=(tile_t, tile_x, tile_y), overlap=overlap, upscale_amount=self.upscale_ratio, out_channels=self.output_channels, index_formulas=self.upscale_index_formula, output_device=self.output_device))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\utils.py", line 959, in tiled_scale_multidim
    ps = function(s_in).to(output_device)
         ^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\sd.py", line 525, in <lambda>
    decode_fn = lambda a: self.first_stage_model.decode(a.to(self.vae_dtype).to(self.device)).float()        
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\ldm\models\autoencoder.py", line 209, in decode
    dec = self.decoder(dec, **decoder_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl     
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 723, in forward
    h = self.up[i_level].upsample(h)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl     
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 114, in forward
    x = self.conv(x)
        ^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl     
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 62, in forward
    return self.conv(x)
           ^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl     
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\comfy\ops.py", line 128, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\conv.py", line 725, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\.venv\Lib\site-packages\torch\nn\modules\conv.py", line 720, in _conv_forward     
    return F.conv3d(
           ^^^^^^^^^
RuntimeError: miopenStatusUnknownError

**Comment by rishkhandelwal** [comment]
Laptop claims to allocate up to 96GB to the GPU, so I think the GPU won't be an issue?

**Comment by jammm** [comment]
> Laptop claims to allocate up to 96GB to the GPU, so I think the GPU won't be an issue?

yeah it hasn't run out of VRAM yet

**Comment by rishkhandelwal** [comment]
Is there any other way to fix it?

**Comment by benrichard-amd** [comment]
Hi @rishkhandelwal. This issue is a few months old now. Are you still running into this issue?

**Comment by rishkhandelwal** [comment]
No. Thanks for the help. Previous comment by jammm worked for me.
